import { pool } from '../db/connection.js';

async function run() {
  console.log('Starting migration for OFFSER in CMS_MENUHIST and SPs...');

  // 1. Add OFFSER to CMS_MENUHIST if not exists
  const [colCheck] = await pool.query(`
    SELECT COUNT(*) AS cnt 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
      AND TABLE_NAME = 'CMS_MENUHIST' 
      AND COLUMN_NAME = 'OFFSER'
  `);

  if (colCheck[0].cnt === 0) {
    console.log('Adding OFFSER column to CMS_MENUHIST...');
    await pool.query(`
      ALTER TABLE CMS_MENUHIST 
      ADD COLUMN OFFSER TINYINT(1) NOT NULL DEFAULT 0 AFTER ISSPECIAL
    `);
    console.log('Column OFFSER added to CMS_MENUHIST successfully.');
  } else {
    console.log('OFFSER column already exists in CMS_MENUHIST.');
  }

  // 2. Drop and Recreate CMSADDMENUITEM
  console.log('Recreating CMSADDMENUITEM...');
  await pool.query('DROP PROCEDURE IF EXISTS CMSADDMENUITEM');
  await pool.query(`
    CREATE PROCEDURE CMSADDMENUITEM (
        IN PSHORTNAME  VARCHAR(30),
        IN PITEMNAME   VARCHAR(100),
        IN PITEMDESCR  VARCHAR(255),
        IN PISSPECIAL  TINYINT,
        IN PSERVICEID  INT,
        IN POFFSER     TINYINT,
        IN PCREATEDBY  INT
    )
    BEGIN
        DECLARE VMENUITEMID INT;
        DECLARE VMENUCODE   VARCHAR(20);
        DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

        IF PSHORTNAME IS NULL OR TRIM(PSHORTNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Short Name is required'; END IF;
        IF PITEMNAME IS NULL OR TRIM(PITEMNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Name is required'; END IF;
        IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid special item flag'; END IF;
        IF COALESCE(POFFSER, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid official service flag'; END IF;

        IF PSERVICEID IS NOT NULL THEN
            IF NOT EXISTS (SELECT 1 FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID AND STATUSID = 10) THEN
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid or inactive Service ID';
            END IF;
        END IF;

        START TRANSACTION;
        CALL CMSGENAUTO('CMS_MENUITEM', 'MENUCODE', VMENUCODE);

        INSERT INTO CMS_MENUITEM (MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, SERVICEID, OFFSER, STATUSID, CREATEDBY)
        VALUES (VMENUCODE, TRIM(PSHORTNAME), TRIM(PITEMNAME), PITEMDESCR, COALESCE(PISSPECIAL, 0), PSERVICEID, COALESCE(POFFSER, 0), 10, PCREATEDBY);
        
        SET VMENUITEMID = LAST_INSERT_ID();
        COMMIT;

        SELECT VMENUITEMID AS MENUITEMID, VMENUCODE AS MENUCODE;
    END
  `);

  // 3. Drop and Recreate CMSUPDMENUITEM
  console.log('Recreating CMSUPDMENUITEM...');
  await pool.query('DROP PROCEDURE IF EXISTS CMSUPDMENUITEM');
  await pool.query(`
    CREATE PROCEDURE CMSUPDMENUITEM (
        IN PMENUITEMID INT,
        IN PSHORTNAME  VARCHAR(30),
        IN PITEMNAME   VARCHAR(100),
        IN PITEMDESCR  VARCHAR(255),
        IN PISSPECIAL  TINYINT,
        IN PSERVICEID  INT,
        IN POFFSER     TINYINT,
        IN PSTATUSCODE VARCHAR(10),
        IN PCHANGEDBY  INT,
        IN PCHGREASON  VARCHAR(255)
    )
    BEGIN
        DECLARE VCOUNT INT DEFAULT 0;
        DECLARE VSTATUSID INT;
        DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

        IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
        SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
        IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;
        IF PSHORTNAME IS NULL OR TRIM(PSHORTNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Short Name is required'; END IF;
        IF PITEMNAME IS NULL OR TRIM(PITEMNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Name is required'; END IF;
        IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid special item flag'; END IF;
        IF COALESCE(POFFSER, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid official service flag'; END IF;
        
        IF PSERVICEID IS NOT NULL THEN
            IF NOT EXISTS (SELECT 1 FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID AND STATUSID = 10) THEN
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid or inactive Service ID';
            END IF;
        END IF;

        SELECT STATUSID INTO VSTATUSID FROM CMS_STATUS WHERE STATUSCODE = PSTATUSCODE AND STATUSGRP = 'SYS';
        IF VSTATUSID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid status code'; END IF;

        START TRANSACTION;

        INSERT INTO CMS_MENUHIST (MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, OFFSER, STATUSID, CHANGEDBY, CHGREASON)
        SELECT MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, OFFSER, STATUSID, PCHANGEDBY, PCHGREASON
        FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;

        UPDATE CMS_MENUITEM
        SET    SHORTNAME = TRIM(PSHORTNAME),
               ITEMNAME  = TRIM(PITEMNAME),
               ITEMDESCR = PITEMDESCR,
               ISSPECIAL = COALESCE(PISSPECIAL, ISSPECIAL),
               SERVICEID = PSERVICEID,
               OFFSER    = COALESCE(POFFSER, OFFSER),
               STATUSID  = VSTATUSID,
               UPDATEDAT = CURRENT_TIMESTAMP
        WHERE  MENUITEMID = PMENUITEMID;
        COMMIT;

        SELECT PMENUITEMID AS MENUITEMID;
    END
  `);

  // 4. Drop and Recreate CMSGETMENUITEM
  console.log('Recreating CMSGETMENUITEM...');
  await pool.query('DROP PROCEDURE IF EXISTS CMSGETMENUITEM');
  await pool.query(`
    CREATE PROCEDURE CMSGETMENUITEM (IN PMENUITEMID INT)
    BEGIN
        SELECT MI.MENUITEMID, MI.SERVICEID, S.SERVCODE, S.SERVNAME,
               MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
               MI.ITEMDESCR, MI.ISSPECIAL, MI.OFFSER, MI.STATUSID, ST.STATUSCODE AS STATUSCODE, ST.STATUSNAME AS STATUSNAME,
               MI.CREATEDBY, MI.CREATEDAT, MI.UPDATEDAT
        FROM   CMS_MENUITEM MI
        LEFT JOIN CMS_SERVICE S ON S.SERVICEID = MI.SERVICEID
        JOIN   CMS_STATUS ST ON ST.STATUSID = MI.STATUSID
        WHERE  MI.MENUITEMID = PMENUITEMID;
    END
  `);

  // 5. Drop and Recreate CMSLISTMENUITEM
  console.log('Recreating CMSLISTMENUITEM...');
  await pool.query('DROP PROCEDURE IF EXISTS CMSLISTMENUITEM');
  await pool.query(`
    CREATE PROCEDURE CMSLISTMENUITEM (
        IN PISSPECIAL TINYINT,
        IN PSTATUSCODE VARCHAR(10)
    )
    BEGIN
        SELECT MI.MENUITEMID, MI.SERVICEID, S.SERVCODE, S.SERVNAME,
               MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
               MI.ITEMDESCR, MI.ISSPECIAL, MI.OFFSER, MI.STATUSID, ST.STATUSCODE AS STATUSCODE,
               MI.CREATEDBY, MI.CREATEDAT, MI.UPDATEDAT
        FROM   CMS_MENUITEM MI
        LEFT JOIN CMS_SERVICE S ON S.SERVICEID = MI.SERVICEID
        JOIN   CMS_STATUS ST ON ST.STATUSID = MI.STATUSID
        WHERE  (PISSPECIAL IS NULL OR MI.ISSPECIAL = PISSPECIAL)
          AND  (PSTATUSCODE  IS NULL OR ST.STATUSCODE  = PSTATUSCODE)
        ORDER BY MI.ITEMNAME;
    END
  `);

  // 6. Drop and Recreate CMSACTMENUITEM & CMSDEACTMENUITEM
  console.log('Recreating CMSACTMENUITEM & CMSDEACTMENUITEM...');
  await pool.query('DROP PROCEDURE IF EXISTS CMSACTMENUITEM');
  await pool.query(`
    CREATE PROCEDURE CMSACTMENUITEM (IN PMENUITEMID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
    BEGIN
        DECLARE VCOUNT INT DEFAULT 0;
        DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
        IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
        SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
        IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;

        START TRANSACTION;
        INSERT INTO CMS_MENUHIST (MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, OFFSER, STATUSID, CHANGEDBY, CHGREASON)
        SELECT MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, OFFSER, STATUSID, PCHANGEDBY, PCHGREASON
        FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
        
        UPDATE CMS_MENUITEM SET STATUSID = 10, UPDATEDAT = CURRENT_TIMESTAMP WHERE MENUITEMID = PMENUITEMID;
        COMMIT;
        SELECT PMENUITEMID AS MENUITEMID;
    END
  `);

  await pool.query('DROP PROCEDURE IF EXISTS CMSDEACTMENUITEM');
  await pool.query(`
    CREATE PROCEDURE CMSDEACTMENUITEM (IN PMENUITEMID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
    BEGIN
        DECLARE VCOUNT INT DEFAULT 0;
        DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
        IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
        SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
        IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;

        START TRANSACTION;
        INSERT INTO CMS_MENUHIST (MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, OFFSER, STATUSID, CHANGEDBY, CHGREASON)
        SELECT MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, OFFSER, STATUSID, PCHANGEDBY, PCHGREASON
        FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
        
        UPDATE CMS_MENUITEM SET STATUSID = 11, UPDATEDAT = CURRENT_TIMESTAMP WHERE MENUITEMID = PMENUITEMID;
        COMMIT;
        SELECT PMENUITEMID AS MENUITEMID;
    END
  `);

  console.log('All migrations and stored procedures updated successfully!');
  await pool.end();
}

run().catch((err) => {
  console.error('Migration failed:', err);
  process.exit(1);
});
