/* ============================================================
   MODULE 0: COMMON MASTER / SYSTEM CONFIGURATION
   Naming rule:
   - Table names start with CMS_ and suffix length <= 10 characters
   - Column names are uppercase and do not contain underscores
   ============================================================ */

CREATE DATABASE IF NOT EXISTS cms_db;
USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_AUTONOS;
DROP TABLE IF EXISTS CMS_SCREEN;
DROP TABLE IF EXISTS CMS_CUSTTYPE;
DROP TABLE IF EXISTS CMS_STATUS;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE CMS_STATUS (
    STATUSID INT AUTO_INCREMENT PRIMARY KEY,
    STATUSCODE VARCHAR(10) NOT NULL,
    STATUSNAME VARCHAR(50) NOT NULL,
    STATUSGRP VARCHAR(30) NOT NULL,
    DESCR VARCHAR(255),
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_STATUS_CODE_GRP (STATUSCODE, STATUSGRP)
) ENGINE=InnoDB;

CREATE TABLE CMS_AUTONOS (
    AUTONOID INT AUTO_INCREMENT PRIMARY KEY,
    TBLNAME VARCHAR(50) NOT NULL,
    DATAITEM VARCHAR(30) NOT NULL,
    ITEMLEN INT NOT NULL,
    FLDTYPE VARCHAR(10) NOT NULL DEFAULT 'CHAR',
    PREFIXCHAR VARCHAR(5) NOT NULL,
    STARTNO BIGINT NOT NULL DEFAULT 1,
    STARTDATE DATE NULL,
    LASTNO BIGINT NOT NULL DEFAULT 0,
    STATUS VARCHAR(10) NOT NULL DEFAULT 'A',
    CREATEDBY INT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_AUTONOS (TBLNAME, DATAITEM)
) ENGINE=InnoDB;

CREATE TABLE CMS_CUSTTYPE (
    CTYPEID INT AUTO_INCREMENT PRIMARY KEY,
    CTYPECODE VARCHAR(20) NOT NULL UNIQUE,
    CTYPENAME VARCHAR(80) NOT NULL,
    DESCR VARCHAR(255),
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE CMS_SCREEN (
    SCREENID INT AUTO_INCREMENT PRIMARY KEY,
    SCREENCODE VARCHAR(50) NOT NULL UNIQUE,
    SCREENNAME VARCHAR(100) NOT NULL,
    DESCR VARCHAR(255),
    ROUTEPATH VARCHAR(150),
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATEDBY INT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
