/* ============================================================
   MODULE 1: IDENTITY & ACCESS MANAGEMENT
   ============================================================ */

USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS CMS_CENTER;
DROP TABLE IF EXISTS CMS_CANTEEN;
DROP TABLE IF EXISTS CMS_USER;
DROP TABLE IF EXISTS CMS_ROLE;
DROP TABLE IF EXISTS CMS_CONSUMERROLE;
DROP TABLE IF EXISTS CMS_CANTEENROLE;
DROP TABLE IF EXISTS CMS_ROLESCN;
DROP TABLE IF EXISTS CMS_CUSTOMER;
DROP TABLE IF EXISTS CMS_PERMEMP;
DROP TABLE IF EXISTS CMS_CONTEMP;
DROP TABLE IF EXISTS CMS_OCEEMP;
DROP TABLE IF EXISTS CMS_VISITOR;
DROP TABLE IF EXISTS CMS_ACCKEY;
DROP TABLE IF EXISTS CMS_APPLVL;

SET FOREIGN_KEY_CHECKS = 1;

/* ============================================================
   CENTER MASTER
   ============================================================ */

CREATE TABLE CMS_CENTER (
    CENTERID INT AUTO_INCREMENT PRIMARY KEY,
    CENTERCODE VARCHAR(20) NOT NULL UNIQUE,
    CENTERNAME VARCHAR(120) NOT NULL,
    LOCATION VARCHAR(150),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'A',
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;


/* ============================================================
   CANTEEN MASTER
   ============================================================ */

CREATE TABLE CMS_CANTEEN (
    CANTEENID INT AUTO_INCREMENT PRIMARY KEY,
    CENTERID INT NOT NULL,
    CANTEENCODE VARCHAR(20) NOT NULL,
    CANTEENNAME VARCHAR(120) NOT NULL,
    LOCATION VARCHAR(150),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'A',

    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY UQ_CENTER_CANTEEN
    (
        CENTERID,
        CANTEENCODE
    ),

    CONSTRAINT FK_CAN_CENTER
        FOREIGN KEY (CENTERID)
        REFERENCES CMS_CENTER(CENTERID)
) ENGINE=InnoDB;


/* ============================================================
   USER - ROLE - CANTEEN MAPPING
   ============================================================ */


CREATE TABLE CMS_USER (
    USERID INT AUTO_INCREMENT PRIMARY KEY,
    LOGINID VARCHAR(50) NOT NULL UNIQUE,
    FULLNAME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(120) NULL UNIQUE,
    MOBILENO VARCHAR(20) NULL,
    PWDHASH VARCHAR(255) NOT NULL,
    AUTHPROV VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    AUTHID VARCHAR(120) NULL,
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE CMS_ROLE (
    ROLEID INT AUTO_INCREMENT PRIMARY KEY,
    ROLECODE VARCHAR(50) NOT NULL UNIQUE,
    ROLENAME VARCHAR(100) NOT NULL,
    DESCR VARCHAR(255),
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE CMS_CONSUMERROLE (
    USRROLEID INT AUTO_INCREMENT PRIMARY KEY,
    USERID INT NOT NULL,
    ROLEID INT NOT NULL,
    ASSIGNEDBY INT NULL,
    ASSIGNEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VALIDFROM DATETIME NULL,
    VALIDUNTIL DATETIME NULL,
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    UNIQUE KEY UQ_USRROLE (USERID, ROLEID),
    CONSTRAINT FK_UR_USER FOREIGN KEY (USERID) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLEID) REFERENCES CMS_ROLE(ROLEID),
    CONSTRAINT FK_UR_BY FOREIGN KEY (ASSIGNEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;

CREATE TABLE CMS_CANTEENROLE (
    USRCANROLEID INT AUTO_INCREMENT PRIMARY KEY,
    USERID INT NOT NULL,
    ROLEID INT NOT NULL,
    CANTEENID INT NOT NULL,
    ISDEFAULT TINYINT(1) NOT NULL DEFAULT 0,
    VALIDFROM DATETIME NULL,
    VALIDUNTIL DATETIME NULL,
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    ASSIGNEDBY INT NULL,
    ASSIGNEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_USRCANROLE
    (
        USERID,
        ROLEID,
        CANTEENID
    ),

    CONSTRAINT FK_UCR_USER
        FOREIGN KEY (USERID)
        REFERENCES CMS_USER(USERID),

    CONSTRAINT FK_UCR_ROLE
        FOREIGN KEY (ROLEID)
        REFERENCES CMS_ROLE(ROLEID),

    CONSTRAINT FK_UCR_CANTEEN
        FOREIGN KEY (CANTEENID)
        REFERENCES CMS_CANTEEN(CANTEENID),

    CONSTRAINT FK_UCR_BY
        FOREIGN KEY (ASSIGNEDBY)
        REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;



CREATE TABLE CMS_ROLESCN (
    ROLESCNID INT AUTO_INCREMENT PRIMARY KEY,
    ROLEID INT NOT NULL,
    SCREENID INT NOT NULL,
    CANVIEW TINYINT(1) NOT NULL DEFAULT 0,
    CANCREATE TINYINT(1) NOT NULL DEFAULT 0,
    CANUPDATE TINYINT(1) NOT NULL DEFAULT 0,
    CANDELETE TINYINT(1) NOT NULL DEFAULT 0,
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_ROLESCN (ROLEID, SCREENID),
    CONSTRAINT FK_RS_ROLE FOREIGN KEY (ROLEID) REFERENCES CMS_ROLE(ROLEID),
    CONSTRAINT FK_RS_SCREEN FOREIGN KEY (SCREENID) REFERENCES CMS_SCREEN(SCREENID)
) ENGINE=InnoDB;

CREATE TABLE CMS_CUSTOMER (
    CUSTOMERID INT AUTO_INCREMENT PRIMARY KEY,
    USERID INT NULL UNIQUE,
    CTYPECODE VARCHAR(20) NOT NULL,
    DISPNAME VARCHAR(120) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'A',
    VALIDFROM DATETIME NULL,
    VALIDUNTIL DATETIME NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_CUST_USER FOREIGN KEY (USERID) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_CUST_TYPE FOREIGN KEY (CTYPECODE) REFERENCES CMS_CUSTTYPE(CTYPECODE)
) ENGINE=InnoDB;

CREATE TABLE CMS_PERMEMP (
    PERMEMPID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT NOT NULL UNIQUE,
    EMPCODE VARCHAR(50) NOT NULL UNIQUE,
    DEPT VARCHAR(100) NOT NULL,
    DESIG VARCHAR(100) NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_PE_CUST FOREIGN KEY (CUSTOMERID) REFERENCES CMS_CUSTOMER(CUSTOMERID)
) ENGINE=InnoDB;

CREATE TABLE CMS_CONTEMP (
    CONTEMPID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT NOT NULL UNIQUE,
    CONTCODE VARCHAR(50) NOT NULL UNIQUE,
    VENDORNAME VARCHAR(150) NOT NULL,
    CONTSTART DATE NOT NULL,
    CONTEND DATE NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_CE_CUST FOREIGN KEY (CUSTOMERID) REFERENCES CMS_CUSTOMER(CUSTOMERID),
    CONSTRAINT CK_CONT_DATES CHECK (CONTEND >= CONTSTART)
) ENGINE=InnoDB;

CREATE TABLE CMS_OCEEMP (
    OCEEMPID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT NOT NULL UNIQUE,
    EMPCODE VARCHAR(50) NOT NULL,
    CENTERNAME VARCHAR(120) NOT NULL,
    DEPT VARCHAR(100),
    DESIG VARCHAR(100),
    VALIDFROM DATETIME NULL,
    VALIDUNTIL DATETIME NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_OCE_CODE_CENTRE (EMPCODE, CENTERNAME),
    CONSTRAINT FK_OCE_CUST FOREIGN KEY (CUSTOMERID) REFERENCES CMS_CUSTOMER(CUSTOMERID)
) ENGINE=InnoDB;

CREATE TABLE CMS_VISITOR (
    VISITORID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT NOT NULL UNIQUE,
    VISNAME VARCHAR(120) NOT NULL,
    VISMOBILE VARCHAR(20),
    VISORG VARCHAR(150),
    VISPURPOSE VARCHAR(255),
    VISDATE DATE NOT NULL,
    VALIDUNTIL DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'A',
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_VIS_CUST FOREIGN KEY (CUSTOMERID) REFERENCES CMS_CUSTOMER(CUSTOMERID),
    CONSTRAINT FK_VIS_BY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;

CREATE TABLE CMS_ACCKEY (
    ACCKEYID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT NOT NULL,
    KEYTYPE VARCHAR(30) NOT NULL,
    KEYVALUE VARCHAR(255) NOT NULL UNIQUE,
    EXPIRESAT DATETIME NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'A',
    CREATEDBY INT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    LASTUSEDAT DATETIME NULL,
    CONSTRAINT FK_AK_CUST FOREIGN KEY (CUSTOMERID) REFERENCES CMS_CUSTOMER(CUSTOMERID),
    CONSTRAINT FK_AK_BY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_KEYTYPE CHECK (KEYTYPE IN ('QR','RFID','EMPCARD','VISPASS','TEMPTOKEN'))
) ENGINE=InnoDB;

CREATE TABLE CMS_APPLVL (
    APPLVLID INT AUTO_INCREMENT PRIMARY KEY,
    LEVELNO INT NOT NULL UNIQUE,
    LEVELNAME VARCHAR(100) NOT NULL,
    ROLEID INT NOT NULL,
    DESCR VARCHAR(255),
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_AL_ROLE FOREIGN KEY (ROLEID) REFERENCES CMS_ROLE(ROLEID)
) ENGINE=InnoDB;

