/* ============================================================
   MODULE 2 CANTEEN MENU & SERVICE
   ============================================================ */
USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_SERVICE;
DROP TABLE IF EXISTS CMS_SERVHIST;
DROP TABLE IF EXISTS CMS_MENUITEM;
DROP TABLE IF EXISTS CMS_MENUHIST;
DROP TABLE IF EXISTS CMS_ITEMPRICE;
DROP TABLE IF EXISTS CMS_ITEMPRICEDT;
DROP TABLE IF EXISTS CMS_DAYSLOT;
DROP TABLE IF EXISTS CMS_SLOTHIST;
DROP TABLE IF EXISTS CMS_DAYMENU;
DROP TABLE IF EXISTS CMS_DMENUHIST;
DROP TABLE IF EXISTS CMS_MENUTPL;
DROP TABLE IF EXISTS CMS_MENUTPLDT;

SET FOREIGN_KEY_CHECKS = 1;

/* ============================================================
   SERVICE -- canteen-scoped service catalog (Breakfast/Lunch/..)
   ============================================================ */
CREATE TABLE CMS_SERVICE (
    SERVICEID   INT AUTO_INCREMENT PRIMARY KEY,
    CANTEENID   INT NOT NULL,                 -- which canteen owns this service
    SERVCODE    VARCHAR(20) NOT NULL,          -- short code, unique per canteen
    SERVNAME    VARCHAR(80) NOT NULL,
    DEFSTART    TIME NOT NULL,                 -- default window, copied onto day slots
    DEFEND      TIME NOT NULL,
    STATUS      VARCHAR(20) NOT NULL DEFAULT 'A',  -- disabling cascades to cancel future bookings (app/proc layer)
    CREATEDBY   INT NOT NULL,
    CREATEDAT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT   DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_SERV_CANTEEN (CANTEENID, SERVCODE),
    CONSTRAINT FK_SERV_CAN FOREIGN KEY (CANTEENID) REFERENCES CMS_CANTEEN(CANTEENID),
    CONSTRAINT FK_SERV_BY  FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_SERV_TIME     CHECK (DEFEND > DEFSTART),
    CONSTRAINT CK_SERV_STATUS   CHECK (STATUS IN ('A','D'))
) ENGINE=InnoDB;

CREATE TABLE CMS_SERVHIST (
    SERVHISTID INT AUTO_INCREMENT PRIMARY KEY,
    SERVICEID  INT NOT NULL,
    CANTEENID  INT NOT NULL,
    SERVCODE   VARCHAR(20) NOT NULL,
    SERVNAME   VARCHAR(80) NOT NULL,
    DEFSTART   TIME NOT NULL,
    DEFEND     TIME NOT NULL,
    VALIDFROM  DATE NULL,
    VALIDUNTIL DATE NULL,
    STATUS     VARCHAR(20) NOT NULL,
    CHANGEDBY  INT NOT NULL,
    CHANGEDAT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON  VARCHAR(255),
    CONSTRAINT FK_SH_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_SH_BY   FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;

/* ============================================================
   MENUITEM -- shared catalog, no price columns (see ITEMPRICE)
   ============================================================ */
CREATE TABLE CMS_MENUITEM (
    MENUITEMID INT AUTO_INCREMENT PRIMARY KEY,
    MENUCODE   VARCHAR(20) NOT NULL UNIQUE,
    SHORTNAME  VARCHAR(30) NOT NULL,
    ITEMNAME   VARCHAR(100) NOT NULL,
    ITEMDESCR  VARCHAR(255),
    ISSPECIAL  TINYINT(1) NOT NULL DEFAULT 0,
    STATUS     VARCHAR(20) NOT NULL DEFAULT 'A',  -- disabling cascades to cancel future bookings (app/proc layer)
    CREATEDBY  INT NOT NULL,
    CREATEDAT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT  DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_MI_BY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_MI_SPECIAL CHECK (ISSPECIAL IN (0, 1)),
    CONSTRAINT CK_MI_STATUS  CHECK (STATUS IN ('A','D'))
) ENGINE=InnoDB;

CREATE TABLE CMS_MENUHIST (
    MENUHISTID INT AUTO_INCREMENT PRIMARY KEY,
    MENUITEMID INT NOT NULL,
    MENUCODE   VARCHAR(20) NOT NULL,
    SHORTNAME  VARCHAR(30) NOT NULL,
    ITEMNAME   VARCHAR(100) NOT NULL,
    ITEMDESCR  VARCHAR(255),
    ISSPECIAL  TINYINT(1) NOT NULL,
    STATUS     VARCHAR(20) NOT NULL,
    CHANGEDBY  INT NOT NULL,
    CHANGEDAT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON  VARCHAR(255),
    CONSTRAINT FK_MH_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_MH_BY   FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;

/* ============================================================
   ITEMPRICE (header) + ITEMPRICEDT (per customer-type detail)

   No EFFUNTIL column: the end of one price band is implied by
   the EFFFROM of the next row for that item (type-2 SCD style).
   Rows are append-only once EFFFROM has passed -- old rows ARE
   the audit history, so no separate *_HIST table is needed here.

   Resolving the price applicable to a given item/customer-type
   on a given SERVICEDATE:
       SELECT d.PRICE
       FROM CMS_ITEMPRICE p
       JOIN CMS_ITEMPRICEDT d ON d.ITEMPRICEID = p.ITEMPRICEID
       WHERE p.MENUITEMID = ? AND d.CTYPECODE = ?
         AND p.EFFFROM <= ?                    -- SERVICEDATE
       ORDER BY p.EFFFROM DESC LIMIT 1;
   ============================================================ */
   
CREATE TABLE CMS_ITEMPRICE (
    ITEMPRICEID INT AUTO_INCREMENT PRIMARY KEY,
    MENUITEMID  INT NOT NULL,
    EFFFROM     DATE NOT NULL,
    STATUS      VARCHAR(20) NOT NULL DEFAULT 'A',  -- 'D' = a scheduled price band withdrawn before it took effect
    CREATEDBY   INT NOT NULL,
    CREATEDAT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT   DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_ITEMPRICE (MENUITEMID, EFFFROM),
    CONSTRAINT FK_IP_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_IP_BY   FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_IP_STATUS CHECK (STATUS IN ('A','D')),
    KEY IX_IP_ITEM_EFF (MENUITEMID, EFFFROM)
) ENGINE=InnoDB;

CREATE TABLE CMS_ITEMPRICEDT (
    ITEMPRICEDTID INT AUTO_INCREMENT PRIMARY KEY,
    ITEMPRICEID   INT NOT NULL,
    CTYPECODE     VARCHAR(20) NOT NULL,   -- FK to CMS_CUSTTYPE; PERM/CONT/VIS/OFCL/etc, extensible without DDL
    PRICE         DECIMAL(10,2) NOT NULL,
    UNIQUE KEY UQ_IPDT (ITEMPRICEID, CTYPECODE),
    CONSTRAINT FK_IPDT_HDR  FOREIGN KEY (ITEMPRICEID) REFERENCES CMS_ITEMPRICE(ITEMPRICEID),
    CONSTRAINT FK_IPDT_CTYPE FOREIGN KEY (CTYPECODE) REFERENCES CMS_CUSTTYPE(CTYPECODE),
    CONSTRAINT CK_IPDT_PRICE CHECK (PRICE >= 0)
) ENGINE=InnoDB;




/* ============================================================
   DAYSLOT -- dated instance of a service. Canteen-scoping falls
   out for free via SERVICEID.
   ============================================================ */

CREATE TABLE CMS_DAYSLOT (
    DAYSLOTID INT AUTO_INCREMENT PRIMARY KEY,
    SERVICEID INT NOT NULL,
    SERVDATE  DATE NOT NULL,
    STARTTIME TIME NOT NULL,
    ENDTIME   TIME NOT NULL,
    STATUS    VARCHAR(20) NOT NULL DEFAULT 'A',
    CREATEDBY INT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_DAYSLOT (SERVICEID, SERVDATE),
    CONSTRAINT FK_DS_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_DS_BY   FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_DS_TIME   CHECK (ENDTIME > STARTTIME),
    CONSTRAINT CK_DS_STATUS CHECK (STATUS IN ('A','D'))
) ENGINE=InnoDB;

CREATE TABLE CMS_SLOTHIST (
    SLOTHISTID INT AUTO_INCREMENT PRIMARY KEY,
    DAYSLOTID  INT NOT NULL,
    SERVICEID  INT NOT NULL,
    SERVDATE   DATE NOT NULL,
    STARTTIME  TIME NOT NULL,
    ENDTIME    TIME NOT NULL,
    STATUS     VARCHAR(20) NOT NULL,
    CHANGEDBY  INT NOT NULL,
    CHANGEDAT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON  VARCHAR(255),
    CONSTRAINT FK_SLH_SLOT FOREIGN KEY (DAYSLOTID) REFERENCES CMS_DAYSLOT(DAYSLOTID),
    CONSTRAINT FK_SLH_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_SLH_BY   FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;

/* ============================================================
   DAYMENU -- item offered on a specific day-slot.
   STATUS      = operational availability (A/D), can flip
                 many times a day, unrelated to approval.
   APPRSTATUS  = single-level manager approval workflow state.
   ============================================================ */


CREATE TABLE CMS_DAYMENU (
    DAYMENUID   INT AUTO_INCREMENT PRIMARY KEY,
    DMENUNO     VARCHAR(20) NULL UNIQUE,
    DAYSLOTID   INT NOT NULL,
    MENUITEMID  INT NOT NULL,
    ISSPECIAL   TINYINT(1) NOT NULL DEFAULT 0,
    ISPREBOOK   TINYINT(1) NOT NULL DEFAULT 1,
    ISKIOSK    TINYINT(1) NOT NULL DEFAULT 1,
    BOOKUNTIL    DATETIME NOT NULL,
    CANCELUNTIL  DATETIME NOT NULL,   
    AVAILQTY    INT NOT NULL DEFAULT 0,
    MAXQTY      INT NOT NULL DEFAULT 1,
    STATUS      VARCHAR(20) NOT NULL DEFAULT 'A',      -- operational: A / D / 
    APPRSTATUS  VARCHAR(20) NOT NULL DEFAULT 'PEN',       -- approval workflow: PEN / APP / REJ
    APPROVEDBY  INT NULL,
    APPROVEDAT  DATETIME NULL,
    REMARKS     VARCHAR(255),
    CREATEDAT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATEDBY     INT NOT NULL,
    UPDATEDAT   DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_DAYMENU (DAYSLOTID, MENUITEMID),
    CONSTRAINT FK_DM_SLOT FOREIGN KEY (DAYSLOTID) REFERENCES CMS_DAYSLOT(DAYSLOTID),
    CONSTRAINT FK_DM_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_DM_ADD  FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_DM_APPR FOREIGN KEY (APPROVEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_DM_QTY      CHECK (MAXQTY >= 1 AND AVAILQTY >= 0),
    CONSTRAINT CK_DM_CHANNELS CHECK (ISPREBOOK IN (0,1) AND ISKIOSK IN (0,1) AND ISSPECIAL IN (0,1)),
    CONSTRAINT CK_DM_STATUS   CHECK (STATUS IN ('A','D')),
    CONSTRAINT CK_DM_TIMES CHECK (CANCELUNTIL <= BOOKUNTIL),
    CONSTRAINT CK_DM_APPR     CHECK (APPRSTATUS IN ('PEN','APP','REJ'))
) ENGINE=InnoDB;



CREATE TABLE CMS_DMENUHIST (
    DMENUHISTID INT AUTO_INCREMENT PRIMARY KEY,
    DAYMENUID   INT NOT NULL,
    DAYSLOTID   INT NOT NULL,
    MENUITEMID  INT NOT NULL,
    ISSPECIAL   TINYINT(1) NOT NULL,
    ISPREBOOK   TINYINT(1) NOT NULL,
    ISKIOSK    TINYINT(1) NOT NULL,
    AVAILQTY    INT NOT NULL,
    MAXQTY      INT NOT NULL,
    STATUS      VARCHAR(20) NOT NULL,
    APPRSTATUS  VARCHAR(20) NOT NULL,
    CHANGEDBY   INT NOT NULL,
    CHANGEDAT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON   VARCHAR(255),
    REMARKS     VARCHAR(255),
    CONSTRAINT FK_DMH_DM   FOREIGN KEY (DAYMENUID) REFERENCES CMS_DAYMENU(DAYMENUID),
    CONSTRAINT FK_DMH_SLOT FOREIGN KEY (DAYSLOTID) REFERENCES CMS_DAYSLOT(DAYSLOTID),
    CONSTRAINT FK_DMH_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_DMH_BY   FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;

/* ============================================================
   MENUTPL / MENUTPLDT -- recurring templates so "copy previous
   day/week/month menu" is a materialization from a named
   template, not an ad-hoc row-copy.
   WEEKDAY: 1=Mon..7=Sun; NULL = ad-hoc/reusable template not
   tied to a specific weekday (e.g. a "festival day" template).
   ============================================================ */

CREATE TABLE CMS_MENUTPL (
    MENUTPLID INT AUTO_INCREMENT PRIMARY KEY,
    CANTEENID INT NOT NULL,
    SERVICEID INT NOT NULL,
    TPLNAME   VARCHAR(80) NOT NULL,
    WEEKDAY   TINYINT NULL,
    STATUS    VARCHAR(20) NOT NULL DEFAULT 'A',
    CREATEDBY INT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_MENUTPL (CANTEENID, SERVICEID, TPLNAME),
    CONSTRAINT FK_MTPL_CAN  FOREIGN KEY (CANTEENID) REFERENCES CMS_CANTEEN(CANTEENID),
    CONSTRAINT FK_MTPL_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_MTPL_BY   FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_MTPL_WEEKDAY CHECK (WEEKDAY IS NULL OR WEEKDAY BETWEEN 1 AND 7),
    CONSTRAINT CK_MTPL_STATUS  CHECK (STATUS IN ('A','D'))
) ENGINE=InnoDB;

CREATE TABLE CMS_MENUTPLDT (
    MENUTPLDTID INT AUTO_INCREMENT PRIMARY KEY,
    MENUTPLID   INT NOT NULL,
    MENUITEMID  INT NOT NULL,
    ISSPECIAL   TINYINT(1) NOT NULL DEFAULT 0,
    ISPREBOOK   TINYINT(1) NOT NULL DEFAULT 1,
    ISKIOSK    TINYINT(1) NOT NULL DEFAULT 1,
    MAXQTY      INT NOT NULL DEFAULT 1,
    DEFAVAILQTY INT NOT NULL DEFAULT 0,
    UNIQUE KEY UQ_MTPLDT (MENUTPLID, MENUITEMID),
    CONSTRAINT FK_MTPLDT_TPL  FOREIGN KEY (MENUTPLID) REFERENCES CMS_MENUTPL(MENUTPLID),
    CONSTRAINT FK_MTPLDT_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT CK_MTPLDT_QTY CHECK (MAXQTY >= 1 AND DEFAVAILQTY >= 0)
) ENGINE=InnoDB;


/* ============================================================
   TRIGGERS
   ============================================================ */

DELIMITER $$

-- Editing an approved day-menu row forces it back to Pending

CREATE TRIGGER TRG_DAYMENU_APPR_RESET
BEFORE UPDATE ON CMS_DAYMENU
FOR EACH ROW
BEGIN
    IF OLD.APPRSTATUS = 'APP' AND (
        OLD.AVAILQTY  <> NEW.AVAILQTY OR
        OLD.MAXQTY    <> NEW.MAXQTY OR
        OLD.ISSPECIAL <> NEW.ISSPECIAL OR
        OLD.ISPREBOOK <> NEW.ISPREBOOK OR
        OLD.ISKIOSK  <> NEW.ISKIOSK
    ) THEN
        SET NEW.APPRSTATUS = 'PEN';
        SET NEW.APPROVEDBY = NULL;
        SET NEW.APPROVEDAT = NULL;
    END IF;
END$$

DELIMITER ;