/* ============================================================
   MODULE 2: CANTEEN MENU & SERVICE MANAGEMENT
   ============================================================ */

USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_DMENUHIS;
DROP TABLE IF EXISTS CMS_DAYMENU;
DROP TABLE IF EXISTS CMS_SLOTHIST;
DROP TABLE IF EXISTS CMS_DAYSLOT;
DROP TABLE IF EXISTS CMS_MENUHIST;
DROP TABLE IF EXISTS CMS_MENUITEM;
DROP TABLE IF EXISTS CMS_SERVHIST;
DROP TABLE IF EXISTS CMS_SERVICE;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE CMS_SERVICE (
    SERVICEID INT AUTO_INCREMENT PRIMARY KEY,
    SERVCODE VARCHAR(20) NOT NULL UNIQUE,
    SERVNAME VARCHAR(80) NOT NULL,
    DEFSTART TIME NOT NULL,
    DEFEND TIME NOT NULL,
    VALIDFROM DATE NULL,
    VALIDUNTIL DATE NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'A',
    CREATEDBY INT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_SERV_BY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    -- v2_module2
    -- Added service time, date range, and status constraints.
    CONSTRAINT CK_SERV_TIME CHECK (DEFEND > DEFSTART),
    CONSTRAINT CK_SERV_VALIDITY CHECK (VALIDUNTIL IS NULL OR VALIDFROM IS NULL OR VALIDUNTIL >= VALIDFROM),
    CONSTRAINT CK_SERV_STATUS CHECK (STATUS IN ('A','D','EXP','BLK'))
) ENGINE=InnoDB;

CREATE TABLE CMS_SERVHIST (
    SERVHISTID INT AUTO_INCREMENT PRIMARY KEY,
    SERVICEID INT NOT NULL,
    SERVCODE VARCHAR(20) NOT NULL,
    SERVNAME VARCHAR(80) NOT NULL,
    DEFSTART TIME NOT NULL,
    DEFEND TIME NOT NULL,
    VALIDFROM DATE NULL,
    VALIDUNTIL DATE NULL,
    STATUS VARCHAR(20) NOT NULL,
    CHANGEDBY INT NOT NULL,
    CHANGEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON VARCHAR(255),
    CONSTRAINT FK_SH_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_SH_BY FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;

CREATE TABLE CMS_MENUITEM (
    MENUITEMID INT AUTO_INCREMENT PRIMARY KEY,
    MENUCODE VARCHAR(20) NOT NULL UNIQUE,
    SHORTNAME VARCHAR(30) NOT NULL,
    ITEMNAME VARCHAR(100) NOT NULL,
    ITEMDESCR VARCHAR(255),
    PERMPRICE DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    CONTPRICE DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    VISPRICE DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    OFFPRICE DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ISSPECIAL TINYINT(1) NOT NULL DEFAULT 0,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'A',
    CREATEDBY INT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_MI_BY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    -- v2_module2
    -- Added price, boolean flag, and status constraints.
    CONSTRAINT CK_MI_PRICES CHECK (PERMPRICE >= 0 AND CONTPRICE >= 0 AND VISPRICE >= 0 AND OFFPRICE >= 0),
    CONSTRAINT CK_MI_SPECIAL CHECK (ISSPECIAL IN (0, 1)),
    CONSTRAINT CK_MI_STATUS CHECK (STATUS IN ('A','D','EXP','BLK'))
) ENGINE=InnoDB;

CREATE TABLE CMS_MENUHIST (
    MENUHISTID INT AUTO_INCREMENT PRIMARY KEY,
    MENUITEMID INT NOT NULL,
    MENUCODE VARCHAR(20) NOT NULL,
    SHORTNAME VARCHAR(30) NOT NULL,
    ITEMNAME VARCHAR(100) NOT NULL,
    ITEMDESCR VARCHAR(255),
    PERMPRICE DECIMAL(10,2) NOT NULL,
    CONTPRICE DECIMAL(10,2) NOT NULL,
    VISPRICE DECIMAL(10,2) NOT NULL,
    OFFPRICE DECIMAL(10,2) NOT NULL,
    ISSPECIAL TINYINT(1) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CHANGEDBY INT NOT NULL,
    CHANGEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON VARCHAR(255),
    CONSTRAINT FK_MH_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_MH_BY FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;

CREATE TABLE CMS_DAYSLOT (
    DAYSLOTID INT AUTO_INCREMENT PRIMARY KEY,
    SERVICEID INT NOT NULL,
    SERVDATE DATE NOT NULL,
    STARTTIME TIME NOT NULL,
    ENDTIME TIME NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'A',
    CREATEDBY INT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_DAYSLOT (SERVICEID, SERVDATE),
    CONSTRAINT FK_DS_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_DS_BY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    -- v2_module2
    -- Added slot time and status constraints.
    CONSTRAINT CK_DS_TIME CHECK (ENDTIME > STARTTIME),
    CONSTRAINT CK_DS_STATUS CHECK (STATUS IN ('A','D','EXP','BLK'))
) ENGINE=InnoDB;

CREATE TABLE CMS_SLOTHIST (
    SLOTHISTID INT AUTO_INCREMENT PRIMARY KEY,
    DAYSLOTID INT NOT NULL,
    SERVICEID INT NOT NULL,
    SERVDATE DATE NOT NULL,
    STARTTIME TIME NOT NULL,
    ENDTIME TIME NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CHANGEDBY INT NOT NULL,
    CHANGEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON VARCHAR(255),
    CONSTRAINT FK_SLH_SLOT FOREIGN KEY (DAYSLOTID) REFERENCES CMS_DAYSLOT(DAYSLOTID),
    CONSTRAINT FK_SLH_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_SLH_BY FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;

CREATE TABLE CMS_DAYMENU (
    DAYMENUID INT AUTO_INCREMENT PRIMARY KEY,
    DMENUNO VARCHAR(20) NULL UNIQUE,
    DAYSLOTID INT NOT NULL,
    MENUITEMID INT NOT NULL,
    ISSPECIAL TINYINT(1) NOT NULL DEFAULT 0,
    ISPREBOOK TINYINT(1) NOT NULL DEFAULT 1,
    ISWALKIN TINYINT(1) NOT NULL DEFAULT 1,
    ISKIOSK TINYINT(1) NOT NULL DEFAULT 1,
    AVAILQTY INT NOT NULL DEFAULT 0,
    MAXQTY INT NOT NULL DEFAULT 1,
    BOOKSTART DATETIME NOT NULL,
    BOOKEND DATETIME NOT NULL,
    CANCELAT DATETIME NOT NULL,
    APPRSTATUS VARCHAR(20) NOT NULL DEFAULT 'P',
    ADDEDBY INT NOT NULL,
    APPROVEDBY INT NULL,
    APPROVEDAT DATETIME NULL,
    REMARKS VARCHAR(255),
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_DAYMENU (DAYSLOTID, MENUITEMID),
    CONSTRAINT FK_DM_SLOT FOREIGN KEY (DAYSLOTID) REFERENCES CMS_DAYSLOT(DAYSLOTID),
    CONSTRAINT FK_DM_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_DM_ADD FOREIGN KEY (ADDEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_DM_APPR FOREIGN KEY (APPROVEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_DM_QTY CHECK (MAXQTY >= 1 AND AVAILQTY >= 0),
    CONSTRAINT CK_DM_BOOK CHECK (BOOKEND > BOOKSTART),
    -- v2_module2
    -- Added channel flag and approval status constraints.
    CONSTRAINT CK_DM_CHANNELS CHECK (ISPREBOOK IN (0, 1) AND ISWALKIN IN (0, 1) AND ISKIOSK IN (0, 1) AND ISSPECIAL IN (0, 1)),
    CONSTRAINT CK_DM_APPR CHECK (APPRSTATUS IN ('P','APP','REJ'))
) ENGINE=InnoDB;

CREATE TABLE CMS_DMENUHIS (
    DMENUHISID INT AUTO_INCREMENT PRIMARY KEY,
    DAYMENUID INT NOT NULL,
    DAYSLOTID INT NOT NULL,
    MENUITEMID INT NOT NULL,
    ISSPECIAL TINYINT(1) NOT NULL,
    ISPREBOOK TINYINT(1) NOT NULL,
    ISWALKIN TINYINT(1) NOT NULL,
    ISKIOSK TINYINT(1) NOT NULL,
    AVAILQTY INT NOT NULL,
    MAXQTY INT NOT NULL,
    BOOKSTART DATETIME NOT NULL,
    BOOKEND DATETIME NOT NULL,
    CANCELAT DATETIME NOT NULL,
    APPRSTATUS VARCHAR(20) NOT NULL,
    CHANGEDBY INT NOT NULL,
    CHANGEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON VARCHAR(255),
    REMARKS VARCHAR(255),
    CONSTRAINT FK_DMH_DM FOREIGN KEY (DAYMENUID) REFERENCES CMS_DAYMENU(DAYMENUID),
    CONSTRAINT FK_DMH_SLOT FOREIGN KEY (DAYSLOTID) REFERENCES CMS_DAYSLOT(DAYSLOTID),
    CONSTRAINT FK_DMH_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_DMH_BY FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;

