/* ============================================================
   MODULE 3: BOOKING & SERVING
   ============================================================ */

USE cms_db;


SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_BOOKITMHS;
DROP TABLE IF EXISTS CMS_BOOKHIST;
DROP TABLE IF EXISTS CMS_PBACTIVE;
DROP TABLE IF EXISTS CMS_BOOKITEM;
DROP TABLE IF EXISTS CMS_BOOKING;



DROP TABLE IF EXISTS CMS_BOOKCTR;

DROP TABLE IF EXISTS CMS_BOOKTYPE;

SET FOREIGN_KEY_CHECKS = 1;

-- ------------------------------------------------------------
-- Booking type master (PB / KS)
-- ------------------------------------------------------------


CREATE TABLE CMS_BOOKTYPE (
    BOOKTYPEID INT AUTO_INCREMENT PRIMARY KEY,
    BOOKTYPECODE VARCHAR(10) NOT NULL UNIQUE,
    BOOKTYPENAME VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'A',
    CREATEDBY INT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDBY INT NULL,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_BT_CREATEDBY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_BT_UPDATEDBY FOREIGN KEY (UPDATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_BT_STATUS CHECK (STATUS IN ('A','D'))
) ENGINE=InnoDB;



-- ------------------------------------------------------------
-- Lifetime booking-number counter, scoped per booking type + service.
-- Row is created lazily (first booking of that type/service pair)
-- and locked with FOR UPDATE inside CMSADDBOOK, 
-- ------------------------------------------------------------


CREATE TABLE CMS_BOOKCTR (
    BOOKTYPEID INT NOT NULL,
    SERVICEID INT NOT NULL,
    LASTNO BIGINT NOT NULL DEFAULT 0,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (BOOKTYPEID, SERVICEID),
    CONSTRAINT FK_BC_BOOKTYPE FOREIGN KEY (BOOKTYPEID) REFERENCES CMS_BOOKTYPE(BOOKTYPEID),
    CONSTRAINT FK_BC_SERVICE FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID)
) ENGINE=InnoDB;


-- ------------------------------------------------------------
-- Booking header
-- BOOKNO      = formatted business number, e.g. 'PB-BR001', 
-- BOOKSEQNO   = sequence BOOKNO
-- ------------------------------------------------------------
CREATE TABLE CMS_BOOKING (
    BOOKID INT AUTO_INCREMENT PRIMARY KEY,
    BOOKNO VARCHAR(30) NOT NULL UNIQUE,
    BOOKTYPEID INT NOT NULL,
    CUSTOMERID INT NOT NULL,
    SERVICEID INT NOT NULL,
    SERVICEDATE DATE NOT NULL,
    STATUS VARCHAR(10) NOT NULL DEFAULT 'CR',
    BOOKSEQNO BIGINT NOT NULL,
    TOTALITEMS INT NOT NULL DEFAULT 0,
    TOTALQTY INT NOT NULL DEFAULT 0,
    TOTALAMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    BOOKEDBY INT NOT NULL,
    BOOKEDON DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANCELLEDBY INT NULL,
    CANCELLEDON DATETIME NULL,
    SERVEDBY INT NULL,
    SERVEDON DATETIME NULL,
    NOSHOWON DATETIME NULL,
    REMARKS VARCHAR(255),
    CREATEDBY INT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDBY INT NULL,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_BK_BOOKTYPE FOREIGN KEY (BOOKTYPEID) REFERENCES CMS_BOOKTYPE(BOOKTYPEID),
    CONSTRAINT FK_BK_CUST FOREIGN KEY (CUSTOMERID) REFERENCES CMS_CUSTOMER(CUSTOMERID),
    CONSTRAINT FK_BK_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_BK_BOOKEDBY FOREIGN KEY (BOOKEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_BK_CANCELLEDBY FOREIGN KEY (CANCELLEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_BK_SERVEDBY FOREIGN KEY (SERVEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_BK_CREATEDBY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_BK_UPDATEDBY FOREIGN KEY (UPDATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_BK_STATUS CHECK (STATUS IN ('CR','SRV','CAN','NOS','PRT')),
    CONSTRAINT CK_BK_TOTALS CHECK (TOTALITEMS >= 0 AND TOTALQTY >= 0 AND TOTALAMOUNT >= 0),
    KEY IX_BK_CUST_SVC_DATE (CUSTOMERID, SERVICEID, SERVICEDATE),
    KEY IX_BK_SVC_DATE_STATUS (SERVICEID, SERVICEDATE, STATUS)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- Booking detail. RATE is CALCULATED AT SERVING TIME BUT DUEING BOOKING CURRENT PRICE IS DISPLAYED (customer-type
-- price at that moment) 
-- ------------------------------------------------------------


CREATE TABLE CMS_BOOKITEM (
    BOOKITEMID INT AUTO_INCREMENT PRIMARY KEY,
    BOOKID INT NOT NULL,
    DAYMENUID INT NOT NULL,
    MENUITEMID INT NOT NULL,
    QTY INT NOT NULL,
    RATE DECIMAL(10,2) NOT NULL,
    AMOUNT DECIMAL(12,2) NOT NULL,
    REMARKS VARCHAR(255),
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_BOOKITEM (BOOKID, DAYMENUID),
    STATUS VARCHAR(10) NOT NULL DEFAULT 'CR',
    CONSTRAINT FK_BI_BOOK FOREIGN KEY (BOOKID) REFERENCES CMS_BOOKING(BOOKID),
    CONSTRAINT FK_BI_DAYMENU FOREIGN KEY (DAYMENUID) REFERENCES CMS_DAYMENU(DAYMENUID),
    CONSTRAINT FK_BI_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT CK_BI_QTY CHECK (QTY >= 1),
    CONSTRAINT CK_BI_RATE CHECK (RATE >= 0),
    CONSTRAINT CK_BI_AMOUNT CHECK (AMOUNT >= 0),
    CONSTRAINT CK_BI_STATUS CHECK (STATUS IN ('CR','SRV','CAN','NOS')),
    KEY IX_BI_DAYMENU (DAYMENUID)
) ENGINE=InnoDB;



CREATE TABLE CMS_PBACTIVE (
    CUSTOMERID INT NOT NULL,
    SERVICEID INT NOT NULL,
    SERVICEDATE DATE NOT NULL,
    BOOKID INT NOT NULL UNIQUE,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CUSTOMERID, SERVICEID, SERVICEDATE),
    CONSTRAINT FK_PBA_CUST FOREIGN KEY (CUSTOMERID) REFERENCES CMS_CUSTOMER(CUSTOMERID),
    CONSTRAINT FK_PBA_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_PBA_BOOK FOREIGN KEY (BOOKID) REFERENCES CMS_BOOKING(BOOKID)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- Booking header history. One row per terminal transition
-- (Cancel / Serve / No-Show)
-- ------------------------------------------------------------

CREATE TABLE CMS_BOOKHIST (
    BOOKHISTID INT AUTO_INCREMENT PRIMARY KEY,
    BOOKID INT NOT NULL,
    BOOKNO VARCHAR(30) NOT NULL,
    BOOKTYPEID INT NOT NULL,
    CUSTOMERID INT NOT NULL,
    SERVICEID INT NOT NULL,
    SERVICEDATE DATE NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    BOOKSEQNO BIGINT NOT NULL,
    TOTALITEMS INT NOT NULL,
    TOTALQTY INT NOT NULL,
    TOTALAMOUNT DECIMAL(12,2) NOT NULL,
    BOOKEDBY INT NOT NULL,
    BOOKEDON DATETIME NOT NULL,
    CANCELLEDBY INT NULL,
    CANCELLEDON DATETIME NULL,
    SERVEDBY INT NULL,
    SERVEDON DATETIME NULL,
    NOSHOWON DATETIME NULL,
    REMARKS VARCHAR(255),
    CREATEDBY INT NOT NULL,
    CREATEDAT DATETIME NOT NULL,
    UPDATEDBY INT NULL,
    UPDATEDAT DATETIME NULL,
    CHANGEDBY INT NOT NULL,
    CHGREASON VARCHAR(255),
    CHANGEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BH_BOOK FOREIGN KEY (BOOKID) REFERENCES CMS_BOOKING(BOOKID),
    CONSTRAINT FK_BH_BY FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID),
    KEY IX_BH_BOOK (BOOKID)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- Booking item history. Finalized snapshot 
-- ------------------------------------------------------------

CREATE TABLE CMS_BOOKITMHS (
    BOOKITMHSID INT AUTO_INCREMENT PRIMARY KEY,
    BOOKHISTID INT NOT NULL,
    BOOKITEMID INT NOT NULL,
    DAYMENUID INT NOT NULL,
    MENUITEMID INT NOT NULL,
    QTY INT NOT NULL,
    RATE DECIMAL(10,2) NOT NULL,
    AMOUNT DECIMAL(12,2) NOT NULL,
    REMARKS VARCHAR(255),
    CHANGEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(10) NOT NULL DEFAULT 'CR', 
    CONSTRAINT FK_BIH_HIST FOREIGN KEY (BOOKHISTID) REFERENCES CMS_BOOKHIST(BOOKHISTID),
    CONSTRAINT FK_BIH_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_BIH_DAYMENU FOREIGN KEY (DAYMENUID) REFERENCES CMS_DAYMENU(DAYMENUID),
    CONSTRAINT CK_BIH_STATUS CHECK (STATUS IN ('CR','SRV','CAN','NOS')),
    KEY IX_BIH_HIST (BOOKHISTID)
) ENGINE=InnoDB;
