INSERT INTO CMS_AUTONOS (TBLNAME, DATAITEM, ITEMLEN, PREFIXCHAR, LASTNO, LASTGENDATE, STATUSID) VALUES 
('CMS_DAYSLOT', 'SLOTNO', 15, 'SLT', 0, CURRENT_DATE, 10),
('CMS_DAYMENU', 'DMENUNO', 15, 'DMN', 0, CURRENT_DATE, 10),
('CMS_MENUITEM', 'MENUCODE', 15, 'ITM', 0, CURRENT_DATE, 10),
('CMS_VISITOR', 'VISITORNO', 15, 'VIS', 0, CURRENT_DATE, 10),
('CMS_WALLETTRAN', 'REFNO', 15, 'TXN', 0, CURRENT_DATE, 10);