USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDACCKEY;
DROP PROCEDURE IF EXISTS CMSUPDACCKEY;
DROP PROCEDURE IF EXISTS CMSGETACCKEY;
DROP PROCEDURE IF EXISTS CMSLISTACCKEY;
DROP PROCEDURE IF EXISTS CMSACTACCKEY;
DROP PROCEDURE IF EXISTS CMSDEACTACCKEY;
DROP PROCEDURE IF EXISTS CMSVALIDATEACCKEY;

DELIMITER $$
/* ============================================================
   CMS_ACCKEY  Access Credential Management
   ============================================================ */

CREATE PROCEDURE CMSADDACCKEY (
    IN PCUSTOMERID INT,
    IN PKEYTYPE    VARCHAR(30),
    IN PKEYVALUE   VARCHAR(255),
    IN PEXPIRESAT  DATETIME,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VACCKEYID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    IF PKEYVALUE IS NULL OR TRIM(PKEYVALUE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key value is required';
    END IF;
    IF PKEYTYPE IS NULL OR PKEYTYPE NOT IN ('QR', 'RFID', 'EMPCARD', 'VISPASS', 'TEMPTOKEN') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid access key type';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_ACCKEY (CUSTOMERID, KEYTYPE, KEYVALUE, EXPIRESAT, STATUS, CREATEDBY)
    VALUES (PCUSTOMERID, PKEYTYPE, TRIM(PKEYVALUE), PEXPIRESAT, 'A', PCREATEDBY);
    SET VACCKEYID = LAST_INSERT_ID();
    COMMIT;
    SELECT VACCKEYID AS ACCKEYID;
END$$


CREATE PROCEDURE CMSUPDACCKEY (
    IN PACCKEYID  INT,
    IN PKEYVALUE  VARCHAR(255),
    IN PEXPIRESAT DATETIME
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PACCKEYID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access Key ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_ACCKEY WHERE ACCKEYID = PACCKEYID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_ACCKEY
    SET    KEYVALUE   = COALESCE(PKEYVALUE, KEYVALUE),
           EXPIRESAT  = COALESCE(PEXPIRESAT, EXPIRESAT),
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  ACCKEYID   = PACCKEYID;
    COMMIT;
    SELECT PACCKEYID AS ACCKEYID;
END$$


CREATE PROCEDURE CMSGETACCKEY (IN PACCKEYID INT)
BEGIN
    SELECT AK.ACCKEYID, AK.CUSTOMERID, C.DISPNAME, C.CTYPECODE,
           AK.KEYTYPE, AK.KEYVALUE, AK.EXPIRESAT,
           AK.STATUS, AK.LASTUSEDAT, AK.CREATEDBY,
           AK.CREATEDAT, AK.UPDATEDAT
    FROM   CMS_ACCKEY AK
    JOIN   CMS_CUSTOMER C ON C.CUSTOMERID = AK.CUSTOMERID
    WHERE  AK.ACCKEYID = PACCKEYID;
END$$


CREATE PROCEDURE CMSLISTACCKEY (IN PCUSTOMERID INT)
BEGIN
    SELECT AK.ACCKEYID, AK.CUSTOMERID, AK.KEYTYPE, AK.KEYVALUE,
           AK.EXPIRESAT, AK.STATUS, AK.LASTUSEDAT,
           AK.CREATEDBY, AK.CREATEDAT, AK.UPDATEDAT
    FROM   CMS_ACCKEY AK
    WHERE  AK.CUSTOMERID = PCUSTOMERID
    ORDER BY AK.KEYTYPE, AK.CREATEDAT DESC;
END$$


CREATE PROCEDURE CMSACTACCKEY (IN PACCKEYID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PACCKEYID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access Key ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_ACCKEY WHERE ACCKEYID = PACCKEYID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_ACCKEY SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE ACCKEYID = PACCKEYID;
    COMMIT;
    SELECT PACCKEYID AS ACCKEYID;
END$$


CREATE PROCEDURE CMSDEACTACCKEY (IN PACCKEYID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PACCKEYID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access Key ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_ACCKEY WHERE ACCKEYID = PACCKEYID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_ACCKEY SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE ACCKEYID = PACCKEYID;
    COMMIT;
    SELECT PACCKEYID AS ACCKEYID;
END$$


/* ============================================================
   CMSVALIDATEACCKEY  Kiosk / Serving Identity Lookup

   Given a scanned key value, returns the customer identity
   if the key is active, not expired, and the customer is active.
   Updates LASTUSEDAT on every successful validation.
   ============================================================ */
CREATE PROCEDURE CMSVALIDATEACCKEY (
    IN PKEYVALUE VARCHAR(255)
)
BEGIN
    DECLARE VACCKEYID   INT;
    DECLARE VCUSTOMERID INT;
    DECLARE VKEYSTATUS  VARCHAR(20);
    DECLARE VEXPIRESAT  DATETIME;
    DECLARE VCUSTSTATUS VARCHAR(20);

    IF PKEYVALUE IS NULL OR TRIM(PKEYVALUE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Key value is required';
    END IF;

    SELECT AK.ACCKEYID, AK.CUSTOMERID, AK.STATUS, AK.EXPIRESAT, C.STATUS
    INTO   VACCKEYID, VCUSTOMERID, VKEYSTATUS, VEXPIRESAT, VCUSTSTATUS
    FROM   CMS_ACCKEY AK
    JOIN   CMS_CUSTOMER C ON C.CUSTOMERID = AK.CUSTOMERID
    WHERE  AK.KEYVALUE = TRIM(PKEYVALUE)
    LIMIT 1;

    IF VACCKEYID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key not recognised';
    END IF;

    IF VKEYSTATUS <> 'A' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key is inactive or revoked';
    END IF;

    IF VEXPIRESAT IS NOT NULL AND CURRENT_TIMESTAMP > VEXPIRESAT THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key has expired';
    END IF;

    IF VCUSTSTATUS <> 'A' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer account is not active';
    END IF;

    -- Touch last used timestamp (no transaction needed for single update)
    UPDATE CMS_ACCKEY SET LASTUSEDAT = CURRENT_TIMESTAMP WHERE ACCKEYID = VACCKEYID;

    -- Return customer identity
    SELECT C.CUSTOMERID, C.USERID, C.CTYPECODE, CT.CTYPENAME,
           C.DISPNAME, C.STATUS AS CUSTSTATUS,
           AK.ACCKEYID, AK.KEYTYPE,
           U.LOGINID, U.FULLNAME
    FROM   CMS_CUSTOMER C
    JOIN   CMS_CUSTTYPE CT ON CT.CTYPECODE = C.CTYPECODE
    JOIN   CMS_ACCKEY AK   ON AK.CUSTOMERID = C.CUSTOMERID AND AK.ACCKEYID = VACCKEYID
    LEFT JOIN CMS_USER U   ON U.USERID = C.USERID
    WHERE  C.CUSTOMERID = VCUSTOMERID;
END$$


DELIMITER ;

