USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDCANTEEN;
DROP PROCEDURE IF EXISTS CMSUPDCANTEEN;
DROP PROCEDURE IF EXISTS CMSACTCANTEEN;
DROP PROCEDURE IF EXISTS CMSDEACTCANTEEN;
DROP PROCEDURE IF EXISTS CMSGETCANTEEN;
DROP PROCEDURE IF EXISTS CMSLISTCANTEEN;
DROP PROCEDURE IF EXISTS CMSSEARCHCANTEEN;

DELIMITER $$
/* ============================================================
   CMS_CANTEEN — Canteen Master
   ============================================================ */

CREATE PROCEDURE CMSADDCANTEEN (
    IN PCENTERID    INT,
    IN PCANTEENCODE VARCHAR(20),
    IN PCANTEENNAME VARCHAR(120),
    IN PLOCATION    VARCHAR(150)
)
BEGIN
    DECLARE VCANTEENID INT;
    DECLARE VCENSTATUS VARCHAR(20);

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre ID is required';
    END IF;

    SELECT STATUS INTO VCENSTATUS FROM CMS_CENTER WHERE CENTERID = PCENTERID;
    IF VCENSTATUS IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre not found';
    END IF;
    IF VCENSTATUS <> 'A' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre must be active';
    END IF;

    IF PCANTEENCODE IS NULL OR TRIM(PCANTEENCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen Code is required';
    END IF;

    IF PCANTEENNAME IS NULL OR TRIM(PCANTEENNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen Name is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_CANTEEN (CENTERID, CANTEENCODE, CANTEENNAME, LOCATION)
    VALUES (PCENTERID, TRIM(PCANTEENCODE), TRIM(PCANTEENNAME), PLOCATION);

    SET VCANTEENID = LAST_INSERT_ID();
    COMMIT;

    SELECT VCANTEENID AS CANTEENID;
END$$


CREATE PROCEDURE CMSUPDCANTEEN (
    IN PCANTEENID   INT,
    IN PCANTEENNAME VARCHAR(120),
    IN PLOCATION    VARCHAR(150),
    IN PSTATUS      VARCHAR(20)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCANTEENID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CANTEEN WHERE CANTEENID = PCANTEENID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen not found';
    END IF;

    IF PCANTEENNAME IS NULL OR TRIM(PCANTEENNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen Name is required';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CANTEEN
    SET    CANTEENNAME = TRIM(PCANTEENNAME),
           LOCATION    = PLOCATION,
           STATUS      = COALESCE(PSTATUS, STATUS),
           UPDATEDAT   = CURRENT_TIMESTAMP
    WHERE  CANTEENID   = PCANTEENID;
    COMMIT;

    SELECT PCANTEENID AS CANTEENID;
END$$

CREATE PROCEDURE CMSACTCANTEEN (IN PCANTEENID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCANTEENID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CANTEEN WHERE CANTEENID = PCANTEENID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CANTEEN SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE CANTEENID = PCANTEENID;
    COMMIT;
    SELECT PCANTEENID AS CANTEENID;
END$$


CREATE PROCEDURE CMSDEACTCANTEEN (IN PCANTEENID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCANTEENID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CANTEEN WHERE CANTEENID = PCANTEENID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CANTEEN SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE CANTEENID = PCANTEENID;
    COMMIT;
    SELECT PCANTEENID AS CANTEENID;
END$$

CREATE PROCEDURE CMSGETCANTEEN (IN PCANTEENID INT)
BEGIN
    SELECT C.CANTEENID, C.CENTERID, CT.CENTERCODE, CT.CENTERNAME,
           C.CANTEENCODE, C.CANTEENNAME, C.LOCATION,
           C.STATUS, C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CANTEEN C
    JOIN   CMS_CENTER CT ON CT.CENTERID = C.CENTERID
    WHERE  C.CANTEENID = PCANTEENID;
END$$


CREATE PROCEDURE CMSLISTCANTEEN (IN PCENTERID INT)
BEGIN
    SELECT C.CANTEENID, C.CENTERID, CT.CENTERCODE, CT.CENTERNAME,
           C.CANTEENCODE, C.CANTEENNAME, C.LOCATION,
           C.STATUS, C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CANTEEN C
    JOIN   CMS_CENTER CT ON CT.CENTERID = C.CENTERID
    WHERE  (PCENTERID IS NULL OR C.CENTERID = PCENTERID)
    ORDER BY CT.CENTERNAME, C.CANTEENNAME;
END$$

/* ADDITIONAL */
CREATE PROCEDURE CMSSEARCHCANTEEN (IN PKEYWORD VARCHAR(120))
BEGIN
    SELECT C.CANTEENID, C.CENTERID, CT.CENTERCODE, CT.CENTERNAME,
           C.CANTEENCODE, C.CANTEENNAME, C.LOCATION,
           C.STATUS, C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CANTEEN C
    JOIN   CMS_CENTER CT ON CT.CENTERID = C.CENTERID
    WHERE  (C.CANTEENCODE LIKE CONCAT('%', PKEYWORD, '%')
       OR   C.CANTEENNAME LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY C.CANTEENNAME;
END$$





DELIMITER ;

