USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDCENTER;
DROP PROCEDURE IF EXISTS CMSUPDCENTER;
DROP PROCEDURE IF EXISTS CMSSEARCHCENTER;
DROP PROCEDURE IF EXISTS CMSACTCENTER;
DROP PROCEDURE IF EXISTS CMSDEACTCENTER;
DROP PROCEDURE IF EXISTS CMSGETCENTER;
DROP PROCEDURE IF EXISTS CMSLISTCENTER;

DELIMITER $$
/* ============================================================
   CMS_CENTER — ISRO Centre Master
   ============================================================ */

CREATE PROCEDURE CMSADDCENTER (
    IN PCENTERCODE VARCHAR(20),
    IN PCENTERNAME VARCHAR(120),
    IN PLOCATION   VARCHAR(150)
)
BEGIN
    DECLARE VCENTERID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERCODE IS NULL OR TRIM(PCENTERCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre Code is required';
    END IF;

    IF PCENTERNAME IS NULL OR TRIM(PCENTERNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre Name is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_CENTER (CENTERCODE, CENTERNAME, LOCATION)
    VALUES (TRIM(PCENTERCODE), TRIM(PCENTERNAME), PLOCATION);

    SET VCENTERID = LAST_INSERT_ID();
    COMMIT;

    SELECT VCENTERID AS CENTERID;
END$$


CREATE PROCEDURE CMSUPDCENTER (
    IN PCENTERID   INT,
    IN PCENTERNAME  VARCHAR(120),
    IN PLOCATION    VARCHAR(150),
    IN PSTATUS      VARCHAR(20)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT FROM CMS_CENTER WHERE CENTERID = PCENTERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre not found';
    END IF;

    IF PCENTERNAME IS NULL OR TRIM(PCENTERNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre Name is required';
    END IF;

    START TRANSACTION;

    UPDATE CMS_CENTER
    SET    CENTERNAME = TRIM(PCENTERNAME),
           LOCATION  = PLOCATION,
           STATUS    = COALESCE(PSTATUS, STATUS),
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  CENTERID  = PCENTERID;

    COMMIT;
    SELECT PCENTERID AS CENTERID;
END$$

CREATE PROCEDURE CMSACTCENTER (IN PCENTERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CENTER WHERE CENTERID = PCENTERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CENTER SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE CENTERID = PCENTERID;
    COMMIT;
    SELECT PCENTERID AS CENTERID;
END$$


CREATE PROCEDURE CMSDEACTCENTER (IN PCENTERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CENTER WHERE CENTERID = PCENTERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CENTER SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE CENTERID = PCENTERID;
    COMMIT;
    SELECT PCENTERID AS CENTERID;
END$$


CREATE PROCEDURE CMSGETCENTER (IN PCENTERID INT)
BEGIN
    SELECT CENTERID, CENTERCODE, CENTERNAME, LOCATION,
           STATUS, CREATEDAT, UPDATEDAT
    FROM   CMS_CENTER
    WHERE  CENTERID = PCENTERID;
END$$


CREATE PROCEDURE CMSLISTCENTER ()
BEGIN
    SELECT CENTERID, CENTERCODE, CENTERNAME, LOCATION,
           STATUS, CREATEDAT, UPDATEDAT
    FROM   CMS_CENTER
    ORDER BY CENTERNAME;
END$$


CREATE PROCEDURE CMSSEARCHCENTER (IN PKEYWORD VARCHAR(120))
BEGIN
    SELECT CENTERID, CENTERCODE, CENTERNAME, LOCATION,
           STATUS, CREATEDAT, UPDATEDAT
    FROM   CMS_CENTER
    WHERE  (CENTERCODE LIKE CONCAT('%', PKEYWORD, '%')
       OR   CENTERNAME LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY CENTERNAME;
END$$





DELIMITER ;

