USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDCUST;
DROP PROCEDURE IF EXISTS CMSUPDCUST;
DROP PROCEDURE IF EXISTS CMSGETCUST;
DROP PROCEDURE IF EXISTS CMSLISTCUST;
DROP PROCEDURE IF EXISTS CMSSEARCHCUST;
DROP PROCEDURE IF EXISTS CMSACTCUST;
DROP PROCEDURE IF EXISTS CMSDEACTCUST;
DROP PROCEDURE IF EXISTS CMSGETCUSTBYUSER;

DELIMITER $$
/* ============================================================
   CMS_CUSTOMER — Customer Identity
   ============================================================ */

CREATE PROCEDURE CMSADDCUST (
    IN PUSERID     INT,
    IN PCTYPECODE  VARCHAR(20),
    IN PDISPNAME   VARCHAR(120),
    IN PSTATUS     VARCHAR(20),
    IN PVALIDFROM  DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    DECLARE VCUSTOMERID INT;
    DECLARE VCTYPE INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCTYPECODE IS NULL OR TRIM(PCTYPECODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer Type Code is required';
    END IF;
    IF PDISPNAME IS NULL OR TRIM(PDISPNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Display Name is required';
    END IF;

    SELECT COUNT(*) INTO VCTYPE FROM CMS_CUSTTYPE WHERE CTYPECODE = PCTYPECODE AND ISACTIVE = 1;
    IF VCTYPE = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid or inactive Customer Type Code';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_CUSTOMER (USERID, CTYPECODE, DISPNAME, STATUS, VALIDFROM, VALIDUNTIL)
    VALUES (PUSERID, TRIM(PCTYPECODE), TRIM(PDISPNAME), COALESCE(PSTATUS, 'A'), PVALIDFROM, PVALIDUNTIL);
    SET VCUSTOMERID = LAST_INSERT_ID();
    COMMIT;

    SELECT VCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSUPDCUST (
    IN PCUSTOMERID INT,
    IN PDISPNAME   VARCHAR(120),
    IN PSTATUS     VARCHAR(20),
    IN PVALIDFROM  DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found';
    END IF;
    IF PDISPNAME IS NULL OR TRIM(PDISPNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Display Name is required';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CUSTOMER
    SET    DISPNAME   = TRIM(PDISPNAME),
           STATUS     = COALESCE(PSTATUS, STATUS),
           VALIDFROM  = COALESCE(PVALIDFROM, VALIDFROM),
           VALIDUNTIL = PVALIDUNTIL,
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  CUSTOMERID = PCUSTOMERID;
    COMMIT;

    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSGETCUST (IN PCUSTOMERID INT)
BEGIN
    SELECT C.CUSTOMERID, C.USERID, U.LOGINID, U.FULLNAME,
           C.CTYPECODE, CT.CTYPENAME, C.DISPNAME,
           C.STATUS, C.VALIDFROM, C.VALIDUNTIL,
           C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CUSTOMER C
    LEFT JOIN CMS_USER U     ON U.USERID   = C.USERID
    JOIN   CMS_CUSTTYPE CT   ON CT.CTYPECODE = C.CTYPECODE
    WHERE  C.CUSTOMERID = PCUSTOMERID;
END$$


CREATE PROCEDURE CMSLISTCUST (
    IN PCTYPECODE VARCHAR(20),
    IN PSTATUS    VARCHAR(20)
)
BEGIN
    SELECT C.CUSTOMERID, C.USERID, U.LOGINID, U.FULLNAME,
           C.CTYPECODE, CT.CTYPENAME, C.DISPNAME,
           C.STATUS, C.VALIDFROM, C.VALIDUNTIL,
           C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CUSTOMER C
    LEFT JOIN CMS_USER U     ON U.USERID   = C.USERID
    JOIN   CMS_CUSTTYPE CT   ON CT.CTYPECODE = C.CTYPECODE
    WHERE  (PCTYPECODE IS NULL OR C.CTYPECODE = PCTYPECODE)
      AND  (PSTATUS    IS NULL OR C.STATUS    = PSTATUS)
    ORDER BY C.DISPNAME;
END$$


CREATE PROCEDURE CMSSEARCHCUST (IN PKEYWORD VARCHAR(120))
BEGIN
    SELECT C.CUSTOMERID, C.USERID, U.LOGINID, U.FULLNAME,
           C.CTYPECODE, CT.CTYPENAME, C.DISPNAME,
           C.STATUS, C.VALIDFROM, C.VALIDUNTIL,
           C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CUSTOMER C
    LEFT JOIN CMS_USER U     ON U.USERID   = C.USERID
    JOIN   CMS_CUSTTYPE CT   ON CT.CTYPECODE = C.CTYPECODE
    WHERE  (C.DISPNAME LIKE CONCAT('%', PKEYWORD, '%')
       OR   U.FULLNAME LIKE CONCAT('%', PKEYWORD, '%')
       OR   U.LOGINID  LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY C.DISPNAME;
END$$


CREATE PROCEDURE CMSACTCUST (IN PCUSTOMERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PCUSTOMERID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found'; END IF;
    START TRANSACTION;
    UPDATE CMS_CUSTOMER SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE CUSTOMERID = PCUSTOMERID;
    COMMIT;
    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSDEACTCUST (IN PCUSTOMERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PCUSTOMERID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found'; END IF;
    START TRANSACTION;
    UPDATE CMS_CUSTOMER SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE CUSTOMERID = PCUSTOMERID;
    COMMIT;
    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


/* ============================================================
   CMSGETCUSTBYUSER — Lookup Customer by User ID
   Used by backend to check if a customer already exists
   for a given user before creating a new one.
   ============================================================ */

CREATE PROCEDURE CMSGETCUSTBYUSER (IN PUSERID INT)
BEGIN
    SELECT C.CUSTOMERID, C.USERID, C.CTYPECODE, C.DISPNAME,
           C.STATUS, C.VALIDFROM, C.VALIDUNTIL,
           C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CUSTOMER C
    WHERE  C.USERID = PUSERID;
END$$



DELIMITER ;

