USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDDMENU;
DROP PROCEDURE IF EXISTS CMSUPDDDMENU;
DROP PROCEDURE IF EXISTS CMSGETDMENU;
DROP PROCEDURE IF EXISTS CMSLISTDMENU;
DROP PROCEDURE IF EXISTS CMSAPPDMENU;
DROP PROCEDURE IF EXISTS CMSREJDMENU;
DROP PROCEDURE IF EXISTS CMSACTDMENU;
DROP PROCEDURE IF EXISTS CMSDEACTDMENU;
DROP PROCEDURE IF EXISTS CMSVIEWMENU;

DELIMITER $$


/* ============================================================
   CMS_DAYMENU — Day Menu Items
   ============================================================ */

    -- NOTE: DMENUNO is now generated directly (LPAD of DAYMENUID) instead of
    -- via CMSGENAUTO, because no CMS_AUTONOS seed row exists for
    -- ('CMS_DAYMENU','DMENUNO') in the current schema/data. If you seed one,
    -- swap the SET VDMENUNO line back to CALL CMSGENAUTO(...).

CREATE PROCEDURE CMSADDDMENU (
    IN PDAYSLOTID  INT,
    IN PMENUITEMID INT,
    IN PISSPECIAL  TINYINT,
    IN PISPREBOOK  TINYINT,
    IN PISKIOSK    TINYINT,
    IN PAVAILQTY   INT,
    IN PMAXQTY     INT,
    IN PBOOKUNTIL   DATETIME,
    IN PCANCELUNTIL DATETIME,
    IN PCREATEDBY  INT,
    IN PREMARKS    VARCHAR(255)
)
BEGIN
    DECLARE VDMENUNO    VARCHAR(20);
    DECLARE VDAYMENUID  INT;
    DECLARE VSLOTSTATUS VARCHAR(20);
    DECLARE VMENUSTATUS VARCHAR(20);
    DECLARE VSERVDATE   DATE;
    DECLARE VSTARTTIME  TIME;
    DECLARE VEXISTS     INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PDAYSLOTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required'; END IF;
    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    IF PBOOKUNTIL IS NULL OR PCANCELUNTIL IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking-until and cancel-until deadlines are required';
    END IF;
    IF PCANCELUNTIL > PBOOKUNTIL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cancel-until must be on or before booking-until';
    END IF;
    IF PAVAILQTY IS NULL OR PAVAILQTY < 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Available quantity must be >= 0'; END IF;
    IF PMAXQTY IS NULL OR PMAXQTY < 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Maximum quantity must be >= 1'; END IF;
    IF PCREATEDBY IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Created By is required'; END IF;

    IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) OR COALESCE(PISPREBOOK, 1) NOT IN (0, 1)
       OR COALESCE(PISKIOSK, 1) NOT IN (0, 1) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid day menu channel flag';
    END IF;

    SELECT STATUS, SERVDATE, STARTTIME INTO VSLOTSTATUS, VSERVDATE, VSTARTTIME
    FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    IF VSLOTSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
    IF VSLOTSTATUS <> 'A' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot must be active'; END IF;

    SELECT STATUS INTO VMENUSTATUS FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VMENUSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;
    IF VMENUSTATUS <> 'A' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item must be active'; END IF;

    IF PCANCELUNTIL > TIMESTAMP(VSERVDATE, VSTARTTIME) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cancel-until deadline must be before service begins';
    END IF;

    SELECT COUNT(*) INTO VEXISTS FROM CMS_DAYMENU WHERE DAYSLOTID = PDAYSLOTID AND MENUITEMID = PMENUITEMID;
    IF VEXISTS > 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item is already assigned to this day slot'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_DAYMENU (DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           BOOKUNTIL, CANCELUNTIL, AVAILQTY, MAXQTY, STATUS, APPRSTATUS, CREATEDBY, REMARKS)
    VALUES (PDAYSLOTID, PMENUITEMID, COALESCE(PISSPECIAL, 0), COALESCE(PISPREBOOK, 1),
           COALESCE(PISKIOSK, 1), PBOOKUNTIL, PCANCELUNTIL, PAVAILQTY, PMAXQTY,
           'A', 'PEN', PCREATEDBY, PREMARKS);

    SET VDAYMENUID = LAST_INSERT_ID();
    SET VDMENUNO = CONCAT('DM', LPAD(VDAYMENUID, 8, '0'));

    UPDATE CMS_DAYMENU SET DMENUNO = VDMENUNO WHERE DAYMENUID = VDAYMENUID;

    COMMIT;

    SELECT VDAYMENUID AS DAYMENUID, VDMENUNO AS DMENUNO;
END$$


CREATE PROCEDURE CMSUPDDDMENU (
    IN PDAYMENUID   INT,
    IN PAVAILQTY    INT,
    IN PMAXQTY      INT,
    IN PBOOKUNTIL   DATETIME,
    IN PCANCELUNTIL DATETIME,
    IN PISSPECIAL   TINYINT,
    IN PISPREBOOK   TINYINT,
    IN PISKIOSK     TINYINT,
    IN PREMARKS     VARCHAR(255),
    IN PCHANGEDBY   INT,
    IN PCHGREASON   VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE VNEWBOOKUNTIL DATETIME;
    DECLARE VNEWCANCELUNTIL DATETIME;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PDAYMENUID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found'; END IF;

    SELECT COALESCE(PBOOKUNTIL, BOOKUNTIL), COALESCE(PCANCELUNTIL, CANCELUNTIL)
    INTO VNEWBOOKUNTIL, VNEWCANCELUNTIL
    FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;

    IF VNEWCANCELUNTIL > VNEWBOOKUNTIL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cancel-until must be on or before booking-until';
    END IF;

    START TRANSACTION;

    -- CMS_DMENUHIST has no BOOKUNTIL/CANCELUNTIL columns, so only the
    -- fields it actually tracks are copied.
    INSERT INTO CMS_DMENUHIST (DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, STATUS, APPRSTATUS, CHANGEDBY, CHGREASON, REMARKS)
    SELECT DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, STATUS, APPRSTATUS, PCHANGEDBY, PCHGREASON, REMARKS
    FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;

    UPDATE CMS_DAYMENU
    SET    AVAILQTY    = COALESCE(PAVAILQTY, AVAILQTY),
           MAXQTY      = COALESCE(PMAXQTY, MAXQTY),
           BOOKUNTIL   = COALESCE(PBOOKUNTIL, BOOKUNTIL),
           CANCELUNTIL = COALESCE(PCANCELUNTIL, CANCELUNTIL),
           ISSPECIAL   = COALESCE(PISSPECIAL, ISSPECIAL),
           ISPREBOOK   = COALESCE(PISPREBOOK, ISPREBOOK),
           ISKIOSK     = COALESCE(PISKIOSK, ISKIOSK),
           REMARKS     = COALESCE(PREMARKS, REMARKS),
           UPDATEDAT   = CURRENT_TIMESTAMP
    WHERE  DAYMENUID   = PDAYMENUID;
    -- TRG_DAYMENU_APPR_RESET will reset APPRSTATUS to 'PEN' if it was 'APP'
    -- and AVAILQTY/MAXQTY/ISSPECIAL/ISPREBOOK/ISKIOSK changed.

    COMMIT;
    SELECT PDAYMENUID AS DAYMENUID;
END$$


CREATE PROCEDURE CMSGETDMENU (IN PDAYMENUID INT)
BEGIN
    SELECT DM.DAYMENUID, DM.DMENUNO, DM.DAYSLOTID,
           DS.SERVDATE, DS.STARTTIME, DS.ENDTIME,
           S.SERVICEID, S.SERVCODE, S.SERVNAME,
           DS.CANTEENID, C.CANTEENNAME,
           DM.MENUITEMID, MI.MENUCODE, MI.ITEMNAME, MI.SHORTNAME,
           DM.ISSPECIAL, DM.ISPREBOOK, DM.ISKIOSK,
           DM.AVAILQTY, DM.MAXQTY,
           DM.BOOKUNTIL, DM.CANCELUNTIL,
           DM.STATUS, DM.APPRSTATUS,
           DM.CREATEDBY, DM.APPROVEDBY, DM.APPROVEDAT,
           DM.REMARKS, DM.CREATEDAT, DM.UPDATEDAT
    FROM   CMS_DAYMENU DM
    JOIN   CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
    JOIN   CMS_SERVICE S  ON S.SERVICEID  = DS.SERVICEID
    JOIN   CMS_CANTEEN C  ON C.CANTEENID  = DS.CANTEENID
    JOIN   CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    WHERE  DM.DAYMENUID = PDAYMENUID;
END$$


CREATE PROCEDURE CMSLISTDMENU (
    IN PCANTEENID  INT,
    IN PSERVICEID  INT,
    IN PDAYSLOTID  INT,
    IN PSERVDATE   DATE,
    IN PAPPRSTATUS VARCHAR(20)
)
BEGIN
    SELECT DM.DAYMENUID, DM.DMENUNO, DM.DAYSLOTID,
           DS.SERVDATE, DS.STARTTIME, DS.ENDTIME,
           S.SERVICEID, S.SERVCODE, S.SERVNAME,
           DM.MENUITEMID, MI.MENUCODE, MI.ITEMNAME, MI.SHORTNAME,
           DM.ISSPECIAL, DM.ISPREBOOK, DM.ISKIOSK,
           DM.AVAILQTY, DM.MAXQTY,
           DM.BOOKUNTIL, DM.CANCELUNTIL,
           DM.STATUS, DM.APPRSTATUS,
           DM.CREATEDBY, DM.APPROVEDBY, DM.APPROVEDAT,
           DM.REMARKS
    FROM   CMS_DAYMENU DM
    JOIN   CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
    JOIN   CMS_SERVICE S  ON S.SERVICEID  = DS.SERVICEID
    JOIN   CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    WHERE  (PCANTEENID  IS NULL OR DS.CANTEENID   = PCANTEENID)
      AND  (PSERVICEID  IS NULL OR DS.SERVICEID   = PSERVICEID)
      AND  (PDAYSLOTID  IS NULL OR DM.DAYSLOTID   = PDAYSLOTID)
      AND  (PSERVDATE   IS NULL OR DS.SERVDATE     = PSERVDATE)
      AND  (PAPPRSTATUS IS NULL OR DM.APPRSTATUS   = PAPPRSTATUS)
    ORDER BY DS.SERVDATE, DS.STARTTIME, MI.ITEMNAME;
END$$


CREATE PROCEDURE CMSAPPDMENU (
    IN PDAYMENUID  INT,
    IN PAPPROVEDBY INT,
    IN PREMARKS    VARCHAR(255)
)
BEGIN
    DECLARE VCURRENTSTATUS VARCHAR(20);
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PDAYMENUID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required'; END IF;
    IF PAPPROVEDBY IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Approver ID is required'; END IF;

    SELECT APPRSTATUS INTO VCURRENTSTATUS FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;
    IF VCURRENTSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found'; END IF;
    IF VCURRENTSTATUS <> 'PEN' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu is not in Pending status'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_DMENUHIST (DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, STATUS, APPRSTATUS, CHANGEDBY, CHGREASON, REMARKS)
    SELECT DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, STATUS, APPRSTATUS, PAPPROVEDBY, 'Approved', REMARKS
    FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;

    UPDATE CMS_DAYMENU
    SET    APPRSTATUS = 'APP',
           APPROVEDBY = PAPPROVEDBY,
           APPROVEDAT = CURRENT_TIMESTAMP,
           REMARKS    = COALESCE(PREMARKS, REMARKS),
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  DAYMENUID  = PDAYMENUID;

    COMMIT;
    SELECT PDAYMENUID AS DAYMENUID;
END$$


CREATE PROCEDURE CMSREJDMENU (
    IN PDAYMENUID  INT,
    IN PREJECTEDBY INT,
    IN PREMARKS    VARCHAR(255)
)
BEGIN
    DECLARE VCURRENTSTATUS VARCHAR(20);
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PDAYMENUID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required'; END IF;
    IF PREJECTEDBY IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Rejector ID is required'; END IF;
    IF PREMARKS IS NULL OR TRIM(PREMARKS) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Rejection remarks are required';
    END IF;

    SELECT APPRSTATUS INTO VCURRENTSTATUS FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;
    IF VCURRENTSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found'; END IF;
    IF VCURRENTSTATUS <> 'PEN' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu is not in Pending status'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_DMENUHIST (DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, STATUS, APPRSTATUS, CHANGEDBY, CHGREASON, REMARKS)
    SELECT DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, STATUS, APPRSTATUS, PREJECTEDBY, 'Rejected', REMARKS
    FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;

    UPDATE CMS_DAYMENU
    SET    APPRSTATUS = 'REJ',
           APPROVEDBY = PREJECTEDBY,
           APPROVEDAT = CURRENT_TIMESTAMP,
           REMARKS    = PREMARKS,
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  DAYMENUID  = PDAYMENUID;

    COMMIT;
    SELECT PDAYMENUID AS DAYMENUID;
END$$




CREATE PROCEDURE CMSACTDMENU (IN PDAYMENUID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PDAYMENUID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found'; END IF;
    START TRANSACTION;
    UPDATE CMS_DAYMENU SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE DAYMENUID = PDAYMENUID;
    COMMIT;
    SELECT PDAYMENUID AS DAYMENUID;
END$$


CREATE PROCEDURE CMSDEACTDMENU (IN PDAYMENUID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PDAYMENUID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found'; END IF;
    START TRANSACTION;
    UPDATE CMS_DAYMENU SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE DAYMENUID = PDAYMENUID;
    COMMIT;
    SELECT PDAYMENUID AS DAYMENUID;
END$$






/* ============================================================
   CMSVIEWMENU — Published Menu View (Customer-facing)

   Rewritten for new pricing model:
   - Price resolved via CMS_ITEMPRICE + CMS_ITEMPRICEDT
   - CANTEENID filter (required)
   ============================================================ */

CREATE PROCEDURE CMSVIEWMENU (
    IN PCANTEENID INT,
    IN PSERVDATE  DATE,
    IN PCTYPECODE VARCHAR(20)
)
BEGIN
    SELECT
        DS.CANTEENID,
        C.CANTEENNAME,
        DS.DAYSLOTID,
        S.SERVICEID,
        S.SERVCODE,
        S.SERVNAME,
        DS.SERVDATE,
        DS.STARTTIME,
        DS.ENDTIME,
        DM.DAYMENUID,
        DM.DMENUNO,
        MI.MENUITEMID,
        MI.MENUCODE,
        MI.SHORTNAME,
        MI.ITEMNAME,
        MI.ITEMDESCR,
        DM.ISSPECIAL,
        DM.ISPREBOOK,
        DM.ISKIOSK,
        DM.AVAILQTY,
        DM.MAXQTY,
        DM.BOOKUNTIL,
        DM.CANCELUNTIL,
        (
            SELECT IPD.PRICE
            FROM   CMS_ITEMPRICE IP
            JOIN   CMS_ITEMPRICEDT IPD ON IPD.ITEMPRICEID = IP.ITEMPRICEID
            WHERE  IP.MENUITEMID  = MI.MENUITEMID
              AND  IP.EFFFROM    <= DS.SERVDATE
              AND  IP.STATUS      = 'A'
              AND  (IPD.CTYPECODE = PCTYPECODE OR IPD.CTYPECODE = 'VISITOR')
            ORDER BY 
              IP.EFFFROM DESC,
              CASE WHEN IPD.CTYPECODE = PCTYPECODE THEN 1 ELSE 2 END
            LIMIT 1
        ) AS DISPLAYPRICE
    FROM CMS_DAYMENU DM
    JOIN CMS_DAYSLOT DS  ON DS.DAYSLOTID  = DM.DAYSLOTID
    JOIN CMS_SERVICE S   ON S.SERVICEID   = DS.SERVICEID
    JOIN CMS_CANTEEN C   ON C.CANTEENID   = DS.CANTEENID
    JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    WHERE DS.CANTEENID  = PCANTEENID
      AND DS.SERVDATE  = PSERVDATE
      AND DM.APPRSTATUS = 'APP'
      AND DM.STATUS     = 'A'
      AND DS.STATUS     = 'A'
      AND S.STATUS      = 'A'
      AND MI.STATUS     = 'A'
      AND CURRENT_TIMESTAMP <= DM.BOOKUNTIL
    ORDER BY DS.STARTTIME, S.SERVNAME, MI.ITEMNAME;
END$$

DELIMITER ;
