USE cms_db;

/* --- Drop existing procedures --- */
DROP PROCEDURE IF EXISTS CMSADDSLOT;
DROP PROCEDURE IF EXISTS CMSUPDSLOT;
DROP PROCEDURE IF EXISTS CMSGETSLOT;
DROP PROCEDURE IF EXISTS CMSLISTSLOT;
DROP PROCEDURE IF EXISTS CMSACTSLOT;
DROP PROCEDURE IF EXISTS CMSDEACTSLOT;

DELIMITER $$

/* ============================================================
   CMS_DAYSLOT — Dated Service Instance
   ============================================================ */

CREATE PROCEDURE CMSADDSLOT (
    IN PCANTEENID INT,
    IN PSERVICEID INT,
    IN PSERVDATE  DATE,
    IN PSTARTTIME TIME,
    IN PENDTIME   TIME,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VSERVSTATUS VARCHAR(20);
    DECLARE VDAYSLOTID  INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCANTEENID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required'; END IF;
    IF PSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required'; END IF;
    IF PSERVDATE IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service Date is required'; END IF;
    IF PSTARTTIME IS NULL OR PENDTIME IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Slot start and end time are required'; END IF;
    IF PENDTIME <= PSTARTTIME THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Slot end time must be after start time'; END IF;

    SELECT STATUS INTO VSERVSTATUS
    FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;
    IF VSERVSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service not found'; END IF;
    IF VSERVSTATUS <> 'A' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service must be active'; END IF;
    -- NOTE: CMS_SERVICE no longer has VALIDFROM/VALIDUNTIL, so the
    -- service-validity-window check has been removed here.

    START TRANSACTION;
    INSERT INTO CMS_DAYSLOT (CANTEENID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CREATEDBY)
    VALUES (PCANTEENID, PSERVICEID, PSERVDATE, PSTARTTIME, PENDTIME, 'A', PCREATEDBY);
    SET VDAYSLOTID = LAST_INSERT_ID();
    COMMIT;

    SELECT VDAYSLOTID AS DAYSLOTID;
END$$


CREATE PROCEDURE CMSUPDSLOT (
    IN PDAYSLOTID INT,
    IN PSTARTTIME TIME,
    IN PENDTIME   TIME,
    IN PSTATUS    VARCHAR(20),
    IN PCHANGEDBY INT,
    IN PCHGREASON VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PDAYSLOTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
    IF PSTARTTIME IS NULL OR PENDTIME IS NULL OR PENDTIME <= PSTARTTIME THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Slot end time must be after start time';
    END IF;
    IF PSTATUS IS NULL OR PSTATUS NOT IN ('A', 'D', 'EXP', 'BLK') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid day slot status';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_SLOTHIST (DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CHANGEDBY, CHGREASON)
    SELECT DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;

    UPDATE CMS_DAYSLOT
    SET    STARTTIME = PSTARTTIME, ENDTIME = PENDTIME, STATUS = PSTATUS, UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  DAYSLOTID = PDAYSLOTID;
    COMMIT;

    SELECT PDAYSLOTID AS DAYSLOTID;
END$$


CREATE PROCEDURE CMSGETSLOT (IN PDAYSLOTID INT)
BEGIN
    SELECT DS.DAYSLOTID, DS.SERVICEID, S.SERVCODE, S.SERVNAME,
           DS.CANTEENID, C.CANTEENNAME,
           DS.SERVDATE, DS.STARTTIME, DS.ENDTIME, DS.STATUS,
           DS.CREATEDBY, DS.CREATEDAT, DS.UPDATEDAT
    FROM   CMS_DAYSLOT DS
    JOIN   CMS_SERVICE S  ON S.SERVICEID = DS.SERVICEID
    JOIN   CMS_CANTEEN C  ON C.CANTEENID = DS.CANTEENID
    WHERE  DS.DAYSLOTID = PDAYSLOTID;
END$$


DROP PROCEDURE IF EXISTS CMSLISTSLOT$$
CREATE PROCEDURE CMSLISTSLOT (
    IN PSERVICEID INT,
    IN PCANTEENID INT,
    IN PDATEFROM  DATE,
    IN PDATETO    DATE
)
BEGIN
    SELECT DS.DAYSLOTID, DS.SERVICEID, S.SERVNAME,
           DS.CANTEENID, C.CANTEENNAME,
           DS.SERVDATE, DS.STARTTIME, DS.ENDTIME,
           DS.STATUS, DS.CREATEDBY
    FROM   CMS_DAYSLOT DS
    JOIN   CMS_SERVICE S  ON S.SERVICEID = DS.SERVICEID
    JOIN   CMS_CANTEEN C  ON C.CANTEENID = DS.CANTEENID
    WHERE  (PSERVICEID IS NULL OR DS.SERVICEID   = PSERVICEID)
      AND  (PCANTEENID IS NULL OR DS.CANTEENID   = PCANTEENID)
      AND  (PDATEFROM  IS NULL OR DS.SERVDATE   >= PDATEFROM)
      AND  (PDATETO    IS NULL OR DS.SERVDATE   <= PDATETO)
    ORDER BY DS.SERVDATE, DS.STARTTIME;
END$$


CREATE PROCEDURE CMSACTSLOT (IN PDAYSLOTID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PDAYSLOTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
    START TRANSACTION;
    INSERT INTO CMS_SLOTHIST (DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CHANGEDBY, CHGREASON)
    SELECT DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, PCHANGEDBY, PCHGREASON FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    UPDATE CMS_DAYSLOT SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE DAYSLOTID = PDAYSLOTID;
    COMMIT;
    SELECT PDAYSLOTID AS DAYSLOTID;
END$$


CREATE PROCEDURE CMSDEACTSLOT (IN PDAYSLOTID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PDAYSLOTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
    START TRANSACTION;
    INSERT INTO CMS_SLOTHIST (DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CHANGEDBY, CHGREASON)
    SELECT DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, PCHANGEDBY, PCHGREASON FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    UPDATE CMS_DAYSLOT SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE DAYSLOTID = PDAYSLOTID;
    COMMIT;
    SELECT PDAYSLOTID AS DAYSLOTID;
END$$


DELIMITER ;