
USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDMENUITEM;
DROP PROCEDURE IF EXISTS CMSUPDMENUITEM;
DROP PROCEDURE IF EXISTS CMSGETMENUITEM;
DROP PROCEDURE IF EXISTS CMSLISTMENUITEM;
DROP PROCEDURE IF EXISTS CMSSEARCHMENUITEM;
DROP PROCEDURE IF EXISTS CMSACTMENUITEM;
DROP PROCEDURE IF EXISTS CMSDEACTMENUITEM;

DROP PROCEDURE IF EXISTS CMSADDITEMPRICE;
DROP PROCEDURE IF EXISTS CMSGETITEMPRICE;
DROP PROCEDURE IF EXISTS CMSGETITEMPRICEDT;
DROP PROCEDURE IF EXISTS CMSLISTITEMPRICE;
DROP PROCEDURE IF EXISTS CMSDEACTITEMPRICE;


DELIMITER $$


/* ============================================================
   CMS_MENUITEM — Shared Menu Item Catalog (NO price columns)
   ============================================================ */

CREATE PROCEDURE CMSADDMENUITEM (
    IN PMENUCODE  VARCHAR(20),
    IN PSHORTNAME VARCHAR(30),
    IN PITEMNAME  VARCHAR(100),
    IN PITEMDESCR VARCHAR(255),
    IN PISSPECIAL TINYINT,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VMENUITEMID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUCODE IS NULL OR TRIM(PMENUCODE) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Code is required'; END IF;
    IF PSHORTNAME IS NULL OR TRIM(PSHORTNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Short Name is required'; END IF;
    IF PITEMNAME IS NULL OR TRIM(PITEMNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Name is required'; END IF;
    IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid special item flag'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUITEM (MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, CREATEDBY)
    VALUES (TRIM(PMENUCODE), TRIM(PSHORTNAME), TRIM(PITEMNAME), PITEMDESCR, COALESCE(PISSPECIAL, 0), 'A', PCREATEDBY);
    SET VMENUITEMID = LAST_INSERT_ID();
    COMMIT;

    SELECT VMENUITEMID AS MENUITEMID;
END$$


CREATE PROCEDURE CMSUPDMENUITEM (
    IN PMENUITEMID INT,
    IN PSHORTNAME  VARCHAR(30),
    IN PITEMNAME   VARCHAR(100),
    IN PITEMDESCR  VARCHAR(255),
    IN PISSPECIAL  TINYINT,
    IN PSTATUS     VARCHAR(20),
    IN PCHANGEDBY  INT,
    IN PCHGREASON  VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;
    IF PSHORTNAME IS NULL OR TRIM(PSHORTNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Short Name is required'; END IF;
    IF PITEMNAME IS NULL OR TRIM(PITEMNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Name is required'; END IF;
    IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid special item flag'; END IF;
    IF PSTATUS IS NULL OR PSTATUS NOT IN ('A', 'D', 'EXP', 'BLK') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid menu item status'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_MENUHIST (MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;

    UPDATE CMS_MENUITEM
    SET    SHORTNAME = TRIM(PSHORTNAME),
           ITEMNAME  = TRIM(PITEMNAME),
           ITEMDESCR = PITEMDESCR,
           ISSPECIAL = COALESCE(PISSPECIAL, ISSPECIAL),
           STATUS    = PSTATUS,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  MENUITEMID = PMENUITEMID;
    COMMIT;

    SELECT PMENUITEMID AS MENUITEMID;
END$$


CREATE PROCEDURE CMSGETMENUITEM (IN PMENUITEMID INT)
BEGIN
    SELECT MI.MENUITEMID, MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           MI.ITEMDESCR, MI.ISSPECIAL, MI.STATUS,
           MI.CREATEDBY, MI.CREATEDAT, MI.UPDATEDAT
    FROM   CMS_MENUITEM MI
    WHERE  MI.MENUITEMID = PMENUITEMID;
END$$


CREATE PROCEDURE CMSLISTMENUITEM (
    IN PISSPECIAL TINYINT,
    IN PSTATUS    VARCHAR(20)
)
BEGIN
    SELECT MI.MENUITEMID, MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           MI.ITEMDESCR, MI.ISSPECIAL, MI.STATUS,
           MI.CREATEDBY, MI.CREATEDAT, MI.UPDATEDAT
    FROM   CMS_MENUITEM MI
    WHERE  (PISSPECIAL IS NULL OR MI.ISSPECIAL = PISSPECIAL)
      AND  (PSTATUS    IS NULL OR MI.STATUS    = PSTATUS)
    ORDER BY MI.ITEMNAME;
END$$


CREATE PROCEDURE CMSSEARCHMENUITEM (IN PKEYWORD VARCHAR(100))
BEGIN
    SELECT MI.MENUITEMID, MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           MI.ISSPECIAL, MI.STATUS
    FROM   CMS_MENUITEM MI
    WHERE  (MI.MENUCODE  LIKE CONCAT('%', PKEYWORD, '%')
       OR   MI.SHORTNAME LIKE CONCAT('%', PKEYWORD, '%')
       OR   MI.ITEMNAME  LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY MI.ITEMNAME;
END$$


CREATE PROCEDURE CMSACTMENUITEM (IN PMENUITEMID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUHIST (MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    UPDATE CMS_MENUITEM SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE MENUITEMID = PMENUITEMID;
    COMMIT;
    SELECT PMENUITEMID AS MENUITEMID;
END$$


CREATE PROCEDURE CMSDEACTMENUITEM (IN PMENUITEMID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUHIST (MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    UPDATE CMS_MENUITEM SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE MENUITEMID = PMENUITEMID;
    COMMIT;
    SELECT PMENUITEMID AS MENUITEMID;
END$$


/* ============================================================
   CMS_ITEMPRICE + CMS_ITEMPRICEDT — Pricing Subsystem

   CMSADDITEMPRICE creates a price band header + one detail
   row per customer type in a single JSON array.

   PPRICEJSON shape:
     [{"CTYPECODE":"PERMANENT","PRICE":60.00},
      {"CTYPECODE":"CONTRACT","PRICE":80.00}, ...]
   ============================================================ */

CREATE PROCEDURE CMSADDITEMPRICE (
    IN PMENUITEMID INT,
    IN PEFFFROM    DATE,
    IN PPRICEJSON  JSON,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VITEMPRICEID INT;
    DECLARE VCOUNT       INT DEFAULT 0;
    DECLARE VINVALID     INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    IF PEFFFROM IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Effective From date is required'; END IF;
    IF PPRICEJSON IS NULL OR JSON_TYPE(PPRICEJSON) <> 'ARRAY' OR JSON_LENGTH(PPRICEJSON) = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'At least one price entry is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID AND STATUS = 'A';
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Active menu item not found'; END IF;

    -- Validate all customer type codes exist
    SELECT COUNT(*) INTO VINVALID
    FROM JSON_TABLE(PPRICEJSON, '$[*]' COLUMNS (
        CTYPECODE VARCHAR(20) PATH '$.CTYPECODE',
        PRICE DECIMAL(10,2) PATH '$.PRICE'
    )) JT
    LEFT JOIN CMS_CUSTTYPE CT ON CT.CTYPECODE = JT.CTYPECODE AND CT.ISACTIVE = 1
    WHERE CT.CTYPEID IS NULL OR JT.PRICE IS NULL OR JT.PRICE < 0;

    IF VINVALID > 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'One or more price entries have invalid customer type or negative price';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_ITEMPRICE (MENUITEMID, EFFFROM, STATUS, CREATEDBY)
    VALUES (PMENUITEMID, PEFFFROM, 'A', PCREATEDBY);
    SET VITEMPRICEID = LAST_INSERT_ID();

    INSERT INTO CMS_ITEMPRICEDT (ITEMPRICEID, CTYPECODE, PRICE)
    SELECT VITEMPRICEID, JT.CTYPECODE, JT.PRICE
    FROM JSON_TABLE(PPRICEJSON, '$[*]' COLUMNS (
        CTYPECODE VARCHAR(20) PATH '$.CTYPECODE',
        PRICE DECIMAL(10,2) PATH '$.PRICE'
    )) JT;

    COMMIT;
    SELECT VITEMPRICEID AS ITEMPRICEID;
END$$


CREATE PROCEDURE CMSGETITEMPRICE (
    IN PMENUITEMID  INT,
    IN PSERVICEDATE DATE
)
BEGIN
    DECLARE VEFFDATE DATE;

    SET VEFFDATE = COALESCE(PSERVICEDATE, CURRENT_DATE);

    SELECT IP.ITEMPRICEID, IP.MENUITEMID, IP.EFFFROM, IP.STATUS,
           IPD.ITEMPRICEDTID, IPD.CTYPECODE, CT.CTYPENAME, IPD.PRICE
    FROM   CMS_ITEMPRICE IP
    JOIN   CMS_ITEMPRICEDT IPD ON IPD.ITEMPRICEID = IP.ITEMPRICEID
    JOIN   CMS_CUSTTYPE CT     ON CT.CTYPECODE    = IPD.CTYPECODE
    WHERE  IP.MENUITEMID = PMENUITEMID
      AND  IP.EFFFROM   <= VEFFDATE
      AND  IP.STATUS     = 'A'
      AND  IP.ITEMPRICEID = (
          SELECT IP2.ITEMPRICEID
          FROM   CMS_ITEMPRICE IP2
          WHERE  IP2.MENUITEMID = PMENUITEMID
            AND  IP2.EFFFROM  <= VEFFDATE
            AND  IP2.STATUS    = 'A'
          ORDER BY IP2.EFFFROM DESC
          LIMIT 1
      )
    ORDER BY IPD.CTYPECODE;
END$$


CREATE PROCEDURE CMSGETITEMPRICEDT (
    IN PMENUITEMID  INT,
    IN PCTYPECODE   VARCHAR(20),
    IN PSERVICEDATE DATE
)
BEGIN
    SELECT IPD.PRICE
    FROM   CMS_ITEMPRICE IP
    JOIN   CMS_ITEMPRICEDT IPD ON IPD.ITEMPRICEID = IP.ITEMPRICEID
    WHERE  IP.MENUITEMID  = PMENUITEMID
      AND  IPD.CTYPECODE  = PCTYPECODE
      AND  IP.EFFFROM    <= COALESCE(PSERVICEDATE, CURRENT_DATE)
      AND  IP.STATUS      = 'A'
    ORDER BY IP.EFFFROM DESC
    LIMIT 1;
END$$


CREATE PROCEDURE CMSLISTITEMPRICE (IN PMENUITEMID INT)
BEGIN
    SELECT IP.ITEMPRICEID, IP.MENUITEMID, MI.MENUCODE, MI.ITEMNAME,
           IP.EFFFROM, IP.STATUS, IP.CREATEDBY, IP.CREATEDAT
    FROM   CMS_ITEMPRICE IP
    JOIN   CMS_MENUITEM MI ON MI.MENUITEMID = IP.MENUITEMID
    WHERE  IP.MENUITEMID = PMENUITEMID
    ORDER BY IP.EFFFROM DESC;
END$$


CREATE PROCEDURE CMSDEACTITEMPRICE (IN PITEMPRICEID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE VEFFFROM DATE;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PITEMPRICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Price ID is required'; END IF;
    SELECT COUNT(*), EFFFROM INTO VCOUNT, VEFFFROM FROM CMS_ITEMPRICE WHERE ITEMPRICEID = PITEMPRICEID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Price band not found'; END IF;
    IF VEFFFROM <= CURRENT_DATE THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot withdraw a price band that is already effective'; END IF;

    START TRANSACTION;
    UPDATE CMS_ITEMPRICE SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE ITEMPRICEID = PITEMPRICEID;
    COMMIT;
    SELECT PITEMPRICEID AS ITEMPRICEID;
END$$

DELIMITER ;