
USE cms_db;


DROP PROCEDURE IF EXISTS CMSADDMENUTPL;
DROP PROCEDURE IF EXISTS CMSUPDMENUTPL;
DROP PROCEDURE IF EXISTS CMSGETMENUTPL;
DROP PROCEDURE IF EXISTS CMSLISTMENUTPL;
DROP PROCEDURE IF EXISTS CMSDEACTMENUTPL;
DROP PROCEDURE IF EXISTS CMSADDMENUTPLDT;
DROP PROCEDURE IF EXISTS CMSREMOVEMENUTPLDT;
DROP PROCEDURE IF EXISTS CMSLISTMENUTPLDT;
DROP PROCEDURE IF EXISTS CMSAPPLYMENUTPL;

DELIMITER $$

/* ============================================================
   CMS_MENUTPL / CMS_MENUTPLDT — Menu Templates
   ============================================================ */

CREATE PROCEDURE CMSADDMENUTPL (
    IN PCANTEENID INT,
    IN PSERVICEID INT,
    IN PTPLNAME   VARCHAR(80),
    IN PWEEKDAY   TINYINT,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VMENUTPLID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCANTEENID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required'; END IF;
    IF PSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required'; END IF;
    IF PTPLNAME IS NULL OR TRIM(PTPLNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template Name is required'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUTPL (CANTEENID, SERVICEID, TPLNAME, WEEKDAY, STATUS, CREATEDBY)
    VALUES (PCANTEENID, PSERVICEID, TRIM(PTPLNAME), PWEEKDAY, 'A', PCREATEDBY);
    SET VMENUTPLID = LAST_INSERT_ID();
    COMMIT;
    SELECT VMENUTPLID AS MENUTPLID;
END$$


CREATE PROCEDURE CMSUPDMENUTPL (
    IN PMENUTPLID INT,
    IN PTPLNAME   VARCHAR(80),
    IN PWEEKDAY   TINYINT,
    IN PSTATUS    VARCHAR(20)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUTPLID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUTPL WHERE MENUTPLID = PMENUTPLID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template not found'; END IF;

    START TRANSACTION;
    UPDATE CMS_MENUTPL
    SET    TPLNAME   = COALESCE(PTPLNAME, TPLNAME),
           WEEKDAY   = PWEEKDAY,
           STATUS    = COALESCE(PSTATUS, STATUS),
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  MENUTPLID = PMENUTPLID;
    COMMIT;
    SELECT PMENUTPLID AS MENUTPLID;
END$$


CREATE PROCEDURE CMSGETMENUTPL (IN PMENUTPLID INT)
BEGIN
    SELECT T.MENUTPLID, T.CANTEENID, C.CANTEENNAME,
           T.SERVICEID, S.SERVCODE, S.SERVNAME,
           T.TPLNAME, T.WEEKDAY, T.STATUS,
           T.CREATEDBY, T.CREATEDAT, T.UPDATEDAT
    FROM   CMS_MENUTPL T
    JOIN   CMS_CANTEEN C ON C.CANTEENID = T.CANTEENID
    JOIN   CMS_SERVICE S ON S.SERVICEID = T.SERVICEID
    WHERE  T.MENUTPLID = PMENUTPLID;
END$$


CREATE PROCEDURE CMSLISTMENUTPL (IN PCANTEENID INT, IN PSERVICEID INT)
BEGIN
    SELECT T.MENUTPLID, T.CANTEENID, C.CANTEENNAME,
           T.SERVICEID, S.SERVCODE, S.SERVNAME,
           T.TPLNAME, T.WEEKDAY, T.STATUS
    FROM   CMS_MENUTPL T
    JOIN   CMS_CANTEEN C ON C.CANTEENID = T.CANTEENID
    JOIN   CMS_SERVICE S ON S.SERVICEID = T.SERVICEID
    WHERE  (PCANTEENID IS NULL OR T.CANTEENID = PCANTEENID)
      AND  (PSERVICEID IS NULL OR T.SERVICEID = PSERVICEID)
      AND  T.STATUS = 'A'
    ORDER BY T.TPLNAME;
END$$


CREATE PROCEDURE CMSDEACTMENUTPL (IN PMENUTPLID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUTPLID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUTPL WHERE MENUTPLID = PMENUTPLID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template not found'; END IF;
    START TRANSACTION;
    UPDATE CMS_MENUTPL SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE MENUTPLID = PMENUTPLID;
    COMMIT;
    SELECT PMENUTPLID AS MENUTPLID;
END$$


CREATE PROCEDURE CMSADDMENUTPLDT (
    IN PMENUTPLID   INT,
    IN PMENUITEMID  INT,
    IN PISSPECIAL   TINYINT,
    IN PISPREBOOK   TINYINT,
    IN PISKIOSK    TINYINT,
    IN PMAXQTY      INT,
    IN PDEFAVAILQTY INT
)
BEGIN
    DECLARE VMENUTPLDTID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUTPLID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template ID is required'; END IF;
    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUTPLDT (MENUTPLID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK, MAXQTY, DEFAVAILQTY)
    VALUES (PMENUTPLID, PMENUITEMID, COALESCE(PISSPECIAL, 0), COALESCE(PISPREBOOK, 1),
            COALESCE(PISKIOSK, 1), COALESCE(PMAXQTY, 1), COALESCE(PDEFAVAILQTY, 0));
    SET VMENUTPLDTID = LAST_INSERT_ID();
    COMMIT;
    SELECT VMENUTPLDTID AS MENUTPLDTID;
END$$


CREATE PROCEDURE CMSREMOVEMENUTPLDT (IN PMENUTPLDTID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUTPLDTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template Detail ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUTPLDT WHERE MENUTPLDTID = PMENUTPLDTID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template detail not found'; END IF;
    START TRANSACTION;
    DELETE FROM CMS_MENUTPLDT WHERE MENUTPLDTID = PMENUTPLDTID;
    COMMIT;
    SELECT PMENUTPLDTID AS MENUTPLDTID;
END$$


CREATE PROCEDURE CMSLISTMENUTPLDT (IN PMENUTPLID INT)
BEGIN
    SELECT TD.MENUTPLDTID, TD.MENUTPLID, TD.MENUITEMID,
           MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           TD.ISSPECIAL, TD.ISPREBOOK, TD.ISKIOSK,
           TD.MAXQTY, TD.DEFAVAILQTY
    FROM   CMS_MENUTPLDT TD
    JOIN   CMS_MENUITEM MI ON MI.MENUITEMID = TD.MENUITEMID
    WHERE  TD.MENUTPLID = PMENUTPLID
    ORDER BY MI.ITEMNAME;
END$$


/* ============================================================
   CMSAPPLYMENUTPL — Materialise a template into day-menu rows

   Creates the day slot if it doesn't exist, then inserts
   day-menu items from the template. Booking windows default
   to: BOOKSTART = previous day 06:00, BOOKEND = slot start - 1h,
   CANCELAT = slot start - 30min.  All can be overridden after.
   ============================================================ */

CREATE PROCEDURE CMSAPPLYMENUTPL (
    IN PMENUTPLID  INT,
    IN PTARGETDATE DATE,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VSERVICEID   INT;
    DECLARE VCANTEENID   INT;
    DECLARE VTPLSTATUS   VARCHAR(20);
    DECLARE VDEFSTART    TIME;
    DECLARE VDEFEND      TIME;
    DECLARE VDAYSLOTID   INT;
    DECLARE VITEMCOUNT   INT DEFAULT 0;
    DECLARE VINSERTED    INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUTPLID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template ID is required'; END IF;
    IF PTARGETDATE IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Target Date is required'; END IF;

    SELECT T.SERVICEID, T.CANTEENID, T.STATUS
    INTO   VSERVICEID, VCANTEENID, VTPLSTATUS
    FROM   CMS_MENUTPL T
    WHERE  T.MENUTPLID = PMENUTPLID;

    IF VSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template not found'; END IF;
    IF VTPLSTATUS <> 'A' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template is not active'; END IF;

    SELECT DEFSTART, DEFEND INTO VDEFSTART, VDEFEND
    FROM CMS_SERVICE WHERE SERVICEID = VSERVICEID;

    START TRANSACTION;

    -- Create or find existing day slot
    SELECT DAYSLOTID INTO VDAYSLOTID
    FROM CMS_DAYSLOT WHERE SERVICEID = VSERVICEID AND SERVDATE = PTARGETDATE;

    IF VDAYSLOTID IS NULL THEN
        INSERT INTO CMS_DAYSLOT (SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CREATEDBY)
        VALUES (VSERVICEID, PTARGETDATE, VDEFSTART, VDEFEND, 'A', PCREATEDBY);
        SET VDAYSLOTID = LAST_INSERT_ID();
    END IF;

    -- Insert template items as day menus (skip duplicates)
    INSERT INTO CMS_DAYMENU (DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, BOOKSTART, BOOKEND, CANCELAT, STATUS, APPRSTATUS, ADDEDBY)
    SELECT VDAYSLOTID, TD.MENUITEMID, TD.ISSPECIAL, TD.ISPREBOOK, TD.ISKIOSK,
           TD.DEFAVAILQTY, TD.MAXQTY,
           TIMESTAMP(DATE_SUB(PTARGETDATE, INTERVAL 1 DAY), '06:00:00'),
           TIMESTAMP(PTARGETDATE, SUBTIME(VDEFSTART, '01:00:00')),
           TIMESTAMP(PTARGETDATE, SUBTIME(VDEFSTART, '00:30:00')),
           'A', 'P', PCREATEDBY
    FROM   CMS_MENUTPLDT TD
    WHERE  TD.MENUTPLID = PMENUTPLID
      AND  NOT EXISTS (
          SELECT 1 FROM CMS_DAYMENU DM
          WHERE DM.DAYSLOTID = VDAYSLOTID AND DM.MENUITEMID = TD.MENUITEMID
      );

    SET VINSERTED = ROW_COUNT();

    COMMIT;

    SELECT VDAYSLOTID AS DAYSLOTID, VINSERTED AS ITEMSINSERTED;
END$$




DELIMITER ;