USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDROLE;
DROP PROCEDURE IF EXISTS CMSUPDROL;
DROP PROCEDURE IF EXISTS CMSGETROL;
DROP PROCEDURE IF EXISTS CMSACTROL;
DROP PROCEDURE IF EXISTS CMSDEACTROL;
DROP PROCEDURE IF EXISTS CMSLISTROL;

DELIMITER $$
/* ============================================================
   CMS_ROLE — Role Master
   ============================================================ */

CREATE PROCEDURE CMSADDROLE (
    IN PROLECODE VARCHAR(50),
    IN PROLENAME VARCHAR(100),
    IN PDESCR    VARCHAR(255)
)
BEGIN
    DECLARE VROLEID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PROLECODE IS NULL OR TRIM(PROLECODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role Code is required';
    END IF;
    IF PROLENAME IS NULL OR TRIM(PROLENAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role Name is required';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_ROLE (ROLECODE, ROLENAME, DESCR)
    VALUES (TRIM(PROLECODE), TRIM(PROLENAME), PDESCR);
    SET VROLEID = LAST_INSERT_ID();
    COMMIT;

    SELECT VROLEID AS ROLEID;
END$$


CREATE PROCEDURE CMSUPDROL (
    IN PROLEID   INT,
    IN PROLENAME VARCHAR(100),
    IN PDESCR    VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PROLEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_ROLE WHERE ROLEID = PROLEID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role not found';
    END IF;
    IF PROLENAME IS NULL OR TRIM(PROLENAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role Name is required';
    END IF;

    START TRANSACTION;
    UPDATE CMS_ROLE
    SET    ROLENAME  = TRIM(PROLENAME),
           DESCR     = PDESCR,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  ROLEID    = PROLEID;
    COMMIT;

    SELECT PROLEID AS ROLEID;
END$$

CREATE PROCEDURE CMSACTROL (IN PROLEID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PROLEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_ROLE WHERE ROLEID = PROLEID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_ROLE SET ISACTIVE = 1, UPDATEDAT = CURRENT_TIMESTAMP WHERE ROLEID = PROLEID;
    COMMIT;
    SELECT PROLEID AS ROLEID;
END$$

CREATE PROCEDURE CMSDEACTROL (IN PROLEID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PROLEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_ROLE WHERE ROLEID = PROLEID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_ROLE SET ISACTIVE = 0, UPDATEDAT = CURRENT_TIMESTAMP WHERE ROLEID = PROLEID;
    COMMIT;
    SELECT PROLEID AS ROLEID;
END$$

CREATE PROCEDURE CMSGETROL (IN PROLEID INT)
BEGIN
    SELECT ROLEID, ROLECODE, ROLENAME, DESCR,
           ISACTIVE, CREATEDAT, UPDATEDAT
    FROM   CMS_ROLE
    WHERE  ROLEID = PROLEID;
END$$


CREATE PROCEDURE CMSLISTROL ()
BEGIN
    SELECT ROLEID, ROLECODE, ROLENAME, DESCR,
           ISACTIVE, CREATEDAT, UPDATEDAT
    FROM   CMS_ROLE
    ORDER BY ROLECODE;
END$$






DELIMITER ;

