
USE cms_db;

/* --- Drop all existing procedures --- */
DROP PROCEDURE IF EXISTS CMSADDSERV;
DROP PROCEDURE IF EXISTS CMSUPDSERV;
DROP PROCEDURE IF EXISTS CMSGETSERV;
DROP PROCEDURE IF EXISTS CMSLISTSERV;
DROP PROCEDURE IF EXISTS CMSSEARCHSERV;
DROP PROCEDURE IF EXISTS CMSACTSERV;
DROP PROCEDURE IF EXISTS CMSDEACTSERV;


DELIMITER $$


/* ============================================================
   CMS_SERVICE — Canteen-scoped Service Catalog
   ============================================================ */

CREATE PROCEDURE CMSADDSERV (
    IN PSERVCODE  VARCHAR(20),
    IN PSERVNAME  VARCHAR(80),
    IN PDEFSTART  TIME,
    IN PDEFEND    TIME,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VSERVICEID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PSERVCODE IS NULL OR TRIM(PSERVCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service Code is required';
    END IF;
    IF PSERVNAME IS NULL OR TRIM(PSERVNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service Name is required';
    END IF;
    IF PDEFSTART IS NULL OR PDEFEND IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service default start and end time are required';
    END IF;
    IF PDEFEND <= PDEFSTART THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service end time must be after start time';
    END IF;
    IF PCREATEDBY IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Created By is required';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_SERVICE (SERVCODE, SERVNAME, DEFSTART, DEFEND, STATUS, CREATEDBY)
    VALUES (TRIM(PSERVCODE), TRIM(PSERVNAME), PDEFSTART, PDEFEND, 'A', PCREATEDBY);
    SET VSERVICEID = LAST_INSERT_ID();
    COMMIT;

    SELECT VSERVICEID AS SERVICEID;
END$$


CREATE PROCEDURE CMSUPDSERV (
    IN PSERVICEID INT,
    IN PSERVNAME  VARCHAR(80),
    IN PDEFSTART  TIME,
    IN PDEFEND    TIME,
    IN PSTATUS    VARCHAR(20),
    IN PCHANGEDBY INT,
    IN PCHGREASON VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service not found'; END IF;
    IF PSERVNAME IS NULL OR TRIM(PSERVNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service Name is required'; END IF;
    IF PDEFSTART IS NULL OR PDEFEND IS NULL OR PDEFEND <= PDEFSTART THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service end time must be after start time';
    END IF;
    IF PSTATUS IS NULL OR PSTATUS NOT IN ('A', 'D') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid service status';
    END IF;

    START TRANSACTION;

    -- History table has VALIDFROM/VALIDUNTIL columns (nullable) that no
    -- longer exist on CMS_SERVICE itself; they are simply left NULL here.
    INSERT INTO CMS_SERVHIST (SERVICEID, SERVCODE, SERVNAME, DEFSTART, DEFEND, VALIDFROM, VALIDUNTIL, STATUS, CHANGEDBY, CHGREASON)
    SELECT SERVICEID, SERVCODE, SERVNAME, DEFSTART, DEFEND, NULL, NULL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;

    UPDATE CMS_SERVICE
    SET    SERVNAME  = TRIM(PSERVNAME),
           DEFSTART  = PDEFSTART,
           DEFEND    = PDEFEND,
           STATUS    = PSTATUS,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  SERVICEID = PSERVICEID;

    COMMIT;
    SELECT PSERVICEID AS SERVICEID;
END$$


CREATE PROCEDURE CMSGETSERV (IN PSERVICEID INT)
BEGIN
    SELECT S.SERVICEID,
           S.SERVCODE, S.SERVNAME, S.DEFSTART, S.DEFEND,
           S.STATUS, S.CREATEDBY, S.CREATEDAT, S.UPDATEDAT
    FROM   CMS_SERVICE S
    WHERE  S.SERVICEID = PSERVICEID;
END$$


CREATE PROCEDURE CMSLISTSERV ()
BEGIN
    SELECT S.SERVICEID,
           S.SERVCODE, S.SERVNAME, S.DEFSTART, S.DEFEND,
           S.STATUS, S.CREATEDBY, S.CREATEDAT, S.UPDATEDAT
    FROM   CMS_SERVICE S
    ORDER BY S.DEFSTART;
END$$


CREATE PROCEDURE CMSACTSERV (IN PSERVICEID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service not found'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_SERVHIST (SERVICEID, SERVCODE, SERVNAME, DEFSTART, DEFEND, VALIDFROM, VALIDUNTIL, STATUS, CHANGEDBY, CHGREASON)
    SELECT SERVICEID, SERVCODE, SERVNAME, DEFSTART, DEFEND, NULL, NULL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;
    UPDATE CMS_SERVICE SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE SERVICEID = PSERVICEID;
    COMMIT;
    SELECT PSERVICEID AS SERVICEID;
END$$


CREATE PROCEDURE CMSDEACTSERV (IN PSERVICEID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service not found'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_SERVHIST (SERVICEID, SERVCODE, SERVNAME, DEFSTART, DEFEND, VALIDFROM, VALIDUNTIL, STATUS, CHANGEDBY, CHGREASON)
    SELECT SERVICEID, SERVCODE, SERVNAME, DEFSTART, DEFEND, NULL, NULL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;
    UPDATE CMS_SERVICE SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE SERVICEID = PSERVICEID;
    COMMIT;
    SELECT PSERVICEID AS SERVICEID;
END$$



CREATE PROCEDURE CMSSEARCHSERV (IN PKEYWORD VARCHAR(80))
BEGIN
    SELECT S.SERVICEID,
           S.SERVCODE, S.SERVNAME, S.STATUS
    FROM   CMS_SERVICE S
    WHERE  (S.SERVCODE LIKE CONCAT('%', PKEYWORD, '%')
       OR   S.SERVNAME LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY S.SERVNAME;
END$$



DELIMITER ;