DROP EVENT IF EXISTS EVT_CMS_DAILY_NOSHOW$$

CREATE EVENT EVT_CMS_DAILY_NOSHOW
ON SCHEDULE EVERY 1 DAY
STARTS (CURRENT_DATE + INTERVAL 1 DAY - INTERVAL 10 SECOND) -- 23:59:50 daily
ON COMPLETION PRESERVE
ENABLE
DO
BEGIN
    CALL CMSNOSHOWBOOK(CURDATE(), NULL, 1);
END$$
