/* ============================================================
   MODULE 0 STORED PROCEDURES
   ============================================================ */

USE cms_db;

DROP PROCEDURE IF EXISTS CMSGENAUTO;
DROP PROCEDURE IF EXISTS CMSADDSTATUS;
DROP PROCEDURE IF EXISTS CMSADDSCREEN;
DROP PROCEDURE IF EXISTS CMSSETROLESCN;

DELIMITER $$

CREATE PROCEDURE CMSGENAUTO (
    IN PTBLNAME VARCHAR(50),
    IN PDATAITEM VARCHAR(30),
    OUT PNEWNO VARCHAR(30)
)
BEGIN
    DECLARE VPREFIX VARCHAR(5);
    DECLARE VLASTNO BIGINT;
    DECLARE VNEWNO BIGINT;
    DECLARE VYEAR CHAR(4);
    DECLARE VLENGTH INT;

    START TRANSACTION;

    SELECT PREFIXCHAR, LASTNO, ITEMLEN
    INTO VPREFIX, VLASTNO, VLENGTH
    FROM CMS_AUTONOS
    WHERE TBLNAME = PTBLNAME
      AND DATAITEM = PDATAITEM
      AND STATUS = 'A'
    FOR UPDATE;

    SET VNEWNO = VLASTNO + 1;
    SET VYEAR = DATE_FORMAT(CURRENT_DATE, '%Y');
    SET PNEWNO = CONCAT(VPREFIX, VYEAR, LPAD(VNEWNO, GREATEST(VLENGTH - LENGTH(VPREFIX) - 4, 1), '0'));

    UPDATE CMS_AUTONOS
    SET LASTNO = VNEWNO,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE TBLNAME = PTBLNAME
      AND DATAITEM = PDATAITEM;

    COMMIT;
END$$

CREATE PROCEDURE CMSADDSTATUS (
    IN PSTATUSCODE VARCHAR(10),
    IN PSTATUSNAME VARCHAR(50),
    IN PSTATUSGRP VARCHAR(30),
    IN PDESCR VARCHAR(255)
)
BEGIN
    INSERT INTO CMS_STATUS (STATUSCODE, STATUSNAME, STATUSGRP, DESCR)
    VALUES (PSTATUSCODE, PSTATUSNAME, PSTATUSGRP, PDESCR);
END$$

CREATE PROCEDURE CMSADDSCREEN (
    IN PSCREENCODE VARCHAR(50),
    IN PSCREENNAME VARCHAR(100),
    IN PDESCR VARCHAR(255),
    IN PROUTEPATH VARCHAR(150),
    IN PCREATEDBY INT
)
BEGIN
    INSERT INTO CMS_SCREEN (SCREENCODE, SCREENNAME, DESCR, ROUTEPATH, CREATEDBY)
    VALUES (PSCREENCODE, PSCREENNAME, PDESCR, PROUTEPATH, PCREATEDBY);
END$$

CREATE PROCEDURE CMSSETROLESCN (
    IN PROLEID INT,
    IN PSCREENID INT,
    IN PCANVIEW TINYINT,
    IN PCANCREATE TINYINT,
    IN PCANUPDATE TINYINT,
    IN PCANDELETE TINYINT
)
BEGIN
    INSERT INTO CMS_ROLESCN (ROLEID, SCREENID, CANVIEW, CANCREATE, CANUPDATE, CANDELETE)
    VALUES (PROLEID, PSCREENID, PCANVIEW, PCANCREATE, PCANUPDATE, PCANDELETE)
    ON DUPLICATE KEY UPDATE
        CANVIEW = PCANVIEW,
        CANCREATE = PCANCREATE,
        CANUPDATE = PCANUPDATE,
        CANDELETE = PCANDELETE,
        ISACTIVE = 1,
        UPDATEDAT = CURRENT_TIMESTAMP;
END$$

DELIMITER ;
