/* ============================================================
   MODULE 1 STORED PROCEDURES
   ============================================================ */

USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDUSER;
DROP PROCEDURE IF EXISTS CMSADDROLE;
DROP PROCEDURE IF EXISTS CMSASSIGNROL;
DROP PROCEDURE IF EXISTS CMSADDCUST;
DROP PROCEDURE IF EXISTS CMSADDPERM;
DROP PROCEDURE IF EXISTS CMSADDCONT;
DROP PROCEDURE IF EXISTS CMSADDOCE;
DROP PROCEDURE IF EXISTS CMSADDVIS;
DROP PROCEDURE IF EXISTS CMSADDACCKEY;
DROP PROCEDURE IF EXISTS CMSADDAPPLVL;
DROP PROCEDURE IF EXISTS CMSLOGININFO;

DELIMITER $$

CREATE PROCEDURE CMSADDUSER (
    IN PLOGINID VARCHAR(50),
    IN PFULLNAME VARCHAR(120),
    IN PEMAIL VARCHAR(120),
    IN PMOBILENO VARCHAR(20),
    IN PPWDHASH VARCHAR(255),
    IN PAUTHPROV VARCHAR(20),
    IN PAUTHID VARCHAR(120)
)
BEGIN
    INSERT INTO CMS_USER (LOGINID, FULLNAME, EMAIL, MOBILENO, PWDHASH, AUTHPROV, AUTHID)
    VALUES (PLOGINID, PFULLNAME, PEMAIL, PMOBILENO, PPWDHASH, COALESCE(PAUTHPROV, 'LOCAL'), PAUTHID);

    SELECT LAST_INSERT_ID() AS USERID;
END$$

CREATE PROCEDURE CMSADDROLE (
    IN PROLECODE VARCHAR(50),
    IN PROLENAME VARCHAR(100),
    IN PDESCR VARCHAR(255)
)
BEGIN
    INSERT INTO CMS_ROLE (ROLECODE, ROLENAME, DESCR)
    VALUES (PROLECODE, PROLENAME, PDESCR);

    SELECT LAST_INSERT_ID() AS ROLEID;
END$$

CREATE PROCEDURE CMSASSIGNROL (
    IN PUSERID INT,
    IN PROLEID INT,
    IN PASSIGNEDBY INT,
    IN PVALIDFROM DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    INSERT INTO CMS_USRROLE (USERID, ROLEID, ASSIGNEDBY, VALIDFROM, VALIDUNTIL, ISACTIVE)
    VALUES (PUSERID, PROLEID, PASSIGNEDBY, COALESCE(PVALIDFROM, CURRENT_TIMESTAMP), PVALIDUNTIL, 1)
    ON DUPLICATE KEY UPDATE
        ASSIGNEDBY = PASSIGNEDBY,
        VALIDFROM = COALESCE(PVALIDFROM, CURRENT_TIMESTAMP),
        VALIDUNTIL = PVALIDUNTIL,
        ISACTIVE = 1,
        ASSIGNEDAT = CURRENT_TIMESTAMP;
END$$

CREATE PROCEDURE CMSADDCUST (
    IN PUSERID INT,
    IN PCTYPECODE VARCHAR(20),
    IN PDISPNAME VARCHAR(120),
    IN PSTATUS VARCHAR(20),
    IN PVALIDFROM DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    INSERT INTO CMS_CUSTOMER (USERID, CTYPECODE, DISPNAME, STATUS, VALIDFROM, VALIDUNTIL)
    VALUES (PUSERID, PCTYPECODE, PDISPNAME, COALESCE(PSTATUS, 'A'), PVALIDFROM, PVALIDUNTIL);

    SELECT LAST_INSERT_ID() AS CUSTOMERID;
END$$

CREATE PROCEDURE CMSADDPERM (
    IN PCUSTOMERID INT,
    IN PEMPCODE VARCHAR(50),
    IN PDEPT VARCHAR(100),
    IN PDESIG VARCHAR(100)
)
BEGIN
    INSERT INTO CMS_PERMEMP (CUSTOMERID, EMPCODE, DEPT, DESIG)
    VALUES (PCUSTOMERID, PEMPCODE, PDEPT, PDESIG);

    SELECT LAST_INSERT_ID() AS PERMEMPID;
END$$

CREATE PROCEDURE CMSADDCONT (
    IN PCUSTOMERID INT,
    IN PCONTCODE VARCHAR(50),
    IN PVENDORNAME VARCHAR(150),
    IN PCONTSTART DATE,
    IN PCONTEND DATE
)
BEGIN
    INSERT INTO CMS_CONTEMP (CUSTOMERID, CONTCODE, VENDORNAME, CONTSTART, CONTEND)
    VALUES (PCUSTOMERID, PCONTCODE, PVENDORNAME, PCONTSTART, PCONTEND);

    SELECT LAST_INSERT_ID() AS CONTEMPID;
END$$

CREATE PROCEDURE CMSADDOCE (
    IN PCUSTOMERID INT,
    IN PEMPCODE VARCHAR(50),
    IN PCENTRENAME VARCHAR(120),
    IN PDEPT VARCHAR(100),
    IN PDESIG VARCHAR(100),
    IN PVALIDFROM DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    INSERT INTO CMS_OCEEMP (CUSTOMERID, EMPCODE, CENTRENAME, DEPT, DESIG, VALIDFROM, VALIDUNTIL)
    VALUES (PCUSTOMERID, PEMPCODE, PCENTRENAME, PDEPT, PDESIG, PVALIDFROM, PVALIDUNTIL);

    SELECT LAST_INSERT_ID() AS OCEEMPID;
END$$

CREATE PROCEDURE CMSADDVIS (
    IN PCUSTOMERID INT,
    IN PVISNAME VARCHAR(120),
    IN PVISMOBILE VARCHAR(20),
    IN PVISORG VARCHAR(150),
    IN PVISPURPOSE VARCHAR(255),
    IN PVISDATE DATE,
    IN PVALIDUNTIL DATETIME,
    IN PCREATEDBY INT
)
BEGIN
    INSERT INTO CMS_VISITOR (CUSTOMERID, VISNAME, VISMOBILE, VISORG, VISPURPOSE, VISDATE, VALIDUNTIL, CREATEDBY, STATUS)
    VALUES (PCUSTOMERID, PVISNAME, PVISMOBILE, PVISORG, PVISPURPOSE, PVISDATE, PVALIDUNTIL, PCREATEDBY, 'A');

    SELECT LAST_INSERT_ID() AS VISITORID;
END$$

CREATE PROCEDURE CMSADDACCKEY (
    IN PCUSTOMERID INT,
    IN PKEYTYPE VARCHAR(30),
    IN PKEYVALUE VARCHAR(255),
    IN PEXPIRESAT DATETIME,
    IN PCREATEDBY INT
)
BEGIN
    INSERT INTO CMS_ACCKEY (CUSTOMERID, KEYTYPE, KEYVALUE, EXPIRESAT, STATUS, CREATEDBY)
    VALUES (PCUSTOMERID, PKEYTYPE, PKEYVALUE, PEXPIRESAT, 'A', PCREATEDBY);

    SELECT LAST_INSERT_ID() AS ACCKEYID;
END$$

CREATE PROCEDURE CMSADDAPPLVL (
    IN PLEVELNO INT,
    IN PLEVELNAME VARCHAR(100),
    IN PROLEID INT,
    IN PDESCR VARCHAR(255)
)
BEGIN
    INSERT INTO CMS_APPLVL (LEVELNO, LEVELNAME, ROLEID, DESCR)
    VALUES (PLEVELNO, PLEVELNAME, PROLEID, PDESCR);

    SELECT LAST_INSERT_ID() AS APPLVLID;
END$$

CREATE PROCEDURE CMSLOGININFO (
    IN PLOGINID VARCHAR(50)
)
BEGIN
    SELECT
        U.USERID,
        U.LOGINID,
        U.FULLNAME,
        U.EMAIL,
        U.MOBILENO,
        U.PWDHASH,
        U.AUTHPROV,
        U.ISACTIVE,
        C.CUSTOMERID,
        C.CTYPECODE,
        C.DISPNAME,
        GROUP_CONCAT(R.ROLECODE ORDER BY R.ROLECODE) AS ROLECODES
    FROM CMS_USER U
    LEFT JOIN CMS_CUSTOMER C ON C.USERID = U.USERID
    LEFT JOIN CMS_USRROLE UR ON UR.USERID = U.USERID AND UR.ISACTIVE = 1
    LEFT JOIN CMS_ROLE R ON R.ROLEID = UR.ROLEID AND R.ISACTIVE = 1
    WHERE U.LOGINID = PLOGINID
    GROUP BY U.USERID, U.LOGINID, U.FULLNAME, U.EMAIL, U.MOBILENO, U.PWDHASH, U.AUTHPROV, U.ISACTIVE, C.CUSTOMERID, C.CTYPECODE, C.DISPNAME;
END$$

DELIMITER ;
