/* ============================================================
   MODULE 2 STORED PROCEDURES
   ============================================================ */

USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDSERV;
DROP PROCEDURE IF EXISTS CMSUPDSERV;
DROP PROCEDURE IF EXISTS CMSADDMENU;
DROP PROCEDURE IF EXISTS CMSUPDMENU;
DROP PROCEDURE IF EXISTS CMSADDSLOT;
DROP PROCEDURE IF EXISTS CMSUPDSLOT;
DROP PROCEDURE IF EXISTS CMSADDDMENU;
DROP PROCEDURE IF EXISTS CMSAPPDMENU;
DROP PROCEDURE IF EXISTS CMSVIEWMENU;

DELIMITER $$

CREATE PROCEDURE CMSADDSERV (
    IN PSERVCODE VARCHAR(20),
    IN PSERVNAME VARCHAR(80),
    IN PDEFSTART TIME,
    IN PDEFEND TIME,
    IN PVALIDFROM DATE,
    IN PVALIDUNTIL DATE,
    IN PCREATEDBY INT
)
BEGIN
    INSERT INTO CMS_SERVICE (SERVCODE, SERVNAME, DEFSTART, DEFEND, VALIDFROM, VALIDUNTIL, STATUS, CREATEDBY)
    VALUES (PSERVCODE, PSERVNAME, PDEFSTART, PDEFEND, PVALIDFROM, PVALIDUNTIL, 'A', PCREATEDBY);

    SELECT LAST_INSERT_ID() AS SERVICEID;
END$$

CREATE PROCEDURE CMSUPDSERV (
    IN PSERVICEID INT,
    IN PSERVNAME VARCHAR(80),
    IN PDEFSTART TIME,
    IN PDEFEND TIME,
    IN PVALIDFROM DATE,
    IN PVALIDUNTIL DATE,
    IN PSTATUS VARCHAR(20),
    IN PCHANGEDBY INT,
    IN PCHGREASON VARCHAR(255)
)
BEGIN
    INSERT INTO CMS_SERVHIST (SERVICEID, SERVCODE, SERVNAME, DEFSTART, DEFEND, VALIDFROM, VALIDUNTIL, STATUS, CHANGEDBY, CHGREASON)
    SELECT SERVICEID, SERVCODE, SERVNAME, DEFSTART, DEFEND, VALIDFROM, VALIDUNTIL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_SERVICE
    WHERE SERVICEID = PSERVICEID;

    UPDATE CMS_SERVICE
    SET SERVNAME = PSERVNAME,
        DEFSTART = PDEFSTART,
        DEFEND = PDEFEND,
        VALIDFROM = PVALIDFROM,
        VALIDUNTIL = PVALIDUNTIL,
        STATUS = PSTATUS,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE SERVICEID = PSERVICEID;
END$$

CREATE PROCEDURE CMSADDMENU (
    IN PMENUCODE VARCHAR(20),
    IN PSHORTNAME VARCHAR(30),
    IN PITEMNAME VARCHAR(100),
    IN PITEMDESCR VARCHAR(255),
    IN PPERMPRICE DECIMAL(10,2),
    IN PCONTPRICE DECIMAL(10,2),
    IN PVISPRICE DECIMAL(10,2),
    IN POFFPRICE DECIMAL(10,2),
    IN PISSPECIAL TINYINT,
    IN PCREATEDBY INT
)
BEGIN
    INSERT INTO CMS_MENUITEM (MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, PERMPRICE, CONTPRICE, VISPRICE, OFFPRICE, ISSPECIAL, STATUS, CREATEDBY)
    VALUES (PMENUCODE, PSHORTNAME, PITEMNAME, PITEMDESCR, PPERMPRICE, PCONTPRICE, PVISPRICE, POFFPRICE, PISSPECIAL, 'A', PCREATEDBY);

    SELECT LAST_INSERT_ID() AS MENUITEMID;
END$$

CREATE PROCEDURE CMSUPDMENU (
    IN PMENUITEMID INT,
    IN PSHORTNAME VARCHAR(30),
    IN PITEMNAME VARCHAR(100),
    IN PITEMDESCR VARCHAR(255),
    IN PPERMPRICE DECIMAL(10,2),
    IN PCONTPRICE DECIMAL(10,2),
    IN PVISPRICE DECIMAL(10,2),
    IN POFFPRICE DECIMAL(10,2),
    IN PISSPECIAL TINYINT,
    IN PSTATUS VARCHAR(20),
    IN PCHANGEDBY INT,
    IN PCHGREASON VARCHAR(255)
)
BEGIN
    INSERT INTO CMS_MENUHIST (MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, PERMPRICE, CONTPRICE, VISPRICE, OFFPRICE, ISSPECIAL, STATUS, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, PERMPRICE, CONTPRICE, VISPRICE, OFFPRICE, ISSPECIAL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM
    WHERE MENUITEMID = PMENUITEMID;

    UPDATE CMS_MENUITEM
    SET SHORTNAME = PSHORTNAME,
        ITEMNAME = PITEMNAME,
        ITEMDESCR = PITEMDESCR,
        PERMPRICE = PPERMPRICE,
        CONTPRICE = PCONTPRICE,
        VISPRICE = PVISPRICE,
        OFFPRICE = POFFPRICE,
        ISSPECIAL = PISSPECIAL,
        STATUS = PSTATUS,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE MENUITEMID = PMENUITEMID;
END$$

CREATE PROCEDURE CMSADDSLOT (
    IN PSERVICEID INT,
    IN PSERVDATE DATE,
    IN PSTARTTIME TIME,
    IN PENDTIME TIME,
    IN PCREATEDBY INT
)
BEGIN
    INSERT INTO CMS_DAYSLOT (SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CREATEDBY)
    VALUES (PSERVICEID, PSERVDATE, PSTARTTIME, PENDTIME, 'A', PCREATEDBY);

    SELECT LAST_INSERT_ID() AS DAYSLOTID;
END$$

CREATE PROCEDURE CMSUPDSLOT (
    IN PDAYSLOTID INT,
    IN PSTARTTIME TIME,
    IN PENDTIME TIME,
    IN PSTATUS VARCHAR(20),
    IN PCHANGEDBY INT,
    IN PCHGREASON VARCHAR(255)
)
BEGIN
    INSERT INTO CMS_SLOTHIST (DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CHANGEDBY, CHGREASON)
    SELECT DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_DAYSLOT
    WHERE DAYSLOTID = PDAYSLOTID;

    UPDATE CMS_DAYSLOT
    SET STARTTIME = PSTARTTIME,
        ENDTIME = PENDTIME,
        STATUS = PSTATUS,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE DAYSLOTID = PDAYSLOTID;
END$$

CREATE PROCEDURE CMSADDDMENU (
    IN PDAYSLOTID INT,
    IN PMENUITEMID INT,
    IN PISSPECIAL TINYINT,
    IN PISPREBOOK TINYINT,
    IN PISWALKIN TINYINT,
    IN PISKIOSK TINYINT,
    IN PAVAILQTY INT,
    IN PMAXQTY INT,
    IN PBOOKSTART DATETIME,
    IN PBOOKEND DATETIME,
    IN PCANCELAT DATETIME,
    IN PADDEDBY INT,
    IN PREMARKS VARCHAR(255)
)
BEGIN
    DECLARE VDMENUNO VARCHAR(30);

    CALL CMSGENAUTO('CMS_DAYMENU', 'DMENUNO', VDMENUNO);

    INSERT INTO CMS_DAYMENU (DMENUNO, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISWALKIN, ISKIOSK, AVAILQTY, MAXQTY, BOOKSTART, BOOKEND, CANCELAT, APPRSTATUS, ADDEDBY, REMARKS)
    VALUES (VDMENUNO, PDAYSLOTID, PMENUITEMID, PISSPECIAL, PISPREBOOK, PISWALKIN, PISKIOSK, PAVAILQTY, PMAXQTY, PBOOKSTART, PBOOKEND, PCANCELAT, 'P', PADDEDBY, PREMARKS);

    SELECT LAST_INSERT_ID() AS DAYMENUID, VDMENUNO AS DMENUNO;
END$$

CREATE PROCEDURE CMSAPPDMENU (
    IN PDAYMENUID INT,
    IN PAPPRSTATUS VARCHAR(20),
    IN PAPPROVEDBY INT,
    IN PREMARKS VARCHAR(255)
)
BEGIN
    INSERT INTO CMS_DMENUHIS (DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISWALKIN, ISKIOSK, AVAILQTY, MAXQTY, BOOKSTART, BOOKEND, CANCELAT, APPRSTATUS, CHANGEDBY, CHGREASON, REMARKS)
    SELECT DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISWALKIN, ISKIOSK, AVAILQTY, MAXQTY, BOOKSTART, BOOKEND, CANCELAT, APPRSTATUS, PAPPROVEDBY, 'Approval status changed', REMARKS
    FROM CMS_DAYMENU
    WHERE DAYMENUID = PDAYMENUID;

    UPDATE CMS_DAYMENU
    SET APPRSTATUS = PAPPRSTATUS,
        APPROVEDBY = PAPPROVEDBY,
        APPROVEDAT = CURRENT_TIMESTAMP,
        REMARKS = PREMARKS,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE DAYMENUID = PDAYMENUID;
END$$

CREATE PROCEDURE CMSVIEWMENU (
    IN PSERVDATE DATE,
    IN PCTYPECODE VARCHAR(20)
)
BEGIN
    SELECT
        DS.DAYSLOTID,
        S.SERVCODE,
        S.SERVNAME,
        DS.SERVDATE,
        DS.STARTTIME,
        DS.ENDTIME,
        DM.DAYMENUID,
        DM.DMENUNO,
        MI.MENUCODE,
        MI.ITEMNAME,
        MI.ITEMDESCR,
        CASE
            WHEN PCTYPECODE IN ('PERMANENT', 'OTHERCENTRE') THEN MI.PERMPRICE
            WHEN PCTYPECODE = 'CONTRACT' THEN MI.CONTPRICE
            WHEN PCTYPECODE = 'VISITOR' THEN MI.VISPRICE
            ELSE MI.VISPRICE
        END AS DISPLAYPRICE,
        DM.AVAILQTY,
        DM.MAXQTY,
        DM.BOOKSTART,
        DM.BOOKEND,
        DM.CANCELAT
    FROM CMS_DAYMENU DM
    JOIN CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
    JOIN CMS_SERVICE S ON S.SERVICEID = DS.SERVICEID
    JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    WHERE DS.SERVDATE = PSERVDATE
      AND DM.APPRSTATUS = 'APP'
      AND DS.STATUS = 'A'
      AND MI.STATUS = 'A'
    ORDER BY DS.STARTTIME, MI.ITEMNAME;
END$$

DELIMITER ;
