/* ============================================================
    BOOKING & SERVING STORED PROCEDURES (Refactored for CMS_STATUS)
   ============================================================ */

USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDBOOK;
DROP PROCEDURE IF EXISTS CMSUPDBOOKITEM;
DROP PROCEDURE IF EXISTS CMSCANCELBOOK;
DROP PROCEDURE IF EXISTS CMSSERVEBOOK;
DROP PROCEDURE IF EXISTS CMSSERVEBOOKITEM;
DROP PROCEDURE IF EXISTS CMSNOSHOWBOOK;
DROP PROCEDURE IF EXISTS CMSNOSHOWSINGLEBOOK;
DROP PROCEDURE IF EXISTS CMSTOGGLEKIOSK;
DROP PROCEDURE IF EXISTS CMSGETBOOK;
DROP PROCEDURE IF EXISTS CMSLISTBOOK;
DROP PROCEDURE IF EXISTS CMSLISTKITCHENPREP;    
DROP PROCEDURE IF EXISTS CMSLISTBOOKTODAY;

DELIMITER $$

-- Creates a PB or KS booking header plus its items in one transaction.
CREATE PROCEDURE CMSADDBOOK (
    IN PBOOKTYPECODE VARCHAR(10),
    IN PCUSTOMERID INT,
    IN PSERVICEID INT,
    IN PSERVICEDATE DATE,
    IN PITEMSJSON JSON,
    IN PBOOKEDBY INT,
    IN PREMARKS VARCHAR(255)
)
BEGIN
    DECLARE VBOOKTYPEID INT;
    DECLARE VBOOKTYPESTATUSID INT;
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VCUSTSTATUSID INT;
    DECLARE VSERVPFX VARCHAR(5);
    DECLARE VSERVSTATUSID INT;
    DECLARE VEXISTINGPB INT DEFAULT 0;
    DECLARE VITEMCOUNT INT DEFAULT 0;
    DECLARE VDISTINCTCOUNT INT DEFAULT 0;
    DECLARE VINVALIDCOUNT INT DEFAULT 0;
    DECLARE VBOOKID INT;
    DECLARE VBOOKNO VARCHAR(30);
    DECLARE VBOOKSEQ BIGINT;
    DECLARE VTOTALITEMS INT DEFAULT 0;
    DECLARE VTOTALQTY INT DEFAULT 0;
    DECLARE VTOTALAMOUNT DECIMAL(12,2) DEFAULT 0.00;
    DECLARE VLASTNO BIGINT;
    DECLARE VWALLETID INT;
    DECLARE VWALLETBALANCE DECIMAL(12,2);
    DECLARE VWALLETRESERVED DECIMAL(12,2);
    DECLARE VAUTOREFNO VARCHAR(80);
    DECLARE VCAPACITY_EXCEEDED INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PBOOKTYPECODE IS NULL OR PBOOKTYPECODE NOT IN ('PB','KS') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking type must be PB or KS';
    END IF;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer is required';
    END IF;

    IF PSERVICEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service is required';
    END IF;

    IF PSERVICEDATE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service date is required';
    END IF;

    IF PITEMSJSON IS NULL OR JSON_TYPE(PITEMSJSON) <> 'ARRAY' OR JSON_LENGTH(PITEMSJSON) = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'At least one booking item is required';
    END IF;

    SELECT BT.BOOKTYPEID, BT.STATUSID INTO VBOOKTYPEID, VBOOKTYPESTATUSID
    FROM CMS_BOOKTYPE BT WHERE BT.BOOKTYPECODE = PBOOKTYPECODE;

    IF VBOOKTYPEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking type not found';
    END IF;

    -- 10 = 'ACT'
    IF VBOOKTYPESTATUSID <> 10 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking type is inactive';
    END IF;

    SELECT C.CTYPECODE, C.STATUSID INTO VCTYPECODE, VCUSTSTATUSID
    FROM CMS_CUSTOMER C WHERE C.CUSTOMERID = PCUSTOMERID;

    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found';
    END IF;

    IF VCUSTSTATUSID <> 10 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer is not active';
    END IF;

    SELECT UPPER(LEFT(S.SERVCODE, 2)), S.STATUSID INTO VSERVPFX, VSERVSTATUSID
    FROM CMS_SERVICE S WHERE S.SERVICEID = PSERVICEID;

    IF VSERVPFX IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service not found';
    END IF;

    IF VSERVSTATUSID <> 10 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service is not active';
    END IF;

    IF PBOOKTYPECODE = 'PB' THEN
        SELECT COUNT(*) INTO VEXISTINGPB
        FROM CMS_BOOKING B
        JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
        WHERE B.CUSTOMERID = PCUSTOMERID
          AND B.SERVICEID = PSERVICEID
          AND B.SERVICEDATE = PSERVICEDATE
          AND B.BOOKTYPEID = VBOOKTYPEID
          AND ST.STATUSCODE <> 'CAN'; -- 33 = CAN

        IF VEXISTINGPB > 0 THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'An active pre-booking already exists for this service and date; use the update operation instead';
        END IF;
    END IF;

    SET VITEMCOUNT = JSON_LENGTH(PITEMSJSON);

    SELECT COUNT(DISTINCT JT.DAYMENUID) INTO VDISTINCTCOUNT
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID'
    )) AS JT;

    IF VDISTINCTCOUNT <> VITEMCOUNT THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Duplicate day menu items in the same booking are not allowed';
    END IF;

    SELECT COUNT(*) INTO VINVALIDCOUNT
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    LEFT JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID
    LEFT JOIN CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
    LEFT JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    LEFT JOIN CMS_STATUS DS_AST ON DS_AST.STATUSID = DS.APPRSTATUSID
    LEFT JOIN CMS_STATUS DS_ST ON DS_ST.STATUSID = DS.STATUSID
    LEFT JOIN CMS_STATUS MI_ST ON MI_ST.STATUSID = MI.STATUSID
    WHERE JT.DAYMENUID IS NULL
       OR JT.QTY IS NULL OR JT.QTY < 1
       OR DM.DAYMENUID IS NULL
       OR DS_AST.STATUSCODE <> 'APR'
       OR DS.SERVICEID <> PSERVICEID
       OR DS.SERVDATE <> PSERVICEDATE
       OR DS_ST.STATUSCODE <> 'ACT'
       OR MI_ST.STATUSCODE <> 'ACT'
       OR CURRENT_TIMESTAMP > DM.BOOKUNTIL
       OR (PBOOKTYPECODE = 'PB' AND (DM.ISPREBOOK <> 1 OR JT.QTY > DM.MAXQTY))
       OR (PBOOKTYPECODE = 'KS' AND DM.ISKIOSK <> 1);

    IF VINVALIDCOUNT > 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'One or more booking items are invalid, inactive, unavailable, or outside the booking window';
    END IF;

    START TRANSACTION;

    SELECT COUNT(*) INTO @dummy
    FROM CMS_DAYMENU
    WHERE DAYMENUID IN (
        SELECT DAYMENUID FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (DAYMENUID INT PATH '$.DAYMENUID')) AS JT
    ) FOR UPDATE;

    SELECT COUNT(*) INTO VCAPACITY_EXCEEDED
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID
    WHERE DM.AVAILQTY IS NOT NULL
      AND (
          SELECT COALESCE(SUM(BI.QTY), 0)
          FROM CMS_BOOKITEM BI
          JOIN CMS_BOOKING B ON B.BOOKID = BI.BOOKID
          JOIN CMS_STATUS B_ST2 ON B_ST2.STATUSID = B.STATUSID
          WHERE BI.DAYMENUID = JT.DAYMENUID
            AND B_ST2.STATUSCODE IN ('CRT', 'SRV', 'NOS')
      ) + JT.QTY > DM.AVAILQTY;

    IF VCAPACITY_EXCEEDED > 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'One or more items have insufficient available capacity';
    END IF;

    INSERT INTO CMS_BOOKCTR (BOOKTYPEID, SERVICEID, LASTNO)
    VALUES (VBOOKTYPEID, PSERVICEID, 0)
    ON DUPLICATE KEY UPDATE LASTNO = LASTNO;

    SELECT LASTNO INTO VLASTNO
    FROM CMS_BOOKCTR
    WHERE BOOKTYPEID = VBOOKTYPEID AND SERVICEID = PSERVICEID
    FOR UPDATE;

    SET VBOOKSEQ = VLASTNO + 1;

    UPDATE CMS_BOOKCTR SET LASTNO = VBOOKSEQ
    WHERE BOOKTYPEID = VBOOKTYPEID AND SERVICEID = PSERVICEID;

    SET VBOOKNO = CONCAT(PBOOKTYPECODE, '-', VSERVPFX, LPAD(VBOOKSEQ, 3, '0'));

    SELECT COUNT(*), SUM(JT.QTY), SUM(JT.QTY * COALESCE(
        (SELECT d.PRICE
         FROM CMS_ITEMPRICE p
         JOIN CMS_STATUS IP_ST ON IP_ST.STATUSID = p.STATUSID
         JOIN CMS_ITEMPRICEDT d ON d.ITEMPRICEID = p.ITEMPRICEID
         WHERE p.MENUITEMID = DM.MENUITEMID
           AND d.CTYPECODE = VCTYPECODE
           AND p.EFFFROM <= PSERVICEDATE
           AND IP_ST.STATUSCODE = 'ACT'
         ORDER BY p.EFFFROM DESC LIMIT 1),
        0))
    INTO VTOTALITEMS, VTOTALQTY, VTOTALAMOUNT
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID;

    IF VCTYPECODE IN ('CNT', 'VIS', 'CONTEMP', 'VISITOR') THEN
        SELECT W.WALLETID, W.BALANCE, W.RESERVEDAMT
        INTO VWALLETID, VWALLETBALANCE, VWALLETRESERVED
        FROM CMS_WALLET W
        JOIN CMS_STATUS W_ST ON W_ST.STATUSID = W.STATUSID
        WHERE W.CUSTOMERID = PCUSTOMERID AND W_ST.STATUSCODE = 'ACT'
        FOR UPDATE;

        IF VWALLETID IS NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Active wallet not found for customer';
        END IF;

        IF VTOTALAMOUNT > (VWALLETBALANCE - VWALLETRESERVED) THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Insufficient available wallet balance to place booking';
        END IF;

        UPDATE CMS_WALLET
        SET BALANCE = BALANCE - VTOTALAMOUNT
        WHERE WALLETID = VWALLETID;
    END IF;

    -- 30 = 'CRT' (Created)
    INSERT INTO CMS_BOOKING (
        BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE, STATUSID,
        BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
        BOOKEDBY, BOOKEDON, REMARKS, CREATEDBY
    )
    VALUES (
        VBOOKNO, VBOOKTYPEID, PCUSTOMERID, PSERVICEID, PSERVICEDATE, 30,
        VBOOKSEQ, VTOTALITEMS, VTOTALQTY, VTOTALAMOUNT,
        PBOOKEDBY, CURRENT_TIMESTAMP, PREMARKS, PBOOKEDBY
    );

    SET VBOOKID = LAST_INSERT_ID();

    IF VCTYPECODE IN ('CNT', 'VIS', 'CONTEMP', 'VISITOR') THEN
        CALL CMSGENAUTO('CMS_WALLETTRAN', 'REFNO', VAUTOREFNO);

        -- 44 = DBT (Debit)
        INSERT INTO CMS_WALLETTRAN
        (
            WALLETID,
            BOOKINGID,
            TRANSTYPE,
            SOURCECODE,
            AMOUNT,
            BALBEFORE,
            BALAFTER,
            PAYMENTMETHOD,
            REFNO,
            STATUSID,
            CREATEDBY,
            REMARKS
        )
        VALUES
        (
            VWALLETID,
            VBOOKID,
            'DEBIT',
            'BOOKING',
            VTOTALAMOUNT,
            VWALLETBALANCE,
            VWALLETBALANCE - VTOTALAMOUNT,
            'WALLET',
            VAUTOREFNO,
            44,
            PBOOKEDBY,
            CONCAT('Pre-booking #', VBOOKNO)
        );
    END IF;

    INSERT INTO CMS_BOOKITEM (BOOKID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, STATUSID)
    SELECT
        VBOOKID,
        DM.DAYMENUID,
        DM.MENUITEMID,
        JT.QTY,
        COALESCE(
            (SELECT d.PRICE
             FROM CMS_ITEMPRICE p
             JOIN CMS_STATUS IP_ST ON IP_ST.STATUSID = p.STATUSID
             JOIN CMS_ITEMPRICEDT d ON d.ITEMPRICEID = p.ITEMPRICEID
             WHERE p.MENUITEMID = DM.MENUITEMID
               AND d.CTYPECODE = VCTYPECODE
               AND p.EFFFROM <= PSERVICEDATE
               AND IP_ST.STATUSCODE = 'ACT'
             ORDER BY p.EFFFROM DESC LIMIT 1),
            0),
        JT.QTY * COALESCE(
            (SELECT d.PRICE
             FROM CMS_ITEMPRICE p
             JOIN CMS_STATUS IP_ST ON IP_ST.STATUSID = p.STATUSID
             JOIN CMS_ITEMPRICEDT d ON d.ITEMPRICEID = p.ITEMPRICEID
             WHERE p.MENUITEMID = DM.MENUITEMID
               AND d.CTYPECODE = VCTYPECODE
               AND p.EFFFROM <= PSERVICEDATE
               AND IP_ST.STATUSCODE = 'ACT'
             ORDER BY p.EFFFROM DESC LIMIT 1),
            0),
        30
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID;

    IF PBOOKTYPECODE = 'PB' THEN
        INSERT INTO CMS_PBACTIVE (CUSTOMERID, SERVICEID, SERVICEDATE, BOOKID)
        VALUES (PCUSTOMERID, PSERVICEID, PSERVICEDATE, VBOOKID);
    END IF;

    COMMIT;

    SELECT VBOOKID AS BOOKID, VBOOKNO AS BOOKNO;
END$$

-- Full replacement of a PB booking's items, pre-cutoff only.
CREATE PROCEDURE CMSUPDBOOKITEM (
    IN PBOOKID INT,
    IN PITEMSJSON JSON,
    IN PCHANGEDBY INT
)
BEGIN
    DECLARE VBOOKTYPECODE VARCHAR(10);
    DECLARE VCUSTOMERID INT;
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VSERVICEID INT;
    DECLARE VSERVICEDATE DATE;
    DECLARE VSTATUSCODE VARCHAR(10);
    DECLARE VCUTOFF DATETIME;
    DECLARE VITEMCOUNT INT DEFAULT 0;
    DECLARE VDISTINCTCOUNT INT DEFAULT 0;
    DECLARE VINVALIDCOUNT INT DEFAULT 0;
    DECLARE VTOTALITEMS INT DEFAULT 0;
    DECLARE VTOTALQTY INT DEFAULT 0;
    DECLARE VTOTALAMOUNT DECIMAL(12,2) DEFAULT 0.00;
    DECLARE VOLDTOTALAMOUNT DECIMAL(12,2) DEFAULT 0.00;
    DECLARE VWALLETID INT;
    DECLARE VWALLETBALANCE DECIMAL(12,2);
    DECLARE VWALLETRESERVED DECIMAL(12,2);
    DECLARE VAUTOREFNO VARCHAR(80);
    DECLARE VCAPACITY_EXCEEDED INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PBOOKID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking ID is required';
    END IF;

    IF PITEMSJSON IS NULL OR JSON_TYPE(PITEMSJSON) <> 'ARRAY' OR JSON_LENGTH(PITEMSJSON) = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'At least one booking item is required';
    END IF;

    SELECT BT.BOOKTYPECODE, BK.CUSTOMERID, BK.SERVICEID, BK.SERVICEDATE, ST.STATUSCODE, BK.TOTALAMOUNT
    INTO VBOOKTYPECODE, VCUSTOMERID, VSERVICEID, VSERVICEDATE, VSTATUSCODE, VOLDTOTALAMOUNT
    FROM CMS_BOOKING BK
    JOIN CMS_BOOKTYPE BT ON BT.BOOKTYPEID = BK.BOOKTYPEID
    JOIN CMS_STATUS ST ON ST.STATUSID = BK.STATUSID
    WHERE BK.BOOKID = PBOOKID;

    IF VBOOKTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking not found';
    END IF;

    IF VBOOKTYPECODE <> 'PB' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only pre-bookings can be edited';
    END IF;

    IF VSTATUSCODE <> 'CRT' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking is not in an editable state';
    END IF;

    SELECT MIN(DM.CANCELUNTIL) INTO VCUTOFF
    FROM CMS_BOOKITEM BI
    JOIN CMS_DAYMENU DM ON DM.DAYMENUID = BI.DAYMENUID
    WHERE BI.BOOKID = PBOOKID;

    IF VCUTOFF IS NOT NULL AND CURRENT_TIMESTAMP > VCUTOFF THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking cutoff time has passed; this booking can no longer be edited';
    END IF;

    SELECT C.CTYPECODE INTO VCTYPECODE FROM CMS_CUSTOMER C WHERE C.CUSTOMERID = VCUSTOMERID;

    SET VITEMCOUNT = JSON_LENGTH(PITEMSJSON);

    SELECT COUNT(DISTINCT JT.DAYMENUID) INTO VDISTINCTCOUNT
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID'
    )) AS JT;

    IF VDISTINCTCOUNT <> VITEMCOUNT THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Duplicate day menu items in the same booking are not allowed';
    END IF;

    SELECT COUNT(*) INTO VINVALIDCOUNT
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    LEFT JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID
    LEFT JOIN CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
    LEFT JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    LEFT JOIN CMS_STATUS DS_AST ON DS_AST.STATUSID = DS.APPRSTATUSID
    LEFT JOIN CMS_STATUS DS_ST ON DS_ST.STATUSID = DS.STATUSID
    LEFT JOIN CMS_STATUS MI_ST ON MI_ST.STATUSID = MI.STATUSID
    WHERE JT.DAYMENUID IS NULL
       OR JT.QTY IS NULL OR JT.QTY < 1
       OR DM.DAYMENUID IS NULL
       OR DS_AST.STATUSCODE <> 'APR'
       OR DS.SERVICEID <> VSERVICEID
       OR DS.SERVDATE <> VSERVICEDATE
       OR DS_ST.STATUSCODE <> 'ACT'
       OR MI_ST.STATUSCODE <> 'ACT'
       OR CURRENT_TIMESTAMP > DM.CANCELUNTIL
       OR DM.ISPREBOOK <> 1
       OR JT.QTY > DM.MAXQTY;

    IF VINVALIDCOUNT > 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'One or more booking items are invalid, inactive, unavailable, or past cutoff';
    END IF;

    START TRANSACTION;

    SELECT COUNT(*) INTO @dummy
    FROM CMS_DAYMENU
    WHERE DAYMENUID IN (
        SELECT DAYMENUID FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (DAYMENUID INT PATH '$.DAYMENUID')) AS JT
    ) FOR UPDATE;

    SELECT COUNT(*) INTO VCAPACITY_EXCEEDED
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID
    WHERE DM.AVAILQTY IS NOT NULL
      AND (
          SELECT COALESCE(SUM(BI.QTY), 0)
          FROM CMS_BOOKITEM BI
          JOIN CMS_BOOKING B ON B.BOOKID = BI.BOOKID
          JOIN CMS_STATUS B_ST2 ON B_ST2.STATUSID = B.STATUSID
          WHERE BI.DAYMENUID = JT.DAYMENUID
            AND B_ST2.STATUSCODE IN ('CRT', 'SRV', 'NOS')
            AND B.BOOKID <> PBOOKID
      ) + JT.QTY > DM.AVAILQTY;

    IF VCAPACITY_EXCEEDED > 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'One or more items have insufficient available capacity';
    END IF;

    DELETE FROM CMS_BOOKITEM WHERE BOOKID = PBOOKID;

    SELECT COUNT(*), SUM(JT.QTY), SUM(JT.QTY * COALESCE(
        (SELECT d.PRICE
         FROM CMS_ITEMPRICE p
         JOIN CMS_STATUS IP_ST ON IP_ST.STATUSID = p.STATUSID
         JOIN CMS_ITEMPRICEDT d ON d.ITEMPRICEID = p.ITEMPRICEID
         WHERE p.MENUITEMID = DM.MENUITEMID
           AND d.CTYPECODE = VCTYPECODE
           AND p.EFFFROM <= VSERVICEDATE
           AND IP_ST.STATUSCODE = 'ACT'
         ORDER BY p.EFFFROM DESC LIMIT 1),
        0))
    INTO VTOTALITEMS, VTOTALQTY, VTOTALAMOUNT
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID;

    INSERT INTO CMS_BOOKITEM (BOOKID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, STATUSID)
    SELECT
        PBOOKID,
        DM.DAYMENUID,
        DM.MENUITEMID,
        JT.QTY,
        COALESCE(
            (SELECT d.PRICE
             FROM CMS_ITEMPRICE p
             JOIN CMS_STATUS IP_ST ON IP_ST.STATUSID = p.STATUSID
             JOIN CMS_ITEMPRICEDT d ON d.ITEMPRICEID = p.ITEMPRICEID
             WHERE p.MENUITEMID = DM.MENUITEMID
               AND d.CTYPECODE = VCTYPECODE
               AND p.EFFFROM <= VSERVICEDATE
               AND IP_ST.STATUSCODE = 'ACT'
             ORDER BY p.EFFFROM DESC LIMIT 1),
            0),
        JT.QTY * COALESCE(
            (SELECT d.PRICE
             FROM CMS_ITEMPRICE p
             JOIN CMS_STATUS IP_ST ON IP_ST.STATUSID = p.STATUSID
             JOIN CMS_ITEMPRICEDT d ON d.ITEMPRICEID = p.ITEMPRICEID
             WHERE p.MENUITEMID = DM.MENUITEMID
               AND d.CTYPECODE = VCTYPECODE
               AND p.EFFFROM <= VSERVICEDATE
               AND IP_ST.STATUSCODE = 'ACT'
             ORDER BY p.EFFFROM DESC LIMIT 1),
            0),
        30 -- 30 = 'CRT'
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID;

    UPDATE CMS_BOOKING
    SET TOTALITEMS = VTOTALITEMS,
        TOTALQTY = VTOTALQTY,
        TOTALAMOUNT = VTOTALAMOUNT,
        UPDATEDBY = PCHANGEDBY,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE BOOKID = PBOOKID;

    IF VCTYPECODE IN ('CNT', 'VIS', 'CONTEMP', 'VISITOR') THEN
        SET VWALLETID = NULL;
        SELECT W.WALLETID, W.BALANCE INTO VWALLETID, VWALLETBALANCE
        FROM CMS_WALLET W
        JOIN CMS_STATUS W_ST ON W_ST.STATUSID = W.STATUSID
        WHERE W.CUSTOMERID = VCUSTOMERID AND W_ST.STATUSCODE = 'ACT'
        FOR UPDATE;

        IF VWALLETID IS NOT NULL THEN
            IF VTOTALAMOUNT > VOLDTOTALAMOUNT THEN
                IF (VWALLETBALANCE - VWALLETRESERVED) < (VTOTALAMOUNT - VOLDTOTALAMOUNT) THEN
                    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Insufficient available wallet balance for edited items';
                END IF;

                UPDATE CMS_WALLET
                SET BALANCE = BALANCE - (VTOTALAMOUNT - VOLDTOTALAMOUNT)
                WHERE WALLETID = VWALLETID;

                CALL CMSGENAUTO('CMS_WALLETTRAN', 'REFNO', VAUTOREFNO);

                -- 44 = DBT (Debit)
                INSERT INTO CMS_WALLETTRAN
                (
                    WALLETID,
                    BOOKINGID,
                    TRANSTYPE,
                    SOURCECODE,
                    AMOUNT,
                    BALBEFORE,
                    BALAFTER,
                    PAYMENTMETHOD,
                    REFNO,
                    STATUSID,
                    CREATEDBY,
                    REMARKS
                )
                VALUES
                (
                    VWALLETID,
                    PBOOKID,
                    'DEBIT',
                    'BOOKING_EDIT',
                    (VTOTALAMOUNT - VOLDTOTALAMOUNT),
                    VWALLETBALANCE,
                    VWALLETBALANCE - (VTOTALAMOUNT - VOLDTOTALAMOUNT),
                    'WALLET',
                    VAUTOREFNO,
                    44,
                    PCHANGEDBY,
                    'Booking items edited (additional charge)'
                );

            ELSEIF VTOTALAMOUNT < VOLDTOTALAMOUNT THEN
                UPDATE CMS_WALLET
                SET BALANCE = BALANCE + (VOLDTOTALAMOUNT - VTOTALAMOUNT)
                WHERE WALLETID = VWALLETID;

                CALL CMSGENAUTO('CMS_WALLETTRAN', 'REFNO', VAUTOREFNO);

                -- 40 = DEP (Credit)
                INSERT INTO CMS_WALLETTRAN
                (
                    WALLETID,
                    BOOKINGID,
                    TRANSTYPE,
                    SOURCECODE,
                    AMOUNT,
                    BALBEFORE,
                    BALAFTER,
                    PAYMENTMETHOD,
                    REFNO,
                    STATUSID,
                    CREATEDBY,
                    REMARKS
                )
                VALUES
                (
                    VWALLETID,
                    PBOOKID,
                    'CREDIT',
                    'REFUND',
                    (VOLDTOTALAMOUNT - VTOTALAMOUNT),
                    VWALLETBALANCE,
                    VWALLETBALANCE + (VOLDTOTALAMOUNT - VTOTALAMOUNT),
                    'WALLET',
                    VAUTOREFNO,
                    40,
                    PCHANGEDBY,
                    'Booking items edited (refund excess)'
                );
            END IF;
        END IF;
    END IF;

    COMMIT;
END$$

-- Cancels a booking.
CREATE PROCEDURE CMSCANCELBOOK (
    IN PBOOKID INT,
    IN PCANCELLEDBY INT,
    IN PISSTAFFOVERRIDE TINYINT,
    IN PCHGREASON VARCHAR(255)
)
BEGIN
    DECLARE VSTATUSCODE VARCHAR(10);
    DECLARE VCUTOFF DATETIME;
    DECLARE VBOOKHISTID INT;
    DECLARE VTOTALAMOUNT DECIMAL(12,2);
    DECLARE VCUSTOMERID INT;
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VWALLETID INT;
    DECLARE VWALLETBALANCE DECIMAL(12,2);
    DECLARE VAUTOREFNO VARCHAR(80);

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PBOOKID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking ID is required';
    END IF;

    SELECT ST.STATUSCODE, B.CUSTOMERID, B.TOTALAMOUNT, C.CTYPECODE 
    INTO VSTATUSCODE, VCUSTOMERID, VTOTALAMOUNT, VCTYPECODE 
    FROM CMS_BOOKING B
    JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
    JOIN CMS_CUSTOMER C ON C.CUSTOMERID = B.CUSTOMERID
    WHERE B.BOOKID = PBOOKID;

    IF VSTATUSCODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking not found';
    END IF;

    IF VSTATUSCODE <> 'CRT' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking cannot be cancelled from its current state';
    END IF;

    IF COALESCE(PISSTAFFOVERRIDE, 0) = 0 THEN
        SELECT MIN(DM.CANCELUNTIL) INTO VCUTOFF
        FROM CMS_BOOKITEM BI
        JOIN CMS_DAYMENU DM ON DM.DAYMENUID = BI.DAYMENUID
        WHERE BI.BOOKID = PBOOKID;

        IF VCUTOFF IS NOT NULL AND CURRENT_TIMESTAMP > VCUTOFF THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cancellation cutoff time has passed';
        END IF;
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_BOOKHIST (
        BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
        STATUSID, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
        BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
        REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, CHANGEDBY, CHGREASON
    )
    SELECT
        BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
        STATUSID, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
        BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
        REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, PCANCELLEDBY, PCHGREASON
    FROM CMS_BOOKING
    WHERE BOOKID = PBOOKID;

    SET VBOOKHISTID = LAST_INSERT_ID();

    INSERT INTO CMS_BOOKITMHS (BOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUSID)
    SELECT VBOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUSID
    FROM CMS_BOOKITEM
    WHERE BOOKID = PBOOKID;

    -- 33 = 'CAN' (Cancelled)
    UPDATE CMS_BOOKING
    SET STATUSID = 33,
        CANCELLEDBY = PCANCELLEDBY,
        CANCELLEDON = CURRENT_TIMESTAMP,
        REMARKS = COALESCE(PCHGREASON, REMARKS),
        UPDATEDBY = PCANCELLEDBY,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE BOOKID = PBOOKID;

    -- Cascade cancellation to line items (33 = CAN)
    UPDATE CMS_BOOKITEM
    SET STATUSID = 33
    WHERE BOOKID = PBOOKID;

    DELETE FROM CMS_PBACTIVE WHERE BOOKID = PBOOKID;

    IF VCTYPECODE IN ('CNT', 'VIS', 'CONTEMP', 'VISITOR') THEN
        SELECT W.WALLETID, W.BALANCE INTO VWALLETID, VWALLETBALANCE
        FROM CMS_WALLET W
        JOIN CMS_STATUS W_ST ON W_ST.STATUSID = W.STATUSID
        WHERE W.CUSTOMERID = VCUSTOMERID AND W_ST.STATUSCODE = 'ACT'
        FOR UPDATE;

        IF VWALLETID IS NOT NULL THEN
            UPDATE CMS_WALLET
            SET BALANCE = BALANCE + VTOTALAMOUNT
            WHERE WALLETID = VWALLETID;

            CALL CMSGENAUTO('CMS_WALLETTRAN', 'REFNO', VAUTOREFNO);

            -- 40 = DEP (Credit)
            INSERT INTO CMS_WALLETTRAN
            (
                WALLETID,
                BOOKINGID,
                TRANSTYPE,
                SOURCECODE,
                AMOUNT,
                BALBEFORE,
                BALAFTER,
                PAYMENTMETHOD,
                REFNO,
                STATUSID,
                CREATEDBY,
                REMARKS
            )
            VALUES
            (
                VWALLETID,
                PBOOKID,
                'CREDIT',
                'REFUND',
                VTOTALAMOUNT,
                VWALLETBALANCE,
                VWALLETBALANCE + VTOTALAMOUNT,
                'WALLET',
                VAUTOREFNO,
                40,
                PCANCELLEDBY,
                'Pre-booking cancelled refund'
            );
        END IF;
    END IF;

    COMMIT;
END$$

-- Marks a booking as served.
CREATE PROCEDURE CMSSERVEBOOK (
    IN PBOOKID INT,
    IN PSERVEDBY INT,
    IN PKIOSKID INT
)
PROC_BLOCK: BEGIN
    DECLARE VSTATUSCODE VARCHAR(10);
    DECLARE VSERVICEDATE DATE;
    DECLARE VBOOKHISTID INT;
    DECLARE VTOTALAMOUNT DECIMAL(12,2);
    DECLARE VCUSTOMERID INT;
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VWALLETID INT;
    DECLARE VWALLETBALANCE DECIMAL(12,2);
    DECLARE VWALLETRESERVED DECIMAL(12,2);
    DECLARE VNEWBALANCE DECIMAL(12,2);

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PBOOKID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking ID is required';
    END IF;

    SELECT ST.STATUSCODE, B.SERVICEDATE, B.CUSTOMERID, B.TOTALAMOUNT, C.CTYPECODE 
    INTO VSTATUSCODE, VSERVICEDATE, VCUSTOMERID, VTOTALAMOUNT, VCTYPECODE 
    FROM CMS_BOOKING B
    JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
    JOIN CMS_CUSTOMER C ON C.CUSTOMERID = B.CUSTOMERID
    WHERE B.BOOKID = PBOOKID;

    IF VSTATUSCODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking not found';
    END IF;

    -- Idempotent check: If already served, return success with ALREADY_SERVED flag
    IF VSTATUSCODE = 'SRV' THEN
        SELECT PBOOKID AS BOOKID, 32 AS STATUSID, 'SRV' AS STATUSCODE, 1 AS ALREADY_SERVED;
        LEAVE PROC_BLOCK;
    END IF;

    IF VSTATUSCODE <> 'CRT' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking cannot be served from its current state';
    END IF;

    IF VSERVICEDATE <> CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only bookings for today can be served';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_BOOKHIST (
        BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
        STATUSID, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
        BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
        KIOSKID,
        REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, CHANGEDBY, CHGREASON
    )
    SELECT
        BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
        STATUSID, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
        BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
        PKIOSKID,
        REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, PSERVEDBY, 'Served'
    FROM CMS_BOOKING
    WHERE BOOKID = PBOOKID;

    SET VBOOKHISTID = LAST_INSERT_ID();

    INSERT INTO CMS_BOOKITMHS (BOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUSID)
    SELECT VBOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUSID
    FROM CMS_BOOKITEM
    WHERE BOOKID = PBOOKID;

    -- 32 = 'SRV' (Served)
    UPDATE CMS_BOOKING
    SET STATUSID = 32,
        SERVEDBY = PSERVEDBY,
        SERVEDON = CURRENT_TIMESTAMP,
        KIOSKID = COALESCE(PKIOSKID, KIOSKID),
        UPDATEDBY = PSERVEDBY,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE BOOKID = PBOOKID;

    UPDATE CMS_BOOKITEM
    SET STATUSID = 32,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE BOOKID = PBOOKID AND STATUSID = 30;

    DELETE FROM CMS_PBACTIVE WHERE BOOKID = PBOOKID;

    IF VCTYPECODE IN ('CNT', 'VIS', 'CONTEMP', 'VISITOR') THEN
        UPDATE CMS_WALLET
        SET RESERVEDAMT = GREATEST(0, RESERVEDAMT - VTOTALAMOUNT),
            UPDATEDBY = PSERVEDBY,
            UPDATEDAT = CURRENT_TIMESTAMP
        WHERE CUSTOMERID = VCUSTOMERID;
    END IF;

    COMMIT;

    SELECT PBOOKID AS BOOKID, 32 AS STATUSID, 'SRV' AS STATUSCODE, 0 AS ALREADY_SERVED;
END$$

-- Marks an individual booking item as served. If all active items are served, finalizes booking header as Served.
CREATE PROCEDURE CMSSERVEBOOKITEM (
    IN PBOOKID     INT,
    IN PBOOKITEMID INT,
    IN PSERVEDBY   INT,
    IN PKIOSKID    INT,
    IN PCHGREASON  VARCHAR(255)
)
PROC_BLOCK: BEGIN
    DECLARE VITEMSTATUSID   INT;
    DECLARE VITEMSTATUSCODE VARCHAR(10);
    DECLARE VBOOKSTATUSID   INT;
    DECLARE VBOOKSTATUSCODE VARCHAR(10);
    DECLARE VSERVICEDATE    DATE;
    DECLARE VCUSTOMERID     INT;
    DECLARE VCTYPECODE      VARCHAR(20);
    DECLARE VTOTALAMOUNT    DECIMAL(12,2);
    DECLARE VUNSERVED_COUNT INT DEFAULT 0;
    DECLARE VBOOKHISTID     INT;
    DECLARE VALL_SERVED     TINYINT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PBOOKID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking ID is required';
    END IF;
    IF PBOOKITEMID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking Item ID is required';
    END IF;
    IF PSERVEDBY IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Served By user ID is required';
    END IF;

    -- Retrieve item and parent booking info
    SELECT BI.STATUSID, BIST.STATUSCODE, B.STATUSID, BST.STATUSCODE, B.SERVICEDATE, B.CUSTOMERID, C.CTYPECODE, B.TOTALAMOUNT
    INTO   VITEMSTATUSID, VITEMSTATUSCODE, VBOOKSTATUSID, VBOOKSTATUSCODE, VSERVICEDATE, VCUSTOMERID, VCTYPECODE, VTOTALAMOUNT
    FROM   CMS_BOOKITEM BI
    JOIN   CMS_BOOKING B    ON B.BOOKID = BI.BOOKID
    JOIN   CMS_CUSTOMER C   ON C.CUSTOMERID = B.CUSTOMERID
    JOIN   CMS_STATUS BIST  ON BIST.STATUSID = BI.STATUSID
    JOIN   CMS_STATUS BST   ON BST.STATUSID = B.STATUSID
    WHERE  BI.BOOKITEMID = PBOOKITEMID AND BI.BOOKID = PBOOKID;

    IF VITEMSTATUSID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking item not found for this booking';
    END IF;

    -- Idempotent check: if already served (32 = 'SRV'), return cleanly
    IF VITEMSTATUSCODE = 'SRV' THEN
        SELECT PBOOKID AS BOOKID, PBOOKITEMID AS BOOKITEMID, 32 AS STATUSID, 'SRV' AS STATUSCODE, 1 AS ALREADY_SERVED, 
               (CASE WHEN VBOOKSTATUSCODE = 'SRV' THEN 1 ELSE 0 END) AS ALL_SERVED;
        LEAVE PROC_BLOCK;
    END IF;

    IF VITEMSTATUSCODE = 'CAN' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot serve a cancelled booking item';
    END IF;

    IF VBOOKSTATUSCODE = 'CAN' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot serve an item from a cancelled booking';
    END IF;

    IF VSERVICEDATE <> CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only bookings for today can be served';
    END IF;

    START TRANSACTION;

    -- 1. Mark this specific item as Served (32 = 'SRV')
    UPDATE CMS_BOOKITEM
    SET STATUSID = 32,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE BOOKITEMID = PBOOKITEMID;

    -- 2. Check how many items remain unserved in this booking (30 = 'CRT')
    SELECT COUNT(*) INTO VUNSERVED_COUNT
    FROM CMS_BOOKITEM
    WHERE BOOKID = PBOOKID AND STATUSID = 30;

    -- 3. If no active unserved items remain, finalize the booking header as Served
    IF VUNSERVED_COUNT = 0 THEN
        INSERT INTO CMS_BOOKHIST (
            BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
            STATUSID, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
            BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
            KIOSKID,
            REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, CHANGEDBY, CHGREASON
        )
        SELECT
            BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
            STATUSID, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
            BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
            PKIOSKID,
            REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, PSERVEDBY, COALESCE(PCHGREASON, 'All items served')
        FROM CMS_BOOKING
        WHERE BOOKID = PBOOKID;

        SET VBOOKHISTID = LAST_INSERT_ID();

        INSERT INTO CMS_BOOKITMHS (BOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUSID)
        SELECT VBOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUSID
        FROM CMS_BOOKITEM
        WHERE BOOKID = PBOOKID;

        UPDATE CMS_BOOKING
        SET STATUSID = 32,
            SERVEDBY = PSERVEDBY,
            SERVEDON = CURRENT_TIMESTAMP,
            KIOSKID = COALESCE(PKIOSKID, KIOSKID),
            UPDATEDBY = PSERVEDBY,
            UPDATEDAT = CURRENT_TIMESTAMP
        WHERE BOOKID = PBOOKID;

        DELETE FROM CMS_PBACTIVE WHERE BOOKID = PBOOKID;

        IF VCTYPECODE IN ('CNT', 'VIS', 'CONTEMP', 'VISITOR') THEN
            UPDATE CMS_WALLET
            SET RESERVEDAMT = GREATEST(0, RESERVEDAMT - VTOTALAMOUNT),
                UPDATEDBY = PSERVEDBY,
                UPDATEDAT = CURRENT_TIMESTAMP
            WHERE CUSTOMERID = VCUSTOMERID;
        END IF;

        SET VALL_SERVED = 1;
    ELSE
        SET VALL_SERVED = 0;
    END IF;

    COMMIT;

    SELECT PBOOKID AS BOOKID, PBOOKITEMID AS BOOKITEMID, 32 AS STATUSID, 'SRV' AS STATUSCODE, 0 AS ALREADY_SERVED, VALL_SERVED AS ALL_SERVED;
END$$

-- End-of-day batch job for No Shows.
CREATE PROCEDURE CMSNOSHOWBOOK (
    IN PSERVICEDATE DATE,
    IN PSERVICEID INT,
    IN PCHANGEDBY INT
)
BEGIN
    DECLARE VDONE INT DEFAULT 0;
    DECLARE VBOOKID INT;
    DECLARE VBOOKHISTID INT;
    DECLARE VCUSTOMERID INT;
    DECLARE VTOTALAMOUNT DECIMAL(12,2);
    DECLARE VCTYPECODE VARCHAR(20);

    DECLARE VCUR CURSOR FOR
        SELECT B.BOOKID, B.CUSTOMERID, B.TOTALAMOUNT, C.CTYPECODE
        FROM CMS_BOOKING B
        JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
        JOIN CMS_CUSTOMER C ON C.CUSTOMERID = B.CUSTOMERID
        WHERE B.SERVICEDATE = PSERVICEDATE
          AND ST.STATUSCODE = 'CRT'
          AND (PSERVICEID IS NULL OR B.SERVICEID = PSERVICEID);

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET VDONE = 1;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PSERVICEDATE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service date is required';
    END IF;

    START TRANSACTION;

    OPEN VCUR;

    READLOOP: LOOP
        FETCH VCUR INTO VBOOKID, VCUSTOMERID, VTOTALAMOUNT, VCTYPECODE;
        IF VDONE = 1 THEN
            LEAVE READLOOP;
        END IF;

        INSERT INTO CMS_BOOKHIST (
            BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
            STATUSID, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
            BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
            REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, CHANGEDBY, CHGREASON
        )
        SELECT
            BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
            STATUSID, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
            BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
            REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, PCHANGEDBY, 'End of day no-show'
        FROM CMS_BOOKING
        WHERE BOOKID = VBOOKID;

        SET VBOOKHISTID = LAST_INSERT_ID();

        INSERT INTO CMS_BOOKITMHS (BOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUSID)
        SELECT VBOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUSID
        FROM CMS_BOOKITEM
        WHERE BOOKID = VBOOKID;

        -- 34 = 'NOS' (No Show)
        UPDATE CMS_BOOKING
        SET STATUSID = 34,
            NOSHOWON = CURRENT_TIMESTAMP,
            UPDATEDBY = PCHANGEDBY,
            UPDATEDAT = CURRENT_TIMESTAMP
        WHERE BOOKID = VBOOKID;

        UPDATE CMS_BOOKITEM
        SET STATUSID = 34,
            UPDATEDAT = CURRENT_TIMESTAMP
        WHERE BOOKID = VBOOKID AND STATUSID = 30;

        DELETE FROM CMS_PBACTIVE WHERE BOOKID = VBOOKID;

        IF VCTYPECODE IN ('CNT', 'VIS', 'CONTEMP', 'VISITOR') THEN
            UPDATE CMS_WALLET
            SET RESERVEDAMT = GREATEST(0, RESERVEDAMT - VTOTALAMOUNT),
                UPDATEDBY = PCHANGEDBY,
                UPDATEDAT = CURRENT_TIMESTAMP
            WHERE CUSTOMERID = VCUSTOMERID;
        END IF;
    END LOOP;

    CLOSE VCUR;

    COMMIT;
END$$

-- Marks an individual booking as No-Show.
CREATE PROCEDURE CMSNOSHOWSINGLEBOOK (
    IN PBOOKID INT,
    IN PCHANGEDBY INT,
    IN PCHGREASON VARCHAR(255)
)
PROC_BLOCK: BEGIN
    DECLARE VSTATUSCODE VARCHAR(10);
    DECLARE VBOOKHISTID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PBOOKID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking ID is required';
    END IF;

    SELECT ST.STATUSCODE INTO VSTATUSCODE 
    FROM CMS_BOOKING B
    JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
    WHERE B.BOOKID = PBOOKID;

    IF VSTATUSCODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking not found';
    END IF;

    -- Idempotent check: If already marked as No-Show, return success
    IF VSTATUSCODE = 'NOS' THEN
        SELECT PBOOKID AS BOOKID, 34 AS STATUSID, 'NOS' AS STATUSCODE, 1 AS ALREADY_NOSHOW;
        LEAVE PROC_BLOCK;
    END IF;

    IF VSTATUSCODE <> 'CRT' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking cannot be marked as no-show from its current state';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_BOOKHIST (
        BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
        STATUSID, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
        BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
        KIOSKID,
        REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, CHANGEDBY, CHGREASON
    )
    SELECT
        BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
        STATUSID, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
        BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, CURRENT_TIMESTAMP,
        KIOSKID,
        REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, PCHANGEDBY, COALESCE(PCHGREASON, 'Staff marked no-show')
    FROM CMS_BOOKING
    WHERE BOOKID = PBOOKID;

    SET VBOOKHISTID = LAST_INSERT_ID();

    INSERT INTO CMS_BOOKITMHS (BOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUSID)
    SELECT VBOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUSID
    FROM CMS_BOOKITEM
    WHERE BOOKID = PBOOKID;

    -- 34 = 'NOS' (No Show)
    UPDATE CMS_BOOKING
    SET STATUSID = 34,
        NOSHOWON = CURRENT_TIMESTAMP,
        UPDATEDBY = PCHANGEDBY,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE BOOKID = PBOOKID;

    UPDATE CMS_BOOKITEM
    SET STATUSID = 34,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE BOOKID = PBOOKID AND STATUSID = 30;

    DELETE FROM CMS_PBACTIVE WHERE BOOKID = PBOOKID;

    COMMIT;

    SELECT PBOOKID AS BOOKID, 34 AS STATUSID, 'NOS' AS STATUSCODE, 0 AS ALREADY_NOSHOW;
END$$

-- Lightweight live toggle for kiosk availability.
CREATE PROCEDURE CMSTOGGLEKIOSK (
    IN PDAYMENUID INT,
    IN PISKIOSK TINYINT,
    IN PCHANGEDBY INT
)
BEGIN
    DECLARE VEXISTS INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PDAYMENUID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required';
    END IF;

    IF PISKIOSK IS NULL OR PISKIOSK NOT IN (0, 1) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid kiosk availability flag';
    END IF;

    SELECT COUNT(*) INTO VEXISTS FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;

    IF VEXISTS = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found';
    END IF;

    START TRANSACTION;

    UPDATE CMS_DAYMENU
    SET ISKIOSK = PISKIOSK,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE DAYMENUID = PDAYMENUID;

    COMMIT;
END$$

-- Fetch a single booking header and its items
CREATE PROCEDURE CMSGETBOOK(
    IN PBOOKID INT
)
BEGIN
    SELECT 
        B.BOOKID, B.BOOKNO, B.BOOKTYPEID, BT.BOOKTYPECODE, BT.BOOKTYPENAME,
        B.CUSTOMERID, C.CTYPECODE, C.DISPNAME AS CUSTOMERNAME,
        B.SERVICEID, S.SERVNAME, B.SERVICEDATE,
        B.STATUSID, ST.STATUSCODE AS STATUSCODE, B.TOTALITEMS, B.TOTALQTY, B.TOTALAMOUNT,
        B.BOOKEDBY, U.FULLNAME AS BOOKEDBYNAME, B.BOOKEDON,
        B.CANCELLEDBY, B.CANCELLEDON, B.SERVEDBY, B.SERVEDON, B.NOSHOWON, B.REMARKS
    FROM CMS_BOOKING B
    INNER JOIN CMS_BOOKTYPE BT ON BT.BOOKTYPEID = B.BOOKTYPEID
    INNER JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
    INNER JOIN CMS_CUSTOMER C ON C.CUSTOMERID = B.CUSTOMERID
    INNER JOIN CMS_SERVICE S ON S.SERVICEID = B.SERVICEID
    LEFT JOIN CMS_USER U ON U.USERID = B.BOOKEDBY
    WHERE B.BOOKID = PBOOKID;

    SELECT 
        BI.BOOKITEMID, BI.DAYMENUID, BI.MENUITEMID, MI.MENUCODE, MI.ITEMNAME,
        BI.QTY, BI.RATE, BI.AMOUNT, BI.REMARKS, BI.STATUSID, BIST.STATUSCODE AS STATUSCODE
    FROM CMS_BOOKITEM BI
    INNER JOIN CMS_MENUITEM MI ON MI.MENUITEMID = BI.MENUITEMID
    INNER JOIN CMS_STATUS BIST ON BIST.STATUSID = BI.STATUSID
    WHERE BI.BOOKID = PBOOKID;
END$$

-- List bookings with optional filters
CREATE PROCEDURE CMSLISTBOOK(
    IN PCUSTOMERID INT,
    IN PSERVICEID INT,
    IN PSTARTDATE DATE,
    IN PENDDATE DATE,
    IN PSTATUSCODE VARCHAR(10)
)
BEGIN
    SELECT 
        B.BOOKID, B.BOOKNO, BT.BOOKTYPECODE, 
        B.CUSTOMERID, C.DISPNAME AS CUSTOMERNAME,
        B.SERVICEID, S.SERVNAME, B.SERVICEDATE,
        B.STATUSID, ST.STATUSCODE AS STATUSCODE, B.TOTALITEMS, B.TOTALQTY, B.TOTALAMOUNT
    FROM CMS_BOOKING B
    INNER JOIN CMS_BOOKTYPE BT ON BT.BOOKTYPEID = B.BOOKTYPEID
    INNER JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
    INNER JOIN CMS_CUSTOMER C ON C.CUSTOMERID = B.CUSTOMERID
    INNER JOIN CMS_SERVICE S ON S.SERVICEID = B.SERVICEID
    WHERE (PCUSTOMERID IS NULL OR B.CUSTOMERID = PCUSTOMERID)
      AND (PSERVICEID IS NULL OR B.SERVICEID = PSERVICEID)
      AND (PSTARTDATE IS NULL OR B.SERVICEDATE >= PSTARTDATE)
      AND (PENDDATE IS NULL OR B.SERVICEDATE <= PENDDATE)
      AND (PSTATUSCODE IS NULL OR ST.STATUSCODE = PSTATUSCODE)
    ORDER BY B.SERVICEDATE DESC, B.BOOKNO DESC;
END$$

CREATE PROCEDURE CMSLISTKITCHENPREP (IN PDAYSLOTID INT)
BEGIN
    SELECT DM.DAYMENUID,
           DM.MENUITEMID,
           MI.ITEMNAME,
           MI.SHORTNAME,
           DM.MAXQTY AS PLANNED_QTY,
           COALESCE(SUM(CASE WHEN B_ST.STATUSCODE IN ('CRT', 'SRV', 'NOS') THEN BI.QTY ELSE 0 END), 0) AS TOTAL_BOOKED,
           COALESCE(SUM(CASE WHEN B_ST.STATUSCODE = 'SRV' THEN BI.QTY ELSE 0 END), 0) AS TOTAL_SERVED,
           COALESCE(SUM(CASE WHEN B_ST.STATUSCODE IN ('CRT', 'NOS') THEN BI.QTY ELSE 0 END), 0) AS REMAINING_QTY
    FROM   CMS_DAYMENU DM
    JOIN   CMS_STATUS DM_ST ON DM_ST.STATUSID = DM.STATUSID
    JOIN   CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    LEFT JOIN CMS_BOOKITEM BI ON BI.DAYMENUID = DM.DAYMENUID
    LEFT JOIN CMS_STATUS B_ST ON B_ST.STATUSID = BI.STATUSID AND B_ST.STATUSCODE IN ('CRT', 'SRV', 'NOS')
    WHERE  DM.DAYSLOTID = PDAYSLOTID
      AND  DM_ST.STATUSCODE = 'ACT'
    GROUP BY DM.DAYMENUID, DM.MENUITEMID, MI.ITEMNAME, MI.SHORTNAME, DM.MAXQTY
    ORDER BY MI.ITEMNAME;
END$$

-- New procedure to list bookings for the current day
CREATE PROCEDURE CMSLISTBOOKTODAY(
    IN PCUSTOMERID INT,
    IN PSERVICEID INT,
    IN PSTATUSCODE VARCHAR(10)
)
BEGIN
    DECLARE TODAY DATE;
    SET TODAY = CURDATE();

    SELECT 
        B.BOOKID, B.BOOKNO, BT.BOOKTYPECODE, 
        B.CUSTOMERID, C.DISPNAME AS CUSTOMERNAME,
        B.SERVICEID, S.SERVNAME, B.SERVICEDATE,
        B.STATUSID, ST.STATUSCODE AS STATUSCODE, B.TOTALITEMS, B.TOTALQTY, B.TOTALAMOUNT
    FROM CMS_BOOKING B
    INNER JOIN CMS_BOOKTYPE BT ON BT.BOOKTYPEID = B.BOOKTYPEID
    INNER JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
    INNER JOIN CMS_CUSTOMER C ON C.CUSTOMERID = B.CUSTOMERID
    INNER JOIN CMS_SERVICE S ON S.SERVICEID = B.SERVICEID
    WHERE (PCUSTOMERID IS NULL OR B.CUSTOMERID = PCUSTOMERID)
      AND (PSERVICEID IS NULL OR B.SERVICEID = PSERVICEID)
      AND B.SERVICEDATE = TODAY
      AND (PSTATUSCODE IS NULL OR ST.STATUSCODE = PSTATUSCODE)
    ORDER BY B.SERVICEDATE DESC, B.BOOKNO DESC;
END$$

-- ============================================================
-- End-of-Day No-Show Automated Reconciliation Database Event
-- Runs daily at 23:59:50 to reconcile all unclaimed bookings for today.
-- ============================================================
DROP EVENT IF EXISTS EVT_CMS_DAILY_NOSHOW$$

CREATE EVENT EVT_CMS_DAILY_NOSHOW
ON SCHEDULE EVERY 1 DAY
STARTS (CURRENT_DATE + INTERVAL 1 DAY - INTERVAL 10 SECOND)
ON COMPLETION PRESERVE
ENABLE
DO
BEGIN
    CALL CMSNOSHOWBOOK(CURDATE(), NULL, 1);
END$$

DELIMITER ;