USE cms_db;

DROP PROCEDURE IF EXISTS CMSASSIGNCANROL;
DROP PROCEDURE IF EXISTS CMSREMOVECANROL;
DROP PROCEDURE IF EXISTS CMSLISTCANROL;
DROP PROCEDURE IF EXISTS CMSLISTCANROLSTAFF;

DELIMITER $$
/* ============================================================
   CMS_CANTEENROLE — Canteen-scoped Role Assignment
   ============================================================ */

CREATE PROCEDURE CMSASSIGNCANROL (
    IN PUSERID     INT,
    IN PROLEID     INT,
    IN PCANTEENID  INT,
    IN PISDEFAULT  TINYINT,
    IN PVALIDFROM  DATETIME,
    IN PVALIDUNTIL DATETIME,
    IN PASSIGNEDBY INT
)
BEGIN
    DECLARE VVALIDFROM DATETIME;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID is required';
    END IF;
    IF PROLEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role ID is required';
    END IF;
    IF PCANTEENID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required';
    END IF;

    SET VVALIDFROM = COALESCE(PVALIDFROM, CURRENT_TIMESTAMP);

    IF PVALIDUNTIL IS NOT NULL AND PVALIDUNTIL < VVALIDFROM THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Valid until date must be >= valid from date';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_CANTEENROLE (USERID, ROLEID, CANTEENID, ISDEFAULT, VALIDFROM, VALIDUNTIL, ISACTIVE, ASSIGNEDBY)
    VALUES (PUSERID, PROLEID, PCANTEENID, COALESCE(PISDEFAULT, 0), VVALIDFROM, PVALIDUNTIL, 1, PASSIGNEDBY)
    ON DUPLICATE KEY UPDATE
        ISDEFAULT  = COALESCE(PISDEFAULT, ISDEFAULT),
        VALIDFROM  = VVALIDFROM,
        VALIDUNTIL = PVALIDUNTIL,
        ISACTIVE   = 1,
        ASSIGNEDBY = PASSIGNEDBY,
        ASSIGNEDAT = CURRENT_TIMESTAMP;

    COMMIT;
    SELECT PUSERID AS USERID, PROLEID AS ROLEID, PCANTEENID AS CANTEENID;
END$$


CREATE PROCEDURE CMSREMOVECANROL (
    IN PUSERID    INT,
    IN PROLEID    INT,
    IN PCANTEENID INT
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL OR PROLEID IS NULL OR PCANTEENID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID, Role ID, and Canteen ID are required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CANTEENROLE
    WHERE USERID = PUSERID AND ROLEID = PROLEID AND CANTEENID = PCANTEENID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen role assignment not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CANTEENROLE SET ISACTIVE = 0, UPDATEDAT = CURRENT_TIMESTAMP
    WHERE USERID = PUSERID AND ROLEID = PROLEID AND CANTEENID = PCANTEENID;
    COMMIT;

    SELECT PUSERID AS USERID, PROLEID AS ROLEID, PCANTEENID AS CANTEENID;
END$$


CREATE PROCEDURE CMSLISTCANROL (IN PUSERID INT)
BEGIN
    SELECT CR.USRCANROLEID, CR.USERID, CR.ROLEID,
           R.ROLECODE, R.ROLENAME,
           CR.CANTEENID, C.CANTEENCODE, C.CANTEENNAME,
           CR.ISDEFAULT, CR.VALIDFROM, CR.VALIDUNTIL,
           CR.ISACTIVE, CR.ASSIGNEDBY, CR.ASSIGNEDAT
    FROM   CMS_CANTEENROLE CR
    JOIN   CMS_ROLE R    ON R.ROLEID     = CR.ROLEID
    JOIN   CMS_CANTEEN C ON C.CANTEENID  = CR.CANTEENID
    WHERE  CR.USERID = PUSERID
    ORDER BY C.CANTEENNAME, R.ROLECODE;
END$$


CREATE PROCEDURE CMSLISTCANROLSTAFF (IN PCANTEENID INT)
BEGIN
    SELECT CR.USRCANROLEID, CR.USERID, U.LOGINID, U.FULLNAME,
           CR.ROLEID, R.ROLECODE, R.ROLENAME,
           CR.ISDEFAULT, CR.VALIDFROM, CR.VALIDUNTIL,
           CR.ISACTIVE, CR.ASSIGNEDBY, CR.ASSIGNEDAT
    FROM   CMS_CANTEENROLE CR
    JOIN   CMS_USER U ON U.USERID = CR.USERID
    JOIN   CMS_ROLE R ON R.ROLEID = CR.ROLEID
    WHERE  CR.CANTEENID = PCANTEENID
      AND  CR.ISACTIVE  = 1
    ORDER BY U.FULLNAME, R.ROLECODE;
END$$



DELIMITER ;

