USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDCENTER;
DROP PROCEDURE IF EXISTS CMSUPDCENTER;
DROP PROCEDURE IF EXISTS CMSSEARCHCENTER;
DROP PROCEDURE IF EXISTS CMSACTCENTER;
DROP PROCEDURE IF EXISTS CMSDEACTCENTER;
DROP PROCEDURE IF EXISTS CMSGETCENTER;
DROP PROCEDURE IF EXISTS CMSLISTCENTER;

DELIMITER $$
/* ============================================================
   CMS_CENTER — ISRO Centre Master
   ============================================================ */

CREATE PROCEDURE CMSADDCENTER (
    IN PCENTERCODE VARCHAR(20),
    IN PCENTERNAME VARCHAR(120),
    IN PLOCATION   VARCHAR(150)
)
BEGIN
    DECLARE VCENTERID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERCODE IS NULL OR TRIM(PCENTERCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre Code is required';
    END IF;

    IF PCENTERNAME IS NULL OR TRIM(PCENTERNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre Name is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_CENTER (CENTERCODE, CENTERNAME, LOCATION, STATUSID)
    VALUES (TRIM(PCENTERCODE), TRIM(PCENTERNAME), PLOCATION, 10);

    SET VCENTERID = LAST_INSERT_ID();
    COMMIT;

    SELECT VCENTERID AS CENTERID;
END$$


CREATE PROCEDURE CMSUPDCENTER (
    IN PCENTERID   INT,
    IN PCENTERNAME  VARCHAR(120),
    IN PLOCATION    VARCHAR(150),
    IN PSTATUSCODE  VARCHAR(20)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE VSTATUSID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT FROM CMS_CENTER WHERE CENTERID = PCENTERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre not found';
    END IF;

    IF PCENTERNAME IS NULL OR TRIM(PCENTERNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre Name is required';
    END IF;

    IF PSTATUSCODE IS NOT NULL THEN
        SELECT STATUSID INTO VSTATUSID FROM CMS_STATUS WHERE STATUSCODE = PSTATUSCODE AND STATUSGRP = 'SYS';
        IF VSTATUSID IS NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid Status Code';
        END IF;
    END IF;

    START TRANSACTION;

    UPDATE CMS_CENTER
    SET    CENTERNAME = TRIM(PCENTERNAME),
           LOCATION  = PLOCATION,
           STATUSID  = COALESCE(VSTATUSID, STATUSID),
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  CENTERID  = PCENTERID;

    COMMIT;
    SELECT PCENTERID AS CENTERID;
END$$

CREATE PROCEDURE CMSACTCENTER (IN PCENTERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CENTER WHERE CENTERID = PCENTERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CENTER SET STATUSID = 10, UPDATEDAT = CURRENT_TIMESTAMP WHERE CENTERID = PCENTERID;
    COMMIT;
    SELECT PCENTERID AS CENTERID;
END$$


CREATE PROCEDURE CMSDEACTCENTER (IN PCENTERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CENTER WHERE CENTERID = PCENTERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CENTER SET STATUSID = 11, UPDATEDAT = CURRENT_TIMESTAMP WHERE CENTERID = PCENTERID;
    COMMIT;
    SELECT PCENTERID AS CENTERID;
END$$


CREATE PROCEDURE CMSGETCENTER (IN PCENTERID INT)
BEGIN
    SELECT C.CENTERID, C.CENTERCODE, C.CENTERNAME, C.LOCATION,
           C.STATUSID, ST.STATUSCODE AS STATUSCODE, C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CENTER C
    JOIN   CMS_STATUS ST ON ST.STATUSID = C.STATUSID
    WHERE  C.CENTERID = PCENTERID;
END$$


CREATE PROCEDURE CMSLISTCENTER ()
BEGIN
    SELECT C.CENTERID, C.CENTERCODE, C.CENTERNAME, C.LOCATION,
           C.STATUSID, ST.STATUSCODE AS STATUSCODE, C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CENTER C
    JOIN   CMS_STATUS ST ON ST.STATUSID = C.STATUSID
    ORDER BY C.CENTERNAME;
END$$


CREATE PROCEDURE CMSSEARCHCENTER (IN PKEYWORD VARCHAR(120))
BEGIN
    SELECT C.CENTERID, C.CENTERCODE, C.CENTERNAME, C.LOCATION,
           C.STATUSID, ST.STATUSCODE AS STATUSCODE, C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CENTER C
    JOIN   CMS_STATUS ST ON ST.STATUSID = C.STATUSID
    WHERE  (C.CENTERCODE LIKE CONCAT('%', PKEYWORD, '%')
       OR   C.CENTERNAME LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY C.CENTERNAME;
END$$

DELIMITER ;
