/* ============================================================
   MODULE 0: COMMON MASTER / SYSTEM CONFIGURATION
   STORED PROCEDURES — ENTERPRISE REDESIGN v2

   Aligned with: 00_COMMON_SCHEMA.sql (Final)
                 01_IDENTITY_ACCESS_SCHEMA.sql (CMS_ROLESCN)

   Changes from v1:
   1. CMSGENAUTO refactored — no internal transaction.
      Caller must own the transaction; FOR UPDATE lock
      on CMS_AUTONOS provides concurrency safety.
   2. Full CRUD + Activate/Deactivate for every table.
   3. Standard output convention: every write returns
      the affected PK.
   4. CMS_ROLESCN procedures moved here (they belong to
      the common RBAC infrastructure, not identity).
   ============================================================ */

USE cms_db;

DROP PROCEDURE IF EXISTS CMSGENAUTO;

DROP PROCEDURE IF EXISTS CMSADDSTATUS;
DROP PROCEDURE IF EXISTS CMSUPDSTATUS;
DROP PROCEDURE IF EXISTS CMSGETSTATUS;
DROP PROCEDURE IF EXISTS CMSLISTSTATUS;
DROP PROCEDURE IF EXISTS CMSACTSTATUS;
DROP PROCEDURE IF EXISTS CMSDEACTSTATUS;

DROP PROCEDURE IF EXISTS CMSADDCUSTTYPE;
DROP PROCEDURE IF EXISTS CMSUPDCUSTTYPE;
DROP PROCEDURE IF EXISTS CMSGETCUSTTYPE;
DROP PROCEDURE IF EXISTS CMSLISTCUSTTYPE;
DROP PROCEDURE IF EXISTS CMSACTCUSTTYPE;
DROP PROCEDURE IF EXISTS CMSDEACTCUSTTYPE;

DROP PROCEDURE IF EXISTS CMSADDSCREEN;
DROP PROCEDURE IF EXISTS CMSUPDSCREEN;
DROP PROCEDURE IF EXISTS CMSGETSCREEN;
DROP PROCEDURE IF EXISTS CMSLISTSCREEN;
DROP PROCEDURE IF EXISTS CMSACTSCREEN;
DROP PROCEDURE IF EXISTS CMSDEACTSCREEN;

DROP PROCEDURE IF EXISTS CMSSETROLESCN;
DROP PROCEDURE IF EXISTS CMSGETROLESCN;
DROP PROCEDURE IF EXISTS CMSLISTROLESCN;
DROP PROCEDURE IF EXISTS CMSREMOVEROLESCN;

DROP PROCEDURE IF EXISTS CMSADDAUTONO;
DROP PROCEDURE IF EXISTS CMSUPDAUTONO;
DROP PROCEDURE IF EXISTS CMSLISTAUTONO;

DELIMITER $$


/* ============================================================
   CMSGENAUTO — Auto-number generator (UTILITY)

   CRITICAL: This procedure does NOT own a transaction.
   It MUST be called from within the caller's transaction.
   The FOR UPDATE lock on CMS_AUTONOS serialises concurrent
   callers within the same transaction scope.

   Usage:
     START TRANSACTION;
     CALL CMSGENAUTO('CMS_DAYMENU', 'DMENUNO', @newno);
     INSERT INTO CMS_DAYMENU (DMENUNO, ...) VALUES (@newno, ...);
     COMMIT;
   ============================================================ */
   
-- CREATE PROCEDURE CMSGENAUTO (
--     IN  PTBLNAME  VARCHAR(50),
--     IN  PDATAITEM VARCHAR(30),
--     OUT PNEWNO    VARCHAR(30)
-- )
-- BEGIN
--     DECLARE VPREFIX  VARCHAR(5);
--     DECLARE VLASTNO  BIGINT;
--     DECLARE VNEWNO   BIGINT;
--     DECLARE VYEAR    CHAR(4);
--     DECLARE VLENGTH  INT;

--     SELECT PREFIXCHAR, LASTNO, ITEMLEN
--     INTO   VPREFIX, VLASTNO, VLENGTH
--     FROM   CMS_AUTONOS
--     WHERE  TBLNAME  = PTBLNAME
--       AND  DATAITEM = PDATAITEM
--       AND  STATUS   = 'A'
--     FOR UPDATE;

--     IF VPREFIX IS NULL THEN
--         SIGNAL SQLSTATE '45000'
--             SET MESSAGE_TEXT = 'Active auto-number configuration not found';
--     END IF;

--     SET VNEWNO = VLASTNO + 1;
--     SET VYEAR  = DATE_FORMAT(CURRENT_DATE, '%Y');
--     SET PNEWNO = CONCAT(
--         VPREFIX,
--         VYEAR,
--         LPAD(VNEWNO, GREATEST(VLENGTH - LENGTH(VPREFIX) - 4, 1), '0')
--     );

--     UPDATE CMS_AUTONOS
--     SET    LASTNO    = VNEWNO,
--            UPDATEDAT = CURRENT_TIMESTAMP
--     WHERE  TBLNAME  = PTBLNAME
--       AND  DATAITEM = PDATAITEM;
-- END$$

/* ============================================================
   CMSGENAUTO — Global Auto-Number Generator (Daily Reset)
   ============================================================ */

CREATE PROCEDURE CMSGENAUTO (
    IN  PTBLNAME   VARCHAR(50),
    IN  PDATAITEM  VARCHAR(30),
    OUT PNEWNO     VARCHAR(50)
)
BEGIN
    DECLARE VPREFIXCHAR  VARCHAR(5);
    DECLARE VITEMLEN     INT;
    DECLARE VLASTNO      BIGINT;
    DECLARE VLASTGENDATE DATE;
    DECLARE VDATESTR     VARCHAR(8);
    DECLARE VNUMSTR      VARCHAR(20);
    DECLARE VCOUNT       INT DEFAULT 0;

    -- 1. Validate configuration exists
    SELECT COUNT(*) INTO VCOUNT
    FROM   CMS_AUTONOS
    WHERE  TBLNAME  = PTBLNAME
      AND  DATAITEM = PDATAITEM;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Auto-number configuration not found for the requested table and column.';
    END IF;

    -- 2. Lock the row for concurrency (prevents race conditions)
    SELECT PREFIXCHAR, ITEMLEN, LASTNO, LASTGENDATE
    INTO   VPREFIXCHAR, VITEMLEN, VLASTNO, VLASTGENDATE
    FROM   CMS_AUTONOS
    WHERE  TBLNAME  = PTBLNAME
      AND  DATAITEM = PDATAITEM
    FOR UPDATE;

    -- 3. Check Daily Reset Logic
    IF VLASTGENDATE IS NULL OR VLASTGENDATE < CURRENT_DATE THEN
        SET VLASTNO = 1; -- Reset counter for a new day
    ELSE
        SET VLASTNO = VLASTNO + 1; -- Continue counter for today
    END IF;

    -- 4. Get exact date (e.g., '20260822')
    SET VDATESTR = DATE_FORMAT(CURRENT_DATE, '%Y%m%d');

    -- 5. Calculate remaining length and pad (Total Length - Prefix Length - Date Length)
    SET VNUMSTR = LPAD(VLASTNO, VITEMLEN - LENGTH(VPREFIXCHAR) - 8, '0');

    -- 6. Construct the final ID (e.g., 'SLT' + '20260822' + '0001')
    SET PNEWNO = CONCAT(VPREFIXCHAR, VDATESTR, VNUMSTR);

    -- 7. Update the configuration table
    UPDATE CMS_AUTONOS
    SET    LASTNO      = VLASTNO,
           LASTGENDATE = CURRENT_DATE,
           UPDATEDAT   = CURRENT_TIMESTAMP
    WHERE  TBLNAME     = PTBLNAME
      AND  DATAITEM    = PDATAITEM;

END$$


-- /* ============================================================
--    CMS_STATUS — System-wide status lookup
--    ============================================================ */

-- CREATE PROCEDURE CMSADDSTATUS (
--     IN PSTATUSCODE VARCHAR(10),
--     IN PSTATUSNAME VARCHAR(50),
--     IN PSTATUSGRP  VARCHAR(30),
--     IN PDESCR      VARCHAR(255)
-- )
-- BEGIN
--     DECLARE VSTATUSID INT;

--     DECLARE EXIT HANDLER FOR SQLEXCEPTION
--     BEGIN
--         ROLLBACK;
--         RESIGNAL;
--     END;

--     IF PSTATUSCODE IS NULL OR TRIM(PSTATUSCODE) = '' THEN
--         SIGNAL SQLSTATE '45000'
--             SET MESSAGE_TEXT = 'Status Code is required';
--     END IF;

--     IF PSTATUSNAME IS NULL OR TRIM(PSTATUSNAME) = '' THEN
--         SIGNAL SQLSTATE '45000'
--             SET MESSAGE_TEXT = 'Status Name is required';
--     END IF;

--     IF PSTATUSGRP IS NULL OR TRIM(PSTATUSGRP) = '' THEN
--         SIGNAL SQLSTATE '45000'
--             SET MESSAGE_TEXT = 'Status Group is required';
--     END IF;

--     START TRANSACTION;

--     INSERT INTO CMS_STATUS (STATUSCODE, STATUSNAME, STATUSGRP, DESCR)
--     VALUES (TRIM(PSTATUSCODE), TRIM(PSTATUSNAME), TRIM(PSTATUSGRP), PDESCR);

--     SET VSTATUSID = LAST_INSERT_ID();

--     COMMIT;

--     SELECT VSTATUSID AS STATUSID;
-- END$$


-- CREATE PROCEDURE CMSUPDSTATUS (
--     IN PSTATUSID   INT,
--     IN PSTATUSNAME VARCHAR(50),
--     IN PSTATUSGRP  VARCHAR(30),
--     IN PDESCR      VARCHAR(255)
-- )
-- BEGIN
--     DECLARE VCOUNT INT DEFAULT 0;

--     DECLARE EXIT HANDLER FOR SQLEXCEPTION
--     BEGIN
--         ROLLBACK;
--         RESIGNAL;
--     END;

--     IF PSTATUSID IS NULL THEN
--         SIGNAL SQLSTATE '45000'
--             SET MESSAGE_TEXT = 'Status ID is required';
--     END IF;

--     SELECT COUNT(*) INTO VCOUNT
--     FROM   CMS_STATUS
--     WHERE  STATUSID = PSTATUSID;

--     IF VCOUNT = 0 THEN
--         SIGNAL SQLSTATE '45000'
--             SET MESSAGE_TEXT = 'Status not found';
--     END IF;

--     IF PSTATUSNAME IS NULL OR TRIM(PSTATUSNAME) = '' THEN
--         SIGNAL SQLSTATE '45000'
--             SET MESSAGE_TEXT = 'Status Name is required';
--     END IF;

--     IF PSTATUSGRP IS NULL OR TRIM(PSTATUSGRP) = '' THEN
--         SIGNAL SQLSTATE '45000'
--             SET MESSAGE_TEXT = 'Status Group is required';
--     END IF;

--     START TRANSACTION;

--     UPDATE CMS_STATUS
--     SET    STATUSNAME = TRIM(PSTATUSNAME),
--            STATUSGRP  = TRIM(PSTATUSGRP),
--            DESCR      = PDESCR,
--            UPDATEDAT  = CURRENT_TIMESTAMP
--     WHERE  STATUSID   = PSTATUSID;

--     COMMIT;

--     SELECT PSTATUSID AS STATUSID;
-- END$$


-- CREATE PROCEDURE CMSGETSTATUS (
--     IN PSTATUSID INT
-- )
-- BEGIN
--     SELECT STATUSID, STATUSCODE, STATUSNAME, STATUSGRP,
--            DESCR, ISACTIVE, CREATEDAT, UPDATEDAT
--     FROM   CMS_STATUS
--     WHERE  STATUSID = PSTATUSID;
-- END$$


-- CREATE PROCEDURE CMSLISTSTATUS (
--     IN PSTATUSGRP VARCHAR(30)
-- )
-- BEGIN
--     SELECT STATUSID, STATUSCODE, STATUSNAME, STATUSGRP,
--            DESCR, ISACTIVE, CREATEDAT, UPDATEDAT
--     FROM   CMS_STATUS
--     WHERE  (PSTATUSGRP IS NULL OR STATUSGRP = PSTATUSGRP)
--     ORDER BY STATUSGRP, STATUSCODE;
-- END$$


-- CREATE PROCEDURE CMSACTSTATUS (
--     IN PSTATUSID INT
-- )
-- BEGIN
--     DECLARE VCOUNT INT DEFAULT 0;

--     DECLARE EXIT HANDLER FOR SQLEXCEPTION
--     BEGIN
--         ROLLBACK;
--         RESIGNAL;
--     END;

--     IF PSTATUSID IS NULL THEN
--         SIGNAL SQLSTATE '45000'
--             SET MESSAGE_TEXT = 'Status ID is required';
--     END IF;

--     SELECT COUNT(*) INTO VCOUNT
--     FROM   CMS_STATUS
--     WHERE  STATUSID = PSTATUSID;

--     IF VCOUNT = 0 THEN
--         SIGNAL SQLSTATE '45000'
--             SET MESSAGE_TEXT = 'Status not found';
--     END IF;

--     START TRANSACTION;

--     UPDATE CMS_STATUS
--     SET    ISACTIVE  = 1,
--            UPDATEDAT = CURRENT_TIMESTAMP
--     WHERE  STATUSID  = PSTATUSID;

--     COMMIT;

--     SELECT PSTATUSID AS STATUSID;
-- END$$


-- CREATE PROCEDURE CMSDEACTSTATUS (
--     IN PSTATUSID INT
-- )
-- BEGIN
--     DECLARE VCOUNT INT DEFAULT 0;

--     DECLARE EXIT HANDLER FOR SQLEXCEPTION
--     BEGIN
--         ROLLBACK;
--         RESIGNAL;
--     END;

--     IF PSTATUSID IS NULL THEN
--         SIGNAL SQLSTATE '45000'
--             SET MESSAGE_TEXT = 'Status ID is required';
--     END IF;

--     SELECT COUNT(*) INTO VCOUNT
--     FROM   CMS_STATUS
--     WHERE  STATUSID = PSTATUSID;

--     IF VCOUNT = 0 THEN
--         SIGNAL SQLSTATE '45000'
--             SET MESSAGE_TEXT = 'Status not found';
--     END IF;

--     START TRANSACTION;

--     UPDATE CMS_STATUS
--     SET    ISACTIVE  = 0,
--            UPDATEDAT = CURRENT_TIMESTAMP
--     WHERE  STATUSID  = PSTATUSID;

--     COMMIT;

--     SELECT PSTATUSID AS STATUSID;
-- END$$

/* ============================================================
   CMS_STATUS — System-wide status lookup
   ============================================================ */

CREATE PROCEDURE CMSADDSTATUS (
    IN PSTATUSID   INT,             -- Must be provided manually
    IN PSTATUSCODE VARCHAR(10),
    IN PSTATUSNAME VARCHAR(50),
    IN PSTATUSGRP  VARCHAR(30),
    IN PDESCR      VARCHAR(255)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    -- Validate explicit ID
    IF PSTATUSID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Status ID is required (Manual ID mapping)';
    END IF;

    IF PSTATUSCODE IS NULL OR TRIM(PSTATUSCODE) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Status Code is required';
    END IF;

    IF PSTATUSNAME IS NULL OR TRIM(PSTATUSNAME) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Status Name is required';
    END IF;

    IF PSTATUSGRP IS NULL OR TRIM(PSTATUSGRP) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Status Group is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_STATUS (STATUSID, STATUSCODE, STATUSNAME, STATUSGRP, DESCR)
    VALUES (PSTATUSID, TRIM(PSTATUSCODE), TRIM(PSTATUSNAME), TRIM(PSTATUSGRP), PDESCR);

    COMMIT;

    SELECT PSTATUSID AS STATUSID;
END$$


CREATE PROCEDURE CMSUPDSTATUS (
    IN PSTATUSID   INT,
    IN PSTATUSNAME VARCHAR(50),
    IN PSTATUSGRP  VARCHAR(30),
    IN PDESCR      VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PSTATUSID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Status ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM   CMS_STATUS
    WHERE  STATUSID = PSTATUSID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Status not found';
    END IF;

    IF PSTATUSNAME IS NULL OR TRIM(PSTATUSNAME) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Status Name is required';
    END IF;

    IF PSTATUSGRP IS NULL OR TRIM(PSTATUSGRP) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Status Group is required';
    END IF;

    START TRANSACTION;

    UPDATE CMS_STATUS
    SET    STATUSNAME = TRIM(PSTATUSNAME),
           STATUSGRP  = TRIM(PSTATUSGRP),
           DESCR      = PDESCR,
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  STATUSID   = PSTATUSID;

    COMMIT;

    SELECT PSTATUSID AS STATUSID;
END$$


CREATE PROCEDURE CMSGETSTATUS (
    IN PSTATUSID INT
)
BEGIN
    SELECT STATUSID, STATUSCODE, STATUSNAME, STATUSGRP,
           DESCR, ISACTIVE, CREATEDAT, UPDATEDAT
    FROM   CMS_STATUS
    WHERE  STATUSID = PSTATUSID;
END$$


CREATE PROCEDURE CMSLISTSTATUS (
    IN PSTATUSGRP VARCHAR(30)
)
BEGIN
    SELECT STATUSID, STATUSCODE, STATUSNAME, STATUSGRP,
           DESCR, ISACTIVE, CREATEDAT, UPDATEDAT
    FROM   CMS_STATUS
    WHERE  (PSTATUSGRP IS NULL OR STATUSGRP = PSTATUSGRP)
    ORDER BY STATUSGRP, STATUSCODE;
END$$


CREATE PROCEDURE CMSACTSTATUS (
    IN PSTATUSID INT
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PSTATUSID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Status ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM   CMS_STATUS
    WHERE  STATUSID = PSTATUSID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Status not found';
    END IF;

    START TRANSACTION;

    UPDATE CMS_STATUS
    SET    ISACTIVE  = 1,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  STATUSID  = PSTATUSID;

    COMMIT;

    SELECT PSTATUSID AS STATUSID;
END$$


CREATE PROCEDURE CMSDEACTSTATUS (
    IN PSTATUSID INT
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PSTATUSID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Status ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM   CMS_STATUS
    WHERE  STATUSID = PSTATUSID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Status not found';
    END IF;

    START TRANSACTION;

    UPDATE CMS_STATUS
    SET    ISACTIVE  = 0,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  STATUSID  = PSTATUSID;

    COMMIT;

    SELECT PSTATUSID AS STATUSID;
END$$

/* ============================================================
   CMS_CUSTTYPE — Customer Type Master
   ============================================================ */

CREATE PROCEDURE CMSADDCUSTTYPE (
    IN PCTYPECODE VARCHAR(20),
    IN PCTYPENAME VARCHAR(80),
    IN PDESCR     VARCHAR(255)
)
BEGIN
    DECLARE VCTYPEID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PCTYPECODE IS NULL OR TRIM(PCTYPECODE) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer Type Code is required';
    END IF;

    IF PCTYPENAME IS NULL OR TRIM(PCTYPENAME) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer Type Name is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_CUSTTYPE (CTYPECODE, CTYPENAME, DESCR)
    VALUES (TRIM(PCTYPECODE), TRIM(PCTYPENAME), PDESCR);

    SET VCTYPEID = LAST_INSERT_ID();

    COMMIT;

    SELECT VCTYPEID AS CTYPEID;
END$$


CREATE PROCEDURE CMSUPDCUSTTYPE (
    IN PCTYPEID   INT,
    IN PCTYPENAME VARCHAR(80),
    IN PDESCR     VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PCTYPEID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer Type ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM   CMS_CUSTTYPE
    WHERE  CTYPEID = PCTYPEID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer Type not found';
    END IF;

    IF PCTYPENAME IS NULL OR TRIM(PCTYPENAME) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer Type Name is required';
    END IF;

    START TRANSACTION;

    UPDATE CMS_CUSTTYPE
    SET    CTYPENAME = TRIM(PCTYPENAME),
           DESCR     = PDESCR,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  CTYPEID   = PCTYPEID;

    COMMIT;

    SELECT PCTYPEID AS CTYPEID;
END$$


CREATE PROCEDURE CMSGETCUSTTYPE (
    IN PCTYPEID INT
)
BEGIN
    SELECT CTYPEID, CTYPECODE, CTYPENAME, DESCR,
           ISACTIVE, CREATEDAT, UPDATEDAT
    FROM   CMS_CUSTTYPE
    WHERE  CTYPEID = PCTYPEID;
END$$


CREATE PROCEDURE CMSLISTCUSTTYPE ()
BEGIN
    SELECT CTYPEID, CTYPECODE, CTYPENAME, DESCR,
           ISACTIVE, CREATEDAT, UPDATEDAT
    FROM   CMS_CUSTTYPE
    ORDER BY CTYPECODE;
END$$


CREATE PROCEDURE CMSACTCUSTTYPE (
    IN PCTYPEID INT
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PCTYPEID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer Type ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM   CMS_CUSTTYPE
    WHERE  CTYPEID = PCTYPEID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer Type not found';
    END IF;

    START TRANSACTION;

    UPDATE CMS_CUSTTYPE
    SET    ISACTIVE  = 1,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  CTYPEID   = PCTYPEID;

    COMMIT;

    SELECT PCTYPEID AS CTYPEID;
END$$


CREATE PROCEDURE CMSDEACTCUSTTYPE (
    IN PCTYPEID INT
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PCTYPEID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer Type ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM   CMS_CUSTTYPE
    WHERE  CTYPEID = PCTYPEID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer Type not found';
    END IF;

    START TRANSACTION;

    UPDATE CMS_CUSTTYPE
    SET    ISACTIVE  = 0,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  CTYPEID   = PCTYPEID;

    COMMIT;

    SELECT PCTYPEID AS CTYPEID;
END$$


/* ============================================================
   CMS_SCREEN — Application Screen Configuration
   ============================================================ */

CREATE PROCEDURE CMSADDSCREEN (
    IN PSCREENCODE VARCHAR(50),
    IN PSCREENNAME VARCHAR(100),
    IN PDESCR      VARCHAR(255),
    IN PROUTEPATH  VARCHAR(150),
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VSCREENID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PSCREENCODE IS NULL OR TRIM(PSCREENCODE) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Screen Code is required';
    END IF;

    IF PSCREENNAME IS NULL OR TRIM(PSCREENNAME) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Screen Name is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_SCREEN (SCREENCODE, SCREENNAME, DESCR, ROUTEPATH, CREATEDBY)
    VALUES (TRIM(PSCREENCODE), TRIM(PSCREENNAME), PDESCR, PROUTEPATH, PCREATEDBY);

    SET VSCREENID = LAST_INSERT_ID();

    COMMIT;

    SELECT VSCREENID AS SCREENID;
END$$


CREATE PROCEDURE CMSUPDSCREEN (
    IN PSCREENID   INT,
    IN PSCREENNAME VARCHAR(100),
    IN PDESCR      VARCHAR(255),
    IN PROUTEPATH  VARCHAR(150)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PSCREENID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Screen ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM   CMS_SCREEN
    WHERE  SCREENID = PSCREENID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Screen not found';
    END IF;

    IF PSCREENNAME IS NULL OR TRIM(PSCREENNAME) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Screen Name is required';
    END IF;

    START TRANSACTION;

    UPDATE CMS_SCREEN
    SET    SCREENNAME = TRIM(PSCREENNAME),
           DESCR      = PDESCR,
           ROUTEPATH  = PROUTEPATH,
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  SCREENID   = PSCREENID;

    COMMIT;

    SELECT PSCREENID AS SCREENID;
END$$


CREATE PROCEDURE CMSGETSCREEN (
    IN PSCREENID INT
)
BEGIN
    SELECT SCREENID, SCREENCODE, SCREENNAME, DESCR,
           ROUTEPATH, ISACTIVE, CREATEDBY, CREATEDAT, UPDATEDAT
    FROM   CMS_SCREEN
    WHERE  SCREENID = PSCREENID;
END$$


CREATE PROCEDURE CMSLISTSCREEN ()
BEGIN
    SELECT SCREENID, SCREENCODE, SCREENNAME, DESCR,
           ROUTEPATH, ISACTIVE, CREATEDBY, CREATEDAT, UPDATEDAT
    FROM   CMS_SCREEN
    ORDER BY SCREENCODE;
END$$


CREATE PROCEDURE CMSACTSCREEN (
    IN PSCREENID INT
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PSCREENID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Screen ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM   CMS_SCREEN
    WHERE  SCREENID = PSCREENID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Screen not found';
    END IF;

    START TRANSACTION;

    UPDATE CMS_SCREEN
    SET    ISACTIVE  = 1,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  SCREENID  = PSCREENID;

    COMMIT;

    SELECT PSCREENID AS SCREENID;
END$$


CREATE PROCEDURE CMSDEACTSCREEN (
    IN PSCREENID INT
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PSCREENID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Screen ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM   CMS_SCREEN
    WHERE  SCREENID = PSCREENID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Screen not found';
    END IF;

    START TRANSACTION;

    UPDATE CMS_SCREEN
    SET    ISACTIVE  = 0,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  SCREENID  = PSCREENID;

    COMMIT;

    SELECT PSCREENID AS SCREENID;
END$$


/* ============================================================
   CMS_ROLESCN — Role-to-Screen Permission Mapping
   ============================================================ */

CREATE PROCEDURE CMSSETROLESCN (
    IN PROLEID    INT,
    IN PSCREENID  INT,
    IN PCANVIEW   TINYINT,
    IN PCANCREATE TINYINT,
    IN PCANUPDATE TINYINT,
    IN PCANDELETE TINYINT
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PROLEID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Role ID is required';
    END IF;

    IF PSCREENID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Screen ID is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_ROLESCN (ROLEID, SCREENID, CANVIEW, CANCREATE, CANUPDATE, CANDELETE)
    VALUES (PROLEID, PSCREENID,
            COALESCE(PCANVIEW, 0),
            COALESCE(PCANCREATE, 0),
            COALESCE(PCANUPDATE, 0),
            COALESCE(PCANDELETE, 0))
    ON DUPLICATE KEY UPDATE
        CANVIEW   = COALESCE(PCANVIEW, CANVIEW),
        CANCREATE = COALESCE(PCANCREATE, CANCREATE),
        CANUPDATE = COALESCE(PCANUPDATE, CANUPDATE),
        CANDELETE = COALESCE(PCANDELETE, CANDELETE),
        ISACTIVE  = 1,
        UPDATEDAT = CURRENT_TIMESTAMP;

    COMMIT;

    SELECT PROLEID AS ROLEID, PSCREENID AS SCREENID;
END$$


CREATE PROCEDURE CMSGETROLESCN (
    IN PROLEID   INT,
    IN PSCREENID INT
)
BEGIN
    SELECT RS.ROLESCNID, RS.ROLEID, R.ROLECODE, R.ROLENAME,
           RS.SCREENID, SC.SCREENCODE, SC.SCREENNAME,
           RS.CANVIEW, RS.CANCREATE, RS.CANUPDATE, RS.CANDELETE,
           RS.ISACTIVE, RS.CREATEDAT, RS.UPDATEDAT
    FROM   CMS_ROLESCN RS
    JOIN   CMS_ROLE R    ON R.ROLEID   = RS.ROLEID
    JOIN   CMS_SCREEN SC ON SC.SCREENID = RS.SCREENID
    WHERE  RS.ROLEID   = PROLEID
      AND  RS.SCREENID = PSCREENID;
END$$


CREATE PROCEDURE CMSLISTROLESCN (
    IN PROLEID INT
)
BEGIN
    SELECT RS.ROLESCNID, RS.ROLEID, R.ROLECODE, R.ROLENAME,
           RS.SCREENID, SC.SCREENCODE, SC.SCREENNAME, SC.ROUTEPATH,
           RS.CANVIEW, RS.CANCREATE, RS.CANUPDATE, RS.CANDELETE,
           RS.ISACTIVE, RS.CREATEDAT, RS.UPDATEDAT
    FROM   CMS_ROLESCN RS
    JOIN   CMS_ROLE R    ON R.ROLEID   = RS.ROLEID
    JOIN   CMS_SCREEN SC ON SC.SCREENID = RS.SCREENID
    WHERE  RS.ROLEID = PROLEID
      AND  RS.ISACTIVE = 1
    ORDER BY SC.SCREENCODE;
END$$


CREATE PROCEDURE CMSREMOVEROLESCN (
    IN PROLEID   INT,
    IN PSCREENID INT
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PROLEID IS NULL OR PSCREENID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Role ID and Screen ID are required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM   CMS_ROLESCN
    WHERE  ROLEID   = PROLEID
      AND  SCREENID = PSCREENID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Role-Screen mapping not found';
    END IF;

    START TRANSACTION;

    UPDATE CMS_ROLESCN
    SET    ISACTIVE  = 0,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  ROLEID   = PROLEID
      AND  SCREENID = PSCREENID;

    COMMIT;

    SELECT PROLEID AS ROLEID, PSCREENID AS SCREENID;
END$$


/* ============================================================
   CMS_AUTONOS — Auto-Number Configuration Management
   ============================================================ */

CREATE PROCEDURE CMSADDAUTONO (
    IN PTBLNAME    VARCHAR(50),
    IN PDATAITEM   VARCHAR(30),
    IN PITEMLEN    INT,
    IN PFLDTYPE    VARCHAR(10),
    IN PPREFIXCHAR VARCHAR(5),
    IN PSTARTNO    BIGINT,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VAUTONOID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PTBLNAME IS NULL OR TRIM(PTBLNAME) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Table Name is required';
    END IF;

    IF PDATAITEM IS NULL OR TRIM(PDATAITEM) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Data Item is required';
    END IF;

    IF PPREFIXCHAR IS NULL OR TRIM(PPREFIXCHAR) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Prefix Character is required';
    END IF;

    IF PITEMLEN IS NULL OR PITEMLEN < 1 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Item Length must be at least 1';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_AUTONOS (
        TBLNAME, DATAITEM, ITEMLEN, FLDTYPE, PREFIXCHAR,
        STARTNO, STARTDATE, LASTNO, STATUS, CREATEDBY
    )
    VALUES (
        TRIM(PTBLNAME), TRIM(PDATAITEM), PITEMLEN,
        COALESCE(PFLDTYPE, 'CHAR'), TRIM(PPREFIXCHAR),
        COALESCE(PSTARTNO, 1), CURRENT_DATE, 0, 'A', PCREATEDBY
    );

    SET VAUTONOID = LAST_INSERT_ID();

    COMMIT;

    SELECT VAUTONOID AS AUTONOID;
END$$


CREATE PROCEDURE CMSUPDAUTONO (
    IN PAUTONOID   INT,
    IN PITEMLEN    INT,
    IN PPREFIXCHAR VARCHAR(5),
    IN PSTATUS     VARCHAR(10)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PAUTONOID IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Auto Number ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM   CMS_AUTONOS
    WHERE  AUTONOID = PAUTONOID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Auto Number configuration not found';
    END IF;

    START TRANSACTION;

    UPDATE CMS_AUTONOS
    SET    ITEMLEN    = COALESCE(PITEMLEN, ITEMLEN),
           PREFIXCHAR = COALESCE(PPREFIXCHAR, PREFIXCHAR),
           STATUS     = COALESCE(PSTATUS, STATUS),
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  AUTONOID   = PAUTONOID;

    COMMIT;

    SELECT PAUTONOID AS AUTONOID;
END$$


CREATE PROCEDURE CMSLISTAUTONO ()
BEGIN
    SELECT AUTONOID, TBLNAME, DATAITEM, ITEMLEN, FLDTYPE,
           PREFIXCHAR, STARTNO, STARTDATE, LASTNO, STATUS,
           CREATEDBY, CREATEDAT, UPDATEDAT
    FROM   CMS_AUTONOS
    ORDER BY TBLNAME, DATAITEM;
END$$


DELIMITER ;
