USE cms_db;

DROP PROCEDURE IF EXISTS CMSASSIGNCONSROL;
DROP PROCEDURE IF EXISTS CMSREMOVECONSROL;
DROP PROCEDURE IF EXISTS CMSLISTCONSROL;

DELIMITER $$
/* ============================================================
   CMS_CONSUMERROLE — Consumer (System-wide) Role Assignment
   Replaces old CMS_USRROLE references.
   ============================================================ */

CREATE PROCEDURE CMSASSIGNCONSROL (
    IN PUSERID     INT,
    IN PROLEID     INT,
    IN PASSIGNEDBY INT,
    IN PVALIDFROM  DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    DECLARE VVALIDFROM DATETIME;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID is required';
    END IF;
    IF PROLEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role ID is required';
    END IF;

    SET VVALIDFROM = COALESCE(PVALIDFROM, CURRENT_TIMESTAMP);

    IF PVALIDUNTIL IS NOT NULL AND PVALIDUNTIL < VVALIDFROM THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Valid until date must be >= valid from date';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_CONSUMERROLE (USERID, ROLEID, ASSIGNEDBY, VALIDFROM, VALIDUNTIL, ISACTIVE)
    VALUES (PUSERID, PROLEID, PASSIGNEDBY, VVALIDFROM, PVALIDUNTIL, 1)
    ON DUPLICATE KEY UPDATE
        ASSIGNEDBY = PASSIGNEDBY,
        VALIDFROM  = VVALIDFROM,
        VALIDUNTIL = PVALIDUNTIL,
        ISACTIVE   = 1,
        ASSIGNEDAT = CURRENT_TIMESTAMP;

    COMMIT;
    SELECT PUSERID AS USERID, PROLEID AS ROLEID;
END$$


CREATE PROCEDURE CMSREMOVECONSROL (
    IN PUSERID INT,
    IN PROLEID INT
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL OR PROLEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID and Role ID are required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CONSUMERROLE WHERE USERID = PUSERID AND ROLEID = PROLEID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Consumer role assignment not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CONSUMERROLE
    SET    ISACTIVE = 0
    WHERE  USERID = PUSERID AND ROLEID = PROLEID;
    COMMIT;

    SELECT PUSERID AS USERID, PROLEID AS ROLEID;
END$$


CREATE PROCEDURE CMSLISTCONSROL (IN PUSERID INT)
BEGIN
    SELECT CR.USRROLEID, CR.USERID, CR.ROLEID,
           R.ROLECODE, R.ROLENAME,
           CR.ASSIGNEDBY, CR.ASSIGNEDAT,
           CR.VALIDFROM, CR.VALIDUNTIL, CR.ISACTIVE
    FROM   CMS_CONSUMERROLE CR
    JOIN   CMS_ROLE R ON R.ROLEID = CR.ROLEID
    WHERE  CR.USERID = PUSERID
    ORDER BY R.ROLECODE;
END$$



DELIMITER ;

