-- USE cms_db;

-- DROP PROCEDURE IF EXISTS CMSVIEWMENU;
-- DROP PROCEDURE IF EXISTS CMSREPLACEDMENUITEMS;
-- DROP PROCEDURE IF EXISTS CMSSUBMITDMENU;
-- DROP PROCEDURE IF EXISTS CMSAPPROVEDMENU;
-- DROP PROCEDURE IF EXISTS CMSREJECTDMENU;
-- DROP PROCEDURE IF EXISTS CMSGETDMENUWORKSPACE;
-- DROP PROCEDURE IF EXISTS CMSLISTPENDINGDMENUS;

-- DELIMITER $$

-- /* ============================================================
--    CMS_DAYMENU — Batch Day Menu Procedures
--    ============================================================ */

-- CREATE PROCEDURE CMSREPLACEDMENUITEMS (
--     IN PDAYSLOTID INT,
--     IN PITEMSJSON JSON,
--     IN PUSERID    INT,
--     IN PREMARKS   VARCHAR(255)
-- )
-- BEGIN
--     DECLARE VSLOTSTATUS VARCHAR(20);
--     DECLARE VSERVDATE   DATE;
--     DECLARE VAPPRSTATUS VARCHAR(3);
--     DECLARE VMISSING    VARCHAR(255);
    
--     DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

--     IF PDAYSLOTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required'; END IF;
--     IF PITEMSJSON IS NULL OR JSON_TYPE(PITEMSJSON) <> 'ARRAY' THEN
--         SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Items JSON array is required';
--     END IF;
    
--     SELECT STATUS, SERVDATE, MENUAPPRSTATUS INTO VSLOTSTATUS, VSERVDATE, VAPPRSTATUS
--     FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    
--     IF VSLOTSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
--     IF VSLOTSTATUS <> 'A' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot must be active'; END IF;
    
--     SELECT GROUP_CONCAT(DISTINCT CONCAT(MI.MENUITEMID, ' missing ', CT.CTYPECODE)) INTO VMISSING
--     FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
--         MENUITEMID INT PATH '$.MENUITEMID'
--     )) JT
--     JOIN CMS_MENUITEM MI ON MI.MENUITEMID = JT.MENUITEMID
--     CROSS JOIN CMS_CUSTTYPE CT
--     WHERE CT.ISACTIVE = 1
--       AND NOT EXISTS (
--           SELECT 1
--           FROM CMS_ITEMPRICE IP
--           JOIN CMS_ITEMPRICEDT IPD ON IP.ITEMPRICEID = IPD.ITEMPRICEID
--           WHERE IP.MENUITEMID = JT.MENUITEMID
--             AND IP.EFFFROM <= VSERVDATE
--             AND IP.STATUS = 'A'
--             AND IPD.CTYPECODE = CT.CTYPECODE
--             AND IP.ITEMPRICEID = (
--                 SELECT IP2.ITEMPRICEID
--                 FROM CMS_ITEMPRICE IP2
--                 WHERE IP2.MENUITEMID = JT.MENUITEMID
--                   AND IP2.EFFFROM <= VSERVDATE
--                   AND IP2.STATUS = 'A'
--                 ORDER BY IP2.EFFFROM DESC
--                 LIMIT 1
--             )
--       );

--     IF VMISSING IS NOT NULL THEN
--         SET @MSG = CONCAT('Price missing for: ', VMISSING);
--         SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @MSG;
--     END IF;

--     START TRANSACTION;
    
--     DELETE FROM CMS_DAYMENU WHERE DAYSLOTID = PDAYSLOTID;
    
--     INSERT INTO CMS_DAYMENU (DAYSLOTID, MENUITEMID, ISBASE, ISSPECIAL, ISPREBOOK, ISKIOSK,
--            BOOKUNTIL, CANCELUNTIL, AVAILQTY, MAXQTY, STATUS, CREATEDBY)
--     SELECT PDAYSLOTID, JT.MENUITEMID, COALESCE(JT.ISBASE, 1), COALESCE(JT.ISSPECIAL, 0), COALESCE(JT.ISPREBOOK, 1), COALESCE(JT.ISKIOSK, 1),
--            JT.BOOKUNTIL, JT.CANCELUNTIL, JT.AVAILQTY, JT.MAXQTY, 'A', PUSERID
--     FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
--         MENUITEMID  INT PATH '$.MENUITEMID',
--         ISBASE      TINYINT PATH '$.ISBASE',
--         ISSPECIAL   TINYINT PATH '$.ISSPECIAL',
--         ISPREBOOK   TINYINT PATH '$.ISPREBOOK',
--         ISKIOSK     TINYINT PATH '$.ISKIOSK',
--         BOOKUNTIL   DATETIME PATH '$.BOOKUNTIL',
--         CANCELUNTIL DATETIME PATH '$.CANCELUNTIL',
--         AVAILQTY    INT PATH '$.AVAILQTY',
--         MAXQTY      INT PATH '$.MAXQTY'
--     )) JT;
    
--     INSERT INTO CMS_SLOTHIST (DAYSLOTID, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, STATUS, MENUAPPRSTATUS, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, MENUAPPROVEDAT, MENUREMARKS, CHANGEDBY, CHGREASON)
--     SELECT DAYSLOTID, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, STATUS, 'DRF', NULL, NULL, NULL, NULL, PREMARKS, PUSERID, 'Draft Updated'
--     FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;

--     UPDATE CMS_DAYSLOT 
--     SET MENUAPPRSTATUS = 'DRF', 
--         MENUSUBMITTEDBY = NULL, 
--         MENUSUBMITTEDAT = NULL,
--         MENUAPPROVEDBY = NULL,
--         MENUAPPROVEDAT = NULL,
--         MENUREMARKS = PREMARKS,
--         UPDATEDAT = CURRENT_TIMESTAMP
--     WHERE DAYSLOTID = PDAYSLOTID;

--     -- Update DMENUNO since we bypassed CMSADDDMENU logic
--     UPDATE CMS_DAYMENU SET DMENUNO = CONCAT('DM', LPAD(DAYMENUID, 8, '0')) WHERE DAYSLOTID = PDAYSLOTID;

--     COMMIT;
    
--     SELECT PDAYSLOTID AS DAYSLOTID;
-- END$$


-- CREATE PROCEDURE CMSSUBMITDMENU (
--     IN PDAYSLOTID INT,
--     IN PUSERID    INT,
--     IN PREMARKS   VARCHAR(255)
-- )
-- BEGIN
--     DECLARE VAPPRSTATUS VARCHAR(3);
--     DECLARE VBASECOUNT INT DEFAULT 0;
--     DECLARE VMISSING    VARCHAR(255);
--     DECLARE VSERVDATE   DATE;
    
--     DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

--     SELECT MENUAPPRSTATUS, SERVDATE INTO VAPPRSTATUS, VSERVDATE FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
--     IF VAPPRSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
--     IF VAPPRSTATUS NOT IN ('DRF', 'REJ') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only Draft or Rejected menus can be submitted'; END IF;
    
--     SELECT COUNT(*) INTO VBASECOUNT FROM CMS_DAYMENU WHERE DAYSLOTID = PDAYSLOTID AND ISBASE = 1 AND STATUS = 'A';
--     IF VBASECOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'At least one active base item is required'; END IF;

--     SELECT GROUP_CONCAT(DISTINCT CONCAT(MI.MENUITEMID, ' missing ', CT.CTYPECODE)) INTO VMISSING
--     FROM CMS_DAYMENU DM
--     JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
--     CROSS JOIN CMS_CUSTTYPE CT
--     WHERE DM.DAYSLOTID = PDAYSLOTID
--       AND CT.ISACTIVE = 1
--       AND NOT EXISTS (
--           SELECT 1
--           FROM CMS_ITEMPRICE IP
--           JOIN CMS_ITEMPRICEDT IPD ON IP.ITEMPRICEID = IPD.ITEMPRICEID
--           WHERE IP.MENUITEMID = DM.MENUITEMID
--             AND IP.EFFFROM <= VSERVDATE
--             AND IP.STATUS = 'A'
--             AND IPD.CTYPECODE = CT.CTYPECODE
--             AND IP.ITEMPRICEID = (
--                 SELECT IP2.ITEMPRICEID
--                 FROM CMS_ITEMPRICE IP2
--                 WHERE IP2.MENUITEMID = DM.MENUITEMID
--                   AND IP2.EFFFROM <= VSERVDATE
--                   AND IP2.STATUS = 'A'
--                 ORDER BY IP2.EFFFROM DESC
--                 LIMIT 1
--             )
--       );

--     IF VMISSING IS NOT NULL THEN
--         SET @MSG = CONCAT('Price missing for: ', VMISSING);
--         SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @MSG;
--     END IF;

--     START TRANSACTION;

--     INSERT INTO CMS_SLOTHIST (DAYSLOTID, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, STATUS, MENUAPPRSTATUS, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, MENUAPPROVEDAT, MENUREMARKS, CHANGEDBY, CHGREASON)
--     SELECT DAYSLOTID, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, STATUS, 'PEN', PUSERID, CURRENT_TIMESTAMP, MENUAPPROVEDBY, MENUAPPROVEDAT, PREMARKS, PUSERID, 'Submitted'
--     FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;

--     UPDATE CMS_DAYSLOT 
--     SET MENUAPPRSTATUS = 'PEN', 
--         MENUSUBMITTEDBY = PUSERID, 
--         MENUSUBMITTEDAT = CURRENT_TIMESTAMP,
--         MENUREMARKS = PREMARKS,
--         UPDATEDAT = CURRENT_TIMESTAMP
--     WHERE DAYSLOTID = PDAYSLOTID;

--     COMMIT;
--     SELECT PDAYSLOTID AS DAYSLOTID;
-- END$$


-- CREATE PROCEDURE CMSAPPROVEDMENU (
--     IN PDAYSLOTID INT,
--     IN PUSERID    INT,
--     IN PREMARKS   VARCHAR(255)
-- )
-- BEGIN
--     DECLARE VAPPRSTATUS VARCHAR(3);
--     DECLARE VBASECOUNT INT;
--     DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

--     SELECT MENUAPPRSTATUS INTO VAPPRSTATUS FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
--     IF VAPPRSTATUS <> 'PEN' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only Pending menus can be approved'; END IF;
    
--     SELECT COUNT(*) INTO VBASECOUNT FROM CMS_DAYMENU WHERE DAYSLOTID = PDAYSLOTID AND ISBASE = 1 AND STATUS = 'A';
--     IF VBASECOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'At least one active base item is required'; END IF;

--     START TRANSACTION;

--     INSERT INTO CMS_SLOTHIST (DAYSLOTID, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, STATUS, MENUAPPRSTATUS, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, MENUAPPROVEDAT, MENUREMARKS, CHANGEDBY, CHGREASON)
--     SELECT DAYSLOTID, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, STATUS, 'APP', MENUSUBMITTEDBY, MENUSUBMITTEDAT, PUSERID, CURRENT_TIMESTAMP, PREMARKS, PUSERID, 'Approved'
--     FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;

--     UPDATE CMS_DAYSLOT 
--     SET MENUAPPRSTATUS = 'APP', 
--         MENUAPPROVEDBY = PUSERID, 
--         MENUAPPROVEDAT = CURRENT_TIMESTAMP,
--         MENUREMARKS = PREMARKS,
--         UPDATEDAT = CURRENT_TIMESTAMP
--     WHERE DAYSLOTID = PDAYSLOTID;

--     COMMIT;
--     SELECT PDAYSLOTID AS DAYSLOTID;
-- END$$


-- CREATE PROCEDURE CMSREJECTDMENU (
--     IN PDAYSLOTID INT,
--     IN PUSERID    INT,
--     IN PREMARKS   VARCHAR(255)
-- )
-- BEGIN
--     DECLARE VAPPRSTATUS VARCHAR(3);
--     DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

--     IF PREMARKS IS NULL OR TRIM(PREMARKS) = '' THEN
--         SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Rejection remarks are required';
--     END IF;

--     SELECT MENUAPPRSTATUS INTO VAPPRSTATUS FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
--     IF VAPPRSTATUS <> 'PEN' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only Pending menus can be rejected'; END IF;
    
--     START TRANSACTION;

--     INSERT INTO CMS_SLOTHIST (DAYSLOTID, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, STATUS, MENUAPPRSTATUS, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, MENUAPPROVEDAT, MENUREMARKS, CHANGEDBY, CHGREASON)
--     SELECT DAYSLOTID, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, STATUS, 'REJ', MENUSUBMITTEDBY, MENUSUBMITTEDAT, PUSERID, CURRENT_TIMESTAMP, PREMARKS, PUSERID, 'Rejected'
--     FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;

--     UPDATE CMS_DAYSLOT 
--     SET MENUAPPRSTATUS = 'REJ', 
--         MENUAPPROVEDBY = PUSERID, 
--         MENUAPPROVEDAT = CURRENT_TIMESTAMP,
--         MENUREMARKS = PREMARKS,
--         UPDATEDAT = CURRENT_TIMESTAMP
--     WHERE DAYSLOTID = PDAYSLOTID;

--     COMMIT;
--     SELECT PDAYSLOTID AS DAYSLOTID;
-- END$$


-- CREATE PROCEDURE CMSGETDMENUWORKSPACE (
--     IN PDAYSLOTID INT
-- )
-- BEGIN
--     SELECT DM.DAYMENUID, DM.DMENUNO, DM.DAYSLOTID,
--            DM.MENUITEMID, MI.MENUCODE, MI.ITEMNAME, MI.SHORTNAME,
--            DM.ISBASE, DM.ISSPECIAL, DM.ISPREBOOK, DM.ISKIOSK,
--            DM.AVAILQTY, DM.MAXQTY,
--            DM.BOOKUNTIL, DM.CANCELUNTIL,
--            DM.STATUS,
--            DM.CREATEDBY, DM.CREATEDAT, DM.UPDATEDAT
--     FROM   CMS_DAYMENU DM
--     JOIN   CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
--     WHERE  DM.DAYSLOTID = PDAYSLOTID
--     ORDER BY MI.ITEMNAME;
-- END$$


-- CREATE PROCEDURE CMSLISTPENDINGDMENUS (
--     IN PCANTEENID INT
-- )
-- BEGIN
--     SELECT DS.DAYSLOTID, DS.SERVICEID, S.SERVNAME,
--            DS.CANTEENID, C.CANTEENNAME,
--            DS.SERVDATE, DS.STARTTIME, DS.ENDTIME,
--            DS.STATUS, DS.MENUAPPRSTATUS, DS.MENUSUBMITTEDBY, DS.MENUSUBMITTEDAT
--     FROM   CMS_DAYSLOT DS
--     JOIN   CMS_SERVICE S  ON S.SERVICEID = DS.SERVICEID
--     JOIN   CMS_CANTEEN C  ON C.CANTEENID = DS.CANTEENID
--     WHERE  (PCANTEENID IS NULL OR DS.CANTEENID = PCANTEENID)
--       AND  DS.MENUAPPRSTATUS = 'PEN'
--     ORDER BY DS.SERVDATE, DS.STARTTIME;
-- END$$


-- /* ============================================================
--    CMSVIEWMENU — Published Menu View (Customer-facing)
--    ============================================================ */

-- CREATE PROCEDURE CMSVIEWMENU (
--     IN PCANTEENID INT,
--     IN PSERVDATE  DATE,
--     IN PCTYPECODE VARCHAR(20)
-- )
-- BEGIN
--     SELECT
--         DS.CANTEENID,
--         C.CANTEENNAME,
--         DS.DAYSLOTID,
--         S.SERVICEID,
--         S.SERVCODE,
--         S.SERVNAME,
--         DS.SERVDATE,
--         DS.STARTTIME,
--         DS.ENDTIME,
--         DM.DAYMENUID,
--         DM.DMENUNO,
--         MI.MENUITEMID,
--         MI.MENUCODE,
--         MI.SHORTNAME,
--         MI.ITEMNAME,
--         MI.ITEMDESCR,
--         DM.ISBASE,
--         DM.ISSPECIAL,
--         DM.ISPREBOOK,
--         DM.ISKIOSK,
--         DM.AVAILQTY,
--         DM.MAXQTY,
--         DM.BOOKUNTIL,
--         DM.CANCELUNTIL,
--         (
--             SELECT IPD.PRICE
--             FROM   CMS_ITEMPRICE IP
--             JOIN   CMS_ITEMPRICEDT IPD ON IPD.ITEMPRICEID = IP.ITEMPRICEID
--             WHERE  IP.MENUITEMID  = MI.MENUITEMID
--               AND  IP.EFFFROM    <= DS.SERVDATE
--               AND  IP.STATUS      = 'A'
--               AND  (IPD.CTYPECODE = PCTYPECODE OR IPD.CTYPECODE = 'VIS')
--             ORDER BY 
--               IP.EFFFROM DESC,
--               CASE WHEN IPD.CTYPECODE = PCTYPECODE THEN 1 ELSE 2 END
--             LIMIT 1
--         ) AS DISPLAYPRICE
--     FROM CMS_DAYMENU DM
--     JOIN CMS_DAYSLOT DS  ON DS.DAYSLOTID  = DM.DAYSLOTID
--     JOIN CMS_SERVICE S   ON S.SERVICEID   = DS.SERVICEID
--     JOIN CMS_CANTEEN C   ON C.CANTEENID   = DS.CANTEENID
--     JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
--     WHERE DS.CANTEENID  = PCANTEENID
--       AND DS.SERVDATE  = PSERVDATE
--       AND DS.MENUAPPRSTATUS = 'APP'
--       AND DM.STATUS     = 'A'
--       AND DS.STATUS     = 'A'
--       AND S.STATUS      = 'A'
--       AND MI.STATUS     = 'A'
--       AND CURRENT_TIMESTAMP <= DM.BOOKUNTIL
--     ORDER BY DS.STARTTIME, S.SERVNAME, MI.ITEMNAME;
-- END$$

-- -- ------------------------------------------------------------
-- -- CMSGETDAYMENUBYID - Fetches a specific day menu by ID along with its menu item details
-- -- ------------------------------------------------------------
-- CREATE PROCEDURE CMSGETDAYMENUBYID (
--     IN PDAYMENUID INT
-- )
-- BEGIN
--     SELECT DM.*, MI.ITEMNAME 
--     FROM CMS_DAYMENU DM 
--     JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID 
--     WHERE DM.DAYMENUID = PDAYMENUID;
-- END$$

-- DELIMITER ;



USE cms_db;

/* --- Drop existing procedures --- */
DROP PROCEDURE IF EXISTS CMSVIEWMENU;
DROP PROCEDURE IF EXISTS CMSREPLACEDMENUITEMS;
DROP PROCEDURE IF EXISTS CMSSUBMITDMENU;
DROP PROCEDURE IF EXISTS CMSAPPROVEDMENU;
DROP PROCEDURE IF EXISTS CMSREJECTDMENU;
DROP PROCEDURE IF EXISTS CMSGETDMENUWORKSPACE;
DROP PROCEDURE IF EXISTS CMSLISTPENDINGDMENUS;
DROP PROCEDURE IF EXISTS CMSGETDAYMENUBYID;

DELIMITER $$

/* ============================================================
   CMS_DAYMENU — Batch Day Menu Procedures
   ============================================================ */

CREATE PROCEDURE CMSREPLACEDMENUITEMS (
    IN PDAYSLOTID INT,
    IN PITEMSJSON JSON,
    IN PUSERID    INT,
    IN PREMARKS   VARCHAR(255)
)
BEGIN
    DECLARE VSLOTSTATUSID INT;
    DECLARE VSERVDATE     DATE;
    DECLARE VAPPRSTATUSID INT;
    DECLARE VMISSING      VARCHAR(255);
    DECLARE VDMENUNO      VARCHAR(20);
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PDAYSLOTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required'; END IF;
    IF PITEMSJSON IS NULL OR JSON_TYPE(PITEMSJSON) <> 'ARRAY' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Items JSON array is required';
    END IF;
    
    SELECT STATUSID, SERVDATE, APPRSTATUSID INTO VSLOTSTATUSID, VSERVDATE, VAPPRSTATUSID
    FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    
    IF VSLOTSTATUSID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
    IF VSLOTSTATUSID <> 10 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot must be active (10 = ACT)'; END IF;
    
    SELECT GROUP_CONCAT(DISTINCT CONCAT(MI.MENUITEMID, ' missing ', CT.CTYPECODE)) INTO VMISSING
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        MENUITEMID INT PATH '$.MENUITEMID'
    )) JT
    JOIN CMS_MENUITEM MI ON MI.MENUITEMID = JT.MENUITEMID
    CROSS JOIN CMS_CUSTTYPE CT
    WHERE CT.ISACTIVE = 1
      AND NOT EXISTS (
          SELECT 1
          FROM CMS_ITEMPRICE IP
          JOIN CMS_ITEMPRICEDT IPD ON IP.ITEMPRICEID = IPD.ITEMPRICEID
          JOIN CMS_STATUS IPST ON IPST.STATUSID = IP.STATUSID
          WHERE IP.MENUITEMID = JT.MENUITEMID
            AND IP.EFFFROM <= VSERVDATE
            AND IPST.STATUSCODE = 'ACT'
            AND IPD.CTYPECODE = CT.CTYPECODE
            AND IP.ITEMPRICEID = (
                SELECT IP2.ITEMPRICEID
                FROM CMS_ITEMPRICE IP2
                JOIN CMS_STATUS IPST2 ON IPST2.STATUSID = IP2.STATUSID
                WHERE IP2.MENUITEMID = JT.MENUITEMID
                  AND IP2.EFFFROM <= VSERVDATE
                  AND IPST2.STATUSCODE = 'ACT'
                ORDER BY IP2.EFFFROM DESC
                LIMIT 1
            )
      );

    IF VMISSING IS NOT NULL THEN
        SET @MSG = CONCAT('Price missing for: ', VMISSING);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @MSG;
    END IF;

    START TRANSACTION;
    
    DELETE FROM CMS_DAYMENU WHERE DAYSLOTID = PDAYSLOTID;
    
    -- Loop / Insert via JSON Table. Note: For bulk inserts with AUTONO, 
    -- we handle individual generation or a cursor if strict sequence ordering per item is required.
    -- Here we insert row-by-row or call CMSGENAUTO for each mapped item element.
    
    -- Temporary approach: Iterate or insert items securely with unique auto-numbers.
    -- For demonstration of bulk JSON mapping with autono, we use a cursor or individual generation:
    -- (Standardizing batch inserts with individual auto-numbers:)
    
    -- Let's process the JSON array items with a secure cursor approach:
    BEGIN
        DECLARE done INT DEFAULT FALSE;
        DECLARE v_menuitemid INT;
        DECLARE v_isbase TINYINT;
        DECLARE v_isspecial TINYINT;
        DECLARE v_isprebook TINYINT;
        DECLARE v_iskiosk TINYINT;
        DECLARE v_bookuntil DATETIME;
        DECLARE v_canceluntil DATETIME;
        DECLARE v_availqty INT;
        DECLARE v_maxqty INT;
        
        DECLARE cur CURSOR FOR 
            SELECT MENUITEMID, COALESCE(ISBASE, 1), COALESCE(ISSPECIAL, 0), 
                   COALESCE(ISPREBOOK, 1), COALESCE(ISKIOSK, 1), 
                   BOOKUNTIL, CANCELUNTIL, AVAILQTY, MAXQTY
            FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
                MENUITEMID  INT PATH '$.MENUITEMID',
                ISBASE      TINYINT PATH '$.ISBASE',
                ISSPECIAL   TINYINT PATH '$.ISSPECIAL',
                ISPREBOOK   TINYINT PATH '$.ISPREBOOK',
                ISKIOSK     TINYINT PATH '$.ISKIOSK',
                BOOKUNTIL   DATETIME PATH '$.BOOKUNTIL',
                CANCELUNTIL DATETIME PATH '$.CANCELUNTIL',
                AVAILQTY    INT PATH '$.AVAILQTY',
                MAXQTY      INT PATH '$.MAXQTY'
            )) JT;
            
        DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
        
        OPEN cur;
        read_loop: LOOP
            FETCH cur INTO v_menuitemid, v_isbase, v_isspecial, v_isprebook, v_iskiosk, 
                           v_bookuntil, v_canceluntil, v_availqty, v_maxqty;
            IF done THEN
                LEAVE read_loop;
            END IF;
            
            -- Generate unique DMENUNO for each item
            CALL CMSGENAUTO('CMS_DAYMENU', 'DMENUNO', VDMENUNO);
            
            INSERT INTO CMS_DAYMENU (
                DMENUNO, DAYSLOTID, MENUITEMID, ISBASE, ISSPECIAL, ISPREBOOK, ISKIOSK,
                BOOKUNTIL, CANCELUNTIL, AVAILQTY, MAXQTY, STATUSID, CREATEDBY
            ) VALUES (
                VDMENUNO, PDAYSLOTID, v_menuitemid, v_isbase, v_isspecial, v_isprebook, v_iskiosk,
                v_bookuntil, v_canceluntil, v_availqty, v_maxqty, 10, PUSERID
            );
        END LOOP;
        CLOSE cur;
    END;
    
    -- Record History (20 = DRF)
    INSERT INTO CMS_SLOTHIST (
        DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
        STATUSID, APPRSTATUSID, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, 
        MENUAPPROVEDAT, MENUREMARKS, CHANGEDBY, CHGREASON
    )
    SELECT 
        DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
        STATUSID, APPRSTATUSID, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, 
        MENUAPPROVEDAT, MENUREMARKS, PUSERID, 'Draft Updated'
    FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;

    UPDATE CMS_DAYSLOT 
    SET APPRSTATUSID = 20, -- 20 = 'DRF'
        MENUSUBMITTEDBY = NULL, 
        MENUSUBMITTEDAT = NULL,
        MENUAPPROVEDBY = NULL,
        MENUAPPROVEDAT = NULL,
        MENUREMARKS = PREMARKS,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE DAYSLOTID = PDAYSLOTID;

    COMMIT;
    SELECT PDAYSLOTID AS DAYSLOTID;
END$$


CREATE PROCEDURE CMSSUBMITDMENU (
    IN PDAYSLOTID INT,
    IN PUSERID    INT,
    IN PREMARKS   VARCHAR(255)
)
BEGIN
    DECLARE VAPPRSTATUSID INT;
    DECLARE VBASECOUNT INT DEFAULT 0;
    DECLARE VMISSING      VARCHAR(255);
    DECLARE VSERVDATE     DATE;
    DECLARE VISMANAGER    INT DEFAULT 0;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    SELECT APPRSTATUSID, SERVDATE INTO VAPPRSTATUSID, VSERVDATE FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    IF VAPPRSTATUSID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
    
    -- 20 = 'DRF', 23 = 'REJ'
    IF VAPPRSTATUSID NOT IN (20, 23) THEN 
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only Draft or Rejected menus can be submitted'; 
    END IF;
    
    -- 10 = 'ACT'
    SELECT COUNT(*) INTO VBASECOUNT 
    FROM CMS_DAYMENU DM 
    JOIN CMS_STATUS ST ON ST.STATUSID = DM.STATUSID
    WHERE DM.DAYSLOTID = PDAYSLOTID AND DM.ISBASE = 1 AND ST.STATUSCODE = 'ACT';
    
    IF VBASECOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'At least one active base item is required'; END IF;

    SELECT GROUP_CONCAT(DISTINCT CONCAT(MI.MENUITEMID, ' missing ', CT.CTYPECODE)) INTO VMISSING
    FROM CMS_DAYMENU DM
    JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    CROSS JOIN CMS_CUSTTYPE CT
    WHERE DM.DAYSLOTID = PDAYSLOTID
      AND CT.ISACTIVE = 1
      AND NOT EXISTS (
          SELECT 1
          FROM CMS_ITEMPRICE IP
          JOIN CMS_ITEMPRICEDT IPD ON IP.ITEMPRICEID = IPD.ITEMPRICEID
          JOIN CMS_STATUS IPST ON IPST.STATUSID = IP.STATUSID
          WHERE IP.MENUITEMID = DM.MENUITEMID
            AND IP.EFFFROM <= VSERVDATE
            AND IPST.STATUSCODE = 'ACT'
            AND IPD.CTYPECODE = CT.CTYPECODE
            AND IP.ITEMPRICEID = (
                SELECT IP2.ITEMPRICEID
                FROM CMS_ITEMPRICE IP2
                JOIN CMS_STATUS IPST2 ON IPST2.STATUSID = IP2.STATUSID
                WHERE IP2.MENUITEMID = DM.MENUITEMID
                  AND IP2.EFFFROM <= VSERVDATE
                  AND IPST2.STATUSCODE = 'ACT'
                ORDER BY IP2.EFFFROM DESC
                LIMIT 1
            )
      );

    IF VMISSING IS NOT NULL THEN
        SET @MSG = CONCAT('Price missing for: ', VMISSING);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @MSG;
    END IF;

    SELECT COUNT(*) INTO VISMANAGER
    FROM CMS_CANTEENROLE CR
    JOIN CMS_ROLE R ON R.ROLEID = CR.ROLEID
    JOIN CMS_DAYSLOT DS ON DS.CANTEENID = CR.CANTEENID
    WHERE DS.DAYSLOTID = PDAYSLOTID
      AND CR.USERID = PUSERID
      AND R.ROLECODE = 'CTNMGR';

    START TRANSACTION;

    IF VISMANAGER > 0 THEN
        INSERT INTO CMS_SLOTHIST (
            DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
            STATUSID, APPRSTATUSID, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, 
            MENUAPPROVEDAT, MENUREMARKS, CHANGEDBY, CHGREASON
        )
        SELECT 
            DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
            STATUSID, 22, PUSERID, CURRENT_TIMESTAMP, PUSERID, CURRENT_TIMESTAMP, PREMARKS, PUSERID, 'Auto-Approved (Manager)'
        FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;

        UPDATE CMS_DAYSLOT 
        SET APPRSTATUSID = 22, -- 22 = 'APP'
            MENUSUBMITTEDBY = PUSERID, 
            MENUSUBMITTEDAT = CURRENT_TIMESTAMP,
            MENUAPPROVEDBY = PUSERID,
            MENUAPPROVEDAT = CURRENT_TIMESTAMP,
            MENUREMARKS = PREMARKS,
            UPDATEDAT = CURRENT_TIMESTAMP
        WHERE DAYSLOTID = PDAYSLOTID;
    ELSE
        INSERT INTO CMS_SLOTHIST (
            DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
            STATUSID, APPRSTATUSID, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, 
            MENUAPPROVEDAT, MENUREMARKS, CHANGEDBY, CHGREASON
        )
        SELECT 
            DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
            STATUSID, 21, PUSERID, CURRENT_TIMESTAMP, MENUAPPROVEDBY, MENUAPPROVEDAT, PREMARKS, PUSERID, 'Submitted'
        FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;

        UPDATE CMS_DAYSLOT 
        SET APPRSTATUSID = 21, -- 21 = 'PEN'
            MENUSUBMITTEDBY = PUSERID, 
            MENUSUBMITTEDAT = CURRENT_TIMESTAMP,
            MENUREMARKS = PREMARKS,
            UPDATEDAT = CURRENT_TIMESTAMP
        WHERE DAYSLOTID = PDAYSLOTID;
    END IF;

    COMMIT;
    SELECT PDAYSLOTID AS DAYSLOTID;
END$$


CREATE PROCEDURE CMSAPPROVEDMENU (
    IN PDAYSLOTID INT,
    IN PUSERID    INT,
    IN PREMARKS   VARCHAR(255)
)
BEGIN
    DECLARE VAPPRSTATUSID INT;
    DECLARE VBASECOUNT INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    SELECT APPRSTATUSID INTO VAPPRSTATUSID FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    -- 21 = 'PEN'
    IF VAPPRSTATUSID <> 21 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only Pending menus can be approved'; END IF;
    
    -- 10 = 'ACT'
    SELECT COUNT(*) INTO VBASECOUNT 
    FROM CMS_DAYMENU DM 
    JOIN CMS_STATUS ST ON ST.STATUSID = DM.STATUSID
    WHERE DM.DAYSLOTID = PDAYSLOTID AND DM.ISBASE = 1 AND ST.STATUSCODE = 'ACT';
    
    IF VBASECOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'At least one active base item is required'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_SLOTHIST (
        DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
        STATUSID, APPRSTATUSID, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, 
        MENUAPPROVEDAT, MENUREMARKS, CHANGEDBY, CHGREASON
    )
    SELECT 
        DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
        STATUSID, 22, MENUSUBMITTEDBY, MENUSUBMITTEDAT, PUSERID, CURRENT_TIMESTAMP, PREMARKS, PUSERID, 'Approved'
    FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;

    UPDATE CMS_DAYSLOT 
    SET APPRSTATUSID = 22, -- 22 = 'APR'
        MENUAPPROVEDBY = PUSERID, 
        MENUAPPROVEDAT = CURRENT_TIMESTAMP,
        MENUREMARKS = PREMARKS,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE DAYSLOTID = PDAYSLOTID;

    COMMIT;
    SELECT PDAYSLOTID AS DAYSLOTID;
END$$


CREATE PROCEDURE CMSREJECTDMENU (
    IN PDAYSLOTID INT,
    IN PUSERID    INT,
    IN PREMARKS   VARCHAR(255)
)
BEGIN
    DECLARE VAPPRSTATUSID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PREMARKS IS NULL OR TRIM(PREMARKS) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Rejection remarks are required';
    END IF;

    SELECT APPRSTATUSID INTO VAPPRSTATUSID FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    -- 21 = 'PEN'
    IF VAPPRSTATUSID <> 21 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only Pending menus can be rejected'; END IF;
    
    START TRANSACTION;

    INSERT INTO CMS_SLOTHIST (
        DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
        STATUSID, APPRSTATUSID, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, 
        MENUAPPROVEDAT, MENUREMARKS, CHANGEDBY, CHGREASON
    )
    SELECT 
        DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
        STATUSID, 23, MENUSUBMITTEDBY, MENUSUBMITTEDAT, PUSERID, CURRENT_TIMESTAMP, PREMARKS, PUSERID, 'Rejected'
    FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;

    UPDATE CMS_DAYSLOT 
    SET APPRSTATUSID = 23, -- 23 = 'REJ'
        MENUAPPROVEDBY = PUSERID, 
        MENUAPPROVEDAT = CURRENT_TIMESTAMP,
        MENUREMARKS = PREMARKS,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE DAYSLOTID = PDAYSLOTID;

    COMMIT;
    SELECT PDAYSLOTID AS DAYSLOTID;
END$$


CREATE PROCEDURE CMSGETDMENUWORKSPACE (
    IN PDAYSLOTID INT
)
BEGIN
    SELECT DM.DAYMENUID, DM.DMENUNO, DM.DAYSLOTID,
           DM.MENUITEMID, MI.MENUCODE, MI.ITEMNAME, MI.SHORTNAME,
           DM.ISBASE, DM.ISSPECIAL, DM.ISPREBOOK, DM.ISKIOSK,
           DM.AVAILQTY, DM.MAXQTY,
           DM.BOOKUNTIL, DM.CANCELUNTIL,
           DM.STATUSID, ST.STATUSCODE AS STATUSCODE,
           DM.CREATEDBY, DM.CREATEDAT, DM.UPDATEDAT
    FROM   CMS_DAYMENU DM
    JOIN   CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    JOIN   CMS_STATUS ST ON ST.STATUSID = DM.STATUSID
    WHERE  DM.DAYSLOTID = PDAYSLOTID
    ORDER BY MI.ITEMNAME;
END$$


CREATE PROCEDURE CMSLISTPENDINGDMENUS (
    IN PCANTEENID INT
)
BEGIN
    SELECT DS.DAYSLOTID, DS.SLOTNO, DS.SERVICEID, S.SERVNAME,
           DS.CANTEENID, C.CANTEENNAME,
           DS.SERVDATE, DS.STARTTIME, DS.ENDTIME,
           DS.STATUSID, DS.APPRSTATUSID, DS.MENUSUBMITTEDBY, DS.MENUSUBMITTEDAT
    FROM   CMS_DAYSLOT DS
    JOIN   CMS_SERVICE S   ON S.SERVICEID = DS.SERVICEID
    JOIN   CMS_CANTEEN C   ON C.CANTEENID = DS.CANTEENID
    JOIN   CMS_STATUS AST  ON AST.STATUSID = DS.APPRSTATUSID
    WHERE  (PCANTEENID IS NULL OR DS.CANTEENID = PCANTEENID)
      AND  AST.STATUSCODE = 'PEN'
    ORDER BY DS.SERVDATE, DS.STARTTIME;
END$$


/* ============================================================
   CMSVIEWMENU — Published Menu View (Customer-facing)
   ============================================================ */

CREATE PROCEDURE CMSVIEWMENU (
    IN PCANTEENID INT,
    IN PSERVDATE  DATE,
    IN PCTYPECODE VARCHAR(20)
)
BEGIN
    SELECT
        DS.CANTEENID,
        C.CANTEENNAME,
        DS.DAYSLOTID,
        S.SERVICEID,
        S.SERVCODE,
        S.SERVNAME,
        DS.SERVDATE,
        DS.STARTTIME,
        DS.ENDTIME,
        DM.DAYMENUID,
        DM.DMENUNO,
        MI.MENUITEMID,
        MI.MENUCODE,
        MI.SHORTNAME,
        MI.ITEMNAME,
        MI.ITEMDESCR,
        DM.ISBASE,
        DM.ISSPECIAL,
        DM.ISPREBOOK,
        DM.ISKIOSK,
        DM.AVAILQTY,
        DM.MAXQTY,
        DM.BOOKUNTIL,
        DM.CANCELUNTIL,
        (
            SELECT IPD.PRICE
            FROM   CMS_ITEMPRICE IP
            JOIN   CMS_ITEMPRICEDT IPD ON IPD.ITEMPRICEID = IP.ITEMPRICEID
            JOIN   CMS_STATUS IPST ON IPST.STATUSID = IP.STATUSID
            WHERE  IP.MENUITEMID  = MI.MENUITEMID
              AND  IP.EFFFROM    <= DS.SERVDATE
              AND  IPST.STATUSCODE = 'ACT'
              AND  (IPD.CTYPECODE = PCTYPECODE OR IPD.CTYPECODE = 'VIS')
            ORDER BY 
              IP.EFFFROM DESC,
              CASE WHEN IPD.CTYPECODE = PCTYPECODE THEN 1 ELSE 2 END
            LIMIT 1
        ) AS DISPLAYPRICE
    FROM CMS_DAYMENU DM
    JOIN CMS_DAYSLOT DS  ON DS.DAYSLOTID  = DM.DAYSLOTID
    JOIN CMS_SERVICE S   ON S.SERVICEID   = DS.SERVICEID
    JOIN CMS_CANTEEN C   ON C.CANTEENID   = DS.CANTEENID
    JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    JOIN CMS_STATUS DS_ST ON DS_ST.STATUSID = DS.STATUSID
    JOIN CMS_STATUS DS_AST ON DS_AST.STATUSID = DS.APPRSTATUSID
    JOIN CMS_STATUS DM_ST ON DM_ST.STATUSID = DM.STATUSID
    JOIN CMS_STATUS S_ST ON S_ST.STATUSID = S.STATUSID
    JOIN CMS_STATUS MI_ST ON MI_ST.STATUSID = MI.STATUSID
    WHERE DS.CANTEENID  = PCANTEENID
      AND DS.SERVDATE   = PSERVDATE
      AND DS_AST.STATUSCODE = 'APR'
      AND DM_ST.STATUSCODE  = 'ACT'
      AND DS_ST.STATUSCODE  = 'ACT'
      AND S_ST.STATUSCODE   = 'ACT'
      AND MI_ST.STATUSCODE  = 'ACT'
      AND CURRENT_TIMESTAMP <= DM.BOOKUNTIL
    ORDER BY DS.STARTTIME, S.SERVNAME, MI.ITEMNAME;
END$$


CREATE PROCEDURE CMSGETDAYMENUBYID (
    IN PDAYMENUID INT
)
BEGIN
    SELECT DM.*, MI.ITEMNAME 
    FROM CMS_DAYMENU DM 
    JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID 
    WHERE DM.DAYMENUID = PDAYMENUID;
END$$

DELIMITER ;