USE cms_db;

/* --- Drop existing procedures --- */
DROP PROCEDURE IF EXISTS CMSADDSLOT;
DROP PROCEDURE IF EXISTS CMSUPDSLOT;
DROP PROCEDURE IF EXISTS CMSGETSLOT;
DROP PROCEDURE IF EXISTS CMSLISTSLOT;
DROP PROCEDURE IF EXISTS CMSACTSLOT;
DROP PROCEDURE IF EXISTS CMSDEACTSLOT;

DELIMITER $$

/* ============================================================
   CMS_DAYSLOT — Dated Service Instance
   A service is reusable across multiple canteens.
   ============================================================ */

CREATE PROCEDURE CMSADDSLOT (
    IN PCANTEENID INT,
    IN PSERVICEID INT,
    IN PSERVDATE  DATE,
    IN PSTARTTIME TIME,
    IN PENDTIME   TIME,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VSERVSTATUSID INT;
    DECLARE VDAYSLOTID    INT;
    DECLARE VSLOTNO       VARCHAR(30);

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCANTEENID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required'; END IF;
    IF PSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required'; END IF;
    IF PSERVDATE IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service Date is required'; END IF;
    IF PSTARTTIME IS NULL OR PENDTIME IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Slot start and end time are required'; END IF;
    IF PENDTIME <= PSTARTTIME THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Slot end time must be after start time'; END IF;

    -- Verify service is active (Status ID 10 = ACT)
    SELECT STATUSID INTO VSERVSTATUSID
    FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;
    
    IF VSERVSTATUSID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service not found'; END IF;
    IF VSERVSTATUSID <> 10 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service must be active'; END IF;

    START TRANSACTION;
    
    -- Generate Auto-Number (e.g., SLT202608220001)
    CALL CMSGENAUTO('CMS_DAYSLOT', 'SLOTNO', VSLOTNO);

    -- Insert Day Slot (10 = ACT, 20 = DRF)
    INSERT INTO CMS_DAYSLOT (
        SLOTNO, CANTEENID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUSID, APPRSTATUSID, CREATEDBY
    ) VALUES (
        VSLOTNO, PCANTEENID, PSERVICEID, PSERVDATE, PSTARTTIME, PENDTIME, 10, 20, PCREATEDBY
    );
    
    SET VDAYSLOTID = LAST_INSERT_ID();

    -- Insert initial audit history
    INSERT INTO CMS_SLOTHIST (
        DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
        STATUSID, APPRSTATUSID, CHANGEDBY, CHGREASON
    ) VALUES (
        VDAYSLOTID, VSLOTNO, PSERVICEID, PCANTEENID, PSERVDATE, PSTARTTIME, PENDTIME, 
        10, 20, PCREATEDBY, 'Initial Creation'
    );

    COMMIT;

    SELECT VDAYSLOTID AS DAYSLOTID, VSLOTNO AS SLOTNO;
END$$


CREATE PROCEDURE CMSUPDSLOT (
    IN PDAYSLOTID INT,
    IN PSTARTTIME TIME,
    IN PENDTIME   TIME,
    IN PSTATUSCODE VARCHAR(10),
    IN PCHANGEDBY INT,
    IN PCHGREASON VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE VSTATUSID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PDAYSLOTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
    IF PSTARTTIME IS NULL OR PENDTIME IS NULL OR PENDTIME <= PSTARTTIME THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Slot end time must be after start time';
    END IF;
    
    -- Validate Status Code exists in CMS_STATUS
    SELECT STATUSID INTO VSTATUSID FROM CMS_STATUS WHERE STATUSCODE = PSTATUSCODE AND STATUSGRP = 'SYS';
    IF VSTATUSID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid status code'; END IF;

    START TRANSACTION;
    
    -- Record history before update
    INSERT INTO CMS_SLOTHIST (
        DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
        STATUSID, APPRSTATUSID, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, 
        MENUAPPROVEDAT, MENUREMARKS, CHANGEDBY, CHGREASON
    )
    SELECT 
        DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
        STATUSID, APPRSTATUSID, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, 
        MENUAPPROVEDAT, MENUREMARKS, PCHANGEDBY, PCHGREASON
    FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;

    -- Update slot
    UPDATE CMS_DAYSLOT
    SET    STARTTIME = PSTARTTIME, 
           ENDTIME = PENDTIME, 
           STATUSID = VSTATUSID, 
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  DAYSLOTID = PDAYSLOTID;
    
    COMMIT;

    SELECT PDAYSLOTID AS DAYSLOTID;
END$$


CREATE PROCEDURE CMSGETSLOT (IN PDAYSLOTID INT)
BEGIN
    SELECT DS.DAYSLOTID, DS.SLOTNO, DS.SERVICEID, S.SERVCODE, S.SERVNAME,
           DS.CANTEENID, C.CANTEENNAME,
           DS.SERVDATE, DS.STARTTIME, DS.ENDTIME, 
           DS.STATUSID, ST.STATUSCODE AS STATUSCODE, ST.STATUSNAME AS STATUSNAME,
           DS.APPRSTATUSID, AST.STATUSCODE AS APPRSTATUSCODE, AST.STATUSNAME AS APPRSTATUSNAME,
           DS.MENUSUBMITTEDBY, DS.MENUSUBMITTEDAT, DS.MENUAPPROVEDBY, DS.MENUAPPROVEDAT, DS.MENUREMARKS,
           DS.CREATEDBY, DS.CREATEDAT, DS.UPDATEDAT
    FROM   CMS_DAYSLOT DS
    JOIN   CMS_SERVICE S   ON S.SERVICEID = DS.SERVICEID
    JOIN   CMS_CANTEEN C   ON C.CANTEENID = DS.CANTEENID
    JOIN   CMS_STATUS ST   ON ST.STATUSID = DS.STATUSID
    JOIN   CMS_STATUS AST  ON AST.STATUSID = DS.APPRSTATUSID
    WHERE  DS.DAYSLOTID = PDAYSLOTID;
END$$


CREATE PROCEDURE CMSLISTSLOT (
    IN PSERVICEID INT,
    IN PCANTEENID INT,
    IN PDATEFROM  DATE,
    IN PDATETO    DATE
)
BEGIN
    SELECT DS.DAYSLOTID, DS.SLOTNO, DS.SERVICEID, S.SERVNAME,
           DS.CANTEENID, C.CANTEENNAME,
           DS.SERVDATE, DS.STARTTIME, DS.ENDTIME,
           DS.STATUSID, ST.STATUSCODE AS STATUSCODE, 
           DS.APPRSTATUSID, AST.STATUSCODE AS APPRSTATUSCODE, 
           DS.CREATEDBY
    FROM   CMS_DAYSLOT DS
    JOIN   CMS_SERVICE S   ON S.SERVICEID = DS.SERVICEID
    JOIN   CMS_CANTEEN C   ON C.CANTEENID = DS.CANTEENID
    JOIN   CMS_STATUS ST   ON ST.STATUSID = DS.STATUSID
    JOIN   CMS_STATUS AST  ON AST.STATUSID = DS.APPRSTATUSID
    WHERE  (PSERVICEID IS NULL OR DS.SERVICEID   = PSERVICEID)
      AND  (PCANTEENID IS NULL OR DS.CANTEENID   = PCANTEENID)
      AND  (PDATEFROM  IS NULL OR DS.SERVDATE   >= PDATEFROM)
      AND  (PDATETO    IS NULL OR DS.SERVDATE   <= PDATETO)
    ORDER BY DS.SERVDATE, DS.STARTTIME;
END$$


CREATE PROCEDURE CMSACTSLOT (IN PDAYSLOTID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PDAYSLOTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
    
    START TRANSACTION;
    
    INSERT INTO CMS_SLOTHIST (
        DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
        STATUSID, APPRSTATUSID, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, 
        MENUAPPROVEDAT, MENUREMARKS, CHANGEDBY, CHGREASON
    )
    SELECT 
        DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
        STATUSID, APPRSTATUSID, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, 
        MENUAPPROVEDAT, MENUREMARKS, PCHANGEDBY, PCHGREASON 
    FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    
    -- 10 = 'ACT'
    UPDATE CMS_DAYSLOT SET STATUSID = 10, UPDATEDAT = CURRENT_TIMESTAMP WHERE DAYSLOTID = PDAYSLOTID;
    
    COMMIT;
    SELECT PDAYSLOTID AS DAYSLOTID;
END$$


CREATE PROCEDURE CMSDEACTSLOT (IN PDAYSLOTID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PDAYSLOTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
    
    START TRANSACTION;
    
    INSERT INTO CMS_SLOTHIST (
        DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
        STATUSID, APPRSTATUSID, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, 
        MENUAPPROVEDAT, MENUREMARKS, CHANGEDBY, CHGREASON
    )
    SELECT 
        DAYSLOTID, SLOTNO, SERVICEID, CANTEENID, SERVDATE, STARTTIME, ENDTIME, 
        STATUSID, APPRSTATUSID, MENUSUBMITTEDBY, MENUSUBMITTEDAT, MENUAPPROVEDBY, 
        MENUAPPROVEDAT, MENUREMARKS, PCHANGEDBY, PCHGREASON 
    FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    
    -- 11 = 'DIS'
    UPDATE CMS_DAYSLOT SET STATUSID = 11, UPDATEDAT = CURRENT_TIMESTAMP WHERE DAYSLOTID = PDAYSLOTID;
    
    COMMIT;
    SELECT PDAYSLOTID AS DAYSLOTID;
END$$

DELIMITER ;