USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDPERM;
DROP PROCEDURE IF EXISTS CMSUPDPERM;
DROP PROCEDURE IF EXISTS CMSGETPERM;
DROP PROCEDURE IF EXISTS CMSADDCONT;
DROP PROCEDURE IF EXISTS CMSUPDCONT;
DROP PROCEDURE IF EXISTS CMSGETCONT;
DROP PROCEDURE IF EXISTS CMSADDOCE;
DROP PROCEDURE IF EXISTS CMSUPDOCE;
DROP PROCEDURE IF EXISTS CMSGETOCE;
DROP PROCEDURE IF EXISTS CMSADDVIS;
DROP PROCEDURE IF EXISTS CMSUPDVIS;
DROP PROCEDURE IF EXISTS CMSGETVIS;
DROP PROCEDURE IF EXISTS CMSREGPERM;
DROP PROCEDURE IF EXISTS CMSREGCONT;
DROP PROCEDURE IF EXISTS CMSREGOCE;
DROP PROCEDURE IF EXISTS CMSREGVIS;

DELIMITER $$
/* ============================================================
   CMS_PERMEMP — Permanent Employee Profile
   ============================================================ */

CREATE PROCEDURE CMSADDPERM (
    IN PCUSTOMERID INT,
    IN PEMPCODE    VARCHAR(50),
    IN PDEPT       VARCHAR(100),
    IN PDESIG      VARCHAR(100)
)
BEGIN
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VPERMEMPID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    IF PEMPCODE IS NULL OR TRIM(PEMPCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Employee Code is required';
    END IF;
    IF PDEPT IS NULL OR TRIM(PDEPT) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Department is required';
    END IF;
    IF PDESIG IS NULL OR TRIM(PDESIG) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Designation is required';
    END IF;

    SELECT CTYPECODE INTO VCTYPECODE FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found';
    END IF;
    IF VCTYPECODE <> 'PERMANENT' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer type must be PERMANENT';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_PERMEMP (CUSTOMERID, EMPCODE, DEPT, DESIG)
    VALUES (PCUSTOMERID, TRIM(PEMPCODE), TRIM(PDEPT), TRIM(PDESIG));
    SET VPERMEMPID = LAST_INSERT_ID();
    COMMIT;

    SELECT VPERMEMPID AS PERMEMPID;
END$$


CREATE PROCEDURE CMSUPDPERM (
    IN PCUSTOMERID INT,
    IN PDEPT       VARCHAR(100),
    IN PDESIG      VARCHAR(100)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_PERMEMP WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Permanent employee profile not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_PERMEMP
    SET    DEPT      = COALESCE(PDEPT, DEPT),
           DESIG     = COALESCE(PDESIG, DESIG),
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  CUSTOMERID = PCUSTOMERID;
    COMMIT;
    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSGETPERM (IN PCUSTOMERID INT)
BEGIN
    SELECT PE.PERMEMPID, PE.CUSTOMERID, PE.EMPCODE, PE.DEPT, PE.DESIG,
           C.DISPNAME, C.STATUS, U.USERID, U.LOGINID, U.FULLNAME
    FROM   CMS_PERMEMP PE
    JOIN   CMS_CUSTOMER C ON C.CUSTOMERID = PE.CUSTOMERID
    LEFT JOIN CMS_USER U  ON U.USERID     = C.USERID
    WHERE  PE.CUSTOMERID = PCUSTOMERID;
END$$


/* ============================================================
   CMS_CONTEMP — Contract Employee Profile
   ============================================================ */

CREATE PROCEDURE CMSADDCONT (
    IN PCUSTOMERID  INT,
    IN PCONTCODE    VARCHAR(50),
    IN PVENDORNAME  VARCHAR(150),
    IN PCONTSTART   DATE,
    IN PCONTEND     DATE
)
BEGIN
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VCONTEMPID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    IF PCONTCODE IS NULL OR TRIM(PCONTCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract Code is required';
    END IF;
    IF PVENDORNAME IS NULL OR TRIM(PVENDORNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Vendor Name is required';
    END IF;
    IF PCONTSTART IS NULL OR PCONTEND IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract start and end dates are required';
    END IF;
    IF PCONTEND < PCONTSTART THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract end date must be >= start date';
    END IF;

    SELECT CTYPECODE INTO VCTYPECODE FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found';
    END IF;
    IF VCTYPECODE <> 'CONTRACT' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer type must be CONTRACT';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_CONTEMP (CUSTOMERID, CONTCODE, VENDORNAME, CONTSTART, CONTEND)
    VALUES (PCUSTOMERID, TRIM(PCONTCODE), TRIM(PVENDORNAME), PCONTSTART, PCONTEND);
    SET VCONTEMPID = LAST_INSERT_ID();
    COMMIT;
    SELECT VCONTEMPID AS CONTEMPID;
END$$


CREATE PROCEDURE CMSUPDCONT (
    IN PCUSTOMERID INT,
    IN PVENDORNAME VARCHAR(150),
    IN PCONTSTART  DATE,
    IN PCONTEND    DATE
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CONTEMP WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract employee profile not found';
    END IF;
    IF PCONTEND IS NOT NULL AND PCONTSTART IS NOT NULL AND PCONTEND < PCONTSTART THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract end date must be >= start date';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CONTEMP
    SET    VENDORNAME = COALESCE(PVENDORNAME, VENDORNAME),
           CONTSTART  = COALESCE(PCONTSTART, CONTSTART),
           CONTEND    = COALESCE(PCONTEND, CONTEND),
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  CUSTOMERID = PCUSTOMERID;
    COMMIT;
    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSGETCONT (IN PCUSTOMERID INT)
BEGIN
    SELECT CE.CONTEMPID, CE.CUSTOMERID, CE.CONTCODE, CE.VENDORNAME,
           CE.CONTSTART, CE.CONTEND,
           C.DISPNAME, C.STATUS, U.USERID, U.LOGINID, U.FULLNAME
    FROM   CMS_CONTEMP CE
    JOIN   CMS_CUSTOMER C ON C.CUSTOMERID = CE.CUSTOMERID
    LEFT JOIN CMS_USER U  ON U.USERID     = C.USERID
    WHERE  CE.CUSTOMERID = PCUSTOMERID;
END$$


/* ============================================================
   CMS_OCEEMP — Other Centre Employee Profile
   ============================================================ */

CREATE PROCEDURE CMSADDOCE (
    IN PCUSTOMERID  INT,
    IN PEMPCODE     VARCHAR(50),
    IN PCENTERNAME  VARCHAR(120),
    IN PDEPT        VARCHAR(100),
    IN PDESIG       VARCHAR(100),
    IN PVALIDFROM   DATETIME,
    IN PVALIDUNTIL  DATETIME
)
BEGIN
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VOCEEMPID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    IF PEMPCODE IS NULL OR TRIM(PEMPCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Employee Code is required';
    END IF;
    IF PCENTERNAME IS NULL OR TRIM(PCENTERNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre Name is required';
    END IF;

    SELECT CTYPECODE INTO VCTYPECODE FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found';
    END IF;
    IF VCTYPECODE <> 'OTHERCENTRE' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer type must be OTHERCENTRE';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_OCEEMP (CUSTOMERID, EMPCODE, CENTERNAME, DEPT, DESIG, VALIDFROM, VALIDUNTIL)
    VALUES (PCUSTOMERID, TRIM(PEMPCODE), TRIM(PCENTERNAME), PDEPT, PDESIG, PVALIDFROM, PVALIDUNTIL);
    SET VOCEEMPID = LAST_INSERT_ID();
    COMMIT;
    SELECT VOCEEMPID AS OCEEMPID;
END$$


CREATE PROCEDURE CMSUPDOCE (
    IN PCUSTOMERID INT,
    IN PDEPT       VARCHAR(100),
    IN PDESIG      VARCHAR(100),
    IN PVALIDFROM  DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_OCEEMP WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Other centre employee profile not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_OCEEMP
    SET    DEPT       = COALESCE(PDEPT, DEPT),
           DESIG      = COALESCE(PDESIG, DESIG),
           VALIDFROM  = COALESCE(PVALIDFROM, VALIDFROM),
           VALIDUNTIL = PVALIDUNTIL,
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  CUSTOMERID = PCUSTOMERID;
    COMMIT;
    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSGETOCE (IN PCUSTOMERID INT)
BEGIN
    SELECT OE.OCEEMPID, OE.CUSTOMERID, OE.EMPCODE, OE.CENTERNAME,
           OE.DEPT, OE.DESIG, OE.VALIDFROM, OE.VALIDUNTIL,
           C.DISPNAME, C.STATUS, U.USERID, U.LOGINID, U.FULLNAME
    FROM   CMS_OCEEMP OE
    JOIN   CMS_CUSTOMER C ON C.CUSTOMERID = OE.CUSTOMERID
    LEFT JOIN CMS_USER U  ON U.USERID     = C.USERID
    WHERE  OE.CUSTOMERID = PCUSTOMERID;
END$$


/* ============================================================
   CMS_VISITOR — Visitor Profile
   ============================================================ */

CREATE PROCEDURE CMSADDVIS (
    IN PCUSTOMERID INT,
    IN PVISNAME    VARCHAR(120),
    IN PVISMOBILE  VARCHAR(20),
    IN PVISORG     VARCHAR(150),
    IN PVISPURPOSE VARCHAR(255),
    IN PVISDATE    DATE,
    IN PVALIDUNTIL DATETIME,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VVISITORID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    IF PVISNAME IS NULL OR TRIM(PVISNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Visitor Name is required';
    END IF;
    IF PVISDATE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Visit Date is required';
    END IF;
    IF PVALIDUNTIL IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Valid Until is required';
    END IF;
    IF PCREATEDBY IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Created By is required';
    END IF;
    IF PVALIDUNTIL < TIMESTAMP(PVISDATE, '00:00:00') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Valid until must be >= visit date';
    END IF;

    SELECT CTYPECODE INTO VCTYPECODE FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found';
    END IF;
    IF VCTYPECODE <> 'VIS' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only visitors can be created without a User ID';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_VISITOR (CUSTOMERID, VISNAME, VISMOBILE, VISORG, VISPURPOSE, VISDATE, VALIDUNTIL, CREATEDBY, STATUSID)
    VALUES (PCUSTOMERID, TRIM(PVISNAME), PVISMOBILE, PVISORG, PVISPURPOSE, PVISDATE, PVALIDUNTIL, PCREATEDBY, 10);
    SET VVISITORID = LAST_INSERT_ID();
    COMMIT;
    SELECT VVISITORID AS VISITORID;
END$$


CREATE PROCEDURE CMSUPDVIS (
    IN PCUSTOMERID INT,
    IN PVISMOBILE  VARCHAR(20),
    IN PVISORG     VARCHAR(150),
    IN PVISPURPOSE VARCHAR(255),
    IN PVALIDUNTIL DATETIME,
    IN PSTATUSCODE VARCHAR(20)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE VSTATUSID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_VISITOR WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Visitor profile not found';
    END IF;

    IF PSTATUSCODE IS NOT NULL THEN
        SELECT STATUSID INTO VSTATUSID FROM CMS_STATUS WHERE STATUSCODE = PSTATUSCODE AND STATUSGRP = 'SYS';
        IF VSTATUSID IS NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid Status Code';
        END IF;
    END IF;

    START TRANSACTION;
    UPDATE CMS_VISITOR
    SET    VISMOBILE  = COALESCE(PVISMOBILE, VISMOBILE),
           VISORG     = COALESCE(PVISORG, VISORG),
           VISPURPOSE = COALESCE(PVISPURPOSE, VISPURPOSE),
           VALIDUNTIL = COALESCE(PVALIDUNTIL, VALIDUNTIL),
           STATUSID   = COALESCE(VSTATUSID, STATUSID),
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  CUSTOMERID = PCUSTOMERID;
    COMMIT;
    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSGETVIS (IN PCUSTOMERID INT)
BEGIN
    SELECT V.VISITORID, V.CUSTOMERID, V.VISNAME, V.VISMOBILE,
           V.VISORG, V.VISPURPOSE, V.VISDATE, V.VALIDUNTIL,
           V.CREATEDBY, V.STATUSID, STV.STATUSCODE AS STATUSCODE,
           C.DISPNAME, U.USERID, U.LOGINID
    FROM   CMS_VISITOR V
    JOIN   CMS_STATUS STV ON STV.STATUSID = V.STATUSID
    JOIN   CMS_CUSTOMER C ON C.CUSTOMERID = V.CUSTOMERID
    LEFT JOIN CMS_USER U  ON U.USERID     = C.USERID
    WHERE  V.CUSTOMERID = PCUSTOMERID;
END$$


/* ============================================================
   COMPOSITE REGISTRATION PROCEDURES

   Each creates User + Customer + Profile + Access Key
   in a single transaction for data integrity.
   ============================================================ */

CREATE PROCEDURE CMSREGPERM (
    IN PLOGINID   VARCHAR(50),
    IN PFULLNAME  VARCHAR(120),
    IN PEMAIL     VARCHAR(120),
    IN PMOBILENO  VARCHAR(20),
    IN PPWDHASH   VARCHAR(255),
    IN PEMPCODE   VARCHAR(50),
    IN PDEPT      VARCHAR(100),
    IN PDESIG     VARCHAR(100),
    IN PKEYTYPE   VARCHAR(30),
    IN PKEYVALUE  VARCHAR(255),
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VUSERID     INT;
    DECLARE VCUSTOMERID INT;
    DECLARE VPERMEMPID  INT;
    DECLARE VACCKEYID   INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    -- Validate required fields
    IF PLOGINID IS NULL OR TRIM(PLOGINID) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Login ID is required'; END IF;
    IF PFULLNAME IS NULL OR TRIM(PFULLNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Full Name is required'; END IF;
    IF PPWDHASH IS NULL OR TRIM(PPWDHASH) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Password hash is required'; END IF;
    IF PEMPCODE IS NULL OR TRIM(PEMPCODE) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Employee Code is required'; END IF;
    IF PDEPT IS NULL OR TRIM(PDEPT) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Department is required'; END IF;
    IF PDESIG IS NULL OR TRIM(PDESIG) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Designation is required'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_USER (LOGINID, FULLNAME, EMAIL, MOBILENO, PWDHASH, AUTHPROV)
    VALUES (TRIM(PLOGINID), TRIM(PFULLNAME), PEMAIL, PMOBILENO, PPWDHASH, 'LOCAL');
    SET VUSERID = LAST_INSERT_ID();

    INSERT INTO CMS_CUSTOMER (USERID, CTYPECODE, DISPNAME, STATUSID, VALIDFROM)
    VALUES (VUSERID, 'PERMANENT', TRIM(PFULLNAME), 10, CURRENT_TIMESTAMP);
    SET VCUSTOMERID = LAST_INSERT_ID();

    INSERT INTO CMS_PERMEMP (CUSTOMERID, EMPCODE, DEPT, DESIG)
    VALUES (VCUSTOMERID, TRIM(PEMPCODE), TRIM(PDEPT), TRIM(PDESIG));
    SET VPERMEMPID = LAST_INSERT_ID();

    IF PKEYVALUE IS NOT NULL AND TRIM(PKEYVALUE) <> '' THEN
        INSERT INTO CMS_ACCKEY (CUSTOMERID, KEYTYPE, KEYVALUE, STATUSID, CREATEDBY)
        VALUES (VCUSTOMERID, COALESCE(PKEYTYPE, 'EMPCARD'), TRIM(PKEYVALUE), 10, PCREATEDBY);
        SET VACCKEYID = LAST_INSERT_ID();
    END IF;

    COMMIT;

    SELECT VUSERID AS USERID, VCUSTOMERID AS CUSTOMERID, VPERMEMPID AS PERMEMPID, VACCKEYID AS ACCKEYID;
END$$


CREATE PROCEDURE CMSREGCONT (
    IN PLOGINID    VARCHAR(50),
    IN PFULLNAME   VARCHAR(120),
    IN PEMAIL      VARCHAR(120),
    IN PMOBILENO   VARCHAR(20),
    IN PPWDHASH    VARCHAR(255),
    IN PCONTCODE   VARCHAR(50),
    IN PVENDORNAME VARCHAR(150),
    IN PCONTSTART  DATE,
    IN PCONTEND    DATE,
    IN PDISPNAME   VARCHAR(120),
    IN PKEYTYPE    VARCHAR(30),
    IN PKEYVALUE   VARCHAR(255),
    IN PEXPIRESAT  DATETIME,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VUSERID     INT;
    DECLARE VCUSTOMERID INT;
    DECLARE VCONTEMPID  INT;
    DECLARE VACCKEYID   INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PLOGINID IS NULL OR TRIM(PLOGINID) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Login ID is required'; END IF;
    IF PFULLNAME IS NULL OR TRIM(PFULLNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Full Name is required'; END IF;
    IF PPWDHASH IS NULL OR TRIM(PPWDHASH) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Password hash is required'; END IF;
    IF PCONTCODE IS NULL OR TRIM(PCONTCODE) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract Code is required'; END IF;
    IF PVENDORNAME IS NULL OR TRIM(PVENDORNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Vendor Name is required'; END IF;
    IF PCONTSTART IS NULL OR PCONTEND IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract dates are required'; END IF;
    IF PCONTEND < PCONTSTART THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract end must be >= start'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_USER (LOGINID, FULLNAME, EMAIL, MOBILENO, PWDHASH, AUTHPROV)
    VALUES (TRIM(PLOGINID), TRIM(PFULLNAME), PEMAIL, PMOBILENO, PPWDHASH, 'LOCAL');
    SET VUSERID = LAST_INSERT_ID();

    INSERT INTO CMS_CUSTOMER (USERID, CTYPECODE, DISPNAME, STATUSID, VALIDFROM)
    VALUES (VUSERID, 'CONTRACT', COALESCE(TRIM(PDISPNAME), TRIM(PFULLNAME)), 10, CURRENT_TIMESTAMP);
    SET VCUSTOMERID = LAST_INSERT_ID();

    INSERT INTO CMS_CONTEMP (CUSTOMERID, CONTCODE, VENDORNAME, CONTSTART, CONTEND)
    VALUES (VCUSTOMERID, TRIM(PCONTCODE), TRIM(PVENDORNAME), PCONTSTART, PCONTEND);
    SET VCONTEMPID = LAST_INSERT_ID();

    IF PKEYVALUE IS NOT NULL AND TRIM(PKEYVALUE) <> '' THEN
        INSERT INTO CMS_ACCKEY (CUSTOMERID, KEYTYPE, KEYVALUE, EXPIRESAT, STATUSID, CREATEDBY)
        VALUES (VCUSTOMERID, COALESCE(PKEYTYPE, 'QR'), TRIM(PKEYVALUE), PEXPIRESAT, 10, PCREATEDBY);
        SET VACCKEYID = LAST_INSERT_ID();
    END IF;

    COMMIT;
    SELECT VUSERID AS USERID, VCUSTOMERID AS CUSTOMERID, VCONTEMPID AS CONTEMPID, VACCKEYID AS ACCKEYID;
END$$


CREATE PROCEDURE CMSREGOCE (
    IN PLOGINID    VARCHAR(50),
    IN PFULLNAME   VARCHAR(120),
    IN PEMAIL      VARCHAR(120),
    IN PMOBILENO   VARCHAR(20),
    IN PPWDHASH    VARCHAR(255),
    IN PEMPCODE    VARCHAR(50),
    IN PCENTERNAME VARCHAR(120),
    IN PDEPT       VARCHAR(100),
    IN PDESIG      VARCHAR(100),
    IN PVALIDFROM  DATETIME,
    IN PVALIDUNTIL DATETIME,
    IN PDISPNAME   VARCHAR(120),
    IN PKEYTYPE    VARCHAR(30),
    IN PKEYVALUE   VARCHAR(255),
    IN PEXPIRESAT  DATETIME,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VUSERID     INT;
    DECLARE VCUSTOMERID INT;
    DECLARE VOCEEMPID   INT;
    DECLARE VACCKEYID   INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PLOGINID IS NULL OR TRIM(PLOGINID) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Login ID is required'; END IF;
    IF PFULLNAME IS NULL OR TRIM(PFULLNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Full Name is required'; END IF;
    IF PPWDHASH IS NULL OR TRIM(PPWDHASH) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Password hash is required'; END IF;
    IF PEMPCODE IS NULL OR TRIM(PEMPCODE) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Employee Code is required'; END IF;
    IF PCENTERNAME IS NULL OR TRIM(PCENTERNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre Name is required'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_USER (LOGINID, FULLNAME, EMAIL, MOBILENO, PWDHASH, AUTHPROV)
    VALUES (TRIM(PLOGINID), TRIM(PFULLNAME), PEMAIL, PMOBILENO, PPWDHASH, 'LOCAL');
    SET VUSERID = LAST_INSERT_ID();

    INSERT INTO CMS_CUSTOMER (USERID, CTYPECODE, DISPNAME, STATUSID, VALIDFROM, VALIDUNTIL)
    VALUES (VUSERID, 'OTHERCENTRE', COALESCE(TRIM(PDISPNAME), TRIM(PFULLNAME)), 10, PVALIDFROM, PVALIDUNTIL);
    SET VCUSTOMERID = LAST_INSERT_ID();

    INSERT INTO CMS_OCEEMP (CUSTOMERID, EMPCODE, CENTERNAME, DEPT, DESIG, VALIDFROM, VALIDUNTIL)
    VALUES (VCUSTOMERID, TRIM(PEMPCODE), TRIM(PCENTERNAME), PDEPT, PDESIG, PVALIDFROM, PVALIDUNTIL);
    SET VOCEEMPID = LAST_INSERT_ID();

    IF PKEYVALUE IS NOT NULL AND TRIM(PKEYVALUE) <> '' THEN
        INSERT INTO CMS_ACCKEY (CUSTOMERID, KEYTYPE, KEYVALUE, EXPIRESAT, STATUSID, CREATEDBY)
        VALUES (VCUSTOMERID, COALESCE(PKEYTYPE, 'TEMPTOKEN'), TRIM(PKEYVALUE), PEXPIRESAT, 10, PCREATEDBY);
        SET VACCKEYID = LAST_INSERT_ID();
    END IF;

    COMMIT;
    SELECT VUSERID AS USERID, VCUSTOMERID AS CUSTOMERID, VOCEEMPID AS OCEEMPID, VACCKEYID AS ACCKEYID;
END$$


CREATE PROCEDURE CMSREGVIS (
    IN PVISNAME    VARCHAR(120),
    IN PVISMOBILE  VARCHAR(20),
    IN PVISORG     VARCHAR(150),
    IN PVISPURPOSE VARCHAR(255),
    IN PVISDATE    DATE,
    IN PVALIDUNTIL DATETIME,
    IN PKEYTYPE    VARCHAR(30),
    IN PKEYVALUE   VARCHAR(255),
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VCUSTOMERID INT;
    DECLARE VVISITORID  INT;
    DECLARE VACCKEYID   INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PVISNAME IS NULL OR TRIM(PVISNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Visitor Name is required'; END IF;
    IF PVISDATE IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Visit Date is required'; END IF;
    IF PVALIDUNTIL IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Valid Until is required'; END IF;
    IF PCREATEDBY IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Created By is required'; END IF;
    IF PVALIDUNTIL < TIMESTAMP(PVISDATE, '00:00:00') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Valid until must be >= visit date';
    END IF;

    START TRANSACTION;

    -- Visitors may not have a CMS_USER; USERID is NULL
    INSERT INTO CMS_CUSTOMER (USERID, CTYPECODE, DISPNAME, STATUSID, VALIDFROM, VALIDUNTIL)
    VALUES (NULL, 'VIS', TRIM(PVISNAME), 10, CURRENT_TIMESTAMP, PVALIDUNTIL);
    SET VCUSTOMERID = LAST_INSERT_ID();

    INSERT INTO CMS_VISITOR (CUSTOMERID, VISNAME, VISMOBILE, VISORG, VISPURPOSE, VISDATE, VALIDUNTIL, CREATEDBY, STATUSID)
    VALUES (VCUSTOMERID, TRIM(PVISNAME), PVISMOBILE, PVISORG, PVISPURPOSE, PVISDATE, PVALIDUNTIL, PCREATEDBY, 10);
    SET VVISITORID = LAST_INSERT_ID();

    IF PKEYVALUE IS NOT NULL AND TRIM(PKEYVALUE) <> '' THEN
        INSERT INTO CMS_ACCKEY (CUSTOMERID, KEYTYPE, KEYVALUE, EXPIRESAT, STATUSID, CREATEDBY)
        VALUES (VCUSTOMERID, COALESCE(PKEYTYPE, 'VISPASS'), TRIM(PKEYVALUE), PVALIDUNTIL, 10, PCREATEDBY);
        SET VACCKEYID = LAST_INSERT_ID();
    END IF;

    COMMIT;
    SELECT VCUSTOMERID AS CUSTOMERID, VVISITORID AS VISITORID, VACCKEYID AS ACCKEYID;
END$$



DELIMITER ;

