USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDHOLIDAY;
DROP PROCEDURE IF EXISTS CMSUPDHOLIDAY;
DROP PROCEDURE IF EXISTS CMSLISTHOLIDAY;
DROP PROCEDURE IF EXISTS CMSDEACTHOLIDAY;
DROP PROCEDURE IF EXISTS CMSGETHOLIDAY;

DELIMITER $$
/* ============================================================
   CMS_HOLIDAY — Holiday Master
   ============================================================ */

CREATE PROCEDURE CMSADDHOLIDAY (
    IN PHOLIDAYDATE DATE,
    IN PHOLIDAYNAME VARCHAR(100),
    IN PHOLIDAYTYPE VARCHAR(20),
    IN PISRECURRING TINYINT(1),
    IN PCREATEDBY   INT
)
BEGIN
    DECLARE VHOLIDAYID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PHOLIDAYDATE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Holiday Date is required';
    END IF;

    IF PHOLIDAYNAME IS NULL OR TRIM(PHOLIDAYNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Holiday Name is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_HOLIDAY (HOLIDAYDATE, HOLIDAYNAME, HOLIDAYTYPE, ISRECURRING, STATUSID, CREATEDBY)
    VALUES (PHOLIDAYDATE, TRIM(PHOLIDAYNAME), COALESCE(PHOLIDAYTYPE, 'NATIONAL'), COALESCE(PISRECURRING, 0), 10, PCREATEDBY);

    SET VHOLIDAYID = LAST_INSERT_ID();
    COMMIT;

    SELECT VHOLIDAYID AS HOLIDAYID;
END$$


CREATE PROCEDURE CMSUPDHOLIDAY (
    IN PHOLIDAYID   INT,
    IN PHOLIDAYDATE DATE,
    IN PHOLIDAYNAME VARCHAR(100),
    IN PHOLIDAYTYPE VARCHAR(20),
    IN PISRECURRING TINYINT(1),
    IN PSTATUSCODE  VARCHAR(20)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE VSTATUSID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PHOLIDAYID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Holiday ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT FROM CMS_HOLIDAY WHERE HOLIDAYID = PHOLIDAYID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Holiday not found';
    END IF;

    IF PSTATUSCODE IS NOT NULL THEN
        SELECT STATUSID INTO VSTATUSID FROM CMS_STATUS WHERE STATUSCODE = PSTATUSCODE AND STATUSGRP = 'SYS';
        IF VSTATUSID IS NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid Status Code';
        END IF;
    END IF;

    START TRANSACTION;

    UPDATE CMS_HOLIDAY
    SET    HOLIDAYDATE = COALESCE(PHOLIDAYDATE, HOLIDAYDATE),
           HOLIDAYNAME = COALESCE(TRIM(PHOLIDAYNAME), HOLIDAYNAME),
           HOLIDAYTYPE = COALESCE(PHOLIDAYTYPE, HOLIDAYTYPE),
           ISRECURRING = COALESCE(PISRECURRING, ISRECURRING),
           STATUSID    = COALESCE(VSTATUSID, STATUSID),
           UPDATEDAT   = CURRENT_TIMESTAMP
    WHERE  HOLIDAYID   = PHOLIDAYID;

    COMMIT;
    SELECT PHOLIDAYID AS HOLIDAYID;
END$$


CREATE PROCEDURE CMSGETHOLIDAY (IN PHOLIDAYID INT)
BEGIN
    SELECT H.HOLIDAYID, H.HOLIDAYDATE, H.HOLIDAYNAME, H.HOLIDAYTYPE, H.ISRECURRING,
           H.STATUSID, ST.STATUSCODE AS STATUSCODE, H.CREATEDAT, H.UPDATEDAT
    FROM   CMS_HOLIDAY H
    JOIN   CMS_STATUS ST ON ST.STATUSID = H.STATUSID
    WHERE  H.HOLIDAYID = PHOLIDAYID;
END$$


CREATE PROCEDURE CMSLISTHOLIDAY (
    IN PYEAR INT
)
BEGIN
    SELECT H.HOLIDAYID, H.HOLIDAYDATE, H.HOLIDAYNAME, H.HOLIDAYTYPE, H.ISRECURRING,
           H.STATUSID, ST.STATUSCODE AS STATUSCODE, H.CREATEDAT, H.UPDATEDAT
    FROM   CMS_HOLIDAY H
    JOIN   CMS_STATUS ST ON ST.STATUSID = H.STATUSID
    WHERE  (PYEAR IS NULL OR YEAR(H.HOLIDAYDATE) = PYEAR OR H.ISRECURRING = 1)
    ORDER BY MONTH(H.HOLIDAYDATE), DAY(H.HOLIDAYDATE), YEAR(H.HOLIDAYDATE);
END$$


CREATE PROCEDURE CMSDEACTHOLIDAY (IN PHOLIDAYID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PHOLIDAYID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Holiday ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_HOLIDAY WHERE HOLIDAYID = PHOLIDAYID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Holiday not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_HOLIDAY SET STATUSID = 11, UPDATEDAT = CURRENT_TIMESTAMP WHERE HOLIDAYID = PHOLIDAYID;
    COMMIT;
    SELECT PHOLIDAYID AS HOLIDAYID;
END$$

DELIMITER ;
