USE cms_db;

DROP PROCEDURE IF EXISTS CMSIDENTIFYKIOSK;
DROP PROCEDURE IF EXISTS CMSREGISTERKIOSKDEVICE;
DROP PROCEDURE IF EXISTS CMSHEARTBEATKIOSK;
DROP PROCEDURE IF EXISTS CMSLISTKIOSKDEVICES;

DELIMITER $$

/* ============================================================
   CMSIDENTIFYKIOSK
   Resolves physical kiosk metadata and assigned canteen by IP address
   ============================================================ */
CREATE PROCEDURE CMSIDENTIFYKIOSK (
    IN PIPADDRESS VARCHAR(45)
)
BEGIN
    DECLARE VKIOSKID INT DEFAULT NULL;

    IF PIPADDRESS IS NULL OR TRIM(PIPADDRESS) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Client IP address is required';
    END IF;

    -- Lookup active kiosk matching the IP
    SELECT KD.KIOSKID INTO VKIOSKID
    FROM CMS_KIOSK_DEVICE KD
    WHERE KD.IPADDRESS = TRIM(PIPADDRESS)
      AND KD.ISACTIVE = 1
    LIMIT 1;

    IF VKIOSKID IS NOT NULL THEN
        -- Update last seen IP and heartbeat
        UPDATE CMS_KIOSK_DEVICE
        SET LASTHEARTBEATAT = CURRENT_TIMESTAMP,
            LASTSEENIP = TRIM(PIPADDRESS)
        WHERE KIOSKID = VKIOSKID;

        -- Return Kiosk + Canteen Configuration
        SELECT 
            KD.KIOSKID,
            KD.DEVICECODE,
            KD.DEVICENAME,
            KD.IPADDRESS,
            KD.MACADDRESS,
            KD.CANTEENID,
            C.CANTEENNAME,
            C.CANTEENCODE,
            C.LOCATION AS CANTEENLOCATION,
            KD.KIOSKTYPE,
            KD.ISACTIVE,
            ST.STATUSCODE
        FROM CMS_KIOSK_DEVICE KD
        JOIN CMS_CANTEEN C ON C.CANTEENID = KD.CANTEENID
        JOIN CMS_STATUS ST ON ST.STATUSID = KD.STATUSID
        WHERE KD.KIOSKID = VKIOSKID;
    ELSE
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Kiosk device not registered for this IP address';
    END IF;
END$$

/* ============================================================
   CMSREGISTERKIOSKDEVICE
   Upserts hardware kiosk record for physical terminals
   ============================================================ */
CREATE PROCEDURE CMSREGISTERKIOSKDEVICE (
    IN PDEVICECODE VARCHAR(30),
    IN PDEVICENAME VARCHAR(100),
    IN PIPADDRESS  VARCHAR(45),
    IN PMACADDRESS VARCHAR(17),
    IN PCANTEENID  INT,
    IN PKIOSKTYPE  VARCHAR(30),
    IN PUSERID     INT
)
BEGIN
    DECLARE VCANTEENSTATUSID INT;
    DECLARE VKIOSKID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PDEVICECODE IS NULL OR TRIM(PDEVICECODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Device code is required';
    END IF;
    IF PIPADDRESS IS NULL OR TRIM(PIPADDRESS) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Static IP address is required';
    END IF;
    IF PCANTEENID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen facility ID is required';
    END IF;
    IF PKIOSKTYPE NOT IN ('STAFF_COUNTER', 'EMP_SELF_SERVICE') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid Kiosk Type. Must be STAFF_COUNTER or EMP_SELF_SERVICE';
    END IF;

    SELECT STATUSID INTO VCANTEENSTATUSID FROM CMS_CANTEEN WHERE CANTEENID = PCANTEENID;
    IF VCANTEENSTATUSID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Target canteen facility not found';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_KIOSK_DEVICE (
        DEVICECODE, DEVICENAME, IPADDRESS, MACADDRESS, CANTEENID, KIOSKTYPE, STATUSID, ISACTIVE, CREATEDBY
    ) VALUES (
        TRIM(PDEVICECODE),
        TRIM(PDEVICENAME),
        TRIM(PIPADDRESS),
        TRIM(PMACADDRESS),
        PCANTEENID,
        PKIOSKTYPE,
        10,
        1,
        PUSERID
    )
    ON DUPLICATE KEY UPDATE
        DEVICENAME = VALUES(DEVICENAME),
        IPADDRESS = VALUES(IPADDRESS),
        MACADDRESS = VALUES(MACADDRESS),
        CANTEENID = VALUES(CANTEENID),
        KIOSKTYPE = VALUES(KIOSKTYPE),
        UPDATEDBY = PUSERID,
        UPDATEDAT = CURRENT_TIMESTAMP;

    SELECT KIOSKID INTO VKIOSKID FROM CMS_KIOSK_DEVICE WHERE DEVICECODE = TRIM(PDEVICECODE);

    COMMIT;

    SELECT VKIOSKID AS KIOSKID, 'SUCCESS' AS RESULT;
END$$

/* ============================================================
   CMSHEARTBEATKIOSK
   Updates telemetry timestamp and last seen IP for a kiosk
   ============================================================ */
CREATE PROCEDURE CMSHEARTBEATKIOSK (
    IN PKIOSKID   INT,
    IN PIPADDRESS VARCHAR(45)
)
BEGIN
    UPDATE CMS_KIOSK_DEVICE
    SET LASTHEARTBEATAT = CURRENT_TIMESTAMP,
        LASTSEENIP = COALESCE(PIPADDRESS, LASTSEENIP)
    WHERE KIOSKID = PKIOSKID;

    SELECT PKIOSKID AS KIOSKID, 'HEARTBEAT_ACK' AS STATUS;
END$$

/* ============================================================
   CMSLISTKIOSKDEVICES
   Lists all registered kiosks, optionally scoped by canteen
   ============================================================ */
CREATE PROCEDURE CMSLISTKIOSKDEVICES (
    IN PCANTEENID INT
)
BEGIN
    SELECT 
        KD.KIOSKID,
        KD.DEVICECODE,
        KD.DEVICENAME,
        KD.IPADDRESS,
        KD.MACADDRESS,
        KD.CANTEENID,
        C.CANTEENNAME,
        C.CANTEENCODE,
        KD.KIOSKTYPE,
        KD.ISACTIVE,
        KD.LASTHEARTBEATAT,
        KD.LASTSEENIP,
        ST.STATUSCODE
    FROM CMS_KIOSK_DEVICE KD
    JOIN CMS_CANTEEN C ON C.CANTEENID = KD.CANTEENID
    JOIN CMS_STATUS ST ON ST.STATUSID = KD.STATUSID
    WHERE (PCANTEENID IS NULL OR KD.CANTEENID = PCANTEENID)
    ORDER BY KD.CANTEENID ASC, KD.KIOSKTYPE ASC, KD.KIOSKID ASC;
END$$

/* ============================================================
   CMSKIOSKGETCURRENTSLOT
   Returns the meal slot currently active for the canteen based on clock time,
   or the next upcoming slot for today.
   ============================================================ */
DROP PROCEDURE IF EXISTS CMSKIOSKGETCURRENTSLOT$$

CREATE PROCEDURE CMSKIOSKGETCURRENTSLOT (
    IN PCANTEENID INT,
    IN PKIOSKID   INT
)
BEGIN
    DECLARE VCANTEENID INT DEFAULT PCANTEENID;
    DECLARE VSLOTCOUNT INT DEFAULT 0;

    -- If CANTEENID was not passed but KIOSKID is available, resolve from Kiosk record
    IF VCANTEENID IS NULL AND PKIOSKID IS NOT NULL THEN
        SELECT KD.CANTEENID INTO VCANTEENID
        FROM CMS_KIOSK_DEVICE KD
        WHERE KD.KIOSKID = PKIOSKID
        LIMIT 1;
    END IF;

    IF VCANTEENID IS NULL THEN
        SET VCANTEENID = 1;
    END IF;

    -- 1. Check for slot currently serving (within STARTTIME - 15m and ENDTIME + 15m buffer)
    SELECT COUNT(*) INTO VSLOTCOUNT
    FROM CMS_DAYSLOT DS
    WHERE DS.CANTEENID = VCANTEENID
      AND DS.SERVDATE = CURDATE()
      AND DS.STATUSID = 10
      AND CURRENT_TIME() BETWEEN (DS.STARTTIME - INTERVAL 15 MINUTE) AND (DS.ENDTIME + INTERVAL 15 MINUTE);

    IF VSLOTCOUNT > 0 THEN
        SELECT 
            DS.DAYSLOTID,
            DS.SLOTNO,
            DS.SERVICEID,
            S.SERVCODE,
            S.SERVNAME,
            DS.CANTEENID,
            C.CANTEENNAME,
            C.CANTEENCODE,
            DS.SERVDATE,
            DS.STARTTIME,
            DS.ENDTIME,
            1 AS ISACTIVENOW,
            GREATEST(0, TIMESTAMPDIFF(MINUTE, CURRENT_TIMESTAMP, CONCAT(DS.SERVDATE, ' ', DS.ENDTIME))) AS MINUTESREMAINING,
            0 AS MINUTESUNTILSTART,
            'SERVING' AS SLOTSTATE
        FROM CMS_DAYSLOT DS
        JOIN CMS_SERVICE S ON S.SERVICEID = DS.SERVICEID
        JOIN CMS_CANTEEN C ON C.CANTEENID = DS.CANTEENID
        WHERE DS.CANTEENID = VCANTEENID
          AND DS.SERVDATE = CURDATE()
          AND DS.STATUSID = 10
          AND CURRENT_TIME() BETWEEN (DS.STARTTIME - INTERVAL 15 MINUTE) AND (DS.ENDTIME + INTERVAL 15 MINUTE)
        ORDER BY DS.STARTTIME ASC
        LIMIT 1;
    ELSE
        -- 2. Fallback: Find the nearest UPCOMING slot today
        SELECT 
            DS.DAYSLOTID,
            DS.SLOTNO,
            DS.SERVICEID,
            S.SERVCODE,
            S.SERVNAME,
            DS.CANTEENID,
            C.CANTEENNAME,
            C.CANTEENCODE,
            DS.SERVDATE,
            DS.STARTTIME,
            DS.ENDTIME,
            0 AS ISACTIVENOW,
            0 AS MINUTESREMAINING,
            GREATEST(0, TIMESTAMPDIFF(MINUTE, CURRENT_TIMESTAMP, CONCAT(DS.SERVDATE, ' ', DS.STARTTIME))) AS MINUTESUNTILSTART,
            'UPCOMING' AS SLOTSTATE
        FROM CMS_DAYSLOT DS
        JOIN CMS_SERVICE S ON S.SERVICEID = DS.SERVICEID
        JOIN CMS_CANTEEN C ON C.CANTEENID = DS.CANTEENID
        WHERE DS.CANTEENID = VCANTEENID
          AND DS.SERVDATE = CURDATE()
          AND DS.STATUSID = 10
          AND DS.STARTTIME > CURRENT_TIME()
        ORDER BY DS.STARTTIME ASC
        LIMIT 1;
    END IF;
END$$

/* ============================================================
   CMSKIOSKRESOLVEBOOKING
   Dedicated Kiosk Serving resolver:
   - Priority resolution: RFID KeyCard UID -> LoginID -> CustomerID -> BookNo
   - Slot-aware matching: prioritized to active meal slot at current time
   - Returns 2 Result Sets: Header (with slot & out-of-window warning) + Items
   ============================================================ */
DROP PROCEDURE IF EXISTS CMSKIOSKRESOLVEBOOKING$$

CREATE PROCEDURE CMSKIOSKRESOLVEBOOKING (
    IN PIDENTIFIER VARCHAR(255),
    IN PCANTEENID   INT,
    IN PKIOSKID     INT,
    IN PDAYSLOTID   INT
)
BEGIN
    DECLARE VBOOKID        INT DEFAULT NULL;
    DECLARE VCUSTOMERID    INT DEFAULT NULL;
    DECLARE VCANTEENID     INT DEFAULT PCANTEENID;
    DECLARE VACTIVESLOTID  INT DEFAULT PDAYSLOTID;
    DECLARE VIDENTIFIER    VARCHAR(255);

    IF PIDENTIFIER IS NULL OR TRIM(PIDENTIFIER) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Identifier or Booking Number is required';
    END IF;

    SET VIDENTIFIER = TRIM(PIDENTIFIER);

    -- If CANTEENID was not provided, derive from Kiosk hardware record
    IF VCANTEENID IS NULL AND PKIOSKID IS NOT NULL THEN
        SELECT KD.CANTEENID INTO VCANTEENID
        FROM CMS_KIOSK_DEVICE KD
        WHERE KD.KIOSKID = PKIOSKID
        LIMIT 1;
    END IF;

    -- 1. Direct formatted Booking Number (PB... / BK...)
    IF UPPER(VIDENTIFIER) LIKE 'PB%' OR UPPER(VIDENTIFIER) LIKE 'BK%' THEN
        SELECT B.BOOKID INTO VBOOKID
        FROM CMS_BOOKING B
        WHERE B.BOOKNO = VIDENTIFIER
        LIMIT 1;
    ELSE
        -- 2. Try RFID Access Key
        SELECT AK.CUSTOMERID INTO VCUSTOMERID
        FROM CMS_ACCKEY AK
        JOIN CMS_STATUS STAK ON STAK.STATUSID = AK.STATUSID
        WHERE AK.KEYVALUE = VIDENTIFIER
          AND STAK.STATUSCODE = 'ACT'
          AND (AK.EXPIRESAT IS NULL OR AK.EXPIRESAT > CURRENT_TIMESTAMP)
        LIMIT 1;

        -- 3. Fallback to CMS_USER.LOGINID
        IF VCUSTOMERID IS NULL THEN
            SELECT C.CUSTOMERID INTO VCUSTOMERID
            FROM CMS_USER U
            JOIN CMS_CUSTOMER C ON C.USERID = U.USERID
            WHERE U.LOGINID = VIDENTIFIER
            LIMIT 1;
        END IF;

        -- 4. Fallback to direct numeric CUSTOMERID
        IF VCUSTOMERID IS NULL AND VIDENTIFIER REGEXP '^[0-9]+$' THEN
            SELECT C.CUSTOMERID INTO VCUSTOMERID
            FROM CMS_CUSTOMER C
            WHERE C.CUSTOMERID = CAST(VIDENTIFIER AS UNSIGNED)
            LIMIT 1;
        END IF;

        IF VCUSTOMERID IS NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Employee or badge not recognized';
        END IF;

        -- 5. Auto-detect active meal slot if PDAYSLOTID was not explicitly specified
        IF VACTIVESLOTID IS NULL AND VCANTEENID IS NOT NULL THEN
            SELECT DS.DAYSLOTID INTO VACTIVESLOTID
            FROM CMS_DAYSLOT DS
            WHERE DS.CANTEENID = VCANTEENID
              AND DS.SERVDATE = CURDATE()
              AND DS.STATUSID = 10
              AND CURRENT_TIME() BETWEEN (DS.STARTTIME - INTERVAL 30 MINUTE) AND (DS.ENDTIME + INTERVAL 30 MINUTE)
            ORDER BY DS.STARTTIME ASC
            LIMIT 1;
        END IF;

        -- 6. Slot-Aware Matching: First look for a booking in the active meal slot
        IF VACTIVESLOTID IS NOT NULL THEN
            SELECT B.BOOKID INTO VBOOKID
            FROM CMS_BOOKING B
            JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
            JOIN CMS_BOOKITEM BI ON BI.BOOKID = B.BOOKID
            JOIN CMS_DAYMENU DM ON DM.DAYMENUID = BI.DAYMENUID
            WHERE B.CUSTOMERID = VCUSTOMERID
              AND B.SERVICEDATE = CURDATE()
              AND DM.DAYSLOTID = VACTIVESLOTID
              AND ST.STATUSCODE IN ('CRT', 'SRV')
            ORDER BY (CASE WHEN ST.STATUSCODE = 'CRT' THEN 0 ELSE 1 END) ASC, B.BOOKID DESC
            LIMIT 1;
        END IF;

        -- 7. Fallback: If no booking in current slot, find ANY booking for today (prioritizing CRT)
        IF VBOOKID IS NULL THEN
            SELECT B.BOOKID INTO VBOOKID
            FROM CMS_BOOKING B
            JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
            LEFT JOIN CMS_BOOKITEM BI ON BI.BOOKID = B.BOOKID
            LEFT JOIN CMS_DAYMENU DM ON DM.DAYMENUID = BI.DAYMENUID
            LEFT JOIN CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
            WHERE B.CUSTOMERID = VCUSTOMERID
              AND B.SERVICEDATE = CURDATE()
              AND ST.STATUSCODE IN ('CRT', 'SRV')
              AND (VCANTEENID IS NULL OR DS.CANTEENID = VCANTEENID)
            ORDER BY (CASE WHEN ST.STATUSCODE = 'CRT' THEN 0 ELSE 1 END) ASC, B.BOOKID DESC
            LIMIT 1;
        END IF;
    END IF;

    IF VBOOKID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'No active booking found for today';
    END IF;

    -- Result Set 1: Booking Header with Slot Window context
    SELECT
        B.BOOKID,
        B.BOOKNO,
        BT.BOOKTYPECODE,
        BT.BOOKTYPENAME,
        B.CUSTOMERID,
        C.CTYPECODE,
        C.DISPNAME AS CUSTOMERNAME,
        U.LOGINID,
        B.SERVICEID,
        S.SERVCODE,
        S.SERVNAME,
        DS.DAYSLOTID,
        DS.SLOTNO,
        DS.STARTTIME AS SLOTSTARTTIME,
        DS.ENDTIME AS SLOTENDTIME,
        DS.CANTEENID,
        CAN.CANTEENNAME,
        B.SERVICEDATE,
        B.STATUSID,
        ST.STATUSCODE AS STATUSCODE,
        B.TOTALITEMS,
        B.TOTALQTY,
        B.TOTALAMOUNT,
        B.BOOKEDON,
        B.SERVEDBY,
        USRV.FULLNAME AS SERVEDBYNAME,
        B.SERVEDON,
        B.KIOSKID,
        KD.DEVICECODE AS SERVEDKIOSKCODE,
        (CASE 
            WHEN DS.STARTTIME IS NOT NULL AND CURRENT_TIME() BETWEEN (DS.STARTTIME - INTERVAL 15 MINUTE) AND (DS.ENDTIME + INTERVAL 15 MINUTE) THEN 1 
            ELSE 0 
        END) AS ISINWINDOW,
        B.REMARKS
    FROM CMS_BOOKING B
    JOIN CMS_BOOKTYPE BT ON BT.BOOKTYPEID = B.BOOKTYPEID
    JOIN CMS_CUSTOMER C  ON C.CUSTOMERID  = B.CUSTOMERID
    JOIN CMS_SERVICE  S  ON S.SERVICEID   = B.SERVICEID
    JOIN CMS_STATUS   ST ON ST.STATUSID   = B.STATUSID
    LEFT JOIN CMS_USER U ON U.USERID      = C.USERID
    LEFT JOIN CMS_USER USRV ON USRV.USERID = B.SERVEDBY
    LEFT JOIN CMS_KIOSK_DEVICE KD ON KD.KIOSKID = B.KIOSKID
    LEFT JOIN CMS_BOOKITEM BI ON BI.BOOKID = B.BOOKID
    LEFT JOIN CMS_DAYMENU DM ON DM.DAYMENUID = BI.DAYMENUID
    LEFT JOIN CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
    LEFT JOIN CMS_CANTEEN CAN ON CAN.CANTEENID = DS.CANTEENID
    WHERE B.BOOKID = VBOOKID
    LIMIT 1;

    -- Result Set 2: Booking Items
    SELECT
        BI.BOOKITEMID,
        BI.DAYMENUID,
        BI.MENUITEMID,
        MI.MENUCODE,
        MI.SHORTNAME,
        MI.ITEMNAME,
        MI.ISVEG,
        BI.QTY,
        BI.RATE,
        BI.AMOUNT,
        BI.STATUSID,
        ST.STATUSCODE AS STATUSCODE
    FROM CMS_BOOKITEM BI
    JOIN CMS_MENUITEM MI ON MI.MENUITEMID = BI.MENUITEMID
    JOIN CMS_STATUS ST ON ST.STATUSID = BI.STATUSID
    WHERE BI.BOOKID = VBOOKID
    ORDER BY BI.BOOKITEMID ASC;

END$$

/* ============================================================
   CMSKIOSKSERVEBOOKING
   Atomically marks booking as served, attributing staff user & physical kiosk.
   Includes built-in idempotency (returns ALREADY_SERVED = 1).
   ============================================================ */
DROP PROCEDURE IF EXISTS CMSKIOSKSERVEBOOKING$$

CREATE PROCEDURE CMSKIOSKSERVEBOOKING (
    IN PBOOKID  INT,
    IN PUSERID  INT,
    IN PKIOSKID INT
)
BEGIN
    DECLARE VSTATUSID     INT;
    DECLARE VBOOKHISTID   INT;
    DECLARE VCUSTOMERID   INT;
    DECLARE VCTYPECODE    VARCHAR(10);
    DECLARE VTOTALAMOUNT  DECIMAL(12,2);

    DECLARE EXIT HANDLER FOR SQLEXCEPTION 
    BEGIN 
        ROLLBACK; 
        RESIGNAL; 
    END;

    IF PBOOKID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking ID is required';
    END IF;

    -- Check current status
    SELECT B.STATUSID, B.CUSTOMERID, C.CTYPECODE, B.TOTALAMOUNT
    INTO VSTATUSID, VCUSTOMERID, VCTYPECODE, VTOTALAMOUNT
    FROM CMS_BOOKING B
    JOIN CMS_CUSTOMER C ON C.CUSTOMERID = B.CUSTOMERID
    WHERE B.BOOKID = PBOOKID;

    IF VSTATUSID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking not found';
    END IF;

    -- Idempotent check: if already served (32 = 'SRV'), acknowledge cleanly
    IF VSTATUSID = 32 THEN
        SELECT PBOOKID AS BOOKID, 32 AS STATUSID, 'SRV' AS STATUSCODE, 1 AS ALREADY_SERVED;
    ELSEIF VSTATUSID = 33 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot serve a cancelled booking';
    ELSE
        START TRANSACTION;

        -- Record Audit History
        INSERT INTO CMS_BOOKHIST (
            BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
            STATUSID, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
            BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
            KIOSKID,
            REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, CHANGEDBY, CHGREASON
        )
        SELECT
            BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
            STATUSID, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
            BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
            PKIOSKID,
            REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, PUSERID, 'Served at Kiosk'
        FROM CMS_BOOKING
        WHERE BOOKID = PBOOKID;

        SET VBOOKHISTID = LAST_INSERT_ID();

        INSERT INTO CMS_BOOKITMHS (BOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUSID)
        SELECT VBOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUSID
        FROM CMS_BOOKITEM
        WHERE BOOKID = PBOOKID;

        -- 32 = 'SRV' (Served)
        UPDATE CMS_BOOKING
        SET STATUSID = 32,
            SERVEDBY = PUSERID,
            SERVEDON = CURRENT_TIMESTAMP,
            KIOSKID = COALESCE(PKIOSKID, KIOSKID),
            UPDATEDBY = PUSERID,
            UPDATEDAT = CURRENT_TIMESTAMP
        WHERE BOOKID = PBOOKID;

        UPDATE CMS_BOOKITEM
        SET STATUSID = 32,
            UPDATEDAT = CURRENT_TIMESTAMP
        WHERE BOOKID = PBOOKID AND STATUSID = 30;

        DELETE FROM CMS_PBACTIVE WHERE BOOKID = PBOOKID;

        -- Settle wallet reserved funds for contract employees & visitors
        IF VCTYPECODE IN ('CNT', 'VIS', 'CONTEMP', 'VISITOR') THEN
            UPDATE CMS_WALLET
            SET RESERVEDAMT = GREATEST(0, RESERVEDAMT - VTOTALAMOUNT),
                UPDATEDBY = PUSERID,
                UPDATEDAT = CURRENT_TIMESTAMP
            WHERE CUSTOMERID = VCUSTOMERID;
        END IF;

        COMMIT;

        SELECT PBOOKID AS BOOKID, 32 AS STATUSID, 'SRV' AS STATUSCODE, 0 AS ALREADY_SERVED;
    END IF;
END$$

/* ============================================================
   CMSKIOSKSCANSELFSERVICE
   High-performance single round-trip scan for Employee Self-Service Kiosks.
   Returns:
     RS-1: Customer Profile + Wallet Eligibility & Balance
     RS-2: Today's Bookings for current meal slots
     RS-3: Upcoming Pre-Bookings
   ============================================================ */
DROP PROCEDURE IF EXISTS CMSKIOSKSCANSELFSERVICE$$

CREATE PROCEDURE CMSKIOSKSCANSELFSERVICE (
    IN PIDENTIFIER VARCHAR(255),
    IN PCANTEENID   INT,
    IN PKIOSKID     INT
)
BEGIN
    DECLARE VCUSTOMERID INT DEFAULT NULL;
    DECLARE VIDENTIFIER VARCHAR(255);

    IF PIDENTIFIER IS NULL OR TRIM(PIDENTIFIER) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Identifier or card badge is required';
    END IF;

    SET VIDENTIFIER = TRIM(PIDENTIFIER);

    -- 1. Try RFID KeyCard
    SELECT AK.CUSTOMERID INTO VCUSTOMERID
    FROM CMS_ACCKEY AK
    JOIN CMS_STATUS STAK ON STAK.STATUSID = AK.STATUSID
    WHERE AK.KEYVALUE = VIDENTIFIER
      AND STAK.STATUSCODE = 'ACT'
      AND (AK.EXPIRESAT IS NULL OR AK.EXPIRESAT > CURRENT_TIMESTAMP)
    LIMIT 1;

    -- 2. Fallback to CMS_USER.LOGINID
    IF VCUSTOMERID IS NULL THEN
        SELECT C.CUSTOMERID INTO VCUSTOMERID
        FROM CMS_USER U
        JOIN CMS_CUSTOMER C ON C.USERID = U.USERID
        WHERE U.LOGINID = VIDENTIFIER
        LIMIT 1;
    END IF;

    -- 3. Fallback to direct numeric CUSTOMERID
    IF VCUSTOMERID IS NULL AND VIDENTIFIER REGEXP '^[0-9]+$' THEN
        SELECT C.CUSTOMERID INTO VCUSTOMERID
        FROM CMS_CUSTOMER C
        WHERE C.CUSTOMERID = CAST(VIDENTIFIER AS UNSIGNED)
        LIMIT 1;
    END IF;

    IF VCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Employee or badge not recognized';
    END IF;

    -- Result Set 1: Customer Profile + Wallet
    SELECT 
        C.CUSTOMERID,
        C.DISPNAME,
        C.CTYPECODE,
        U.LOGINID,
        (CASE WHEN C.CTYPECODE IN ('CONTEMP', 'CNT', 'VIS', 'VISITOR') THEN 1 ELSE 0 END) AS ISWALLETELIGIBLE,
        COALESCE(W.BALANCE, 0.00) AS WALLETBALANCE,
        COALESCE(W.RESERVEDAMT, 0.00) AS RESERVEDAMT,
        W.STATUSID AS WALLETSTATUSID
    FROM CMS_CUSTOMER C
    LEFT JOIN CMS_USER U ON U.USERID = C.USERID
    LEFT JOIN CMS_WALLET W ON W.CUSTOMERID = C.CUSTOMERID
    WHERE C.CUSTOMERID = VCUSTOMERID;

    -- Result Set 2: Today's Bookings
    SELECT 
        B.BOOKID,
        B.BOOKNO,
        B.SERVICEID,
        S.SERVNAME,
        B.SERVICEDATE,
        B.STATUSID,
        ST.STATUSCODE,
        B.TOTALITEMS,
        B.TOTALQTY,
        B.TOTALAMOUNT,
        B.SERVEDON,
        B.SERVEDBY
    FROM CMS_BOOKING B
    JOIN CMS_SERVICE S ON S.SERVICEID = B.SERVICEID
    JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
    WHERE B.CUSTOMERID = VCUSTOMERID
      AND B.SERVICEDATE = CURDATE()
    ORDER BY B.BOOKID DESC;

    -- Result Set 3: Upcoming Pre-Bookings
    SELECT 
        B.BOOKID,
        B.BOOKNO,
        B.SERVICEID,
        S.SERVNAME,
        B.SERVICEDATE,
        B.STATUSID,
        ST.STATUSCODE,
        B.TOTALITEMS,
        B.TOTALQTY,
        B.TOTALAMOUNT,
        B.BOOKEDON
    FROM CMS_BOOKING B
    JOIN CMS_SERVICE S ON S.SERVICEID = B.SERVICEID
    JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
    WHERE B.CUSTOMERID = VCUSTOMERID
      AND B.SERVICEDATE > CURDATE()
      AND ST.STATUSCODE = 'CRT'
    ORDER BY B.SERVICEDATE ASC, B.BOOKID ASC;

END$$

DELIMITER ;
