USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDMENUTPL;
DROP PROCEDURE IF EXISTS CMSUPDMENUTPL;
DROP PROCEDURE IF EXISTS CMSGETMENUTPL;
DROP PROCEDURE IF EXISTS CMSLISTMENUTPL;
DROP PROCEDURE IF EXISTS CMSDEACTMENUTPL;
DROP PROCEDURE IF EXISTS CMSADDMENUTPLDT;
DROP PROCEDURE IF EXISTS CMSREMOVEMENUTPLDT;
DROP PROCEDURE IF EXISTS CMSLISTMENUTPLDT;
DROP PROCEDURE IF EXISTS CMSAPPLYMENUTPL;
DROP PROCEDURE IF EXISTS CMSBULKGENERATEMENU;
DROP PROCEDURE IF EXISTS CMSDRAFTMENUTPL;

DELIMITER $$

/* ============================================================
   CMS_MENUTPL / CMS_MENUTPLDT — Menu Templates
   ============================================================ */

CREATE PROCEDURE CMSADDMENUTPL (
    IN PCANTEENID INT,
    IN PSERVICEID INT,
    IN PTPLNAME   VARCHAR(80),
    IN PWEEKDAY   TINYINT,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VMENUTPLID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCANTEENID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required'; END IF;
    IF PSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required'; END IF;
    IF PTPLNAME IS NULL OR TRIM(PTPLNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template Name is required'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUTPL (CANTEENID, SERVICEID, TPLNAME, WEEKDAY, STATUSID, CREATEDBY)
    VALUES (PCANTEENID, PSERVICEID, TRIM(PTPLNAME), PWEEKDAY, 10, PCREATEDBY);
    SET VMENUTPLID = LAST_INSERT_ID();
    COMMIT;
    SELECT VMENUTPLID AS MENUTPLID;
END$$


CREATE PROCEDURE CMSUPDMENUTPL (
    IN PMENUTPLID INT,
    IN PTPLNAME   VARCHAR(80),
    IN PWEEKDAY   TINYINT,
    IN PSTATUSCODE VARCHAR(20)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE VSTATUSID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUTPLID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUTPL WHERE MENUTPLID = PMENUTPLID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template not found'; END IF;

    IF PSTATUSCODE IS NOT NULL THEN
        SELECT STATUSID INTO VSTATUSID FROM CMS_STATUS WHERE STATUSCODE = PSTATUSCODE AND STATUSGRP = 'SYS';
        IF VSTATUSID IS NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid Status Code';
        END IF;
    END IF;

    START TRANSACTION;
    UPDATE CMS_MENUTPL
    SET    TPLNAME   = COALESCE(PTPLNAME, TPLNAME),
           WEEKDAY   = PWEEKDAY,
           STATUSID  = COALESCE(VSTATUSID, STATUSID),
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  MENUTPLID = PMENUTPLID;
    COMMIT;
    SELECT PMENUTPLID AS MENUTPLID;
END$$


CREATE PROCEDURE CMSGETMENUTPL (IN PMENUTPLID INT)
BEGIN
    SELECT T.MENUTPLID, T.CANTEENID, C.CANTEENNAME,
           T.SERVICEID, S.SERVCODE, S.SERVNAME,
           T.TPLNAME, T.WEEKDAY, T.STATUSID, ST.STATUSCODE AS STATUSCODE,
           T.CREATEDBY, T.CREATEDAT, T.UPDATEDAT
    FROM   CMS_MENUTPL T
    JOIN   CMS_STATUS ST ON ST.STATUSID = T.STATUSID
    JOIN   CMS_CANTEEN C ON C.CANTEENID = T.CANTEENID
    JOIN   CMS_SERVICE S ON S.SERVICEID = T.SERVICEID
    WHERE  T.MENUTPLID = PMENUTPLID;
END$$


CREATE PROCEDURE CMSLISTMENUTPL (IN PCANTEENID INT, IN PSERVICEID INT)
BEGIN
    SELECT T.MENUTPLID, T.CANTEENID, C.CANTEENNAME,
           T.SERVICEID, S.SERVCODE, S.SERVNAME,
           T.TPLNAME, T.WEEKDAY, T.STATUSID, ST.STATUSCODE AS STATUSCODE
    FROM   CMS_MENUTPL T
    JOIN   CMS_STATUS ST ON ST.STATUSID = T.STATUSID
    JOIN   CMS_CANTEEN C ON C.CANTEENID = T.CANTEENID
    JOIN   CMS_SERVICE S ON S.SERVICEID = T.SERVICEID
    WHERE  (PCANTEENID IS NULL OR T.CANTEENID = PCANTEENID)
      AND  (PSERVICEID IS NULL OR T.SERVICEID = PSERVICEID)
      AND  ST.STATUSCODE = 'ACT'
    ORDER BY T.TPLNAME;
END$$


CREATE PROCEDURE CMSDEACTMENUTPL (IN PMENUTPLID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUTPLID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUTPL WHERE MENUTPLID = PMENUTPLID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template not found'; END IF;
    START TRANSACTION;
    UPDATE CMS_MENUTPL SET STATUSID = 11, UPDATEDAT = CURRENT_TIMESTAMP WHERE MENUTPLID = PMENUTPLID;
    COMMIT;
    SELECT PMENUTPLID AS MENUTPLID;
END$$


CREATE PROCEDURE CMSADDMENUTPLDT (
    IN PMENUTPLID   INT,
    IN PMENUITEMID  INT,
    IN PISSPECIAL   TINYINT,
    IN PISPREBOOK   TINYINT,
    IN PISKIOSK    TINYINT,
    IN PMAXQTY      INT,
    IN PDEFAVAILQTY INT
)
BEGIN
    DECLARE VMENUTPLDTID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUTPLID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template ID is required'; END IF;
    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUTPLDT (MENUTPLID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK, MAXQTY, DEFAVAILQTY)
    VALUES (PMENUTPLID, PMENUITEMID, COALESCE(PISSPECIAL, 0), COALESCE(PISPREBOOK, 1),
            COALESCE(PISKIOSK, 1), COALESCE(PMAXQTY, 1), COALESCE(PDEFAVAILQTY, 0));
    SET VMENUTPLDTID = LAST_INSERT_ID();
    COMMIT;
    SELECT VMENUTPLDTID AS MENUTPLDTID;
END$$


CREATE PROCEDURE CMSREMOVEMENUTPLDT (IN PMENUTPLDTID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUTPLDTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template Detail ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUTPLDT WHERE MENUTPLDTID = PMENUTPLDTID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template detail not found'; END IF;
    START TRANSACTION;
    DELETE FROM CMS_MENUTPLDT WHERE MENUTPLDTID = PMENUTPLDTID;
    COMMIT;
    SELECT PMENUTPLDTID AS MENUTPLDTID;
END$$


CREATE PROCEDURE CMSLISTMENUTPLDT (IN PMENUTPLID INT)
BEGIN
    SELECT TD.MENUTPLDTID, TD.MENUTPLID, TD.MENUITEMID,
           MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           TD.ISSPECIAL, TD.ISPREBOOK, TD.ISKIOSK,
           TD.MAXQTY, TD.DEFAVAILQTY
    FROM   CMS_MENUTPLDT TD
    JOIN   CMS_MENUITEM MI ON MI.MENUITEMID = TD.MENUITEMID
    WHERE  TD.MENUTPLID = PMENUTPLID
    ORDER BY MI.ITEMNAME;
END$$


/* ============================================================
   CMSAPPLYMENUTPL — Materialise a template into day-menu rows

   Creates the day slot if it doesn't exist, then inserts
   day-menu items from the template. Booking windows default
   to: BOOKUNTIL = slot start - 1h,
   CANCELUNTIL = slot start - 30min.  All can be overridden after.
   ============================================================ */

CREATE PROCEDURE CMSAPPLYMENUTPL (
    IN PMENUTPLID  INT,
    IN PTARGETDATE DATE,
    IN PCREATEDBY  INT,
    OUT POUTDAYSLOTID INT,
    OUT POUTITEMSINSERTED INT
)
BEGIN
    DECLARE VSERVICEID   INT;
    DECLARE VCANTEENID   INT;
    DECLARE VTPLSTATUSID INT;
    DECLARE VDEFSTART    TIME;
    DECLARE VDEFEND      TIME;
    DECLARE VDAYSLOTID   INT;
    DECLARE VSLOTNO      VARCHAR(30);
    DECLARE VDMENUNO     VARCHAR(20);
    DECLARE VINSERTED    INT DEFAULT 0;
    
    DECLARE done INT DEFAULT FALSE;
    DECLARE v_menuitemid INT;
    DECLARE v_isspecial TINYINT;
    DECLARE v_isprebook TINYINT;
    DECLARE v_iskiosk TINYINT;
    DECLARE v_defavailqty INT;
    DECLARE v_maxqty INT;
    
    DECLARE cur CURSOR FOR 
        SELECT TD.MENUITEMID, TD.ISSPECIAL, TD.ISPREBOOK, TD.ISKIOSK, TD.DEFAVAILQTY, TD.MAXQTY
        FROM   CMS_MENUTPLDT TD
        WHERE  TD.MENUTPLID = PMENUTPLID
          AND  NOT EXISTS (
              SELECT 1 FROM CMS_DAYMENU DM
              WHERE DM.DAYSLOTID = VDAYSLOTID AND DM.MENUITEMID = TD.MENUITEMID
          );
          
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUTPLID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template ID is required'; END IF;
    IF PTARGETDATE IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Target Date is required'; END IF;

    SELECT T.SERVICEID, T.CANTEENID, T.STATUSID
    INTO   VSERVICEID, VCANTEENID, VTPLSTATUSID
    FROM   CMS_MENUTPL T
    WHERE  T.MENUTPLID = PMENUTPLID;

    IF VSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template not found'; END IF;
    IF VTPLSTATUSID <> 10 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template is not active'; END IF;

    SELECT DEFSTART, DEFEND INTO VDEFSTART, VDEFEND
    FROM CMS_SERVICE WHERE SERVICEID = VSERVICEID;

    START TRANSACTION;

    -- Create or find existing day slot
    SELECT DAYSLOTID INTO VDAYSLOTID
    FROM CMS_DAYSLOT WHERE SERVICEID = VSERVICEID AND SERVDATE = PTARGETDATE;

    IF VDAYSLOTID IS NULL THEN
        CALL CMSGENAUTO('CMS_DAYSLOT', 'SLOTNO', VSLOTNO);
        -- 10 = 'ACT', 20 = 'DRF'
        INSERT INTO CMS_DAYSLOT (SLOTNO, CANTEENID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUSID, APPRSTATUSID, CREATEDBY)
        VALUES (VSLOTNO, VCANTEENID, VSERVICEID, PTARGETDATE, VDEFSTART, VDEFEND, 10, 20, PCREATEDBY);
        SET VDAYSLOTID = LAST_INSERT_ID();
    END IF;

    OPEN cur;
    read_loop: LOOP
        FETCH cur INTO v_menuitemid, v_isspecial, v_isprebook, v_iskiosk, v_defavailqty, v_maxqty;
        IF done THEN
            LEAVE read_loop;
        END IF;
        
        CALL CMSGENAUTO('CMS_DAYMENU', 'DMENUNO', VDMENUNO);
        
        INSERT INTO CMS_DAYMENU (
            DMENUNO, DAYSLOTID, MENUITEMID, ISBASE, ISSPECIAL, ISPREBOOK, ISKIOSK,
            BOOKUNTIL, CANCELUNTIL, AVAILQTY, MAXQTY, STATUSID, CREATEDBY
        ) VALUES (
            VDMENUNO, VDAYSLOTID, v_menuitemid, 1, v_isspecial, v_isprebook, v_iskiosk,
            TIMESTAMP(PTARGETDATE, SUBTIME(VDEFSTART, '01:00:00')),
            TIMESTAMP(PTARGETDATE, SUBTIME(VDEFSTART, '00:30:00')),
            v_defavailqty, v_maxqty, 10, PCREATEDBY
        );
        SET VINSERTED = VINSERTED + 1;
    END LOOP;
    CLOSE cur;

    COMMIT;

    SET POUTDAYSLOTID = VDAYSLOTID;
    SET POUTITEMSINSERTED = VINSERTED;
END$$

/* ============================================================
   CMSBULKGENERATEMENU — Generate menus for a date range
   Skips holidays. Uses Weekday mapping to find templates.
   ============================================================ */

CREATE PROCEDURE CMSBULKGENERATEMENU (
    IN PCANTEENID INT,
    IN PSERVICEID INT,
    IN PSTARTDATE DATE,
    IN PENDDATE   DATE,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VCURDATE DATE;
    DECLARE VISHOLIDAY INT;
    DECLARE VMENUTPLID INT;
    DECLARE VWEEKDAY TINYINT;
    DECLARE VOUTDAYSLOTID INT;
    DECLARE VOUTITEMSINSERTED INT;
    DECLARE VTOTALSLOTS INT DEFAULT 0;
    DECLARE VTOTALITEMS INT DEFAULT 0;

    IF PCANTEENID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required'; END IF;
    IF PSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required'; END IF;
    IF PSTARTDATE IS NULL OR PENDDATE IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Start and End dates are required'; END IF;
    IF PENDDATE < PSTARTDATE THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'End date cannot be before Start date'; END IF;

    IF DATEDIFF(PENDDATE, PSTARTDATE) > 31 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot bulk generate for more than 31 days at a time';
    END IF;

    SET VCURDATE = PSTARTDATE;

    WHILE VCURDATE <= PENDDATE DO
        -- Check for holidays (exact date match or recurring match by month/day)
        SELECT COUNT(*) INTO VISHOLIDAY
        FROM CMS_HOLIDAY
        WHERE STATUSID = 10
          AND (HOLIDAYDATE = VCURDATE 
               OR (ISRECURRING = 1 AND MONTH(HOLIDAYDATE) = MONTH(VCURDATE) AND DAY(HOLIDAYDATE) = DAY(VCURDATE)));

        IF VISHOLIDAY = 0 THEN
            -- MySQL WEEKDAY: 0=Mon, 6=Sun. We map to 1=Mon, 7=Sun
            SET VWEEKDAY = WEEKDAY(VCURDATE) + 1;
            
            SET VMENUTPLID = NULL;
            SELECT MENUTPLID INTO VMENUTPLID
            FROM CMS_MENUTPL
            WHERE CANTEENID = PCANTEENID
              AND SERVICEID = PSERVICEID
              AND WEEKDAY = VWEEKDAY
              AND STATUSID = 10
            LIMIT 1;
              
            IF VMENUTPLID IS NOT NULL THEN
                CALL CMSAPPLYMENUTPL(VMENUTPLID, VCURDATE, PCREATEDBY, VOUTDAYSLOTID, VOUTITEMSINSERTED);
                SET VTOTALSLOTS = VTOTALSLOTS + 1;
                SET VTOTALITEMS = VTOTALITEMS + COALESCE(VOUTITEMSINSERTED, 0);
            END IF;
        END IF;

        SET VCURDATE = DATE_ADD(VCURDATE, INTERVAL 1 DAY);
    END WHILE;

    SELECT VTOTALSLOTS AS TOTALSLOTS_CREATED, VTOTALITEMS AS TOTALITEMS_INSERTED;
END$$


/* ============================================================
   CMSDRAFTMENUTPL — Smart Sample Generator for Menu Templates
   Fetches active items matching the selected Service (or generic items)
   and provides ready-to-use template defaults.
   ============================================================ */
CREATE PROCEDURE CMSDRAFTMENUTPL (
    IN PCANTEENID INT,
    IN PSERVICEID INT,
    IN PCOUNT     INT
)
BEGIN
    DECLARE VCOUNT INT;
    SET VCOUNT = COALESCE(PCOUNT, 6);
    IF VCOUNT <= 0 THEN SET VCOUNT = 6; END IF;
    IF VCOUNT > 30 THEN SET VCOUNT = 30; END IF;

    IF PSERVICEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required';
    END IF;

    SELECT MI.MENUITEMID,
           MI.MENUCODE,
           MI.ITEMNAME,
           MI.SHORTNAME,
           MI.ITEMDESCR,
           MI.ISSPECIAL,
           MI.SERVICEID,
           S.SERVCODE,
           S.SERVNAME,
           1 AS ISPREBOOK,
           1 AS ISKIOSK,
           1 AS MAXQTY,
           100 AS DEFAVAILQTY
    FROM   CMS_MENUITEM MI
    LEFT JOIN CMS_SERVICE S ON S.SERVICEID = MI.SERVICEID
    WHERE  MI.STATUSID = 10
      AND  (MI.SERVICEID = PSERVICEID OR MI.SERVICEID IS NULL)
    ORDER BY (CASE WHEN MI.SERVICEID = PSERVICEID THEN 0 ELSE 1 END), RAND()
    LIMIT VCOUNT;
END$$

DELIMITER ;