USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDMENUITEM;
DROP PROCEDURE IF EXISTS CMSUPDMENUITEM;
DROP PROCEDURE IF EXISTS CMSGETMENUITEM;
DROP PROCEDURE IF EXISTS CMSLISTMENUITEM;
DROP PROCEDURE IF EXISTS CMSSEARCHMENUITEM;
DROP PROCEDURE IF EXISTS CMSACTMENUITEM;
DROP PROCEDURE IF EXISTS CMSDEACTMENUITEM;

DROP PROCEDURE IF EXISTS CMSADDITEMPRICE;
DROP PROCEDURE IF EXISTS CMSGETITEMPRICE;
DROP PROCEDURE IF EXISTS CMSGETITEMPRICEDT;
DROP PROCEDURE IF EXISTS CMSLISTITEMPRICE;
DROP PROCEDURE IF EXISTS CMSDEACTITEMPRICE;
DROP PROCEDURE IF EXISTS CMSCHECKITEMPRICEREADINESS;


DELIMITER $$


/* ============================================================
   CMS_MENUITEM — Shared Menu Item Catalog (NO price columns)
   ============================================================ */

CREATE PROCEDURE CMSADDMENUITEM (
    IN PSHORTNAME VARCHAR(30),
    IN PITEMNAME  VARCHAR(100),
    IN PITEMDESCR VARCHAR(255),
    IN PISSPECIAL TINYINT,
    IN PSERVICEID INT,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VMENUITEMID INT;
    DECLARE VMENUCODE   VARCHAR(20);
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PSHORTNAME IS NULL OR TRIM(PSHORTNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Short Name is required'; END IF;
    IF PITEMNAME IS NULL OR TRIM(PITEMNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Name is required'; END IF;
    IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid special item flag'; END IF;

    -- Validate Service ID if provided
    IF PSERVICEID IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID AND STATUSID = 10) THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid or inactive Service ID';
        END IF;
    END IF;

    START TRANSACTION;
    
    -- Generate Auto-Number (e.g., ITM202608220001)
    CALL CMSGENAUTO('CMS_MENUITEM', 'MENUCODE', VMENUCODE);

    -- Insert Menu Item (10 = ACT)
    INSERT INTO CMS_MENUITEM (MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, SERVICEID, STATUSID, CREATEDBY)
    VALUES (VMENUCODE, TRIM(PSHORTNAME), TRIM(PITEMNAME), PITEMDESCR, COALESCE(PISSPECIAL, 0), PSERVICEID, 10, PCREATEDBY);
    
    SET VMENUITEMID = LAST_INSERT_ID();
    COMMIT;

    SELECT VMENUITEMID AS MENUITEMID, VMENUCODE AS MENUCODE;
END$$


CREATE PROCEDURE CMSUPDMENUITEM (
    IN PMENUITEMID INT,
    IN PSHORTNAME  VARCHAR(30),
    IN PITEMNAME   VARCHAR(100),
    IN PITEMDESCR  VARCHAR(255),
    IN PISSPECIAL  TINYINT,
    IN PSERVICEID  INT,
    IN PSTATUSCODE VARCHAR(10),
    IN PCHANGEDBY  INT,
    IN PCHGREASON  VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE VSTATUSID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;
    IF PSHORTNAME IS NULL OR TRIM(PSHORTNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Short Name is required'; END IF;
    IF PITEMNAME IS NULL OR TRIM(PITEMNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Name is required'; END IF;
    IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid special item flag'; END IF;
    
    -- Validate Service ID if provided
    IF PSERVICEID IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID AND STATUSID = 10) THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid or inactive Service ID';
        END IF;
    END IF;

    -- Validate Status Code exists
    SELECT STATUSID INTO VSTATUSID FROM CMS_STATUS WHERE STATUSCODE = PSTATUSCODE AND STATUSGRP = 'SYS';
    IF VSTATUSID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid status code'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_MENUHIST (MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUSID, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUSID, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;

    UPDATE CMS_MENUITEM
    SET    SHORTNAME = TRIM(PSHORTNAME),
           ITEMNAME  = TRIM(PITEMNAME),
           ITEMDESCR = PITEMDESCR,
           ISSPECIAL = COALESCE(PISSPECIAL, ISSPECIAL),
           SERVICEID = PSERVICEID,
           STATUSID  = VSTATUSID,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  MENUITEMID = PMENUITEMID;
    COMMIT;

    SELECT PMENUITEMID AS MENUITEMID;
END$$


CREATE PROCEDURE CMSGETMENUITEM (IN PMENUITEMID INT)
BEGIN
    SELECT MI.MENUITEMID, MI.SERVICEID, S.SERVCODE, S.SERVNAME,
           MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           MI.ITEMDESCR, MI.ISSPECIAL, MI.STATUSID, ST.STATUSCODE AS STATUSCODE, ST.STATUSNAME AS STATUSNAME,
           MI.CREATEDBY, MI.CREATEDAT, MI.UPDATEDAT
    FROM   CMS_MENUITEM MI
    LEFT JOIN CMS_SERVICE S ON S.SERVICEID = MI.SERVICEID
    JOIN   CMS_STATUS ST ON ST.STATUSID = MI.STATUSID
    WHERE  MI.MENUITEMID = PMENUITEMID;
END$$


CREATE PROCEDURE CMSLISTMENUITEM (
    IN PISSPECIAL TINYINT,
    IN PSTATUSCODE VARCHAR(10)
)
BEGIN
    SELECT MI.MENUITEMID, MI.SERVICEID, S.SERVCODE, S.SERVNAME,
           MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           MI.ITEMDESCR, MI.ISSPECIAL, MI.STATUSID, ST.STATUSCODE AS STATUSCODE,
           MI.CREATEDBY, MI.CREATEDAT, MI.UPDATEDAT
    FROM   CMS_MENUITEM MI
    LEFT JOIN CMS_SERVICE S ON S.SERVICEID = MI.SERVICEID
    JOIN   CMS_STATUS ST ON ST.STATUSID = MI.STATUSID
    WHERE  (PISSPECIAL IS NULL OR MI.ISSPECIAL = PISSPECIAL)
      AND  (PSTATUSCODE  IS NULL OR ST.STATUSCODE  = PSTATUSCODE)
    ORDER BY MI.ITEMNAME;
END$$


CREATE PROCEDURE CMSSEARCHMENUITEM (IN PKEYWORD VARCHAR(100))
BEGIN
    SELECT MI.MENUITEMID, MI.SERVICEID, S.SERVCODE, S.SERVNAME,
           MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           MI.ISSPECIAL, MI.STATUSID, ST.STATUSCODE AS STATUSCODE
    FROM   CMS_MENUITEM MI
    LEFT JOIN CMS_SERVICE S ON S.SERVICEID = MI.SERVICEID
    JOIN   CMS_STATUS ST ON ST.STATUSID = MI.STATUSID
    WHERE  (MI.MENUCODE  LIKE CONCAT('%', PKEYWORD, '%')
       OR   MI.SHORTNAME LIKE CONCAT('%', PKEYWORD, '%')
       OR   MI.ITEMNAME  LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY MI.ITEMNAME;
END$$


CREATE PROCEDURE CMSACTMENUITEM (IN PMENUITEMID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUHIST (MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUSID, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUSID, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    
    -- 10 = 'ACT'
    UPDATE CMS_MENUITEM SET STATUSID = 10, UPDATEDAT = CURRENT_TIMESTAMP WHERE MENUITEMID = PMENUITEMID;
    COMMIT;
    SELECT PMENUITEMID AS MENUITEMID;
END$$


CREATE PROCEDURE CMSDEACTMENUITEM (IN PMENUITEMID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUHIST (MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUSID, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUSID, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    
    -- 11 = 'DIS'
    UPDATE CMS_MENUITEM SET STATUSID = 11, UPDATEDAT = CURRENT_TIMESTAMP WHERE MENUITEMID = PMENUITEMID;
    COMMIT;
    SELECT PMENUITEMID AS MENUITEMID;
END$$


/* ============================================================
   CMS_ITEMPRICE + CMS_ITEMPRICEDT — Pricing Subsystem
   ============================================================ */

CREATE PROCEDURE CMSCHECKITEMPRICEREADINESS (
    IN PMENUITEMID INT,
    IN PSERVICEDATE DATE
)
BEGIN
    DECLARE VMISSINGTYPES VARCHAR(255);
    DECLARE VITEMPRICEID INT;
    DECLARE VMSG VARCHAR(255);

    SELECT IP.ITEMPRICEID INTO VITEMPRICEID
    FROM CMS_ITEMPRICE IP
    JOIN CMS_STATUS ST ON ST.STATUSID = IP.STATUSID
    WHERE IP.MENUITEMID = PMENUITEMID
      AND IP.EFFFROM <= COALESCE(PSERVICEDATE, CURRENT_DATE)
      AND ST.STATUSCODE = 'ACT'
    ORDER BY IP.EFFFROM DESC
    LIMIT 1;

    IF VITEMPRICEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'No effective price band found for this item on the given date';
    END IF;

    SELECT GROUP_CONCAT(CT.CTYPENAME SEPARATOR ', ') INTO VMISSINGTYPES
    FROM CMS_CUSTTYPE CT
    WHERE CT.ISACTIVE = 1
      AND NOT EXISTS (
          SELECT 1
          FROM CMS_ITEMPRICEDT IPD
          WHERE IPD.ITEMPRICEID = VITEMPRICEID
            AND IPD.CTYPECODE = CT.CTYPECODE
      );

    IF VMISSINGTYPES IS NOT NULL THEN
        SET VMSG = CONCAT('Price missing for active customer types: ', VMISSINGTYPES);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = VMSG;
    END IF;
END$$


CREATE PROCEDURE CMSADDITEMPRICE (
    IN PMENUITEMID INT,
    IN PEFFFROM    DATE,
    IN PPRICEJSON  JSON,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VITEMPRICEID INT;
    DECLARE VCOUNT       INT DEFAULT 0;
    DECLARE VINVALID     INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    IF PEFFFROM IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Effective From date is required'; END IF;
    IF PPRICEJSON IS NULL OR JSON_TYPE(PPRICEJSON) <> 'ARRAY' OR JSON_LENGTH(PPRICEJSON) = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'At least one price entry is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT 
    FROM CMS_MENUITEM MI 
    JOIN CMS_STATUS ST ON ST.STATUSID = MI.STATUSID
    WHERE MI.MENUITEMID = PMENUITEMID AND ST.STATUSCODE = 'ACT';
    
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Active menu item not found'; END IF;

    -- Validate all customer type codes exist
    SELECT COUNT(*) INTO VINVALID
    FROM JSON_TABLE(PPRICEJSON, '$[*]' COLUMNS (
        CTYPECODE VARCHAR(20) PATH '$.CTYPECODE',
        PRICE DECIMAL(10,2) PATH '$.PRICE'
    )) JT
    LEFT JOIN CMS_CUSTTYPE CT ON CT.CTYPECODE = JT.CTYPECODE
    WHERE CT.CTYPEID IS NULL OR CT.ISACTIVE = 0 OR JT.PRICE IS NULL OR JT.PRICE < 0;

    IF VINVALID > 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'One or more price entries have invalid customer type or negative price';
    END IF;

    START TRANSACTION;

    -- 10 = 'ACT'
    INSERT INTO CMS_ITEMPRICE (MENUITEMID, EFFFROM, STATUSID, CREATEDBY)
    VALUES (PMENUITEMID, PEFFFROM, 10, PCREATEDBY);
    SET VITEMPRICEID = LAST_INSERT_ID();

    INSERT INTO CMS_ITEMPRICEDT (ITEMPRICEID, CTYPECODE, PRICE)
    SELECT VITEMPRICEID, JT.CTYPECODE, JT.PRICE
    FROM JSON_TABLE(PPRICEJSON, '$[*]' COLUMNS (
        CTYPECODE VARCHAR(20) PATH '$.CTYPECODE',
        PRICE DECIMAL(10,2) PATH '$.PRICE'
    )) JT;

    COMMIT;
    SELECT VITEMPRICEID AS ITEMPRICEID;
END$$


CREATE PROCEDURE CMSGETITEMPRICE (
    IN PMENUITEMID  INT,
    IN PSERVICEDATE DATE
)
BEGIN
    DECLARE VEFFDATE DATE;

    SET VEFFDATE = COALESCE(PSERVICEDATE, CURRENT_DATE);

    SELECT IP.ITEMPRICEID, IP.MENUITEMID, IP.EFFFROM, IP.STATUSID, ST.STATUSCODE AS STATUSCODE,
           IPD.ITEMPRICEDTID, IPD.CTYPECODE, CT.CTYPENAME, IPD.PRICE
    FROM   CMS_ITEMPRICE IP
    JOIN   CMS_STATUS ST ON ST.STATUSID = IP.STATUSID
    JOIN   CMS_ITEMPRICEDT IPD ON IPD.ITEMPRICEID = IP.ITEMPRICEID
    JOIN   CMS_CUSTTYPE CT     ON CT.CTYPECODE    = IPD.CTYPECODE
    WHERE  IP.MENUITEMID = PMENUITEMID
      AND  IP.EFFFROM   <= VEFFDATE
      AND  ST.STATUSCODE = 'ACT'
      AND  IP.ITEMPRICEID = (
          SELECT IP2.ITEMPRICEID
          FROM   CMS_ITEMPRICE IP2
          JOIN   CMS_STATUS ST2 ON ST2.STATUSID = IP2.STATUSID
          WHERE  IP2.MENUITEMID = PMENUITEMID
            AND  IP2.EFFFROM  <= VEFFDATE
            AND  ST2.STATUSCODE = 'ACT'
          ORDER BY IP2.EFFFROM DESC
          LIMIT 1
      )
    ORDER BY IPD.CTYPECODE;
END$$


CREATE PROCEDURE CMSGETITEMPRICEDT (
    IN PMENUITEMID  INT,
    IN PCTYPECODE   VARCHAR(20),
    IN PSERVICEDATE DATE
)
BEGIN
    SELECT IPD.PRICE
    FROM   CMS_ITEMPRICE IP
    JOIN   CMS_STATUS ST ON ST.STATUSID = IP.STATUSID
    JOIN   CMS_ITEMPRICEDT IPD ON IPD.ITEMPRICEID = IP.ITEMPRICEID
    WHERE  IP.MENUITEMID  = PMENUITEMID
      AND  IPD.CTYPECODE  = PCTYPECODE
      AND  IP.EFFFROM    <= COALESCE(PSERVICEDATE, CURRENT_DATE)
      AND  ST.STATUSCODE = 'ACT'
    ORDER BY IP.EFFFROM DESC
    LIMIT 1;
END$$


CREATE PROCEDURE CMSLISTITEMPRICE (IN PMENUITEMID INT)
BEGIN
    SELECT IP.ITEMPRICEID, IP.MENUITEMID, MI.MENUCODE, MI.ITEMNAME,
           IP.EFFFROM, IP.STATUSID, ST.STATUSCODE AS STATUSCODE, IP.CREATEDBY, IP.CREATEDAT
    FROM   CMS_ITEMPRICE IP
    JOIN   CMS_STATUS ST ON ST.STATUSID = IP.STATUSID
    JOIN   CMS_MENUITEM MI ON MI.MENUITEMID = IP.MENUITEMID
    WHERE  IP.MENUITEMID = PMENUITEMID
    ORDER BY IP.EFFFROM DESC;
END$$


CREATE PROCEDURE CMSDEACTITEMPRICE (IN PITEMPRICEID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE VEFFFROM DATE;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PITEMPRICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Price ID is required'; END IF;
    SELECT COUNT(*), MAX(EFFFROM) INTO VCOUNT, VEFFFROM FROM CMS_ITEMPRICE WHERE ITEMPRICEID = PITEMPRICEID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Price band not found'; END IF;
    IF VEFFFROM <= CURRENT_DATE THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot withdraw a price band that is already effective'; END IF;

    START TRANSACTION;
    -- 11 = 'DIS'
    UPDATE CMS_ITEMPRICE SET STATUSID = 11, UPDATEDAT = CURRENT_TIMESTAMP WHERE ITEMPRICEID = PITEMPRICEID;
    COMMIT;
    SELECT PITEMPRICEID AS ITEMPRICEID;
END$$

DELIMITER ;