USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDUSER;
DROP PROCEDURE IF EXISTS CMSUPDUSER;
DROP PROCEDURE IF EXISTS CMSCHANGEPWD;
DROP PROCEDURE IF EXISTS CMSGETUSER;
DROP PROCEDURE IF EXISTS CMSLISTUSER;
DROP PROCEDURE IF EXISTS CMSSEARCHUSER;
DROP PROCEDURE IF EXISTS CMSACTUSER;
DROP PROCEDURE IF EXISTS CMSDEACTUSER;
DROP PROCEDURE IF EXISTS CMSLOGININFO;

DELIMITER $$
/* ============================================================
   CMS_USER — System User
   ============================================================ */




CREATE PROCEDURE CMSADDUSER (
    IN PLOGINID   VARCHAR(50),
    IN PFULLNAME  VARCHAR(120),
    IN PEMAIL     VARCHAR(120),
    IN PMOBILENO  VARCHAR(20),
    IN PPWDHASH   VARCHAR(255),
    IN PAUTHPROV  VARCHAR(20),
    IN PAUTHID    VARCHAR(120)
)
BEGIN
    DECLARE VUSERID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PLOGINID IS NULL OR TRIM(PLOGINID) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Login ID is required';
    END IF;
    IF PFULLNAME IS NULL OR TRIM(PFULLNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Full Name is required';
    END IF;
    IF PPWDHASH IS NULL OR TRIM(PPWDHASH) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Password hash is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_USER (LOGINID, FULLNAME, EMAIL, MOBILENO, PWDHASH, AUTHPROV, AUTHID)
    VALUES (TRIM(PLOGINID), TRIM(PFULLNAME), PEMAIL, PMOBILENO,
            PPWDHASH, COALESCE(PAUTHPROV, 'LOCAL'), PAUTHID);

    SET VUSERID = LAST_INSERT_ID();
    COMMIT;

    SELECT VUSERID AS USERID;
END$$


CREATE PROCEDURE CMSUPDUSER (
    IN PUSERID   INT,
    IN PFULLNAME VARCHAR(120),
    IN PEMAIL    VARCHAR(120),
    IN PMOBILENO VARCHAR(20),
    IN PAUTHPROV VARCHAR(20),
    IN PAUTHID   VARCHAR(120)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_USER WHERE USERID = PUSERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User not found';
    END IF;
    IF PFULLNAME IS NULL OR TRIM(PFULLNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Full Name is required';
    END IF;

    START TRANSACTION;
    UPDATE CMS_USER
    SET    FULLNAME  = TRIM(PFULLNAME),
           EMAIL     = PEMAIL,
           MOBILENO  = PMOBILENO,
           AUTHPROV  = COALESCE(PAUTHPROV, AUTHPROV),
           AUTHID    = PAUTHID,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  USERID    = PUSERID;
    COMMIT;

    SELECT PUSERID AS USERID;
END$$


CREATE PROCEDURE CMSGETUSER (IN PUSERID INT)
BEGIN
    SELECT U.USERID, U.LOGINID, U.FULLNAME, U.EMAIL, U.MOBILENO,
           U.AUTHPROV, U.ISACTIVE, U.CREATEDAT, U.UPDATEDAT
    FROM   CMS_USER U
    WHERE  U.USERID = PUSERID;
END$$


CREATE PROCEDURE CMSLISTUSER (
    IN PISACTIVE TINYINT
)
BEGIN
    SELECT U.USERID, U.LOGINID, U.FULLNAME, U.EMAIL, U.MOBILENO,
           U.AUTHPROV, U.ISACTIVE, U.CREATEDAT, U.UPDATEDAT
    FROM   CMS_USER U
    WHERE  (PISACTIVE IS NULL OR U.ISACTIVE = PISACTIVE)
    ORDER BY U.FULLNAME;
END$$


CREATE PROCEDURE CMSSEARCHUSER (IN PKEYWORD VARCHAR(120))
BEGIN
    SELECT U.USERID, U.LOGINID, U.FULLNAME, U.EMAIL, U.MOBILENO,
           U.AUTHPROV, U.ISACTIVE, U.CREATEDAT, U.UPDATEDAT
    FROM   CMS_USER U
    WHERE  (U.LOGINID  LIKE CONCAT('%', PKEYWORD, '%')
       OR   U.FULLNAME LIKE CONCAT('%', PKEYWORD, '%')
       OR   U.EMAIL    LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY U.FULLNAME;
END$$





CREATE PROCEDURE CMSCHANGEPWD (
    IN PUSERID     INT,
    IN PNEWPWDHASH VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID is required';
    END IF;
    IF PNEWPWDHASH IS NULL OR TRIM(PNEWPWDHASH) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'New password hash is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_USER WHERE USERID = PUSERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_USER SET PWDHASH = PNEWPWDHASH, UPDATEDAT = CURRENT_TIMESTAMP WHERE USERID = PUSERID;
    COMMIT;
    SELECT PUSERID AS USERID;
END$$


CREATE PROCEDURE CMSACTUSER (IN PUSERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_USER WHERE USERID = PUSERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_USER SET ISACTIVE = 1, UPDATEDAT = CURRENT_TIMESTAMP WHERE USERID = PUSERID;
    COMMIT;
    SELECT PUSERID AS USERID;
END$$


CREATE PROCEDURE CMSDEACTUSER (IN PUSERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_USER WHERE USERID = PUSERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_USER SET ISACTIVE = 0, UPDATEDAT = CURRENT_TIMESTAMP WHERE USERID = PUSERID;
    COMMIT;
    SELECT PUSERID AS USERID;
END$$


/* ============================================================
   CMSLOGININFO — Login Profile Fetch

   Rewritten for CMS_CONSUMERROLE + CMS_CANTEENROLE.
   Returns:
     Result set 1: User profile
     Result set 2: Consumer role
     Result set 3: Canteen role 
   ============================================================ */

CREATE PROCEDURE CMSLOGININFO (
    IN PLOGINID VARCHAR(50)
)
BEGIN
    DECLARE VUSERID INT DEFAULT NULL;

    /*------------------------------------------------------------
      Get USERID
    ------------------------------------------------------------*/
    SELECT USERID
      INTO VUSERID
    FROM CMS_USER
    WHERE LOGINID = PLOGINID
      AND ISACTIVE = 1
    LIMIT 1;

    /*------------------------------------------------------------
      Result Set 1
      User + Customer Information
    ------------------------------------------------------------*/
    SELECT
        U.USERID,
        U.LOGINID,
        U.FULLNAME,
        U.EMAIL,
        U.MOBILENO,
        U.PWDHASH,
        U.AUTHPROV,
        U.AUTHID,
        U.ISACTIVE,

        C.CUSTOMERID,
        C.CTYPECODE,
        C.DISPNAME,
        C.STATUSID AS CUSTOMERSTATUS

    FROM CMS_USER U
    LEFT JOIN CMS_CUSTOMER C
           ON C.USERID = U.USERID
    WHERE U.USERID = VUSERID;

    /*------------------------------------------------------------
      Result Set 2
      Consumer Roles
    ------------------------------------------------------------*/
    IF VUSERID IS NOT NULL THEN

        SELECT
            CR.USRROLEID,
            CR.ROLEID,
            R.ROLECODE,
            R.ROLENAME
        FROM CMS_CONSUMERROLE CR
        INNER JOIN CMS_ROLE R
                ON R.ROLEID = CR.ROLEID
        WHERE CR.USERID = VUSERID
          AND CR.ISACTIVE = 1
          AND R.ISACTIVE = 1
          AND (CR.VALIDFROM IS NULL
               OR CURRENT_TIMESTAMP >= CR.VALIDFROM)
          AND (CR.VALIDUNTIL IS NULL
               OR CURRENT_TIMESTAMP <= CR.VALIDUNTIL)
        ORDER BY R.ROLECODE;

    END IF;

    /*------------------------------------------------------------
      Result Set 3
      Canteen Role Assignments
    ------------------------------------------------------------*/
    IF VUSERID IS NOT NULL THEN

        SELECT
            CR.USRCANROLEID,
            CR.CANTEENID,
            CN.CANTEENCODE,
            CN.CANTEENNAME,

            CR.ROLEID,
            R.ROLECODE,
            R.ROLENAME,

            CR.ISDEFAULT

        FROM CMS_CANTEENROLE CR
        INNER JOIN CMS_CANTEEN CN
                ON CN.CANTEENID = CR.CANTEENID
        INNER JOIN CMS_ROLE R
                ON R.ROLEID = CR.ROLEID

        WHERE CR.USERID = VUSERID
          AND CR.ISACTIVE = 1
          AND R.ISACTIVE = 1
          AND (CR.VALIDFROM IS NULL
               OR CURRENT_TIMESTAMP >= CR.VALIDFROM)
          AND (CR.VALIDUNTIL IS NULL
               OR CURRENT_TIMESTAMP <= CR.VALIDUNTIL)

        ORDER BY
            CR.ISDEFAULT DESC,
            CN.CANTEENNAME;

    END IF;

END$$



DELIMITER ;

