-- ============================================================
-- MIGRATION: Add OFFSER to CMS_MENUHIST and update Stored Procedures
-- Run this script in MySQL Workbench or MySQL CLI against CMS_DB
-- ============================================================

USE cms_db;

-- 1. Add OFFSER column to CMS_MENUHIST if not present
SET @col_offser_hist_exists = (
    SELECT COUNT(*) 
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() 
      AND TABLE_NAME = 'CMS_MENUHIST' 
      AND COLUMN_NAME = 'OFFSER'
);

SET @sql_menuhist = IF(@col_offser_hist_exists = 0, 
    'ALTER TABLE CMS_MENUHIST ADD COLUMN OFFSER TINYINT(1) NOT NULL DEFAULT 0 AFTER ISSPECIAL;', 
    'SELECT 1;'
);
PREPARE stmt_mh FROM @sql_menuhist;
EXECUTE stmt_mh;
DEALLOCATE PREPARE stmt_mh;

-- 2. Update CMSADDMENUITEM
DELIMITER $$

DROP PROCEDURE IF EXISTS CMSADDMENUITEM$$
CREATE PROCEDURE CMSADDMENUITEM (
    IN PSHORTNAME  VARCHAR(30),
    IN PITEMNAME   VARCHAR(100),
    IN PITEMDESCR  VARCHAR(255),
    IN PISSPECIAL  TINYINT,
    IN PSERVICEID  INT,
    IN POFFSER     TINYINT,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VMENUITEMID INT;
    DECLARE VMENUCODE   VARCHAR(20);
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PSHORTNAME IS NULL OR TRIM(PSHORTNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Short Name is required'; END IF;
    IF PITEMNAME IS NULL OR TRIM(PITEMNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Name is required'; END IF;
    IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid special item flag'; END IF;
    IF COALESCE(POFFSER, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid official service flag'; END IF;

    IF PSERVICEID IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID AND STATUSID = 10) THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid or inactive Service ID';
        END IF;
    END IF;

    START TRANSACTION;
    CALL CMSGENAUTO('CMS_MENUITEM', 'MENUCODE', VMENUCODE);

    INSERT INTO CMS_MENUITEM (MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, SERVICEID, OFFSER, STATUSID, CREATEDBY)
    VALUES (VMENUCODE, TRIM(PSHORTNAME), TRIM(PITEMNAME), PITEMDESCR, COALESCE(PISSPECIAL, 0), PSERVICEID, COALESCE(POFFSER, 0), 10, PCREATEDBY);
    
    SET VMENUITEMID = LAST_INSERT_ID();
    COMMIT;

    SELECT VMENUITEMID AS MENUITEMID, VMENUCODE AS MENUCODE;
END$$

-- 3. Update CMSUPDMENUITEM
DROP PROCEDURE IF EXISTS CMSUPDMENUITEM$$
CREATE PROCEDURE CMSUPDMENUITEM (
    IN PMENUITEMID INT,
    IN PSHORTNAME  VARCHAR(30),
    IN PITEMNAME   VARCHAR(100),
    IN PITEMDESCR  VARCHAR(255),
    IN PISSPECIAL  TINYINT,
    IN PSERVICEID  INT,
    IN POFFSER     TINYINT,
    IN PSTATUSCODE VARCHAR(10),
    IN PCHANGEDBY  INT,
    IN PCHGREASON  VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE VSTATUSID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;
    IF PSHORTNAME IS NULL OR TRIM(PSHORTNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Short Name is required'; END IF;
    IF PITEMNAME IS NULL OR TRIM(PITEMNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Name is required'; END IF;
    IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid special item flag'; END IF;
    IF COALESCE(POFFSER, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid official service flag'; END IF;
    
    IF PSERVICEID IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID AND STATUSID = 10) THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid or inactive Service ID';
        END IF;
    END IF;

    SELECT STATUSID INTO VSTATUSID FROM CMS_STATUS WHERE STATUSCODE = PSTATUSCODE AND STATUSGRP = 'SYS';
    IF VSTATUSID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid status code'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_MENUHIST (MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, OFFSER, STATUSID, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, OFFSER, STATUSID, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;

    UPDATE CMS_MENUITEM
    SET    SHORTNAME = TRIM(PSHORTNAME),
           ITEMNAME  = TRIM(PITEMNAME),
           ITEMDESCR = PITEMDESCR,
           ISSPECIAL = COALESCE(PISSPECIAL, ISSPECIAL),
           SERVICEID = PSERVICEID,
           OFFSER    = COALESCE(POFFSER, OFFSER),
           STATUSID  = VSTATUSID,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  MENUITEMID = PMENUITEMID;
    COMMIT;

    SELECT PMENUITEMID AS MENUITEMID;
END$$

-- 4. Update CMSGETMENUITEM
DROP PROCEDURE IF EXISTS CMSGETMENUITEM$$
CREATE PROCEDURE CMSGETMENUITEM (IN PMENUITEMID INT)
BEGIN
    SELECT MI.MENUITEMID, MI.SERVICEID, S.SERVCODE, S.SERVNAME,
           MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           MI.ITEMDESCR, MI.ISSPECIAL, MI.OFFSER, MI.STATUSID, ST.STATUSCODE AS STATUSCODE, ST.STATUSNAME AS STATUSNAME,
           MI.CREATEDBY, MI.CREATEDAT, MI.UPDATEDAT
    FROM   CMS_MENUITEM MI
    LEFT JOIN CMS_SERVICE S ON S.SERVICEID = MI.SERVICEID
    JOIN   CMS_STATUS ST ON ST.STATUSID = MI.STATUSID
    WHERE  MI.MENUITEMID = PMENUITEMID;
END$$

-- 5. Update CMSLISTMENUITEM
DROP PROCEDURE IF EXISTS CMSLISTMENUITEM$$
CREATE PROCEDURE CMSLISTMENUITEM (
    IN PISSPECIAL TINYINT,
    IN PSTATUSCODE VARCHAR(10)
)
BEGIN
    SELECT MI.MENUITEMID, MI.SERVICEID, S.SERVCODE, S.SERVNAME,
           MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           MI.ITEMDESCR, MI.ISSPECIAL, MI.OFFSER, MI.STATUSID, ST.STATUSCODE AS STATUSCODE,
           MI.CREATEDBY, MI.CREATEDAT, MI.UPDATEDAT
    FROM   CMS_MENUITEM MI
    LEFT JOIN CMS_SERVICE S ON S.SERVICEID = MI.SERVICEID
    JOIN   CMS_STATUS ST ON ST.STATUSID = MI.STATUSID
    WHERE  (PISSPECIAL IS NULL OR MI.ISSPECIAL = PISSPECIAL)
      AND  (PSTATUSCODE  IS NULL OR ST.STATUSCODE  = PSTATUSCODE)
    ORDER BY MI.ITEMNAME;
END$$

-- 6. Update CMSACTMENUITEM & CMSDEACTMENUITEM
DROP PROCEDURE IF EXISTS CMSACTMENUITEM$$
CREATE PROCEDURE CMSACTMENUITEM (IN PMENUITEMID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUHIST (MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, OFFSER, STATUSID, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, OFFSER, STATUSID, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    
    UPDATE CMS_MENUITEM SET STATUSID = 10, UPDATEDAT = CURRENT_TIMESTAMP WHERE MENUITEMID = PMENUITEMID;
    COMMIT;
    SELECT PMENUITEMID AS MENUITEMID;
END$$

DROP PROCEDURE IF EXISTS CMSDEACTMENUITEM$$
CREATE PROCEDURE CMSDEACTMENUITEM (IN PMENUITEMID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUHIST (MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, OFFSER, STATUSID, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, SERVICEID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, OFFSER, STATUSID, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    
    UPDATE CMS_MENUITEM SET STATUSID = 11, UPDATEDAT = CURRENT_TIMESTAMP WHERE MENUITEMID = PMENUITEMID;
    COMMIT;
    SELECT PMENUITEMID AS MENUITEMID;
END$$

DELIMITER ;
