-- ============================================================
-- Migration: Add PCANTEENID filter to CMSLISTBOOK Stored Procedure
-- Purpose: Bind Bookings Monitor & Kiosk listing with Canteen
-- ============================================================

DELIMITER $$

DROP PROCEDURE IF EXISTS CMSLISTBOOK$$

CREATE PROCEDURE CMSLISTBOOK(
    IN PCUSTOMERID INT,
    IN PSERVICEID INT,
    IN PSTARTDATE DATE,
    IN PENDDATE DATE,
    IN PSTATUSCODE VARCHAR(10),
    IN PCANTEENID INT
)
BEGIN
    SELECT 
        B.BOOKID, B.BOOKNO, BT.BOOKTYPECODE, 
        B.CUSTOMERID, C.DISPNAME AS CUSTOMERNAME, CU.LOGINID,
        BK_CAN.CANTEENID, BK_CAN.CANTEENNAME,
        B.SERVICEID, S.SERVNAME, B.SERVICEDATE,
        B.STATUSID, ST.STATUSCODE AS STATUSCODE, B.TOTALITEMS, B.TOTALQTY, B.TOTALAMOUNT
    FROM CMS_BOOKING B
    INNER JOIN CMS_BOOKTYPE BT ON BT.BOOKTYPEID = B.BOOKTYPEID
    INNER JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
    INNER JOIN CMS_CUSTOMER C ON C.CUSTOMERID = B.CUSTOMERID
    LEFT JOIN CMS_USER CU ON CU.USERID = C.USERID
    INNER JOIN CMS_SERVICE S ON S.SERVICEID = B.SERVICEID
    LEFT JOIN (
        SELECT BI.BOOKID, DS.CANTEENID, C.CANTEENNAME
        FROM CMS_BOOKITEM BI
        JOIN CMS_DAYMENU DM ON DM.DAYMENUID = BI.DAYMENUID
        JOIN CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
        JOIN CMS_CANTEEN C  ON C.CANTEENID  = DS.CANTEENID
        GROUP BY BI.BOOKID, DS.CANTEENID, C.CANTEENNAME
    ) BK_CAN ON BK_CAN.BOOKID = B.BOOKID
    WHERE (PCUSTOMERID IS NULL OR B.CUSTOMERID = PCUSTOMERID)
      AND (PSERVICEID IS NULL OR B.SERVICEID = PSERVICEID)
      AND (PSTARTDATE IS NULL OR B.SERVICEDATE >= PSTARTDATE)
      AND (PENDDATE IS NULL OR B.SERVICEDATE <= PENDDATE)
      AND (PSTATUSCODE IS NULL OR ST.STATUSCODE = PSTATUSCODE)
      AND (PCANTEENID IS NULL OR BK_CAN.CANTEENID = PCANTEENID)
    ORDER BY B.SERVICEDATE DESC, B.BOOKNO DESC;
END$$

DELIMITER ;
