-- ============================================================
-- Migration: Add CANTEENID and CANTEENNAME to Booking Queries
-- Applies to: CMSGETBOOK, CMSLISTBOOK, CMSLISTBOOKHISTORY
-- ============================================================

DELIMITER $$

-- 1. CMSGETBOOK
DROP PROCEDURE IF EXISTS CMSGETBOOK$$
CREATE PROCEDURE CMSGETBOOK(
    IN PBOOKID INT
)
BEGIN
    SELECT 
        B.BOOKID, B.BOOKNO, B.BOOKTYPEID, BT.BOOKTYPECODE, BT.BOOKTYPENAME,
        B.CUSTOMERID, C.CTYPECODE, C.DISPNAME AS CUSTOMERNAME,
        BK_CAN.CANTEENID, BK_CAN.CANTEENNAME,
        B.SERVICEID, S.SERVNAME, B.SERVICEDATE,
        B.STATUSID, ST.STATUSCODE AS STATUSCODE, B.TOTALITEMS, B.TOTALQTY, B.TOTALAMOUNT,
        B.BOOKEDBY, U.FULLNAME AS BOOKEDBYNAME, B.BOOKEDON,
        B.CANCELLEDBY, B.CANCELLEDON, B.SERVEDBY, B.SERVEDON, B.NOSHOWON, B.REMARKS
    FROM CMS_BOOKING B
    INNER JOIN CMS_BOOKTYPE BT ON BT.BOOKTYPEID = B.BOOKTYPEID
    INNER JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
    INNER JOIN CMS_CUSTOMER C ON C.CUSTOMERID = B.CUSTOMERID
    INNER JOIN CMS_SERVICE S ON S.SERVICEID = B.SERVICEID
    LEFT JOIN CMS_USER U ON U.USERID = B.BOOKEDBY
    LEFT JOIN (
        SELECT BI.BOOKID, DS.CANTEENID, C.CANTEENNAME
        FROM CMS_BOOKITEM BI
        JOIN CMS_DAYMENU DM ON DM.DAYMENUID = BI.DAYMENUID
        JOIN CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
        JOIN CMS_CANTEEN C  ON C.CANTEENID  = DS.CANTEENID
        GROUP BY BI.BOOKID, DS.CANTEENID, C.CANTEENNAME
    ) BK_CAN ON BK_CAN.BOOKID = B.BOOKID
    WHERE B.BOOKID = PBOOKID;

    SELECT 
        BI.BOOKITEMID, BI.DAYMENUID, BI.MENUITEMID, MI.MENUCODE, MI.ITEMNAME,
        BI.QTY, BI.RATE, BI.AMOUNT, BI.REMARKS, BI.STATUSID, BIST.STATUSCODE AS STATUSCODE
    FROM CMS_BOOKITEM BI
    INNER JOIN CMS_MENUITEM MI ON MI.MENUITEMID = BI.MENUITEMID
    INNER JOIN CMS_STATUS BIST ON BIST.STATUSID = BI.STATUSID
    WHERE BI.BOOKID = PBOOKID;
END$$

-- 2. CMSLISTBOOK
DROP PROCEDURE IF EXISTS CMSLISTBOOK$$
CREATE PROCEDURE CMSLISTBOOK(
    IN PCUSTOMERID INT,
    IN PSERVICEID INT,
    IN PSTARTDATE DATE,
    IN PENDDATE DATE,
    IN PSTATUSCODE VARCHAR(10)
)
BEGIN
    SELECT 
        B.BOOKID, B.BOOKNO, BT.BOOKTYPECODE, 
        B.CUSTOMERID, C.DISPNAME AS CUSTOMERNAME,
        BK_CAN.CANTEENID, BK_CAN.CANTEENNAME,
        B.SERVICEID, S.SERVNAME, B.SERVICEDATE,
        B.STATUSID, ST.STATUSCODE AS STATUSCODE, B.TOTALITEMS, B.TOTALQTY, B.TOTALAMOUNT
    FROM CMS_BOOKING B
    INNER JOIN CMS_BOOKTYPE BT ON BT.BOOKTYPEID = B.BOOKTYPEID
    INNER JOIN CMS_STATUS ST ON ST.STATUSID = B.STATUSID
    INNER JOIN CMS_CUSTOMER C ON C.CUSTOMERID = B.CUSTOMERID
    INNER JOIN CMS_SERVICE S ON S.SERVICEID = B.SERVICEID
    LEFT JOIN (
        SELECT BI.BOOKID, DS.CANTEENID, C.CANTEENNAME
        FROM CMS_BOOKITEM BI
        JOIN CMS_DAYMENU DM ON DM.DAYMENUID = BI.DAYMENUID
        JOIN CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
        JOIN CMS_CANTEEN C  ON C.CANTEENID  = DS.CANTEENID
        GROUP BY BI.BOOKID, DS.CANTEENID, C.CANTEENNAME
    ) BK_CAN ON BK_CAN.BOOKID = B.BOOKID
    WHERE (PCUSTOMERID IS NULL OR B.CUSTOMERID = PCUSTOMERID)
      AND (PSERVICEID IS NULL OR B.SERVICEID = PSERVICEID)
      AND (PSTARTDATE IS NULL OR B.SERVICEDATE >= PSTARTDATE)
      AND (PENDDATE IS NULL OR B.SERVICEDATE <= PENDDATE)
      AND (PSTATUSCODE IS NULL OR ST.STATUSCODE = PSTATUSCODE)
    ORDER BY B.SERVICEDATE DESC, B.BOOKNO DESC;
END$$

-- 3. CMSLISTBOOKHISTORY
DROP PROCEDURE IF EXISTS CMSLISTBOOKHISTORY$$
CREATE PROCEDURE CMSLISTBOOKHISTORY (
    IN PCUSTOMERID INT,
    IN PSTARTDATE  DATE,
    IN PENDDATE    DATE,
    IN PSTATUSCODE VARCHAR(10),
    IN PPAGE       INT,
    IN PPAGESIZE   INT
)
BEGIN
    DECLARE VOFFSET    INT DEFAULT 0;
    DECLARE VTOTAL     INT DEFAULT 0;
    DECLARE VSTATUSID  INT DEFAULT NULL;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;

    IF PSTATUSCODE IS NOT NULL THEN
        SELECT STATUSID INTO VSTATUSID FROM CMS_STATUS WHERE STATUSCODE = PSTATUSCODE AND STATUSGRP = 'BOOKING';
        IF VSTATUSID IS NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid status code';
        END IF;
    END IF;

    -- Sanitise pagination inputs
    SET PPAGE     = COALESCE(PPAGE, 1);
    SET PPAGESIZE = COALESCE(PPAGESIZE, 20);
    IF PPAGE < 1       THEN SET PPAGE     = 1;  END IF;
    IF PPAGESIZE < 1   THEN SET PPAGESIZE = 20; END IF;
    IF PPAGESIZE > 100 THEN SET PPAGESIZE = 100; END IF;

    SET VOFFSET = (PPAGE - 1) * PPAGESIZE;

    -- Count matching rows first
    SELECT COUNT(*) INTO VTOTAL
    FROM CMS_BOOKING B
    WHERE B.CUSTOMERID = PCUSTOMERID
      AND (PSTARTDATE IS NULL OR B.SERVICEDATE >= PSTARTDATE)
      AND (PENDDATE   IS NULL OR B.SERVICEDATE <= PENDDATE)
      AND (VSTATUSID  IS NULL OR B.STATUSID     = VSTATUSID);

    -- Return the requested page with pagination metadata and Canteen
    SELECT
        B.BOOKID,
        B.BOOKNO,
        BT.BOOKTYPECODE,
        BK_CAN.CANTEENID,
        BK_CAN.CANTEENNAME,
        B.SERVICEID,
        S.SERVNAME,
        B.SERVICEDATE,
        B.STATUSID,
        ST.STATUSCODE AS STATUSCODE,
        B.TOTALITEMS,
        B.TOTALQTY,
        B.TOTALAMOUNT,
        B.BOOKEDON,
        B.CANCELLEDON,
        B.SERVEDON,
        B.NOSHOWON,
        VTOTAL                        AS TOTALROWS,
        PPAGE                         AS CURRENTPAGE,
        PPAGESIZE                     AS PAGESIZE,
        CEIL(VTOTAL / PPAGESIZE)      AS TOTALPAGES
    FROM CMS_BOOKING  B
    JOIN CMS_BOOKTYPE BT ON BT.BOOKTYPEID = B.BOOKTYPEID
    JOIN CMS_SERVICE  S  ON S.SERVICEID   = B.SERVICEID
    JOIN CMS_STATUS   ST ON ST.STATUSID   = B.STATUSID
    LEFT JOIN (
        SELECT BI.BOOKID, DS.CANTEENID, C.CANTEENNAME
        FROM CMS_BOOKITEM BI
        JOIN CMS_DAYMENU DM ON DM.DAYMENUID = BI.DAYMENUID
        JOIN CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
        JOIN CMS_CANTEEN C  ON C.CANTEENID  = DS.CANTEENID
        GROUP BY BI.BOOKID, DS.CANTEENID, C.CANTEENNAME
    ) BK_CAN ON BK_CAN.BOOKID = B.BOOKID
    WHERE B.CUSTOMERID = PCUSTOMERID
      AND (PSTARTDATE IS NULL OR B.SERVICEDATE >= PSTARTDATE)
      AND (PENDDATE   IS NULL OR B.SERVICEDATE <= PENDDATE)
      AND (VSTATUSID  IS NULL OR B.STATUSID     = VSTATUSID)
    ORDER BY B.SERVICEDATE DESC, B.BOOKID DESC
    LIMIT PPAGESIZE OFFSET VOFFSET;
END$$

DELIMITER ;
