-- 03_SEED_BOOKINGS.sql
-- Seed data for Bookings and Booking Items

USE cms_db;

/* ---- CMS_BOOKTYPE ---- */
INSERT IGNORE INTO CMS_BOOKTYPE (BOOKTYPEID, BOOKTYPECODE, BOOKTYPENAME, STATUS, CREATEDBY) VALUES
(1, 'PB', 'Pre-Booking', 'A', 1),
(2, 'KS', 'Kiosk Booking', 'A', 1);

/* ---- CMS_BOOKING ---- */
-- Customers:
-- 1 - Ravi
-- 2 - Suresh
-- 3 - Anil
-- 4 - Mahesh

INSERT IGNORE INTO CMS_BOOKING (BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE, STATUS, BOOKSEQNO, BOOKEDBY, CREATEDBY) VALUES
(1, 'PB-2026-0001', 1, 2, 2, CURRENT_DATE, 'CR', 1, 5, 1), -- Suresh booked Breakfast for today
(2, 'PB-2026-0002', 1, 2, 4, CURRENT_DATE, 'CR', 2, 5, 1), -- Suresh booked Lunch for today
(3, 'KS-2026-0003', 2, 4, 2, CURRENT_DATE, 'CR', 3, 4, 1), -- Mahesh kiosk booking Breakfast
(4, 'PB-2026-0004', 1, 3, 4, DATE_ADD(CURRENT_DATE, INTERVAL 1 DAY), 'CR', 4, 7, 1); -- Anil booked Lunch for tomorrow

/* ---- CMS_BOOKITEM ---- */
-- BOOKID 1: Breakfast (DAYMENUID 1, MENUITEMID 3)
INSERT IGNORE INTO CMS_BOOKITEM (BOOKID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, STATUS) VALUES
(1, 1, 3, 1, 15.00, 15.00, 'SRV'); -- Already served (simulating past time)

-- BOOKID 2: Lunch (DAYMENUID 2, MENUITEMID 4 and DAYMENUID 3, MENUITEMID 7)
INSERT IGNORE INTO CMS_BOOKITEM (BOOKID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, STATUS) VALUES
(2, 2, 4, 1, 40.00, 40.00, 'CR'),
(2, 3, 7, 2, 35.00, 70.00, 'CR');

-- BOOKID 3: Breakfast Kiosk (DAYMENUID 1, MENUITEMID 3)
INSERT IGNORE INTO CMS_BOOKITEM (BOOKID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, STATUS) VALUES
(3, 1, 3, 1, 25.00, 25.00, 'CAN'); -- Cancelled Kiosk booking

-- BOOKID 4: Tomorrow Lunch (DAYMENUID 6, MENUITEMID 4)
INSERT IGNORE INTO CMS_BOOKITEM (BOOKID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, STATUS) VALUES
(4, 6, 4, 1, 40.00, 40.00, 'CR');

/* ---- Update booking totals based on items ---- */
UPDATE CMS_BOOKING
SET TOTALAMOUNT = 15.00, TOTALITEMS = 1, TOTALQTY = 1, STATUS = 'SRV'
WHERE BOOKID = 1;

UPDATE CMS_BOOKING
SET TOTALAMOUNT = 110.00, TOTALITEMS = 2, TOTALQTY = 3
WHERE BOOKID = 2;

UPDATE CMS_BOOKING
SET TOTALAMOUNT = 25.00, TOTALITEMS = 1, TOTALQTY = 1, STATUS = 'CAN'
WHERE BOOKID = 3;

UPDATE CMS_BOOKING
SET TOTALAMOUNT = 40.00, TOTALITEMS = 1, TOTALQTY = 1
WHERE BOOKID = 4;

/* ---- CMS_BOOKCTR ---- */
INSERT IGNORE INTO CMS_BOOKCTR (BOOKTYPEID, SERVICEID, LASTNO) VALUES
(1, 2, 1),
(1, 4, 2),
(2, 2, 1);
