/* ============================================================
   MODULE 1: IDENTITY & ACCESS MANAGEMENT STORED PROCEDURES
   ============================================================ */

USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDUSER;
DROP PROCEDURE IF EXISTS CMSADDROLE;
DROP PROCEDURE IF EXISTS CMSASSIGNROL;
DROP PROCEDURE IF EXISTS CMSADDCUST;
DROP PROCEDURE IF EXISTS CMSADDPERM;
DROP PROCEDURE IF EXISTS CMSADDCONT;
DROP PROCEDURE IF EXISTS CMSADDOCE;
DROP PROCEDURE IF EXISTS CMSADDVIS;
DROP PROCEDURE IF EXISTS CMSADDACCKEY;
DROP PROCEDURE IF EXISTS CMSADDAPPLVL;
DROP PROCEDURE IF EXISTS CMSLOGININFO;

DELIMITER $$

-- v2_module1
-- Modified to add mandatory input validation and transaction exception handling.
CREATE PROCEDURE CMSADDUSER (
    IN PLOGINID VARCHAR(50),
    IN PFULLNAME VARCHAR(120),
    IN PEMAIL VARCHAR(120),
    IN PMOBILENO VARCHAR(20),
    IN PPWDHASH VARCHAR(255),
    IN PAUTHPROV VARCHAR(20),
    IN PAUTHID VARCHAR(120)
)
BEGIN
    DECLARE VUSERID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PLOGINID IS NULL OR TRIM(PLOGINID) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Login ID is required';
    END IF;

    IF PFULLNAME IS NULL OR TRIM(PFULLNAME) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Full Name is required';
    END IF;

    IF PPWDHASH IS NULL OR TRIM(PPWDHASH) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Password hash is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_USER (LOGINID, FULLNAME, EMAIL, MOBILENO, PWDHASH, AUTHPROV, AUTHID)
    VALUES (TRIM(PLOGINID), TRIM(PFULLNAME), PEMAIL, PMOBILENO, PPWDHASH, COALESCE(PAUTHPROV, 'LOCAL'), PAUTHID);

    SET VUSERID = LAST_INSERT_ID();

    COMMIT;

    SELECT VUSERID AS USERID;
END$$

-- v2_module1
-- Modified to add mandatory input validation and transaction exception handling.
CREATE PROCEDURE CMSADDROLE (
    IN PROLECODE VARCHAR(50),
    IN PROLENAME VARCHAR(100),
    IN PDESCR VARCHAR(255)
)
BEGIN
    DECLARE VROLEID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PROLECODE IS NULL OR TRIM(PROLECODE) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Role Code is required';
    END IF;

    IF PROLENAME IS NULL OR TRIM(PROLENAME) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Role Name is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_ROLE (ROLECODE, ROLENAME, DESCR)
    VALUES (TRIM(PROLECODE), TRIM(PROLENAME), PDESCR);

    SET VROLEID = LAST_INSERT_ID();

    COMMIT;

    SELECT VROLEID AS ROLEID;
END$$

-- v2_module1
-- Modified to validate role assignment date range and add transaction exception handling.
CREATE PROCEDURE CMSASSIGNROL (
    IN PUSERID INT,
    IN PROLEID INT,
    IN PASSIGNEDBY INT,
    IN PVALIDFROM DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    DECLARE VVALIDFROM DATETIME;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    SET VVALIDFROM = COALESCE(PVALIDFROM, CURRENT_TIMESTAMP);

    IF PVALIDUNTIL IS NOT NULL AND PVALIDUNTIL < VVALIDFROM THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Role valid until date must be greater than or equal to valid from date';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_USRROLE (USERID, ROLEID, ASSIGNEDBY, VALIDFROM, VALIDUNTIL, ISACTIVE)
    VALUES (PUSERID, PROLEID, PASSIGNEDBY, VVALIDFROM, PVALIDUNTIL, 1)
    ON DUPLICATE KEY UPDATE
        ASSIGNEDBY = PASSIGNEDBY,
        VALIDFROM = VVALIDFROM,
        VALIDUNTIL = PVALIDUNTIL,
        ISACTIVE = 1,
        ASSIGNEDAT = CURRENT_TIMESTAMP;

    COMMIT;
END$$

-- v2_module1
-- Modified to add mandatory input validation and transaction exception handling.
CREATE PROCEDURE CMSADDCUST (
    IN PUSERID INT,
    IN PCTYPECODE VARCHAR(20),
    IN PDISPNAME VARCHAR(120),
    IN PSTATUS VARCHAR(20),
    IN PVALIDFROM DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    DECLARE VCUSTOMERID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PCTYPECODE IS NULL OR TRIM(PCTYPECODE) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer Type is required';
    END IF;

    IF PDISPNAME IS NULL OR TRIM(PDISPNAME) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Display Name is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_CUSTOMER (USERID, CTYPECODE, DISPNAME, STATUS, VALIDFROM, VALIDUNTIL)
    VALUES (PUSERID, TRIM(PCTYPECODE), TRIM(PDISPNAME), COALESCE(PSTATUS, 'A'), PVALIDFROM, PVALIDUNTIL);

    SET VCUSTOMERID = LAST_INSERT_ID();

    COMMIT;

    SELECT VCUSTOMERID AS CUSTOMERID;
END$$

-- v2_module1
-- Modified to enforce PERMANENT customer type and add transaction exception handling.
CREATE PROCEDURE CMSADDPERM (
    IN PCUSTOMERID INT,
    IN PEMPCODE VARCHAR(50),
    IN PDEPT VARCHAR(100),
    IN PDESIG VARCHAR(100)
)
BEGIN
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VPERMEMPID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    SELECT CTYPECODE
    INTO VCTYPECODE
    FROM CMS_CUSTOMER
    WHERE CUSTOMERID = PCUSTOMERID;

    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer not found';
    END IF;

    IF VCTYPECODE <> 'PERMANENT' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer type must be PERMANENT';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_PERMEMP (CUSTOMERID, EMPCODE, DEPT, DESIG)
    VALUES (PCUSTOMERID, PEMPCODE, PDEPT, PDESIG);

    SET VPERMEMPID = LAST_INSERT_ID();

    COMMIT;

    SELECT VPERMEMPID AS PERMEMPID;
END$$

-- v2_module1
-- Modified to enforce CONTRACT customer type, validate contract dates, and add transaction exception handling.
CREATE PROCEDURE CMSADDCONT (
    IN PCUSTOMERID INT,
    IN PCONTCODE VARCHAR(50),
    IN PVENDORNAME VARCHAR(150),
    IN PCONTSTART DATE,
    IN PCONTEND DATE
)
BEGIN
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VCONTEMPID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    SELECT CTYPECODE
    INTO VCTYPECODE
    FROM CMS_CUSTOMER
    WHERE CUSTOMERID = PCUSTOMERID;

    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer not found';
    END IF;

    IF VCTYPECODE <> 'CONTRACT' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer type must be CONTRACT';
    END IF;

    IF PCONTEND < PCONTSTART THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Contract end date must be greater than or equal to contract start date';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_CONTEMP (CUSTOMERID, CONTCODE, VENDORNAME, CONTSTART, CONTEND)
    VALUES (PCUSTOMERID, PCONTCODE, PVENDORNAME, PCONTSTART, PCONTEND);

    SET VCONTEMPID = LAST_INSERT_ID();

    COMMIT;

    SELECT VCONTEMPID AS CONTEMPID;
END$$

-- v2_module1
-- Modified to enforce OTHERCENTRE customer type and add transaction exception handling.
CREATE PROCEDURE CMSADDOCE (
    IN PCUSTOMERID INT,
    IN PEMPCODE VARCHAR(50),
    IN PCENTRENAME VARCHAR(120),
    IN PDEPT VARCHAR(100),
    IN PDESIG VARCHAR(100),
    IN PVALIDFROM DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VOCEEMPID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    SELECT CTYPECODE
    INTO VCTYPECODE
    FROM CMS_CUSTOMER
    WHERE CUSTOMERID = PCUSTOMERID;

    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer not found';
    END IF;

    IF VCTYPECODE <> 'OTHERCENTRE' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer type must be OTHERCENTRE';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_OCEEMP (CUSTOMERID, EMPCODE, CENTRENAME, DEPT, DESIG, VALIDFROM, VALIDUNTIL)
    VALUES (PCUSTOMERID, PEMPCODE, PCENTRENAME, PDEPT, PDESIG, PVALIDFROM, PVALIDUNTIL);

    SET VOCEEMPID = LAST_INSERT_ID();

    COMMIT;

    SELECT VOCEEMPID AS OCEEMPID;
END$$

-- v2_module1
-- Modified to enforce VISITOR customer type, validate visitor validity date, and add transaction exception handling.
CREATE PROCEDURE CMSADDVIS (
    IN PCUSTOMERID INT,
    IN PVISNAME VARCHAR(120),
    IN PVISMOBILE VARCHAR(20),
    IN PVISORG VARCHAR(150),
    IN PVISPURPOSE VARCHAR(255),
    IN PVISDATE DATE,
    IN PVALIDUNTIL DATETIME,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VVISITORID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    SELECT CTYPECODE
    INTO VCTYPECODE
    FROM CMS_CUSTOMER
    WHERE CUSTOMERID = PCUSTOMERID;

    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer not found';
    END IF;

    IF VCTYPECODE <> 'VISITOR' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Customer type must be VISITOR';
    END IF;

    IF PVALIDUNTIL < TIMESTAMP(PVISDATE, '00:00:00') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Visitor valid until date must be greater than or equal to visit date';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_VISITOR (CUSTOMERID, VISNAME, VISMOBILE, VISORG, VISPURPOSE, VISDATE, VALIDUNTIL, CREATEDBY, STATUS)
    VALUES (PCUSTOMERID, PVISNAME, PVISMOBILE, PVISORG, PVISPURPOSE, PVISDATE, PVALIDUNTIL, PCREATEDBY, 'A');

    SET VVISITORID = LAST_INSERT_ID();

    COMMIT;

    SELECT VVISITORID AS VISITORID;
END$$

-- v2_module1
-- Modified to validate key value, key type, and add transaction exception handling.
CREATE PROCEDURE CMSADDACCKEY (
    IN PCUSTOMERID INT,
    IN PKEYTYPE VARCHAR(30),
    IN PKEYVALUE VARCHAR(255),
    IN PEXPIRESAT DATETIME,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VACCKEYID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PKEYVALUE IS NULL OR TRIM(PKEYVALUE) = '' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Access key value is required';
    END IF;

    IF PKEYTYPE IS NULL OR PKEYTYPE NOT IN ('QR', 'RFID', 'EMPCARD', 'VISPASS', 'TEMPTOKEN') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Invalid access key type';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_ACCKEY (CUSTOMERID, KEYTYPE, KEYVALUE, EXPIRESAT, STATUS, CREATEDBY)
    VALUES (PCUSTOMERID, PKEYTYPE, TRIM(PKEYVALUE), PEXPIRESAT, 'A', PCREATEDBY);

    SET VACCKEYID = LAST_INSERT_ID();

    COMMIT;

    SELECT VACCKEYID AS ACCKEYID;
END$$

-- v2_module1
-- Modified to add transaction exception handling.
CREATE PROCEDURE CMSADDAPPLVL (
    IN PLEVELNO INT,
    IN PLEVELNAME VARCHAR(100),
    IN PROLEID INT,
    IN PDESCR VARCHAR(255)
)
BEGIN
    DECLARE VAPPLVLID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    START TRANSACTION;

    INSERT INTO CMS_APPLVL (LEVELNO, LEVELNAME, ROLEID, DESCR)
    VALUES (PLEVELNO, PLEVELNAME, PROLEID, PDESCR);

    SET VAPPLVLID = LAST_INSERT_ID();

    COMMIT;

    SELECT VAPPLVLID AS APPLVLID;
END$$

-- v2_module1
-- Modified to return only active users with active, currently valid role assignments.
CREATE PROCEDURE CMSLOGININFO (
    IN PLOGINID VARCHAR(50)
)
BEGIN
    SELECT
        U.USERID,
        U.LOGINID,
        U.FULLNAME,
        U.EMAIL,
        U.MOBILENO,
        U.PWDHASH,
        U.AUTHPROV,
        U.ISACTIVE,
        C.CUSTOMERID,
        C.CTYPECODE,
        C.DISPNAME,
        GROUP_CONCAT(R.ROLECODE ORDER BY R.ROLECODE) AS ROLECODES
    FROM CMS_USER U
    LEFT JOIN CMS_CUSTOMER C
        ON C.USERID = U.USERID
    LEFT JOIN CMS_USRROLE UR
        ON UR.USERID = U.USERID
       AND UR.ISACTIVE = 1
       AND (UR.VALIDFROM IS NULL OR CURRENT_TIMESTAMP >= UR.VALIDFROM)
       AND (UR.VALIDUNTIL IS NULL OR CURRENT_TIMESTAMP <= UR.VALIDUNTIL)
    LEFT JOIN CMS_ROLE R
        ON R.ROLEID = UR.ROLEID
       AND R.ISACTIVE = 1
    WHERE U.LOGINID = PLOGINID
      AND U.ISACTIVE = 1
    GROUP BY U.USERID, U.LOGINID, U.FULLNAME, U.EMAIL, U.MOBILENO, U.PWDHASH, U.AUTHPROV, U.ISACTIVE, C.CUSTOMERID, C.CTYPECODE, C.DISPNAME;
END$$

DELIMITER ;
