/* ============================================================
   MODULE 1: IDENTITY & ACCESS MANAGEMENT

   STORED PROCE — ENTERPRISE REDESIGN v2

   Aligned with: 01_IDENTITY_ACCESS_SCHEMA.sql (Revised)

   KEY CHANGES FROM v1:

   1. All CMS_USRROLE references → CMS_CONSUMERROLE

   2. New CMS_CENTER and CMS_CANTEEN proce

   3. New CMS_CANTEENROLE proce

   4. CMSLOGININFO rewritten for CMS_CONSUMERROLE +  CMS_CANTEENROLE

   5. Full CRUD + Activate/Deactivate for every table
   
   6. Composite registration proc (CMSREGPERM, etc.)
   
   7. CMSVALIDATEACCKEY for kiosk/serving identity
   ============================================================ */

USE cms_db;

/* --- Drop existing procedures --- */
DROP PROCEDURE IF EXISTS CMSLISTCENTER;
DROP PROCEDURE IF EXISTS CMSGETCENTER;

/* ---These will be added/updated manually to database using INSERT statement--- */
DROP PROCEDURE IF EXISTS CMSADDCENTER;
DROP PROCEDURE IF EXISTS CMSUPDCENTER;
DROP PROCEDURE IF EXISTS CMSSEARCHCENTER;
DROP PROCEDURE IF EXISTS CMSACTCENTER;
DROP PROCEDURE IF EXISTS CMSDEACTCENTER;

DROP PROCEDURE IF EXISTS CMSGETCANTEEN;
DROP PROCEDURE IF EXISTS CMSLISTCANTEEN;
DROP PROCEDURE IF EXISTS CMSSEARCHCANTEEN;

/* ---These will be added manually to database using INS statement--- */
DROP PROCEDURE IF EXISTS CMSADDCANTEEN;
DROP PROCEDURE IF EXISTS CMSUPDCANTEEN;
DROP PROCEDURE IF EXISTS CMSACTCANTEEN;
DROP PROCEDURE IF EXISTS CMSDEACTCANTEEN;

DROP PROCEDURE IF EXISTS CMSADDUSER;
DROP PROCEDURE IF EXISTS CMSUPDUSER;
DROP PROCEDURE IF EXISTS CMSCHANGEPWD;
DROP PROCEDURE IF EXISTS CMSGETUSER;
DROP PROCEDURE IF EXISTS CMSLISTUSER;
DROP PROCEDURE IF EXISTS CMSSEARCHUSER;

DROP PROCEDURE IF EXISTS CMSACTUSER;
DROP PROCEDURE IF EXISTS CMSDEACTUSER;

DROP PROCEDURE IF EXISTS CMSLISTROL;

/* ---These will be added/updated manually to database using INS statement--- */
DROP PROCEDURE IF EXISTS CMSADDROLE;
DROP PROCEDURE IF EXISTS CMSUPDROL;
DROP PROCEDURE IF EXISTS CMSGETROL;
DROP PROCEDURE IF EXISTS CMSACTROL;
DROP PROCEDURE IF EXISTS CMSDEACTROL;

DROP PROCEDURE IF EXISTS CMSASSIGNROL;
DROP PROCEDURE IF EXISTS CMSASSIGNCONSROL;
DROP PROCEDURE IF EXISTS CMSREMOVECONSROL;
DROP PROCEDURE IF EXISTS CMSLISTCONSROL;

DROP PROCEDURE IF EXISTS CMSASSIGNCANROL;
DROP PROCEDURE IF EXISTS CMSREMOVECANROL;
DROP PROCEDURE IF EXISTS CMSLISTCANROL;
DROP PROCEDURE IF EXISTS CMSLISTCANROLSTAFF;

DROP PROCEDURE IF EXISTS CMSADDCUST;
DROP PROCEDURE IF EXISTS CMSUPDCUST;
DROP PROCEDURE IF EXISTS CMSGETCUST;
DROP PROCEDURE IF EXISTS CMSLISTCUST;
DROP PROCEDURE IF EXISTS CMSSEARCHCUST;

DROP PROCEDURE IF EXISTS CMSACTCUST;
DROP PROCEDURE IF EXISTS CMSDEACTCUST;
DROP PROCEDURE IF EXISTS CMSGETCUSTBYUSER;

DROP PROCEDURE IF EXISTS CMSADDPERM;
DROP PROCEDURE IF EXISTS CMSUPDPERM;
DROP PROCEDURE IF EXISTS CMSGETPERM;

DROP PROCEDURE IF EXISTS CMSADDCONT;
DROP PROCEDURE IF EXISTS CMSUPDCONT;
DROP PROCEDURE IF EXISTS CMSGETCONT;

DROP PROCEDURE IF EXISTS CMSADDOCE;
DROP PROCEDURE IF EXISTS CMSUPDOCE;
DROP PROCEDURE IF EXISTS CMSGETOCE;



DROP PROCEDURE IF EXISTS CMSADDVIS;
DROP PROCEDURE IF EXISTS CMSUPDVIS;
DROP PROCEDURE IF EXISTS CMSGETVIS;

DROP PROCEDURE IF EXISTS CMSADDACCKEY;
DROP PROCEDURE IF EXISTS CMSUPDACCKEY;
DROP PROCEDURE IF EXISTS CMSGETACCKEY;
DROP PROCEDURE IF EXISTS CMSLISTACCKEY;
DROP PROCEDURE IF EXISTS CMSACTACCKEY;
DROP PROCEDURE IF EXISTS CMSDEACTACCKEY;
DROP PROCEDURE IF EXISTS CMSVALIDATEACCKEY;



DROP PROCEDURE IF EXISTS CMSLOGININFO;

/* ---These will be added/updated manually to database using INS statement--- */
DROP PROCEDURE IF EXISTS CMSREGPERM;
DROP PROCEDURE IF EXISTS CMSREGCONT;
DROP PROCEDURE IF EXISTS CMSREGOCE;
DROP PROCEDURE IF EXISTS CMSREGVIS;


DELIMITER $$


/* ============================================================
   CMS_CENTER — ISRO Centre Master
   ============================================================ */

CREATE PROCEDURE CMSADDCENTER (
    IN PCENTERCODE VARCHAR(20),
    IN PCENTERNAME VARCHAR(120),
    IN PLOCATION   VARCHAR(150)
)
BEGIN
    DECLARE VCENTERID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERCODE IS NULL OR TRIM(PCENTERCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre Code is required';
    END IF;

    IF PCENTERNAME IS NULL OR TRIM(PCENTERNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre Name is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_CENTER (CENTERCODE, CENTERNAME, LOCATION)
    VALUES (TRIM(PCENTERCODE), TRIM(PCENTERNAME), PLOCATION);

    SET VCENTERID = LAST_INSERT_ID();
    COMMIT;

    SELECT VCENTERID AS CENTERID;
END$$


CREATE PROCEDURE CMSUPDCENTER (
    IN PCENTERID   INT,
    IN PCENTERNAME  VARCHAR(120),
    IN PLOCATION    VARCHAR(150),
    IN PSTATUS      VARCHAR(20)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT FROM CMS_CENTER WHERE CENTERID = PCENTERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre not found';
    END IF;

    IF PCENTERNAME IS NULL OR TRIM(PCENTERNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre Name is required';
    END IF;

    START TRANSACTION;

    UPDATE CMS_CENTER
    SET    CENTERNAME = TRIM(PCENTERNAME),
           LOCATION  = PLOCATION,
           STATUS    = COALESCE(PSTATUS, STATUS),
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  CENTERID  = PCENTERID;

    COMMIT;
    SELECT PCENTERID AS CENTERID;
END$$

CREATE PROCEDURE CMSACTCENTER (IN PCENTERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CENTER WHERE CENTERID = PCENTERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CENTER SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE CENTERID = PCENTERID;
    COMMIT;
    SELECT PCENTERID AS CENTERID;
END$$


CREATE PROCEDURE CMSDEACTCENTER (IN PCENTERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CENTER WHERE CENTERID = PCENTERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CENTER SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE CENTERID = PCENTERID;
    COMMIT;
    SELECT PCENTERID AS CENTERID;
END$$


CREATE PROCEDURE CMSGETCENTER (IN PCENTERID INT)
BEGIN
    SELECT CENTERID, CENTERCODE, CENTERNAME, LOCATION,
           STATUS, CREATEDAT, UPDATEDAT
    FROM   CMS_CENTER
    WHERE  CENTERID = PCENTERID;
END$$


CREATE PROCEDURE CMSLISTCENTER ()
BEGIN
    SELECT CENTERID, CENTERCODE, CENTERNAME, LOCATION,
           STATUS, CREATEDAT, UPDATEDAT
    FROM   CMS_CENTER
    ORDER BY CENTERNAME;
END$$


CREATE PROCEDURE CMSSEARCHCENTER (IN PKEYWORD VARCHAR(120))
BEGIN
    SELECT CENTERID, CENTERCODE, CENTERNAME, LOCATION,
           STATUS, CREATEDAT, UPDATEDAT
    FROM   CMS_CENTER
    WHERE  (CENTERCODE LIKE CONCAT('%', PKEYWORD, '%')
       OR   CENTERNAME LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY CENTERNAME;
END$$




/* ============================================================
   CMS_CANTEEN — Canteen Master
   ============================================================ */

CREATE PROCEDURE CMSADDCANTEEN (
    IN PCENTERID    INT,
    IN PCANTEENCODE VARCHAR(20),
    IN PCANTEENNAME VARCHAR(120),
    IN PLOCATION    VARCHAR(150)
)
BEGIN
    DECLARE VCANTEENID INT;
    DECLARE VCENSTATUS VARCHAR(20);

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCENTERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre ID is required';
    END IF;

    SELECT STATUS INTO VCENSTATUS FROM CMS_CENTER WHERE CENTERID = PCENTERID;
    IF VCENSTATUS IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre not found';
    END IF;
    IF VCENSTATUS <> 'A' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre must be active';
    END IF;

    IF PCANTEENCODE IS NULL OR TRIM(PCANTEENCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen Code is required';
    END IF;

    IF PCANTEENNAME IS NULL OR TRIM(PCANTEENNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen Name is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_CANTEEN (CENTERID, CANTEENCODE, CANTEENNAME, LOCATION)
    VALUES (PCENTERID, TRIM(PCANTEENCODE), TRIM(PCANTEENNAME), PLOCATION);

    SET VCANTEENID = LAST_INSERT_ID();
    COMMIT;

    SELECT VCANTEENID AS CANTEENID;
END$$


CREATE PROCEDURE CMSUPDCANTEEN (
    IN PCANTEENID   INT,
    IN PCANTEENNAME VARCHAR(120),
    IN PLOCATION    VARCHAR(150),
    IN PSTATUS      VARCHAR(20)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCANTEENID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CANTEEN WHERE CANTEENID = PCANTEENID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen not found';
    END IF;

    IF PCANTEENNAME IS NULL OR TRIM(PCANTEENNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen Name is required';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CANTEEN
    SET    CANTEENNAME = TRIM(PCANTEENNAME),
           LOCATION    = PLOCATION,
           STATUS      = COALESCE(PSTATUS, STATUS),
           UPDATEDAT   = CURRENT_TIMESTAMP
    WHERE  CANTEENID   = PCANTEENID;
    COMMIT;

    SELECT PCANTEENID AS CANTEENID;
END$$

CREATE PROCEDURE CMSACTCANTEEN (IN PCANTEENID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCANTEENID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CANTEEN WHERE CANTEENID = PCANTEENID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CANTEEN SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE CANTEENID = PCANTEENID;
    COMMIT;
    SELECT PCANTEENID AS CANTEENID;
END$$


CREATE PROCEDURE CMSDEACTCANTEEN (IN PCANTEENID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCANTEENID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CANTEEN WHERE CANTEENID = PCANTEENID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CANTEEN SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE CANTEENID = PCANTEENID;
    COMMIT;
    SELECT PCANTEENID AS CANTEENID;
END$$

CREATE PROCEDURE CMSGETCANTEEN (IN PCANTEENID INT)
BEGIN
    SELECT C.CANTEENID, C.CENTERID, CT.CENTERCODE, CT.CENTERNAME,
           C.CANTEENCODE, C.CANTEENNAME, C.LOCATION,
           C.STATUS, C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CANTEEN C
    JOIN   CMS_CENTER CT ON CT.CENTERID = C.CENTERID
    WHERE  C.CANTEENID = PCANTEENID;
END$$


CREATE PROCEDURE CMSLISTCANTEEN (IN PCENTERID INT)
BEGIN
    SELECT C.CANTEENID, C.CENTERID, CT.CENTERCODE, CT.CENTERNAME,
           C.CANTEENCODE, C.CANTEENNAME, C.LOCATION,
           C.STATUS, C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CANTEEN C
    JOIN   CMS_CENTER CT ON CT.CENTERID = C.CENTERID
    WHERE  (PCENTERID IS NULL OR C.CENTERID = PCENTERID)
    ORDER BY CT.CENTERNAME, C.CANTEENNAME;
END$$

/* ADDITIONAL */
CREATE PROCEDURE CMSSEARCHCANTEEN (IN PKEYWORD VARCHAR(120))
BEGIN
    SELECT C.CANTEENID, C.CENTERID, CT.CENTERCODE, CT.CENTERNAME,
           C.CANTEENCODE, C.CANTEENNAME, C.LOCATION,
           C.STATUS, C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CANTEEN C
    JOIN   CMS_CENTER CT ON CT.CENTERID = C.CENTERID
    WHERE  (C.CANTEENCODE LIKE CONCAT('%', PKEYWORD, '%')
       OR   C.CANTEENNAME LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY C.CANTEENNAME;
END$$




/* ============================================================
   CMS_USER — System User
   ============================================================ */



CREATE PROCEDURE CMSACTUSER (IN PUSERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_USER WHERE USERID = PUSERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_USER SET ISACTIVE = 1, UPDATEDAT = CURRENT_TIMESTAMP WHERE USERID = PUSERID;
    COMMIT;
    SELECT PUSERID AS USERID;
END$$


CREATE PROCEDURE CMSDEACTUSER (IN PUSERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_USER WHERE USERID = PUSERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_USER SET ISACTIVE = 0, UPDATEDAT = CURRENT_TIMESTAMP WHERE USERID = PUSERID;
    COMMIT;
    SELECT PUSERID AS USERID;
END$$

CREATE PROCEDURE CMSADDUSER (
    IN PLOGINID   VARCHAR(50),
    IN PFULLNAME  VARCHAR(120),
    IN PEMAIL     VARCHAR(120),
    IN PMOBILENO  VARCHAR(20),
    IN PPWDHASH   VARCHAR(255),
    IN PAUTHPROV  VARCHAR(20),
    IN PAUTHID    VARCHAR(120)
)
BEGIN
    DECLARE VUSERID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PLOGINID IS NULL OR TRIM(PLOGINID) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Login ID is required';
    END IF;
    IF PFULLNAME IS NULL OR TRIM(PFULLNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Full Name is required';
    END IF;
    IF PPWDHASH IS NULL OR TRIM(PPWDHASH) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Password hash is required';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_USER (LOGINID, FULLNAME, EMAIL, MOBILENO, PWDHASH, AUTHPROV, AUTHID)
    VALUES (TRIM(PLOGINID), TRIM(PFULLNAME), PEMAIL, PMOBILENO,
            PPWDHASH, COALESCE(PAUTHPROV, 'LOCAL'), PAUTHID);

    SET VUSERID = LAST_INSERT_ID();
    COMMIT;

    SELECT VUSERID AS USERID;
END$$


CREATE PROCEDURE CMSUPDUSER (
    IN PUSERID   INT,
    IN PFULLNAME VARCHAR(120),
    IN PEMAIL    VARCHAR(120),
    IN PMOBILENO VARCHAR(20),
    IN PAUTHPROV VARCHAR(20),
    IN PAUTHID   VARCHAR(120)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_USER WHERE USERID = PUSERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User not found';
    END IF;
    IF PFULLNAME IS NULL OR TRIM(PFULLNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Full Name is required';
    END IF;

    START TRANSACTION;
    UPDATE CMS_USER
    SET    FULLNAME  = TRIM(PFULLNAME),
           EMAIL     = PEMAIL,
           MOBILENO  = PMOBILENO,
           AUTHPROV  = COALESCE(PAUTHPROV, AUTHPROV),
           AUTHID    = PAUTHID,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  USERID    = PUSERID;
    COMMIT;

    SELECT PUSERID AS USERID;
END$$


CREATE PROCEDURE CMSGETUSER (IN PUSERID INT)
BEGIN
    SELECT U.USERID, U.LOGINID, U.FULLNAME, U.EMAIL, U.MOBILENO,
           U.AUTHPROV, U.ISACTIVE, U.CREATEDAT, U.UPDATEDAT
    FROM   CMS_USER U
    WHERE  U.USERID = PUSERID;
END$$


CREATE PROCEDURE CMSLISTUSER (
    IN PISACTIVE TINYINT
)
BEGIN
    SELECT U.USERID, U.LOGINID, U.FULLNAME, U.EMAIL, U.MOBILENO,
           U.AUTHPROV, U.ISACTIVE, U.CREATEDAT, U.UPDATEDAT
    FROM   CMS_USER U
    WHERE  (PISACTIVE IS NULL OR U.ISACTIVE = PISACTIVE)
    ORDER BY U.FULLNAME;
END$$


CREATE PROCEDURE CMSSEARCHUSER (IN PKEYWORD VARCHAR(120))
BEGIN
    SELECT U.USERID, U.LOGINID, U.FULLNAME, U.EMAIL, U.MOBILENO,
           U.AUTHPROV, U.ISACTIVE, U.CREATEDAT, U.UPDATEDAT
    FROM   CMS_USER U
    WHERE  (U.LOGINID  LIKE CONCAT('%', PKEYWORD, '%')
       OR   U.FULLNAME LIKE CONCAT('%', PKEYWORD, '%')
       OR   U.EMAIL    LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY U.FULLNAME;
END$$





CREATE PROCEDURE CMSCHANGEPWD (
    IN PUSERID     INT,
    IN PNEWPWDHASH VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID is required';
    END IF;
    IF PNEWPWDHASH IS NULL OR TRIM(PNEWPWDHASH) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'New password hash is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_USER WHERE USERID = PUSERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_USER SET PWDHASH = PNEWPWDHASH, UPDATEDAT = CURRENT_TIMESTAMP WHERE USERID = PUSERID;
    COMMIT;
    SELECT PUSERID AS USERID;
END$$


/* ============================================================
   CMS_ROLE — Role Master
   ============================================================ */

CREATE PROCEDURE CMSADDROLE (
    IN PROLECODE VARCHAR(50),
    IN PROLENAME VARCHAR(100),
    IN PDESCR    VARCHAR(255)
)
BEGIN
    DECLARE VROLEID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PROLECODE IS NULL OR TRIM(PROLECODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role Code is required';
    END IF;
    IF PROLENAME IS NULL OR TRIM(PROLENAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role Name is required';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_ROLE (ROLECODE, ROLENAME, DESCR)
    VALUES (TRIM(PROLECODE), TRIM(PROLENAME), PDESCR);
    SET VROLEID = LAST_INSERT_ID();
    COMMIT;

    SELECT VROLEID AS ROLEID;
END$$


CREATE PROCEDURE CMSUPDROL (
    IN PROLEID   INT,
    IN PROLENAME VARCHAR(100),
    IN PDESCR    VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PROLEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_ROLE WHERE ROLEID = PROLEID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role not found';
    END IF;
    IF PROLENAME IS NULL OR TRIM(PROLENAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role Name is required';
    END IF;

    START TRANSACTION;
    UPDATE CMS_ROLE
    SET    ROLENAME  = TRIM(PROLENAME),
           DESCR     = PDESCR,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  ROLEID    = PROLEID;
    COMMIT;

    SELECT PROLEID AS ROLEID;
END$$

CREATE PROCEDURE CMSACTROL (IN PROLEID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PROLEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_ROLE WHERE ROLEID = PROLEID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_ROLE SET ISACTIVE = 1, UPDATEDAT = CURRENT_TIMESTAMP WHERE ROLEID = PROLEID;
    COMMIT;
    SELECT PROLEID AS ROLEID;
END$$

CREATE PROCEDURE CMSDEACTROL (IN PROLEID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PROLEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_ROLE WHERE ROLEID = PROLEID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_ROLE SET ISACTIVE = 0, UPDATEDAT = CURRENT_TIMESTAMP WHERE ROLEID = PROLEID;
    COMMIT;
    SELECT PROLEID AS ROLEID;
END$$

CREATE PROCEDURE CMSGETROL (IN PROLEID INT)
BEGIN
    SELECT ROLEID, ROLECODE, ROLENAME, DESCR,
           ISACTIVE, CREATEDAT, UPDATEDAT
    FROM   CMS_ROLE
    WHERE  ROLEID = PROLEID;
END$$


CREATE PROCEDURE CMSLISTROL ()
BEGIN
    SELECT ROLEID, ROLECODE, ROLENAME, DESCR,
           ISACTIVE, CREATEDAT, UPDATEDAT
    FROM   CMS_ROLE
    ORDER BY ROLECODE;
END$$





/* ============================================================
   CMS_CONSUMERROLE — Consumer (System-wide) Role Assignment
   Replaces old CMS_USRROLE references.
   ============================================================ */

CREATE PROCEDURE CMSASSIGNCONSROL (
    IN PUSERID     INT,
    IN PROLEID     INT,
    IN PASSIGNEDBY INT,
    IN PVALIDFROM  DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    DECLARE VVALIDFROM DATETIME;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID is required';
    END IF;
    IF PROLEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role ID is required';
    END IF;

    SET VVALIDFROM = COALESCE(PVALIDFROM, CURRENT_TIMESTAMP);

    IF PVALIDUNTIL IS NOT NULL AND PVALIDUNTIL < VVALIDFROM THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Valid until date must be >= valid from date';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_CONSUMERROLE (USERID, ROLEID, ASSIGNEDBY, VALIDFROM, VALIDUNTIL, ISACTIVE)
    VALUES (PUSERID, PROLEID, PASSIGNEDBY, VVALIDFROM, PVALIDUNTIL, 1)
    ON DUPLICATE KEY UPDATE
        ASSIGNEDBY = PASSIGNEDBY,
        VALIDFROM  = VVALIDFROM,
        VALIDUNTIL = PVALIDUNTIL,
        ISACTIVE   = 1,
        ASSIGNEDAT = CURRENT_TIMESTAMP;

    COMMIT;
    SELECT PUSERID AS USERID, PROLEID AS ROLEID;
END$$


CREATE PROCEDURE CMSREMOVECONSROL (
    IN PUSERID INT,
    IN PROLEID INT
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL OR PROLEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID and Role ID are required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CONSUMERROLE WHERE USERID = PUSERID AND ROLEID = PROLEID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Consumer role assignment not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CONSUMERROLE
    SET    ISACTIVE = 0
    WHERE  USERID = PUSERID AND ROLEID = PROLEID;
    COMMIT;

    SELECT PUSERID AS USERID, PROLEID AS ROLEID;
END$$


CREATE PROCEDURE CMSLISTCONSROL (IN PUSERID INT)
BEGIN
    SELECT CR.USRROLEID, CR.USERID, CR.ROLEID,
           R.ROLECODE, R.ROLENAME,
           CR.ASSIGNEDBY, CR.ASSIGNEDAT,
           CR.VALIDFROM, CR.VALIDUNTIL, CR.ISACTIVE
    FROM   CMS_CONSUMERROLE CR
    JOIN   CMS_ROLE R ON R.ROLEID = CR.ROLEID
    WHERE  CR.USERID = PUSERID
    ORDER BY R.ROLECODE;
END$$


/* ============================================================
   CMS_CANTEENROLE — Canteen-scoped Role Assignment
   ============================================================ */

CREATE PROCEDURE CMSASSIGNCANROL (
    IN PUSERID     INT,
    IN PROLEID     INT,
    IN PCANTEENID  INT,
    IN PISDEFAULT  TINYINT,
    IN PVALIDFROM  DATETIME,
    IN PVALIDUNTIL DATETIME,
    IN PASSIGNEDBY INT
)
BEGIN
    DECLARE VVALIDFROM DATETIME;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID is required';
    END IF;
    IF PROLEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Role ID is required';
    END IF;
    IF PCANTEENID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required';
    END IF;

    SET VVALIDFROM = COALESCE(PVALIDFROM, CURRENT_TIMESTAMP);

    IF PVALIDUNTIL IS NOT NULL AND PVALIDUNTIL < VVALIDFROM THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Valid until date must be >= valid from date';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_CANTEENROLE (USERID, ROLEID, CANTEENID, ISDEFAULT, VALIDFROM, VALIDUNTIL, ISACTIVE, ASSIGNEDBY)
    VALUES (PUSERID, PROLEID, PCANTEENID, COALESCE(PISDEFAULT, 0), VVALIDFROM, PVALIDUNTIL, 1, PASSIGNEDBY)
    ON DUPLICATE KEY UPDATE
        ISDEFAULT  = COALESCE(PISDEFAULT, ISDEFAULT),
        VALIDFROM  = VVALIDFROM,
        VALIDUNTIL = PVALIDUNTIL,
        ISACTIVE   = 1,
        ASSIGNEDBY = PASSIGNEDBY,
        ASSIGNEDAT = CURRENT_TIMESTAMP;

    COMMIT;
    SELECT PUSERID AS USERID, PROLEID AS ROLEID, PCANTEENID AS CANTEENID;
END$$


CREATE PROCEDURE CMSREMOVECANROL (
    IN PUSERID    INT,
    IN PROLEID    INT,
    IN PCANTEENID INT
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PUSERID IS NULL OR PROLEID IS NULL OR PCANTEENID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User ID, Role ID, and Canteen ID are required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CANTEENROLE
    WHERE USERID = PUSERID AND ROLEID = PROLEID AND CANTEENID = PCANTEENID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen role assignment not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CANTEENROLE SET ISACTIVE = 0, UPDATEDAT = CURRENT_TIMESTAMP
    WHERE USERID = PUSERID AND ROLEID = PROLEID AND CANTEENID = PCANTEENID;
    COMMIT;

    SELECT PUSERID AS USERID, PROLEID AS ROLEID, PCANTEENID AS CANTEENID;
END$$


CREATE PROCEDURE CMSLISTCANROL (IN PUSERID INT)
BEGIN
    SELECT CR.USRCANROLEID, CR.USERID, CR.ROLEID,
           R.ROLECODE, R.ROLENAME,
           CR.CANTEENID, C.CANTEENCODE, C.CANTEENNAME,
           CR.ISDEFAULT, CR.VALIDFROM, CR.VALIDUNTIL,
           CR.ISACTIVE, CR.ASSIGNEDBY, CR.ASSIGNEDAT
    FROM   CMS_CANTEENROLE CR
    JOIN   CMS_ROLE R    ON R.ROLEID     = CR.ROLEID
    JOIN   CMS_CANTEEN C ON C.CANTEENID  = CR.CANTEENID
    WHERE  CR.USERID = PUSERID
    ORDER BY C.CANTEENNAME, R.ROLECODE;
END$$


CREATE PROCEDURE CMSLISTCANROLSTAFF (IN PCANTEENID INT)
BEGIN
    SELECT CR.USRCANROLEID, CR.USERID, U.LOGINID, U.FULLNAME,
           CR.ROLEID, R.ROLECODE, R.ROLENAME,
           CR.ISDEFAULT, CR.VALIDFROM, CR.VALIDUNTIL,
           CR.ISACTIVE, CR.ASSIGNEDBY, CR.ASSIGNEDAT
    FROM   CMS_CANTEENROLE CR
    JOIN   CMS_USER U ON U.USERID = CR.USERID
    JOIN   CMS_ROLE R ON R.ROLEID = CR.ROLEID
    WHERE  CR.CANTEENID = PCANTEENID
      AND  CR.ISACTIVE  = 1
    ORDER BY U.FULLNAME, R.ROLECODE;
END$$


/* ============================================================
   CMS_CUSTOMER — Customer Identity
   ============================================================ */

CREATE PROCEDURE CMSADDCUST (
    IN PUSERID     INT,
    IN PCTYPECODE  VARCHAR(20),
    IN PDISPNAME   VARCHAR(120),
    IN PSTATUS     VARCHAR(20),
    IN PVALIDFROM  DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    DECLARE VCUSTOMERID INT;
    DECLARE VCTYPE INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCTYPECODE IS NULL OR TRIM(PCTYPECODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer Type Code is required';
    END IF;
    IF PDISPNAME IS NULL OR TRIM(PDISPNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Display Name is required';
    END IF;

    SELECT COUNT(*) INTO VCTYPE FROM CMS_CUSTTYPE WHERE CTYPECODE = PCTYPECODE AND ISACTIVE = 1;
    IF VCTYPE = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid or inactive Customer Type Code';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_CUSTOMER (USERID, CTYPECODE, DISPNAME, STATUS, VALIDFROM, VALIDUNTIL)
    VALUES (PUSERID, TRIM(PCTYPECODE), TRIM(PDISPNAME), COALESCE(PSTATUS, 'A'), PVALIDFROM, PVALIDUNTIL);
    SET VCUSTOMERID = LAST_INSERT_ID();
    COMMIT;

    SELECT VCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSUPDCUST (
    IN PCUSTOMERID INT,
    IN PDISPNAME   VARCHAR(120),
    IN PSTATUS     VARCHAR(20),
    IN PVALIDFROM  DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found';
    END IF;
    IF PDISPNAME IS NULL OR TRIM(PDISPNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Display Name is required';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CUSTOMER
    SET    DISPNAME   = TRIM(PDISPNAME),
           STATUS     = COALESCE(PSTATUS, STATUS),
           VALIDFROM  = COALESCE(PVALIDFROM, VALIDFROM),
           VALIDUNTIL = PVALIDUNTIL,
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  CUSTOMERID = PCUSTOMERID;
    COMMIT;

    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSGETCUST (IN PCUSTOMERID INT)
BEGIN
    SELECT C.CUSTOMERID, C.USERID, U.LOGINID, U.FULLNAME,
           C.CTYPECODE, CT.CTYPENAME, C.DISPNAME,
           C.STATUS, C.VALIDFROM, C.VALIDUNTIL,
           C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CUSTOMER C
    LEFT JOIN CMS_USER U     ON U.USERID   = C.USERID
    JOIN   CMS_CUSTTYPE CT   ON CT.CTYPECODE = C.CTYPECODE
    WHERE  C.CUSTOMERID = PCUSTOMERID;
END$$


CREATE PROCEDURE CMSLISTCUST (
    IN PCTYPECODE VARCHAR(20),
    IN PSTATUS    VARCHAR(20)
)
BEGIN
    SELECT C.CUSTOMERID, C.USERID, U.LOGINID, U.FULLNAME,
           C.CTYPECODE, CT.CTYPENAME, C.DISPNAME,
           C.STATUS, C.VALIDFROM, C.VALIDUNTIL,
           C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CUSTOMER C
    LEFT JOIN CMS_USER U     ON U.USERID   = C.USERID
    JOIN   CMS_CUSTTYPE CT   ON CT.CTYPECODE = C.CTYPECODE
    WHERE  (PCTYPECODE IS NULL OR C.CTYPECODE = PCTYPECODE)
      AND  (PSTATUS    IS NULL OR C.STATUS    = PSTATUS)
    ORDER BY C.DISPNAME;
END$$


CREATE PROCEDURE CMSSEARCHCUST (IN PKEYWORD VARCHAR(120))
BEGIN
    SELECT C.CUSTOMERID, C.USERID, U.LOGINID, U.FULLNAME,
           C.CTYPECODE, CT.CTYPENAME, C.DISPNAME,
           C.STATUS, C.VALIDFROM, C.VALIDUNTIL,
           C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CUSTOMER C
    LEFT JOIN CMS_USER U     ON U.USERID   = C.USERID
    JOIN   CMS_CUSTTYPE CT   ON CT.CTYPECODE = C.CTYPECODE
    WHERE  (C.DISPNAME LIKE CONCAT('%', PKEYWORD, '%')
       OR   U.FULLNAME LIKE CONCAT('%', PKEYWORD, '%')
       OR   U.LOGINID  LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY C.DISPNAME;
END$$


CREATE PROCEDURE CMSACTCUST (IN PCUSTOMERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PCUSTOMERID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found'; END IF;
    START TRANSACTION;
    UPDATE CMS_CUSTOMER SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE CUSTOMERID = PCUSTOMERID;
    COMMIT;
    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSDEACTCUST (IN PCUSTOMERID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PCUSTOMERID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found'; END IF;
    START TRANSACTION;
    UPDATE CMS_CUSTOMER SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE CUSTOMERID = PCUSTOMERID;
    COMMIT;
    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


/* ============================================================
   CMS_PERMEMP — Permanent Employee Profile
   ============================================================ */

CREATE PROCEDURE CMSADDPERM (
    IN PCUSTOMERID INT,
    IN PEMPCODE    VARCHAR(50),
    IN PDEPT       VARCHAR(100),
    IN PDESIG      VARCHAR(100)
)
BEGIN
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VPERMEMPID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    IF PEMPCODE IS NULL OR TRIM(PEMPCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Employee Code is required';
    END IF;
    IF PDEPT IS NULL OR TRIM(PDEPT) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Department is required';
    END IF;
    IF PDESIG IS NULL OR TRIM(PDESIG) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Designation is required';
    END IF;

    SELECT CTYPECODE INTO VCTYPECODE FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found';
    END IF;
    IF VCTYPECODE <> 'PERMANENT' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer type must be PERMANENT';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_PERMEMP (CUSTOMERID, EMPCODE, DEPT, DESIG)
    VALUES (PCUSTOMERID, TRIM(PEMPCODE), TRIM(PDEPT), TRIM(PDESIG));
    SET VPERMEMPID = LAST_INSERT_ID();
    COMMIT;

    SELECT VPERMEMPID AS PERMEMPID;
END$$


CREATE PROCEDURE CMSUPDPERM (
    IN PCUSTOMERID INT,
    IN PDEPT       VARCHAR(100),
    IN PDESIG      VARCHAR(100)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_PERMEMP WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Permanent employee profile not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_PERMEMP
    SET    DEPT      = COALESCE(PDEPT, DEPT),
           DESIG     = COALESCE(PDESIG, DESIG),
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  CUSTOMERID = PCUSTOMERID;
    COMMIT;
    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSGETPERM (IN PCUSTOMERID INT)
BEGIN
    SELECT PE.PERMEMPID, PE.CUSTOMERID, PE.EMPCODE, PE.DEPT, PE.DESIG,
           C.DISPNAME, C.STATUS, U.USERID, U.LOGINID, U.FULLNAME
    FROM   CMS_PERMEMP PE
    JOIN   CMS_CUSTOMER C ON C.CUSTOMERID = PE.CUSTOMERID
    LEFT JOIN CMS_USER U  ON U.USERID     = C.USERID
    WHERE  PE.CUSTOMERID = PCUSTOMERID;
END$$


/* ============================================================
   CMS_CONTEMP — Contract Employee Profile
   ============================================================ */

CREATE PROCEDURE CMSADDCONT (
    IN PCUSTOMERID  INT,
    IN PCONTCODE    VARCHAR(50),
    IN PVENDORNAME  VARCHAR(150),
    IN PCONTSTART   DATE,
    IN PCONTEND     DATE
)
BEGIN
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VCONTEMPID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    IF PCONTCODE IS NULL OR TRIM(PCONTCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract Code is required';
    END IF;
    IF PVENDORNAME IS NULL OR TRIM(PVENDORNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Vendor Name is required';
    END IF;
    IF PCONTSTART IS NULL OR PCONTEND IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract start and end dates are required';
    END IF;
    IF PCONTEND < PCONTSTART THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract end date must be >= start date';
    END IF;

    SELECT CTYPECODE INTO VCTYPECODE FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found';
    END IF;
    IF VCTYPECODE <> 'CONTRACT' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer type must be CONTRACT';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_CONTEMP (CUSTOMERID, CONTCODE, VENDORNAME, CONTSTART, CONTEND)
    VALUES (PCUSTOMERID, TRIM(PCONTCODE), TRIM(PVENDORNAME), PCONTSTART, PCONTEND);
    SET VCONTEMPID = LAST_INSERT_ID();
    COMMIT;
    SELECT VCONTEMPID AS CONTEMPID;
END$$


CREATE PROCEDURE CMSUPDCONT (
    IN PCUSTOMERID INT,
    IN PVENDORNAME VARCHAR(150),
    IN PCONTSTART  DATE,
    IN PCONTEND    DATE
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_CONTEMP WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract employee profile not found';
    END IF;
    IF PCONTEND IS NOT NULL AND PCONTSTART IS NOT NULL AND PCONTEND < PCONTSTART THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract end date must be >= start date';
    END IF;

    START TRANSACTION;
    UPDATE CMS_CONTEMP
    SET    VENDORNAME = COALESCE(PVENDORNAME, VENDORNAME),
           CONTSTART  = COALESCE(PCONTSTART, CONTSTART),
           CONTEND    = COALESCE(PCONTEND, CONTEND),
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  CUSTOMERID = PCUSTOMERID;
    COMMIT;
    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSGETCONT (IN PCUSTOMERID INT)
BEGIN
    SELECT CE.CONTEMPID, CE.CUSTOMERID, CE.CONTCODE, CE.VENDORNAME,
           CE.CONTSTART, CE.CONTEND,
           C.DISPNAME, C.STATUS, U.USERID, U.LOGINID, U.FULLNAME
    FROM   CMS_CONTEMP CE
    JOIN   CMS_CUSTOMER C ON C.CUSTOMERID = CE.CUSTOMERID
    LEFT JOIN CMS_USER U  ON U.USERID     = C.USERID
    WHERE  CE.CUSTOMERID = PCUSTOMERID;
END$$


/* ============================================================
   CMS_OCEEMP — Other Centre Employee Profile
   ============================================================ */

CREATE PROCEDURE CMSADDOCE (
    IN PCUSTOMERID  INT,
    IN PEMPCODE     VARCHAR(50),
    IN PCENTERNAME  VARCHAR(120),
    IN PDEPT        VARCHAR(100),
    IN PDESIG       VARCHAR(100),
    IN PVALIDFROM   DATETIME,
    IN PVALIDUNTIL  DATETIME
)
BEGIN
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VOCEEMPID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    IF PEMPCODE IS NULL OR TRIM(PEMPCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Employee Code is required';
    END IF;
    IF PCENTERNAME IS NULL OR TRIM(PCENTERNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre Name is required';
    END IF;

    SELECT CTYPECODE INTO VCTYPECODE FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found';
    END IF;
    IF VCTYPECODE <> 'OTHERCENTRE' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer type must be OTHERCENTRE';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_OCEEMP (CUSTOMERID, EMPCODE, CENTERNAME, DEPT, DESIG, VALIDFROM, VALIDUNTIL)
    VALUES (PCUSTOMERID, TRIM(PEMPCODE), TRIM(PCENTERNAME), PDEPT, PDESIG, PVALIDFROM, PVALIDUNTIL);
    SET VOCEEMPID = LAST_INSERT_ID();
    COMMIT;
    SELECT VOCEEMPID AS OCEEMPID;
END$$


CREATE PROCEDURE CMSUPDOCE (
    IN PCUSTOMERID INT,
    IN PDEPT       VARCHAR(100),
    IN PDESIG      VARCHAR(100),
    IN PVALIDFROM  DATETIME,
    IN PVALIDUNTIL DATETIME
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_OCEEMP WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Other centre employee profile not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_OCEEMP
    SET    DEPT       = COALESCE(PDEPT, DEPT),
           DESIG      = COALESCE(PDESIG, DESIG),
           VALIDFROM  = COALESCE(PVALIDFROM, VALIDFROM),
           VALIDUNTIL = PVALIDUNTIL,
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  CUSTOMERID = PCUSTOMERID;
    COMMIT;
    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSGETOCE (IN PCUSTOMERID INT)
BEGIN
    SELECT OE.OCEEMPID, OE.CUSTOMERID, OE.EMPCODE, OE.CENTERNAME,
           OE.DEPT, OE.DESIG, OE.VALIDFROM, OE.VALIDUNTIL,
           C.DISPNAME, C.STATUS, U.USERID, U.LOGINID, U.FULLNAME
    FROM   CMS_OCEEMP OE
    JOIN   CMS_CUSTOMER C ON C.CUSTOMERID = OE.CUSTOMERID
    LEFT JOIN CMS_USER U  ON U.USERID     = C.USERID
    WHERE  OE.CUSTOMERID = PCUSTOMERID;
END$$


/* ============================================================
   CMS_VISITOR — Visitor Profile
   ============================================================ */

CREATE PROCEDURE CMSADDVIS (
    IN PCUSTOMERID INT,
    IN PVISNAME    VARCHAR(120),
    IN PVISMOBILE  VARCHAR(20),
    IN PVISORG     VARCHAR(150),
    IN PVISPURPOSE VARCHAR(255),
    IN PVISDATE    DATE,
    IN PVALIDUNTIL DATETIME,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VVISITORID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    IF PVISNAME IS NULL OR TRIM(PVISNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Visitor Name is required';
    END IF;
    IF PVISDATE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Visit Date is required';
    END IF;
    IF PVALIDUNTIL IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Valid Until is required';
    END IF;
    IF PCREATEDBY IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Created By is required';
    END IF;
    IF PVALIDUNTIL < TIMESTAMP(PVISDATE, '00:00:00') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Valid until must be >= visit date';
    END IF;

    SELECT CTYPECODE INTO VCTYPECODE FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;
    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found';
    END IF;
    IF VCTYPECODE <> 'VISITOR' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer type must be VISITOR';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_VISITOR (CUSTOMERID, VISNAME, VISMOBILE, VISORG, VISPURPOSE, VISDATE, VALIDUNTIL, CREATEDBY, STATUS)
    VALUES (PCUSTOMERID, TRIM(PVISNAME), PVISMOBILE, PVISORG, PVISPURPOSE, PVISDATE, PVALIDUNTIL, PCREATEDBY, 'A');
    SET VVISITORID = LAST_INSERT_ID();
    COMMIT;
    SELECT VVISITORID AS VISITORID;
END$$


CREATE PROCEDURE CMSUPDVIS (
    IN PCUSTOMERID INT,
    IN PVISMOBILE  VARCHAR(20),
    IN PVISORG     VARCHAR(150),
    IN PVISPURPOSE VARCHAR(255),
    IN PVALIDUNTIL DATETIME,
    IN PSTATUS     VARCHAR(20)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_VISITOR WHERE CUSTOMERID = PCUSTOMERID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Visitor profile not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_VISITOR
    SET    VISMOBILE  = COALESCE(PVISMOBILE, VISMOBILE),
           VISORG     = COALESCE(PVISORG, VISORG),
           VISPURPOSE = COALESCE(PVISPURPOSE, VISPURPOSE),
           VALIDUNTIL = COALESCE(PVALIDUNTIL, VALIDUNTIL),
           STATUS     = COALESCE(PSTATUS, STATUS),
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  CUSTOMERID = PCUSTOMERID;
    COMMIT;
    SELECT PCUSTOMERID AS CUSTOMERID;
END$$


CREATE PROCEDURE CMSGETVIS (IN PCUSTOMERID INT)
BEGIN
    SELECT V.VISITORID, V.CUSTOMERID, V.VISNAME, V.VISMOBILE,
           V.VISORG, V.VISPURPOSE, V.VISDATE, V.VALIDUNTIL,
           V.CREATEDBY, V.STATUS,
           C.DISPNAME, U.USERID, U.LOGINID
    FROM   CMS_VISITOR V
    JOIN   CMS_CUSTOMER C ON C.CUSTOMERID = V.CUSTOMERID
    LEFT JOIN CMS_USER U  ON U.USERID     = C.USERID
    WHERE  V.CUSTOMERID = PCUSTOMERID;
END$$


/* ============================================================
   CMS_ACCKEY — Access Credential Management
   ============================================================ */

CREATE PROCEDURE CMSADDACCKEY (
    IN PCUSTOMERID INT,
    IN PKEYTYPE    VARCHAR(30),
    IN PKEYVALUE   VARCHAR(255),
    IN PEXPIRESAT  DATETIME,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VACCKEYID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer ID is required';
    END IF;
    IF PKEYVALUE IS NULL OR TRIM(PKEYVALUE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key value is required';
    END IF;
    IF PKEYTYPE IS NULL OR PKEYTYPE NOT IN ('QR', 'RFID', 'EMPCARD', 'VISPASS', 'TEMPTOKEN') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid access key type';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_ACCKEY (CUSTOMERID, KEYTYPE, KEYVALUE, EXPIRESAT, STATUS, CREATEDBY)
    VALUES (PCUSTOMERID, PKEYTYPE, TRIM(PKEYVALUE), PEXPIRESAT, 'A', PCREATEDBY);
    SET VACCKEYID = LAST_INSERT_ID();
    COMMIT;
    SELECT VACCKEYID AS ACCKEYID;
END$$


CREATE PROCEDURE CMSUPDACCKEY (
    IN PACCKEYID  INT,
    IN PKEYVALUE  VARCHAR(255),
    IN PEXPIRESAT DATETIME
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PACCKEYID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access Key ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_ACCKEY WHERE ACCKEYID = PACCKEYID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_ACCKEY
    SET    KEYVALUE   = COALESCE(PKEYVALUE, KEYVALUE),
           EXPIRESAT  = COALESCE(PEXPIRESAT, EXPIRESAT),
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  ACCKEYID   = PACCKEYID;
    COMMIT;
    SELECT PACCKEYID AS ACCKEYID;
END$$


CREATE PROCEDURE CMSGETACCKEY (IN PACCKEYID INT)
BEGIN
    SELECT AK.ACCKEYID, AK.CUSTOMERID, C.DISPNAME, C.CTYPECODE,
           AK.KEYTYPE, AK.KEYVALUE, AK.EXPIRESAT,
           AK.STATUS, AK.LASTUSEDAT, AK.CREATEDBY,
           AK.CREATEDAT, AK.UPDATEDAT
    FROM   CMS_ACCKEY AK
    JOIN   CMS_CUSTOMER C ON C.CUSTOMERID = AK.CUSTOMERID
    WHERE  AK.ACCKEYID = PACCKEYID;
END$$


CREATE PROCEDURE CMSLISTACCKEY (IN PCUSTOMERID INT)
BEGIN
    SELECT AK.ACCKEYID, AK.CUSTOMERID, AK.KEYTYPE, AK.KEYVALUE,
           AK.EXPIRESAT, AK.STATUS, AK.LASTUSEDAT,
           AK.CREATEDBY, AK.CREATEDAT, AK.UPDATEDAT
    FROM   CMS_ACCKEY AK
    WHERE  AK.CUSTOMERID = PCUSTOMERID
    ORDER BY AK.KEYTYPE, AK.CREATEDAT DESC;
END$$


CREATE PROCEDURE CMSACTACCKEY (IN PACCKEYID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PACCKEYID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access Key ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_ACCKEY WHERE ACCKEYID = PACCKEYID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_ACCKEY SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE ACCKEYID = PACCKEYID;
    COMMIT;
    SELECT PACCKEYID AS ACCKEYID;
END$$


CREATE PROCEDURE CMSDEACTACCKEY (IN PACCKEYID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PACCKEYID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access Key ID is required';
    END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_ACCKEY WHERE ACCKEYID = PACCKEYID;
    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key not found';
    END IF;

    START TRANSACTION;
    UPDATE CMS_ACCKEY SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE ACCKEYID = PACCKEYID;
    COMMIT;
    SELECT PACCKEYID AS ACCKEYID;
END$$


/* ============================================================
   CMSVALIDATEACCKEY — Kiosk / Serving Identity Lookup

   Given a scanned key value, returns the customer identity
   if the key is active, not expired, and the customer is active.
   Updates LASTUSEDAT on every successful validation.
   ============================================================ */
CREATE PROCEDURE CMSVALIDATEACCKEY (
    IN PKEYVALUE VARCHAR(255)
)
BEGIN
    DECLARE VACCKEYID   INT;
    DECLARE VCUSTOMERID INT;
    DECLARE VKEYSTATUS  VARCHAR(20);
    DECLARE VEXPIRESAT  DATETIME;
    DECLARE VCUSTSTATUS VARCHAR(20);

    IF PKEYVALUE IS NULL OR TRIM(PKEYVALUE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Key value is required';
    END IF;

    SELECT AK.ACCKEYID, AK.CUSTOMERID, AK.STATUS, AK.EXPIRESAT, C.STATUS
    INTO   VACCKEYID, VCUSTOMERID, VKEYSTATUS, VEXPIRESAT, VCUSTSTATUS
    FROM   CMS_ACCKEY AK
    JOIN   CMS_CUSTOMER C ON C.CUSTOMERID = AK.CUSTOMERID
    WHERE  AK.KEYVALUE = TRIM(PKEYVALUE)
    LIMIT 1;

    IF VACCKEYID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key not recognised';
    END IF;

    IF VKEYSTATUS <> 'A' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key is inactive or revoked';
    END IF;

    IF VEXPIRESAT IS NOT NULL AND CURRENT_TIMESTAMP > VEXPIRESAT THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Access key has expired';
    END IF;

    IF VCUSTSTATUS <> 'A' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer account is not active';
    END IF;

    -- Touch last used timestamp (no transaction needed for single update)
    UPDATE CMS_ACCKEY SET LASTUSEDAT = CURRENT_TIMESTAMP WHERE ACCKEYID = VACCKEYID;

    -- Return customer identity
    SELECT C.CUSTOMERID, C.USERID, C.CTYPECODE, CT.CTYPENAME,
           C.DISPNAME, C.STATUS AS CUSTSTATUS,
           AK.ACCKEYID, AK.KEYTYPE,
           U.LOGINID, U.FULLNAME
    FROM   CMS_CUSTOMER C
    JOIN   CMS_CUSTTYPE CT ON CT.CTYPECODE = C.CTYPECODE
    JOIN   CMS_ACCKEY AK   ON AK.CUSTOMERID = C.CUSTOMERID AND AK.ACCKEYID = VACCKEYID
    LEFT JOIN CMS_USER U   ON U.USERID = C.USERID
    WHERE  C.CUSTOMERID = VCUSTOMERID;
END$$

/* ============================================================
   CMSLOGININFO — Login Profile Fetch

   Rewritten for CMS_CONSUMERROLE + CMS_CANTEENROLE.
   Returns:
     Result set 1: User profile
     Result set 2: Consumer role
     Result set 3: Canteen role 
   ============================================================ */

CREATE PROCEDURE CMSLOGININFO (
    IN PLOGINID VARCHAR(50)
)
BEGIN
    DECLARE VUSERID INT DEFAULT NULL;

    /*------------------------------------------------------------
      Get USERID
    ------------------------------------------------------------*/
    SELECT USERID
      INTO VUSERID
    FROM CMS_USER
    WHERE LOGINID = PLOGINID
      AND ISACTIVE = 1
    LIMIT 1;

    /*------------------------------------------------------------
      Result Set 1
      User + Customer Information
    ------------------------------------------------------------*/
    SELECT
        U.USERID,
        U.LOGINID,
        U.FULLNAME,
        U.EMAIL,
        U.MOBILENO,
        U.PWDHASH,
        U.AUTHPROV,
        U.AUTHID,
        U.ISACTIVE,

        C.CUSTOMERID,
        C.CTYPECODE,
        C.DISPNAME,
        C.STATUS AS CUSTOMERSTATUS

    FROM CMS_USER U
    LEFT JOIN CMS_CUSTOMER C
           ON C.USERID = U.USERID
    WHERE U.USERID = VUSERID;

    /*------------------------------------------------------------
      Result Set 2
      Consumer Roles
    ------------------------------------------------------------*/
    IF VUSERID IS NOT NULL THEN

        SELECT
            CR.USRROLEID,
            CR.ROLEID,
            R.ROLECODE,
            R.ROLENAME
        FROM CMS_CONSUMERROLE CR
        INNER JOIN CMS_ROLE R
                ON R.ROLEID = CR.ROLEID
        WHERE CR.USERID = VUSERID
          AND CR.ISACTIVE = 1
          AND R.ISACTIVE = 1
          AND (CR.VALIDFROM IS NULL
               OR CURRENT_TIMESTAMP >= CR.VALIDFROM)
          AND (CR.VALIDUNTIL IS NULL
               OR CURRENT_TIMESTAMP <= CR.VALIDUNTIL)
        ORDER BY R.ROLECODE;

    END IF;

    /*------------------------------------------------------------
      Result Set 3
      Canteen Role Assignments
    ------------------------------------------------------------*/
    IF VUSERID IS NOT NULL THEN

        SELECT
            CR.USRCANROLEID,
            CR.CANTEENID,
            CN.CANTEENCODE,
            CN.CANTEENNAME,

            CR.ROLEID,
            R.ROLECODE,
            R.ROLENAME,

            CR.ISDEFAULT

        FROM CMS_CANTEENROLE CR
        INNER JOIN CMS_CANTEEN CN
                ON CN.CANTEENID = CR.CANTEENID
        INNER JOIN CMS_ROLE R
                ON R.ROLEID = CR.ROLEID

        WHERE CR.USERID = VUSERID
          AND CR.ISACTIVE = 1
          AND R.ISACTIVE = 1
          AND (CR.VALIDFROM IS NULL
               OR CURRENT_TIMESTAMP >= CR.VALIDFROM)
          AND (CR.VALIDUNTIL IS NULL
               OR CURRENT_TIMESTAMP <= CR.VALIDUNTIL)

        ORDER BY
            CR.ISDEFAULT DESC,
            CN.CANTEENNAME;

    END IF;

END$$



/* ============================================================
   COMPOSITE REGISTRATION PROCEDURES

   Each creates User + Customer + Profile + Access Key
   in a single transaction for data integrity.
   ============================================================ */

CREATE PROCEDURE CMSREGPERM (
    IN PLOGINID   VARCHAR(50),
    IN PFULLNAME  VARCHAR(120),
    IN PEMAIL     VARCHAR(120),
    IN PMOBILENO  VARCHAR(20),
    IN PPWDHASH   VARCHAR(255),
    IN PEMPCODE   VARCHAR(50),
    IN PDEPT      VARCHAR(100),
    IN PDESIG     VARCHAR(100),
    IN PKEYTYPE   VARCHAR(30),
    IN PKEYVALUE  VARCHAR(255),
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VUSERID     INT;
    DECLARE VCUSTOMERID INT;
    DECLARE VPERMEMPID  INT;
    DECLARE VACCKEYID   INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    -- Validate required fields
    IF PLOGINID IS NULL OR TRIM(PLOGINID) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Login ID is required'; END IF;
    IF PFULLNAME IS NULL OR TRIM(PFULLNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Full Name is required'; END IF;
    IF PPWDHASH IS NULL OR TRIM(PPWDHASH) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Password hash is required'; END IF;
    IF PEMPCODE IS NULL OR TRIM(PEMPCODE) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Employee Code is required'; END IF;
    IF PDEPT IS NULL OR TRIM(PDEPT) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Department is required'; END IF;
    IF PDESIG IS NULL OR TRIM(PDESIG) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Designation is required'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_USER (LOGINID, FULLNAME, EMAIL, MOBILENO, PWDHASH, AUTHPROV)
    VALUES (TRIM(PLOGINID), TRIM(PFULLNAME), PEMAIL, PMOBILENO, PPWDHASH, 'LOCAL');
    SET VUSERID = LAST_INSERT_ID();

    INSERT INTO CMS_CUSTOMER (USERID, CTYPECODE, DISPNAME, STATUS, VALIDFROM)
    VALUES (VUSERID, 'PERMANENT', TRIM(PFULLNAME), 'A', CURRENT_TIMESTAMP);
    SET VCUSTOMERID = LAST_INSERT_ID();

    INSERT INTO CMS_PERMEMP (CUSTOMERID, EMPCODE, DEPT, DESIG)
    VALUES (VCUSTOMERID, TRIM(PEMPCODE), TRIM(PDEPT), TRIM(PDESIG));
    SET VPERMEMPID = LAST_INSERT_ID();

    IF PKEYVALUE IS NOT NULL AND TRIM(PKEYVALUE) <> '' THEN
        INSERT INTO CMS_ACCKEY (CUSTOMERID, KEYTYPE, KEYVALUE, STATUS, CREATEDBY)
        VALUES (VCUSTOMERID, COALESCE(PKEYTYPE, 'EMPCARD'), TRIM(PKEYVALUE), 'A', PCREATEDBY);
        SET VACCKEYID = LAST_INSERT_ID();
    END IF;

    COMMIT;

    SELECT VUSERID AS USERID, VCUSTOMERID AS CUSTOMERID, VPERMEMPID AS PERMEMPID, VACCKEYID AS ACCKEYID;
END$$


CREATE PROCEDURE CMSREGCONT (
    IN PLOGINID    VARCHAR(50),
    IN PFULLNAME   VARCHAR(120),
    IN PEMAIL      VARCHAR(120),
    IN PMOBILENO   VARCHAR(20),
    IN PPWDHASH    VARCHAR(255),
    IN PCONTCODE   VARCHAR(50),
    IN PVENDORNAME VARCHAR(150),
    IN PCONTSTART  DATE,
    IN PCONTEND    DATE,
    IN PDISPNAME   VARCHAR(120),
    IN PKEYTYPE    VARCHAR(30),
    IN PKEYVALUE   VARCHAR(255),
    IN PEXPIRESAT  DATETIME,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VUSERID     INT;
    DECLARE VCUSTOMERID INT;
    DECLARE VCONTEMPID  INT;
    DECLARE VACCKEYID   INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PLOGINID IS NULL OR TRIM(PLOGINID) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Login ID is required'; END IF;
    IF PFULLNAME IS NULL OR TRIM(PFULLNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Full Name is required'; END IF;
    IF PPWDHASH IS NULL OR TRIM(PPWDHASH) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Password hash is required'; END IF;
    IF PCONTCODE IS NULL OR TRIM(PCONTCODE) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract Code is required'; END IF;
    IF PVENDORNAME IS NULL OR TRIM(PVENDORNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Vendor Name is required'; END IF;
    IF PCONTSTART IS NULL OR PCONTEND IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract dates are required'; END IF;
    IF PCONTEND < PCONTSTART THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Contract end must be >= start'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_USER (LOGINID, FULLNAME, EMAIL, MOBILENO, PWDHASH, AUTHPROV)
    VALUES (TRIM(PLOGINID), TRIM(PFULLNAME), PEMAIL, PMOBILENO, PPWDHASH, 'LOCAL');
    SET VUSERID = LAST_INSERT_ID();

    INSERT INTO CMS_CUSTOMER (USERID, CTYPECODE, DISPNAME, STATUS, VALIDFROM)
    VALUES (VUSERID, 'CONTRACT', COALESCE(TRIM(PDISPNAME), TRIM(PFULLNAME)), 'A', CURRENT_TIMESTAMP);
    SET VCUSTOMERID = LAST_INSERT_ID();

    INSERT INTO CMS_CONTEMP (CUSTOMERID, CONTCODE, VENDORNAME, CONTSTART, CONTEND)
    VALUES (VCUSTOMERID, TRIM(PCONTCODE), TRIM(PVENDORNAME), PCONTSTART, PCONTEND);
    SET VCONTEMPID = LAST_INSERT_ID();

    IF PKEYVALUE IS NOT NULL AND TRIM(PKEYVALUE) <> '' THEN
        INSERT INTO CMS_ACCKEY (CUSTOMERID, KEYTYPE, KEYVALUE, EXPIRESAT, STATUS, CREATEDBY)
        VALUES (VCUSTOMERID, COALESCE(PKEYTYPE, 'QR'), TRIM(PKEYVALUE), PEXPIRESAT, 'A', PCREATEDBY);
        SET VACCKEYID = LAST_INSERT_ID();
    END IF;

    COMMIT;
    SELECT VUSERID AS USERID, VCUSTOMERID AS CUSTOMERID, VCONTEMPID AS CONTEMPID, VACCKEYID AS ACCKEYID;
END$$


CREATE PROCEDURE CMSREGOCE (
    IN PLOGINID    VARCHAR(50),
    IN PFULLNAME   VARCHAR(120),
    IN PEMAIL      VARCHAR(120),
    IN PMOBILENO   VARCHAR(20),
    IN PPWDHASH    VARCHAR(255),
    IN PEMPCODE    VARCHAR(50),
    IN PCENTERNAME VARCHAR(120),
    IN PDEPT       VARCHAR(100),
    IN PDESIG      VARCHAR(100),
    IN PVALIDFROM  DATETIME,
    IN PVALIDUNTIL DATETIME,
    IN PDISPNAME   VARCHAR(120),
    IN PKEYTYPE    VARCHAR(30),
    IN PKEYVALUE   VARCHAR(255),
    IN PEXPIRESAT  DATETIME,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VUSERID     INT;
    DECLARE VCUSTOMERID INT;
    DECLARE VOCEEMPID   INT;
    DECLARE VACCKEYID   INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PLOGINID IS NULL OR TRIM(PLOGINID) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Login ID is required'; END IF;
    IF PFULLNAME IS NULL OR TRIM(PFULLNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Full Name is required'; END IF;
    IF PPWDHASH IS NULL OR TRIM(PPWDHASH) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Password hash is required'; END IF;
    IF PEMPCODE IS NULL OR TRIM(PEMPCODE) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Employee Code is required'; END IF;
    IF PCENTERNAME IS NULL OR TRIM(PCENTERNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Centre Name is required'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_USER (LOGINID, FULLNAME, EMAIL, MOBILENO, PWDHASH, AUTHPROV)
    VALUES (TRIM(PLOGINID), TRIM(PFULLNAME), PEMAIL, PMOBILENO, PPWDHASH, 'LOCAL');
    SET VUSERID = LAST_INSERT_ID();

    INSERT INTO CMS_CUSTOMER (USERID, CTYPECODE, DISPNAME, STATUS, VALIDFROM, VALIDUNTIL)
    VALUES (VUSERID, 'OTHERCENTRE', COALESCE(TRIM(PDISPNAME), TRIM(PFULLNAME)), 'A', PVALIDFROM, PVALIDUNTIL);
    SET VCUSTOMERID = LAST_INSERT_ID();

    INSERT INTO CMS_OCEEMP (CUSTOMERID, EMPCODE, CENTERNAME, DEPT, DESIG, VALIDFROM, VALIDUNTIL)
    VALUES (VCUSTOMERID, TRIM(PEMPCODE), TRIM(PCENTERNAME), PDEPT, PDESIG, PVALIDFROM, PVALIDUNTIL);
    SET VOCEEMPID = LAST_INSERT_ID();

    IF PKEYVALUE IS NOT NULL AND TRIM(PKEYVALUE) <> '' THEN
        INSERT INTO CMS_ACCKEY (CUSTOMERID, KEYTYPE, KEYVALUE, EXPIRESAT, STATUS, CREATEDBY)
        VALUES (VCUSTOMERID, COALESCE(PKEYTYPE, 'TEMPTOKEN'), TRIM(PKEYVALUE), PEXPIRESAT, 'A', PCREATEDBY);
        SET VACCKEYID = LAST_INSERT_ID();
    END IF;

    COMMIT;
    SELECT VUSERID AS USERID, VCUSTOMERID AS CUSTOMERID, VOCEEMPID AS OCEEMPID, VACCKEYID AS ACCKEYID;
END$$


CREATE PROCEDURE CMSREGVIS (
    IN PVISNAME    VARCHAR(120),
    IN PVISMOBILE  VARCHAR(20),
    IN PVISORG     VARCHAR(150),
    IN PVISPURPOSE VARCHAR(255),
    IN PVISDATE    DATE,
    IN PVALIDUNTIL DATETIME,
    IN PKEYTYPE    VARCHAR(30),
    IN PKEYVALUE   VARCHAR(255),
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VCUSTOMERID INT;
    DECLARE VVISITORID  INT;
    DECLARE VACCKEYID   INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PVISNAME IS NULL OR TRIM(PVISNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Visitor Name is required'; END IF;
    IF PVISDATE IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Visit Date is required'; END IF;
    IF PVALIDUNTIL IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Valid Until is required'; END IF;
    IF PCREATEDBY IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Created By is required'; END IF;
    IF PVALIDUNTIL < TIMESTAMP(PVISDATE, '00:00:00') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Valid until must be >= visit date';
    END IF;

    START TRANSACTION;

    -- Visitors may not have a CMS_USER; USERID is NULL
    INSERT INTO CMS_CUSTOMER (USERID, CTYPECODE, DISPNAME, STATUS, VALIDFROM, VALIDUNTIL)
    VALUES (NULL, 'VISITOR', TRIM(PVISNAME), 'A', CURRENT_TIMESTAMP, PVALIDUNTIL);
    SET VCUSTOMERID = LAST_INSERT_ID();

    INSERT INTO CMS_VISITOR (CUSTOMERID, VISNAME, VISMOBILE, VISORG, VISPURPOSE, VISDATE, VALIDUNTIL, CREATEDBY, STATUS)
    VALUES (VCUSTOMERID, TRIM(PVISNAME), PVISMOBILE, PVISORG, PVISPURPOSE, PVISDATE, PVALIDUNTIL, PCREATEDBY, 'A');
    SET VVISITORID = LAST_INSERT_ID();

    IF PKEYVALUE IS NOT NULL AND TRIM(PKEYVALUE) <> '' THEN
        INSERT INTO CMS_ACCKEY (CUSTOMERID, KEYTYPE, KEYVALUE, EXPIRESAT, STATUS, CREATEDBY)
        VALUES (VCUSTOMERID, COALESCE(PKEYTYPE, 'VISPASS'), TRIM(PKEYVALUE), PVALIDUNTIL, 'A', PCREATEDBY);
        SET VACCKEYID = LAST_INSERT_ID();
    END IF;

    COMMIT;
    SELECT VCUSTOMERID AS CUSTOMERID, VVISITORID AS VISITORID, VACCKEYID AS ACCKEYID;
END$$


/* ============================================================
   CMSGETCUSTBYUSER — Lookup Customer by User ID
   Used by backend to check if a customer already exists
   for a given user before creating a new one.
   ============================================================ */

CREATE PROCEDURE CMSGETCUSTBYUSER (IN PUSERID INT)
BEGIN
    SELECT C.CUSTOMERID, C.USERID, C.CTYPECODE, C.DISPNAME,
           C.STATUS, C.VALIDFROM, C.VALIDUNTIL,
           C.CREATEDAT, C.UPDATEDAT
    FROM   CMS_CUSTOMER C
    WHERE  C.USERID = PUSERID;
END$$


DELIMITER ;
