/* ============================================================
   MODULE 2: CANTEEN MENU & SERVICE MANAGEMENT STORED PROCEDURES
   ============================================================ */

USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDSERV;
DROP PROCEDURE IF EXISTS CMSUPDSERV;
DROP PROCEDURE IF EXISTS CMSADDMENU;
DROP PROCEDURE IF EXISTS CMSUPDMENU;
DROP PROCEDURE IF EXISTS CMSADDSLOT;
DROP PROCEDURE IF EXISTS CMSUPDSLOT;
DROP PROCEDURE IF EXISTS CMSADDDMENU;
DROP PROCEDURE IF EXISTS CMSAPPDMENU;
DROP PROCEDURE IF EXISTS CMSVIEWMENU;

DELIMITER $$

-- v2_module2
-- Added mandatory input, time range, date range, and transaction exception validation.
CREATE PROCEDURE CMSADDSERV (
    IN PSERVCODE VARCHAR(20),
    IN PSERVNAME VARCHAR(80),
    IN PDEFSTART TIME,
    IN PDEFEND TIME,
    IN PVALIDFROM DATE,
    IN PVALIDUNTIL DATE,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VSERVICEID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PSERVCODE IS NULL OR TRIM(PSERVCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service Code is required';
    END IF;

    IF PSERVNAME IS NULL OR TRIM(PSERVNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service Name is required';
    END IF;

    IF PDEFSTART IS NULL OR PDEFEND IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service start and end time are required';
    END IF;

    IF PDEFEND <= PDEFSTART THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service end time must be after start time';
    END IF;

    IF PVALIDUNTIL IS NOT NULL AND PVALIDFROM IS NOT NULL AND PVALIDUNTIL < PVALIDFROM THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service valid until date must be greater than or equal to valid from date';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_SERVICE (SERVCODE, SERVNAME, DEFSTART, DEFEND, VALIDFROM, VALIDUNTIL, STATUS, CREATEDBY)
    VALUES (TRIM(PSERVCODE), TRIM(PSERVNAME), PDEFSTART, PDEFEND, PVALIDFROM, PVALIDUNTIL, 'A', PCREATEDBY);

    SET VSERVICEID = LAST_INSERT_ID();

    COMMIT;

    SELECT VSERVICEID AS SERVICEID;
END$$

-- v2_module2
-- Added status validation, history-before-update enforcement, and transaction exception handling.
CREATE PROCEDURE CMSUPDSERV (
    IN PSERVICEID INT,
    IN PSERVNAME VARCHAR(80),
    IN PDEFSTART TIME,
    IN PDEFEND TIME,
    IN PVALIDFROM DATE,
    IN PVALIDUNTIL DATE,
    IN PSTATUS VARCHAR(20),
    IN PCHANGEDBY INT,
    IN PCHGREASON VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PSERVICEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM CMS_SERVICE
    WHERE SERVICEID = PSERVICEID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service not found';
    END IF;

    IF PSERVNAME IS NULL OR TRIM(PSERVNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service Name is required';
    END IF;

    IF PDEFSTART IS NULL OR PDEFEND IS NULL OR PDEFEND <= PDEFSTART THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service end time must be after start time';
    END IF;

    IF PVALIDUNTIL IS NOT NULL AND PVALIDFROM IS NOT NULL AND PVALIDUNTIL < PVALIDFROM THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service valid until date must be greater than or equal to valid from date';
    END IF;

    IF PSTATUS IS NULL OR PSTATUS NOT IN ('A', 'D', 'EXP', 'BLK') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid service status';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_SERVHIST (SERVICEID, SERVCODE, SERVNAME, DEFSTART, DEFEND, VALIDFROM, VALIDUNTIL, STATUS, CHANGEDBY, CHGREASON)
    SELECT SERVICEID, SERVCODE, SERVNAME, DEFSTART, DEFEND, VALIDFROM, VALIDUNTIL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_SERVICE
    WHERE SERVICEID = PSERVICEID;

    UPDATE CMS_SERVICE
    SET SERVNAME = TRIM(PSERVNAME),
        DEFSTART = PDEFSTART,
        DEFEND = PDEFEND,
        VALIDFROM = PVALIDFROM,
        VALIDUNTIL = PVALIDUNTIL,
        STATUS = PSTATUS,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE SERVICEID = PSERVICEID;

    COMMIT;
END$$

-- v2_module2
-- Added mandatory input, price, flag, and transaction exception validation.
CREATE PROCEDURE CMSADDMENU (
    IN PMENUCODE VARCHAR(20),
    IN PSHORTNAME VARCHAR(30),
    IN PITEMNAME VARCHAR(100),
    IN PITEMDESCR VARCHAR(255),
    IN PPERMPRICE DECIMAL(10,2),
    IN PCONTPRICE DECIMAL(10,2),
    IN PVISPRICE DECIMAL(10,2),
    IN POFFPRICE DECIMAL(10,2),
    IN PISSPECIAL TINYINT,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VMENUITEMID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PMENUCODE IS NULL OR TRIM(PMENUCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Code is required';
    END IF;

    IF PSHORTNAME IS NULL OR TRIM(PSHORTNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Short Name is required';
    END IF;

    IF PITEMNAME IS NULL OR TRIM(PITEMNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Name is required';
    END IF;

    IF PPERMPRICE IS NULL OR PCONTPRICE IS NULL OR PVISPRICE IS NULL OR POFFPRICE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'All menu prices are required';
    END IF;

    IF PPERMPRICE < 0 OR PCONTPRICE < 0 OR PVISPRICE < 0 OR POFFPRICE < 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu prices cannot be negative';
    END IF;

    IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid special item flag';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_MENUITEM (MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, PERMPRICE, CONTPRICE, VISPRICE, OFFPRICE, ISSPECIAL, STATUS, CREATEDBY)
    VALUES (TRIM(PMENUCODE), TRIM(PSHORTNAME), TRIM(PITEMNAME), PITEMDESCR, PPERMPRICE, PCONTPRICE, PVISPRICE, POFFPRICE, COALESCE(PISSPECIAL, 0), 'A', PCREATEDBY);

    SET VMENUITEMID = LAST_INSERT_ID();

    COMMIT;

    SELECT VMENUITEMID AS MENUITEMID;
END$$

-- v2_module2
-- Added price/status validation, history-before-update enforcement, and transaction exception handling.
CREATE PROCEDURE CMSUPDMENU (
    IN PMENUITEMID INT,
    IN PSHORTNAME VARCHAR(30),
    IN PITEMNAME VARCHAR(100),
    IN PITEMDESCR VARCHAR(255),
    IN PPERMPRICE DECIMAL(10,2),
    IN PCONTPRICE DECIMAL(10,2),
    IN PVISPRICE DECIMAL(10,2),
    IN POFFPRICE DECIMAL(10,2),
    IN PISSPECIAL TINYINT,
    IN PSTATUS VARCHAR(20),
    IN PCHANGEDBY INT,
    IN PCHGREASON VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PMENUITEMID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM CMS_MENUITEM
    WHERE MENUITEMID = PMENUITEMID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found';
    END IF;

    IF PSHORTNAME IS NULL OR TRIM(PSHORTNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Short Name is required';
    END IF;

    IF PITEMNAME IS NULL OR TRIM(PITEMNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Name is required';
    END IF;

    IF PPERMPRICE IS NULL OR PCONTPRICE IS NULL OR PVISPRICE IS NULL OR POFFPRICE IS NULL
       OR PPERMPRICE < 0 OR PCONTPRICE < 0 OR PVISPRICE < 0 OR POFFPRICE < 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu prices must be zero or greater';
    END IF;

    IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid special item flag';
    END IF;

    IF PSTATUS IS NULL OR PSTATUS NOT IN ('A', 'D', 'EXP', 'BLK') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid menu item status';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_MENUHIST (MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, PERMPRICE, CONTPRICE, VISPRICE, OFFPRICE, ISSPECIAL, STATUS, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, PERMPRICE, CONTPRICE, VISPRICE, OFFPRICE, ISSPECIAL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM
    WHERE MENUITEMID = PMENUITEMID;

    UPDATE CMS_MENUITEM
    SET SHORTNAME = TRIM(PSHORTNAME),
        ITEMNAME = TRIM(PITEMNAME),
        ITEMDESCR = PITEMDESCR,
        PERMPRICE = PPERMPRICE,
        CONTPRICE = PCONTPRICE,
        VISPRICE = PVISPRICE,
        OFFPRICE = POFFPRICE,
        ISSPECIAL = COALESCE(PISSPECIAL, 0),
        STATUS = PSTATUS,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE MENUITEMID = PMENUITEMID;

    COMMIT;
END$$

-- v2_module2
-- Added service existence, active service, mandatory input, time range, and transaction exception validation.
CREATE PROCEDURE CMSADDSLOT (
    IN PSERVICEID INT,
    IN PSERVDATE DATE,
    IN PSTARTTIME TIME,
    IN PENDTIME TIME,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VSERVSTATUS VARCHAR(20);
    DECLARE VVALIDFROM DATE;
    DECLARE VVALIDUNTIL DATE;
    DECLARE VDAYSLOTID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PSERVICEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required';
    END IF;

    IF PSERVDATE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service Date is required';
    END IF;

    IF PSTARTTIME IS NULL OR PENDTIME IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Slot start and end time are required';
    END IF;

    IF PENDTIME <= PSTARTTIME THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Slot end time must be after start time';
    END IF;

    SELECT STATUS, VALIDFROM, VALIDUNTIL
    INTO VSERVSTATUS, VVALIDFROM, VVALIDUNTIL
    FROM CMS_SERVICE
    WHERE SERVICEID = PSERVICEID;

    IF VSERVSTATUS IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service not found';
    END IF;

    IF VSERVSTATUS <> 'A' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service must be active';
    END IF;

    IF (VVALIDFROM IS NOT NULL AND PSERVDATE < VVALIDFROM)
       OR (VVALIDUNTIL IS NOT NULL AND PSERVDATE > VVALIDUNTIL) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service date is outside service validity period';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_DAYSLOT (SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CREATEDBY)
    VALUES (PSERVICEID, PSERVDATE, PSTARTTIME, PENDTIME, 'A', PCREATEDBY);

    SET VDAYSLOTID = LAST_INSERT_ID();

    COMMIT;

    SELECT VDAYSLOTID AS DAYSLOTID;
END$$

-- v2_module2
-- Added status validation, history-before-update enforcement, and transaction exception handling.
CREATE PROCEDURE CMSUPDSLOT (
    IN PDAYSLOTID INT,
    IN PSTARTTIME TIME,
    IN PENDTIME TIME,
    IN PSTATUS VARCHAR(20),
    IN PCHANGEDBY INT,
    IN PCHGREASON VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PDAYSLOTID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT
    FROM CMS_DAYSLOT
    WHERE DAYSLOTID = PDAYSLOTID;

    IF VCOUNT = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found';
    END IF;

    IF PSTARTTIME IS NULL OR PENDTIME IS NULL OR PENDTIME <= PSTARTTIME THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Slot end time must be after start time';
    END IF;

    IF PSTATUS IS NULL OR PSTATUS NOT IN ('A', 'D', 'EXP', 'BLK') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid day slot status';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_SLOTHIST (DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CHANGEDBY, CHGREASON)
    SELECT DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_DAYSLOT
    WHERE DAYSLOTID = PDAYSLOTID;

    UPDATE CMS_DAYSLOT
    SET STARTTIME = PSTARTTIME,
        ENDTIME = PENDTIME,
        STATUS = PSTATUS,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE DAYSLOTID = PDAYSLOTID;

    COMMIT;
END$$

-- v2_module2
-- Added day-menu business validation and atomic DMENUNO generation within this transaction.
CREATE PROCEDURE CMSADDDMENU (
    IN PDAYSLOTID INT,
    IN PMENUITEMID INT,
    IN PISSPECIAL TINYINT,
    IN PISPREBOOK TINYINT,
    IN PISWALKIN TINYINT,
    IN PISKIOSK TINYINT,
    IN PAVAILQTY INT,
    IN PMAXQTY INT,
    IN PBOOKSTART DATETIME,
    IN PBOOKEND DATETIME,
    IN PCANCELAT DATETIME,
    IN PADDEDBY INT,
    IN PREMARKS VARCHAR(255)
)
BEGIN
    DECLARE VDMENUNO VARCHAR(30);
    DECLARE VDAYMENUID INT;
    DECLARE VSLOTSTATUS VARCHAR(20);
    DECLARE VMENUSTATUS VARCHAR(20);
    DECLARE VSERVDATE DATE;
    DECLARE VSTARTTIME TIME;
    DECLARE VEXISTS INT DEFAULT 0;
    DECLARE VPREFIX VARCHAR(5);
    DECLARE VLASTNO BIGINT;
    DECLARE VNEWNO BIGINT;
    DECLARE VYEAR CHAR(4);
    DECLARE VLENGTH INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PDAYSLOTID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required';
    END IF;

    IF PMENUITEMID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required';
    END IF;

    IF PBOOKSTART IS NULL OR PBOOKEND IS NULL OR PCANCELAT IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking start, booking end, and cancellation deadline are required';
    END IF;

    IF PBOOKEND <= PBOOKSTART THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking end must be after booking start';
    END IF;

    IF PAVAILQTY IS NULL OR PAVAILQTY < 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Available quantity must be zero or greater';
    END IF;

    IF PMAXQTY IS NULL OR PMAXQTY < 1 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Maximum quantity must be at least one';
    END IF;

    IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1)
       OR COALESCE(PISPREBOOK, 1) NOT IN (0, 1)
       OR COALESCE(PISWALKIN, 1) NOT IN (0, 1)
       OR COALESCE(PISKIOSK, 1) NOT IN (0, 1) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid day menu channel flag';
    END IF;

    SELECT STATUS, SERVDATE, STARTTIME
    INTO VSLOTSTATUS, VSERVDATE, VSTARTTIME
    FROM CMS_DAYSLOT
    WHERE DAYSLOTID = PDAYSLOTID;

    IF VSLOTSTATUS IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found';
    END IF;

    IF VSLOTSTATUS <> 'A' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot must be active';
    END IF;

    SELECT STATUS
    INTO VMENUSTATUS
    FROM CMS_MENUITEM
    WHERE MENUITEMID = PMENUITEMID;

    IF VMENUSTATUS IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found';
    END IF;

    IF VMENUSTATUS <> 'A' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item must be active';
    END IF;

    IF PCANCELAT > TIMESTAMP(VSERVDATE, VSTARTTIME) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cancellation deadline must be before service begins';
    END IF;

    SELECT COUNT(*) INTO VEXISTS
    FROM CMS_DAYMENU
    WHERE DAYSLOTID = PDAYSLOTID
      AND MENUITEMID = PMENUITEMID;

    IF VEXISTS > 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item is already assigned to this day slot';
    END IF;

    START TRANSACTION;

    SELECT PREFIXCHAR, LASTNO, ITEMLEN
    INTO VPREFIX, VLASTNO, VLENGTH
    FROM CMS_AUTONOS
    WHERE TBLNAME = 'CMS_DAYMENU'
      AND DATAITEM = 'DMENUNO'
      AND STATUS = 'A'
    FOR UPDATE;

    IF VPREFIX IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Active day menu autonumber configuration not found';
    END IF;

    SET VNEWNO = VLASTNO + 1;
    SET VYEAR = DATE_FORMAT(CURRENT_DATE, '%Y');
    SET VDMENUNO = CONCAT(VPREFIX, VYEAR, LPAD(VNEWNO, GREATEST(VLENGTH - LENGTH(VPREFIX) - 4, 1), '0'));

    UPDATE CMS_AUTONOS
    SET LASTNO = VNEWNO,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE TBLNAME = 'CMS_DAYMENU'
      AND DATAITEM = 'DMENUNO';

    INSERT INTO CMS_DAYMENU (DMENUNO, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISWALKIN, ISKIOSK, AVAILQTY, MAXQTY, BOOKSTART, BOOKEND, CANCELAT, APPRSTATUS, ADDEDBY, REMARKS)
    VALUES (VDMENUNO, PDAYSLOTID, PMENUITEMID, COALESCE(PISSPECIAL, 0), COALESCE(PISPREBOOK, 1), COALESCE(PISWALKIN, 1), COALESCE(PISKIOSK, 1), PAVAILQTY, PMAXQTY, PBOOKSTART, PBOOKEND, PCANCELAT, 'P', PADDEDBY, PREMARKS);

    SET VDAYMENUID = LAST_INSERT_ID();

    COMMIT;

    SELECT VDAYMENUID AS DAYMENUID, VDMENUNO AS DMENUNO;
END$$

-- v2_module2
-- Added approval status validation, processed-record protection, history capture, and transaction exception handling.
CREATE PROCEDURE CMSAPPDMENU (
    IN PDAYMENUID INT,
    IN PAPPRSTATUS VARCHAR(20),
    IN PAPPROVEDBY INT,
    IN PREMARKS VARCHAR(255)
)
BEGIN
    DECLARE VCURRENTSTATUS VARCHAR(20);

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PDAYMENUID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required';
    END IF;

    IF PAPPRSTATUS IS NULL OR PAPPRSTATUS NOT IN ('APP', 'REJ') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Approval status must be APP or REJ';
    END IF;

    SELECT APPRSTATUS
    INTO VCURRENTSTATUS
    FROM CMS_DAYMENU
    WHERE DAYMENUID = PDAYMENUID;

    IF VCURRENTSTATUS IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found';
    END IF;

    IF VCURRENTSTATUS <> 'P' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu has already been processed';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_DMENUHIS (DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISWALKIN, ISKIOSK, AVAILQTY, MAXQTY, BOOKSTART, BOOKEND, CANCELAT, APPRSTATUS, CHANGEDBY, CHGREASON, REMARKS)
    SELECT DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISWALKIN, ISKIOSK, AVAILQTY, MAXQTY, BOOKSTART, BOOKEND, CANCELAT, APPRSTATUS, PAPPROVEDBY, 'Approval status changed', REMARKS
    FROM CMS_DAYMENU
    WHERE DAYMENUID = PDAYMENUID;

    UPDATE CMS_DAYMENU
    SET APPRSTATUS = PAPPRSTATUS,
        APPROVEDBY = PAPPROVEDBY,
        APPROVEDAT = CURRENT_TIMESTAMP,
        REMARKS = PREMARKS,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE DAYMENUID = PDAYMENUID;

    COMMIT;
END$$

-- v2_module2
-- Modified to return active services, active slots, active items, approved menus, and currently bookable windows.
CREATE PROCEDURE CMSVIEWMENU (
    IN PSERVDATE DATE,
    IN PCTYPECODE VARCHAR(20)
)
BEGIN
    SELECT
        DS.DAYSLOTID,
        S.SERVCODE,
        S.SERVNAME,
        DS.SERVDATE,
        DS.STARTTIME,
        DS.ENDTIME,
        DM.DAYMENUID,
        DM.DMENUNO,
        MI.MENUCODE,
        MI.ITEMNAME,
        MI.ITEMDESCR,
        CASE
            WHEN PCTYPECODE IN ('PERMANENT', 'OTHERCENTRE') THEN MI.PERMPRICE
            WHEN PCTYPECODE = 'CONTRACT' THEN MI.CONTPRICE
            WHEN PCTYPECODE = 'VISITOR' THEN MI.VISPRICE
            ELSE MI.VISPRICE
        END AS DISPLAYPRICE,
        DM.AVAILQTY,
        DM.MAXQTY,
        DM.BOOKSTART,
        DM.BOOKEND,
        DM.CANCELAT
    FROM CMS_DAYMENU DM
    JOIN CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
    JOIN CMS_SERVICE S ON S.SERVICEID = DS.SERVICEID
    JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    WHERE DS.SERVDATE = PSERVDATE
      AND DM.APPRSTATUS = 'APP'
      AND DS.STATUS = 'A'
      AND S.STATUS = 'A'
      AND MI.STATUS = 'A'
      AND CURRENT_TIMESTAMP BETWEEN DM.BOOKSTART AND DM.BOOKEND
    ORDER BY DS.STARTTIME, S.SERVNAME, MI.ITEMNAME;
END$$

DELIMITER ;
