/* ============================================================
   MODULE 2: CANTEEN MENU & SERVICE MANAGEMENT
   STORED PROCEDURES — ENTERPRISE REDESIGN v2

   Aligned with: 02_MENU_SERVICE_SCHEMA.sql (Revised v3)

   KEY CHANGES FROM v1:
   1. CMSADDSERV / CMSUPDSERV now include CANTEENID
   2. CMSADDMENUITEM / CMSUPDMENUITEM no longer have price
      columns — prices live in CMS_ITEMPRICE + CMS_ITEMPRICEDT
   3. New CMS_ITEMPRICE / CMS_ITEMPRICEDT procedures
   6. CMS_DMENUHIS renamed to CMS_DMENUHIST
   7. CMSVIEWMENU rewritten for new pricing model + CANTEENID
   8. New CMS_MENUTPL / CMS_MENUTPLDT procedures
   9. New CMS_APPRINST / CMS_APPRSTEP procedures
   10. Business procedures: CMSAPPLYMENUTPL, CMSPREPAREMENU
   ============================================================ */

USE cms_db;

/* --- Drop all existing procedures --- */
DROP PROCEDURE IF EXISTS CMSADDSERV;
DROP PROCEDURE IF EXISTS CMSUPDSERV;
DROP PROCEDURE IF EXISTS CMSGETSERV;
DROP PROCEDURE IF EXISTS CMSLISTSERV;
DROP PROCEDURE IF EXISTS CMSACTSERV;
DROP PROCEDURE IF EXISTS CMSDEACTSERV;
DROP PROCEDURE IF EXISTS CMSSEARCHSERV;

DROP PROCEDURE IF EXISTS CMSADDMENU;
DROP PROCEDURE IF EXISTS CMSUPDMENU;

DROP PROCEDURE IF EXISTS CMSADDMENUITEM;
DROP PROCEDURE IF EXISTS CMSUPDMENUITEM;
DROP PROCEDURE IF EXISTS CMSGETMENUITEM;
DROP PROCEDURE IF EXISTS CMSLISTMENUITEM;
DROP PROCEDURE IF EXISTS CMSSEARCHMENUITEM;
DROP PROCEDURE IF EXISTS CMSACTMENUITEM;
DROP PROCEDURE IF EXISTS CMSDEACTMENUITEM;

DROP PROCEDURE IF EXISTS CMSADDITEMPRICE;
DROP PROCEDURE IF EXISTS CMSGETITEMPRICE;
DROP PROCEDURE IF EXISTS CMSGETITEMPRICEDT;
DROP PROCEDURE IF EXISTS CMSLISTITEMPRICE;
DROP PROCEDURE IF EXISTS CMSDEACTITEMPRICE;


DROP PROCEDURE IF EXISTS CMSADDSLOT;
DROP PROCEDURE IF EXISTS CMSUPDSLOT;
DROP PROCEDURE IF EXISTS CMSGETSLOT;
DROP PROCEDURE IF EXISTS CMSLISTSLOT;
DROP PROCEDURE IF EXISTS CMSACTSLOT;
DROP PROCEDURE IF EXISTS CMSDEACTSLOT;

DROP PROCEDURE IF EXISTS CMSADDDMENU;
DROP PROCEDURE IF EXISTS CMSUPDDDMENU;
DROP PROCEDURE IF EXISTS CMSGETDMENU;
DROP PROCEDURE IF EXISTS CMSLISTDMENU;
DROP PROCEDURE IF EXISTS CMSAPPDMENU;
DROP PROCEDURE IF EXISTS CMSREJDMENU;

DROP PROCEDURE IF EXISTS CMSACTDMENU;
DROP PROCEDURE IF EXISTS CMSDEACTDMENU;
DROP PROCEDURE IF EXISTS CMSSOLDOUTDMENU;

DROP PROCEDURE IF EXISTS CMSADDMENUTPL;
DROP PROCEDURE IF EXISTS CMSUPDMENUTPL;
DROP PROCEDURE IF EXISTS CMSGETMENUTPL;
DROP PROCEDURE IF EXISTS CMSLISTMENUTPL;
DROP PROCEDURE IF EXISTS CMSDEACTMENUTPL;
DROP PROCEDURE IF EXISTS CMSADDMENUTPLDT;
DROP PROCEDURE IF EXISTS CMSREMOVEMENUTPLDT;
DROP PROCEDURE IF EXISTS CMSLISTMENUTPLDT;
DROP PROCEDURE IF EXISTS CMSAPPLYMENUTPL;

DROP PROCEDURE IF EXISTS CMSADDAPPRINST;
DROP PROCEDURE IF EXISTS CMSGETAPPRINST;
DROP PROCEDURE IF EXISTS CMSLISTAPPRINST;
DROP PROCEDURE IF EXISTS CMSDECIDEAPPRSTEP;
DROP PROCEDURE IF EXISTS CMSCANCELAPPRINST;

DROP PROCEDURE IF EXISTS CMSVIEWMENU;


DELIMITER $$


/* ============================================================
   CMS_SERVICE — Canteen-scoped Service Catalog
   ============================================================ */

CREATE PROCEDURE CMSADDSERV (
    IN PCANTEENID INT,
    IN PSERVCODE  VARCHAR(20),
    IN PSERVNAME  VARCHAR(80),
    IN PDEFSTART  TIME,
    IN PDEFEND    TIME,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VSERVICEID INT;
    DECLARE VCANSTATUS VARCHAR(20);

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCANTEENID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required';
    END IF;
    SELECT STATUS INTO VCANSTATUS FROM CMS_CANTEEN WHERE CANTEENID = PCANTEENID;
    IF VCANSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen not found'; END IF;
    IF VCANSTATUS <> 'A' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen must be active'; END IF;

    IF PSERVCODE IS NULL OR TRIM(PSERVCODE) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service Code is required';
    END IF;
    IF PSERVNAME IS NULL OR TRIM(PSERVNAME) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service Name is required';
    END IF;
    IF PDEFSTART IS NULL OR PDEFEND IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service default start and end time are required';
    END IF;
    IF PDEFEND <= PDEFSTART THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service end time must be after start time';
    END IF;
    IF PCREATEDBY IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Created By is required';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_SERVICE (CANTEENID, SERVCODE, SERVNAME, DEFSTART, DEFEND, STATUS, CREATEDBY)
    VALUES (PCANTEENID, TRIM(PSERVCODE), TRIM(PSERVNAME), PDEFSTART, PDEFEND, 'A', PCREATEDBY);
    SET VSERVICEID = LAST_INSERT_ID();
    COMMIT;

    SELECT VSERVICEID AS SERVICEID;
END$$


CREATE PROCEDURE CMSUPDSERV (
    IN PSERVICEID INT,
    IN PSERVNAME  VARCHAR(80),
    IN PDEFSTART  TIME,
    IN PDEFEND    TIME,
    IN PSTATUS    VARCHAR(20),
    IN PCHANGEDBY INT,
    IN PCHGREASON VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service not found'; END IF;
    IF PSERVNAME IS NULL OR TRIM(PSERVNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service Name is required'; END IF;
    IF PDEFSTART IS NULL OR PDEFEND IS NULL OR PDEFEND <= PDEFSTART THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service end time must be after start time';
    END IF;
    IF PSTATUS IS NULL OR PSTATUS NOT IN ('A', 'D') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid service status';
    END IF;

    START TRANSACTION;

    -- History table has VALIDFROM/VALIDUNTIL columns (nullable) that no
    -- longer exist on CMS_SERVICE itself; they are simply left NULL here.
    INSERT INTO CMS_SERVHIST (SERVICEID, CANTEENID, SERVCODE, SERVNAME, DEFSTART, DEFEND, VALIDFROM, VALIDUNTIL, STATUS, CHANGEDBY, CHGREASON)
    SELECT SERVICEID, CANTEENID, SERVCODE, SERVNAME, DEFSTART, DEFEND, NULL, NULL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;

    UPDATE CMS_SERVICE
    SET    SERVNAME  = TRIM(PSERVNAME),
           DEFSTART  = PDEFSTART,
           DEFEND    = PDEFEND,
           STATUS    = PSTATUS,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  SERVICEID = PSERVICEID;

    COMMIT;
    SELECT PSERVICEID AS SERVICEID;
END$$


CREATE PROCEDURE CMSGETSERV (IN PSERVICEID INT)
BEGIN
    SELECT S.SERVICEID, S.CANTEENID, C.CANTEENCODE, C.CANTEENNAME,
           S.SERVCODE, S.SERVNAME, S.DEFSTART, S.DEFEND,
           S.STATUS, S.CREATEDBY, S.CREATEDAT, S.UPDATEDAT
    FROM   CMS_SERVICE S
    JOIN   CMS_CANTEEN C ON C.CANTEENID = S.CANTEENID
    WHERE  S.SERVICEID = PSERVICEID;
END$$


CREATE PROCEDURE CMSLISTSERV (IN PCANTEENID INT)
BEGIN
    SELECT S.SERVICEID, S.CANTEENID, C.CANTEENCODE, C.CANTEENNAME,
           S.SERVCODE, S.SERVNAME, S.DEFSTART, S.DEFEND,
           S.STATUS, S.CREATEDBY, S.CREATEDAT, S.UPDATEDAT
    FROM   CMS_SERVICE S
    JOIN   CMS_CANTEEN C ON C.CANTEENID = S.CANTEENID
    WHERE  (PCANTEENID IS NULL OR S.CANTEENID = PCANTEENID)
    ORDER BY C.CANTEENNAME, S.DEFSTART;
END$$


CREATE PROCEDURE CMSACTSERV (IN PSERVICEID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service not found'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_SERVHIST (SERVICEID, CANTEENID, SERVCODE, SERVNAME, DEFSTART, DEFEND, VALIDFROM, VALIDUNTIL, STATUS, CHANGEDBY, CHGREASON)
    SELECT SERVICEID, CANTEENID, SERVCODE, SERVNAME, DEFSTART, DEFEND, NULL, NULL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;
    UPDATE CMS_SERVICE SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE SERVICEID = PSERVICEID;
    COMMIT;
    SELECT PSERVICEID AS SERVICEID;
END$$


CREATE PROCEDURE CMSDEACTSERV (IN PSERVICEID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service not found'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_SERVHIST (SERVICEID, CANTEENID, SERVCODE, SERVNAME, DEFSTART, DEFEND, VALIDFROM, VALIDUNTIL, STATUS, CHANGEDBY, CHGREASON)
    SELECT SERVICEID, CANTEENID, SERVCODE, SERVNAME, DEFSTART, DEFEND, NULL, NULL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;
    UPDATE CMS_SERVICE SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE SERVICEID = PSERVICEID;
    COMMIT;
    SELECT PSERVICEID AS SERVICEID;
END$$



CREATE PROCEDURE CMSSEARCHSERV (IN PKEYWORD VARCHAR(80))
BEGIN
    SELECT S.SERVICEID, S.CANTEENID, C.CANTEENNAME,
           S.SERVCODE, S.SERVNAME, S.STATUS
    FROM   CMS_SERVICE S
    JOIN   CMS_CANTEEN C ON C.CANTEENID = S.CANTEENID
    WHERE  (S.SERVCODE LIKE CONCAT('%', PKEYWORD, '%')
       OR   S.SERVNAME LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY S.SERVNAME;
END$$





/* ============================================================
   CMS_MENUITEM — Shared Menu Item Catalog (NO price columns)
   ============================================================ */

CREATE PROCEDURE CMSADDMENUITEM (
    IN PMENUCODE  VARCHAR(20),
    IN PSHORTNAME VARCHAR(30),
    IN PITEMNAME  VARCHAR(100),
    IN PITEMDESCR VARCHAR(255),
    IN PISSPECIAL TINYINT,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VMENUITEMID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUCODE IS NULL OR TRIM(PMENUCODE) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Code is required'; END IF;
    IF PSHORTNAME IS NULL OR TRIM(PSHORTNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Short Name is required'; END IF;
    IF PITEMNAME IS NULL OR TRIM(PITEMNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Name is required'; END IF;
    IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid special item flag'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUITEM (MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, CREATEDBY)
    VALUES (TRIM(PMENUCODE), TRIM(PSHORTNAME), TRIM(PITEMNAME), PITEMDESCR, COALESCE(PISSPECIAL, 0), 'A', PCREATEDBY);
    SET VMENUITEMID = LAST_INSERT_ID();
    COMMIT;

    SELECT VMENUITEMID AS MENUITEMID;
END$$


CREATE PROCEDURE CMSUPDMENUITEM (
    IN PMENUITEMID INT,
    IN PSHORTNAME  VARCHAR(30),
    IN PITEMNAME   VARCHAR(100),
    IN PITEMDESCR  VARCHAR(255),
    IN PISSPECIAL  TINYINT,
    IN PSTATUS     VARCHAR(20),
    IN PCHANGEDBY  INT,
    IN PCHGREASON  VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;
    IF PSHORTNAME IS NULL OR TRIM(PSHORTNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Short Name is required'; END IF;
    IF PITEMNAME IS NULL OR TRIM(PITEMNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Name is required'; END IF;
    IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid special item flag'; END IF;
    IF PSTATUS IS NULL OR PSTATUS NOT IN ('A', 'D', 'EXP', 'BLK') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid menu item status'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_MENUHIST (MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;

    UPDATE CMS_MENUITEM
    SET    SHORTNAME = TRIM(PSHORTNAME),
           ITEMNAME  = TRIM(PITEMNAME),
           ITEMDESCR = PITEMDESCR,
           ISSPECIAL = COALESCE(PISSPECIAL, ISSPECIAL),
           STATUS    = PSTATUS,
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  MENUITEMID = PMENUITEMID;
    COMMIT;

    SELECT PMENUITEMID AS MENUITEMID;
END$$


CREATE PROCEDURE CMSGETMENUITEM (IN PMENUITEMID INT)
BEGIN
    SELECT MI.MENUITEMID, MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           MI.ITEMDESCR, MI.ISSPECIAL, MI.STATUS,
           MI.CREATEDBY, MI.CREATEDAT, MI.UPDATEDAT
    FROM   CMS_MENUITEM MI
    WHERE  MI.MENUITEMID = PMENUITEMID;
END$$


CREATE PROCEDURE CMSLISTMENUITEM (
    IN PISSPECIAL TINYINT,
    IN PSTATUS    VARCHAR(20)
)
BEGIN
    SELECT MI.MENUITEMID, MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           MI.ITEMDESCR, MI.ISSPECIAL, MI.STATUS,
           MI.CREATEDBY, MI.CREATEDAT, MI.UPDATEDAT
    FROM   CMS_MENUITEM MI
    WHERE  (PISSPECIAL IS NULL OR MI.ISSPECIAL = PISSPECIAL)
      AND  (PSTATUS    IS NULL OR MI.STATUS    = PSTATUS)
    ORDER BY MI.ITEMNAME;
END$$


CREATE PROCEDURE CMSSEARCHMENUITEM (IN PKEYWORD VARCHAR(100))
BEGIN
    SELECT MI.MENUITEMID, MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           MI.ISSPECIAL, MI.STATUS
    FROM   CMS_MENUITEM MI
    WHERE  (MI.MENUCODE  LIKE CONCAT('%', PKEYWORD, '%')
       OR   MI.SHORTNAME LIKE CONCAT('%', PKEYWORD, '%')
       OR   MI.ITEMNAME  LIKE CONCAT('%', PKEYWORD, '%'))
    ORDER BY MI.ITEMNAME;
END$$


CREATE PROCEDURE CMSACTMENUITEM (IN PMENUITEMID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUHIST (MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    UPDATE CMS_MENUITEM SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE MENUITEMID = PMENUITEMID;
    COMMIT;
    SELECT PMENUITEMID AS MENUITEMID;
END$$


CREATE PROCEDURE CMSDEACTMENUITEM (IN PMENUITEMID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUHIST (MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, CHANGEDBY, CHGREASON)
    SELECT MENUITEMID, MENUCODE, SHORTNAME, ITEMNAME, ITEMDESCR, ISSPECIAL, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    UPDATE CMS_MENUITEM SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE MENUITEMID = PMENUITEMID;
    COMMIT;
    SELECT PMENUITEMID AS MENUITEMID;
END$$


/* ============================================================
   CMS_ITEMPRICE + CMS_ITEMPRICEDT — Pricing Subsystem

   CMSADDITEMPRICE creates a price band header + one detail
   row per customer type in a single JSON array.

   PPRICEJSON shape:
     [{"CTYPECODE":"PERMANENT","PRICE":60.00},
      {"CTYPECODE":"CONTRACT","PRICE":80.00}, ...]
   ============================================================ */

CREATE PROCEDURE CMSADDITEMPRICE (
    IN PMENUITEMID INT,
    IN PEFFFROM    DATE,
    IN PPRICEJSON  JSON,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VITEMPRICEID INT;
    DECLARE VCOUNT       INT DEFAULT 0;
    DECLARE VINVALID     INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    IF PEFFFROM IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Effective From date is required'; END IF;
    IF PPRICEJSON IS NULL OR JSON_TYPE(PPRICEJSON) <> 'ARRAY' OR JSON_LENGTH(PPRICEJSON) = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'At least one price entry is required';
    END IF;

    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID AND STATUS = 'A';
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Active menu item not found'; END IF;

    -- Validate all customer type codes exist
    SELECT COUNT(*) INTO VINVALID
    FROM JSON_TABLE(PPRICEJSON, '$[*]' COLUMNS (
        CTYPECODE VARCHAR(20) PATH '$.CTYPECODE',
        PRICE DECIMAL(10,2) PATH '$.PRICE'
    )) JT
    LEFT JOIN CMS_CUSTTYPE CT ON CT.CTYPECODE = JT.CTYPECODE AND CT.ISACTIVE = 1
    WHERE CT.CTYPEID IS NULL OR JT.PRICE IS NULL OR JT.PRICE < 0;

    IF VINVALID > 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'One or more price entries have invalid customer type or negative price';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_ITEMPRICE (MENUITEMID, EFFFROM, STATUS, CREATEDBY)
    VALUES (PMENUITEMID, PEFFFROM, 'A', PCREATEDBY);
    SET VITEMPRICEID = LAST_INSERT_ID();

    INSERT INTO CMS_ITEMPRICEDT (ITEMPRICEID, CTYPECODE, PRICE)
    SELECT VITEMPRICEID, JT.CTYPECODE, JT.PRICE
    FROM JSON_TABLE(PPRICEJSON, '$[*]' COLUMNS (
        CTYPECODE VARCHAR(20) PATH '$.CTYPECODE',
        PRICE DECIMAL(10,2) PATH '$.PRICE'
    )) JT;

    COMMIT;
    SELECT VITEMPRICEID AS ITEMPRICEID;
END$$


CREATE PROCEDURE CMSGETITEMPRICE (
    IN PMENUITEMID  INT,
    IN PSERVICEDATE DATE
)
BEGIN
    DECLARE VEFFDATE DATE;

    SET VEFFDATE = COALESCE(PSERVICEDATE, CURRENT_DATE);

    SELECT IP.ITEMPRICEID, IP.MENUITEMID, IP.EFFFROM, IP.STATUS,
           IPD.ITEMPRICEDTID, IPD.CTYPECODE, CT.CTYPENAME, IPD.PRICE
    FROM   CMS_ITEMPRICE IP
    JOIN   CMS_ITEMPRICEDT IPD ON IPD.ITEMPRICEID = IP.ITEMPRICEID
    JOIN   CMS_CUSTTYPE CT     ON CT.CTYPECODE    = IPD.CTYPECODE
    WHERE  IP.MENUITEMID = PMENUITEMID
      AND  IP.EFFFROM   <= VEFFDATE
      AND  IP.STATUS     = 'A'
      AND  IP.ITEMPRICEID = (
          SELECT IP2.ITEMPRICEID
          FROM   CMS_ITEMPRICE IP2
          WHERE  IP2.MENUITEMID = PMENUITEMID
            AND  IP2.EFFFROM  <= VEFFDATE
            AND  IP2.STATUS    = 'A'
          ORDER BY IP2.EFFFROM DESC
          LIMIT 1
      )
    ORDER BY IPD.CTYPECODE;
END$$


CREATE PROCEDURE CMSGETITEMPRICEDT (
    IN PMENUITEMID  INT,
    IN PCTYPECODE   VARCHAR(20),
    IN PSERVICEDATE DATE
)
BEGIN
    SELECT IPD.PRICE
    FROM   CMS_ITEMPRICE IP
    JOIN   CMS_ITEMPRICEDT IPD ON IPD.ITEMPRICEID = IP.ITEMPRICEID
    WHERE  IP.MENUITEMID  = PMENUITEMID
      AND  IPD.CTYPECODE  = PCTYPECODE
      AND  IP.EFFFROM    <= COALESCE(PSERVICEDATE, CURRENT_DATE)
      AND  IP.STATUS      = 'A'
    ORDER BY IP.EFFFROM DESC
    LIMIT 1;
END$$


CREATE PROCEDURE CMSLISTITEMPRICE (IN PMENUITEMID INT)
BEGIN
    SELECT IP.ITEMPRICEID, IP.MENUITEMID, MI.MENUCODE, MI.ITEMNAME,
           IP.EFFFROM, IP.STATUS, IP.CREATEDBY, IP.CREATEDAT
    FROM   CMS_ITEMPRICE IP
    JOIN   CMS_MENUITEM MI ON MI.MENUITEMID = IP.MENUITEMID
    WHERE  IP.MENUITEMID = PMENUITEMID
    ORDER BY IP.EFFFROM DESC;
END$$


CREATE PROCEDURE CMSDEACTITEMPRICE (IN PITEMPRICEID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE VEFFFROM DATE;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PITEMPRICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Item Price ID is required'; END IF;
    SELECT COUNT(*), EFFFROM INTO VCOUNT, VEFFFROM FROM CMS_ITEMPRICE WHERE ITEMPRICEID = PITEMPRICEID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Price band not found'; END IF;
    IF VEFFFROM <= CURRENT_DATE THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot withdraw a price band that is already effective'; END IF;

    START TRANSACTION;
    UPDATE CMS_ITEMPRICE SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE ITEMPRICEID = PITEMPRICEID;
    COMMIT;
    SELECT PITEMPRICEID AS ITEMPRICEID;
END$$

/* ============================================================
   CMS_DAYSLOT — Dated Service Instance
   ============================================================ */

CREATE PROCEDURE CMSADDSLOT (
    IN PSERVICEID INT,
    IN PSERVDATE  DATE,
    IN PSTARTTIME TIME,
    IN PENDTIME   TIME,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VSERVSTATUS VARCHAR(20);
    DECLARE VDAYSLOTID  INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required'; END IF;
    IF PSERVDATE IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service Date is required'; END IF;
    IF PSTARTTIME IS NULL OR PENDTIME IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Slot start and end time are required'; END IF;
    IF PENDTIME <= PSTARTTIME THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Slot end time must be after start time'; END IF;

    SELECT STATUS INTO VSERVSTATUS
    FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;
    IF VSERVSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service not found'; END IF;
    IF VSERVSTATUS <> 'A' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service must be active'; END IF;
    -- NOTE: CMS_SERVICE no longer has VALIDFROM/VALIDUNTIL, so the
    -- service-validity-window check has been removed here.

    START TRANSACTION;
    INSERT INTO CMS_DAYSLOT (SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CREATEDBY)
    VALUES (PSERVICEID, PSERVDATE, PSTARTTIME, PENDTIME, 'A', PCREATEDBY);
    SET VDAYSLOTID = LAST_INSERT_ID();
    COMMIT;

    SELECT VDAYSLOTID AS DAYSLOTID;
END$$


CREATE PROCEDURE CMSUPDSLOT (
    IN PDAYSLOTID INT,
    IN PSTARTTIME TIME,
    IN PENDTIME   TIME,
    IN PSTATUS    VARCHAR(20),
    IN PCHANGEDBY INT,
    IN PCHGREASON VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PDAYSLOTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
    IF PSTARTTIME IS NULL OR PENDTIME IS NULL OR PENDTIME <= PSTARTTIME THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Slot end time must be after start time';
    END IF;
    IF PSTATUS IS NULL OR PSTATUS NOT IN ('A', 'D', 'EXP', 'BLK') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid day slot status';
    END IF;

    START TRANSACTION;
    INSERT INTO CMS_SLOTHIST (DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CHANGEDBY, CHGREASON)
    SELECT DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, PCHANGEDBY, PCHGREASON
    FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;

    UPDATE CMS_DAYSLOT
    SET    STARTTIME = PSTARTTIME, ENDTIME = PENDTIME, STATUS = PSTATUS, UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  DAYSLOTID = PDAYSLOTID;
    COMMIT;

    SELECT PDAYSLOTID AS DAYSLOTID;
END$$


CREATE PROCEDURE CMSGETSLOT (IN PDAYSLOTID INT)
BEGIN
    SELECT DS.DAYSLOTID, DS.SERVICEID, S.SERVCODE, S.SERVNAME,
           S.CANTEENID, C.CANTEENNAME,
           DS.SERVDATE, DS.STARTTIME, DS.ENDTIME, DS.STATUS,
           DS.CREATEDBY, DS.CREATEDAT, DS.UPDATEDAT
    FROM   CMS_DAYSLOT DS
    JOIN   CMS_SERVICE S  ON S.SERVICEID = DS.SERVICEID
    JOIN   CMS_CANTEEN C  ON C.CANTEENID = S.CANTEENID
    WHERE  DS.DAYSLOTID = PDAYSLOTID;
END$$


CREATE PROCEDURE CMSLISTSLOT (
    IN PSERVICEID  INT,
    IN PCANTEENID  INT,
    IN PDATEFROM   DATE,
    IN PDATETO     DATE
)
BEGIN
    SELECT DS.DAYSLOTID, DS.SERVICEID, S.SERVCODE, S.SERVNAME,
           S.CANTEENID, C.CANTEENNAME,
           DS.SERVDATE, DS.STARTTIME, DS.ENDTIME, DS.STATUS,
           DS.CREATEDBY, DS.CREATEDAT
    FROM   CMS_DAYSLOT DS
    JOIN   CMS_SERVICE S  ON S.SERVICEID = DS.SERVICEID
    JOIN   CMS_CANTEEN C  ON C.CANTEENID = S.CANTEENID
    WHERE  (PSERVICEID IS NULL OR DS.SERVICEID  = PSERVICEID)
      AND  (PCANTEENID IS NULL OR S.CANTEENID   = PCANTEENID)
      AND  (PDATEFROM  IS NULL OR DS.SERVDATE   >= PDATEFROM)
      AND  (PDATETO    IS NULL OR DS.SERVDATE   <= PDATETO)
    ORDER BY DS.SERVDATE, DS.STARTTIME;
END$$


CREATE PROCEDURE CMSACTSLOT (IN PDAYSLOTID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PDAYSLOTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
    START TRANSACTION;
    INSERT INTO CMS_SLOTHIST (DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CHANGEDBY, CHGREASON)
    SELECT DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, PCHANGEDBY, PCHGREASON FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    UPDATE CMS_DAYSLOT SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE DAYSLOTID = PDAYSLOTID;
    COMMIT;
    SELECT PDAYSLOTID AS DAYSLOTID;
END$$


CREATE PROCEDURE CMSDEACTSLOT (IN PDAYSLOTID INT, IN PCHANGEDBY INT, IN PCHGREASON VARCHAR(255))
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PDAYSLOTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
    START TRANSACTION;
    INSERT INTO CMS_SLOTHIST (DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CHANGEDBY, CHGREASON)
    SELECT DAYSLOTID, SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, PCHANGEDBY, PCHGREASON FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    UPDATE CMS_DAYSLOT SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE DAYSLOTID = PDAYSLOTID;
    COMMIT;
    SELECT PDAYSLOTID AS DAYSLOTID;
END$$


/* ============================================================
   CMS_DAYMENU — Day Menu Items
   ============================================================ */



    -- NOTE: DMENUNO is now generated directly (LPAD of DAYMENUID) instead of
    -- via CMSGENAUTO, because no CMS_AUTONOS seed row exists for
    -- ('CMS_DAYMENU','DMENUNO') in the current schema/data. If you seed one,
    -- swap the SET VDMENUNO line back to CALL CMSGENAUTO(...).
CREATE PROCEDURE CMSADDDMENU (
    IN PDAYSLOTID  INT,
    IN PMENUITEMID INT,
    IN PISSPECIAL  TINYINT,
    IN PISPREBOOK  TINYINT,
    IN PISKIOSK    TINYINT,
    IN PAVAILQTY   INT,
    IN PMAXQTY     INT,
    IN PBOOKUNTIL   DATETIME,
    IN PCANCELUNTIL DATETIME,
    IN PCREATEDBY  INT,
    IN PREMARKS    VARCHAR(255)
)
BEGIN
    DECLARE VDMENUNO    VARCHAR(20);
    DECLARE VDAYMENUID  INT;
    DECLARE VSLOTSTATUS VARCHAR(20);
    DECLARE VMENUSTATUS VARCHAR(20);
    DECLARE VSERVDATE   DATE;
    DECLARE VSTARTTIME  TIME;
    DECLARE VEXISTS     INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PDAYSLOTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Slot ID is required'; END IF;
    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;
    IF PBOOKUNTIL IS NULL OR PCANCELUNTIL IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking-until and cancel-until deadlines are required';
    END IF;
    IF PCANCELUNTIL > PBOOKUNTIL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cancel-until must be on or before booking-until';
    END IF;
    IF PAVAILQTY IS NULL OR PAVAILQTY < 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Available quantity must be >= 0'; END IF;
    IF PMAXQTY IS NULL OR PMAXQTY < 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Maximum quantity must be >= 1'; END IF;
    IF PCREATEDBY IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Created By is required'; END IF;

    IF COALESCE(PISSPECIAL, 0) NOT IN (0, 1) OR COALESCE(PISPREBOOK, 1) NOT IN (0, 1)
       OR COALESCE(PISKIOSK, 1) NOT IN (0, 1) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid day menu channel flag';
    END IF;

    SELECT STATUS, SERVDATE, STARTTIME INTO VSLOTSTATUS, VSERVDATE, VSTARTTIME
    FROM CMS_DAYSLOT WHERE DAYSLOTID = PDAYSLOTID;
    IF VSLOTSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot not found'; END IF;
    IF VSLOTSTATUS <> 'A' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day slot must be active'; END IF;

    SELECT STATUS INTO VMENUSTATUS FROM CMS_MENUITEM WHERE MENUITEMID = PMENUITEMID;
    IF VMENUSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item not found'; END IF;
    IF VMENUSTATUS <> 'A' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item must be active'; END IF;

    IF PCANCELUNTIL > TIMESTAMP(VSERVDATE, VSTARTTIME) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cancel-until deadline must be before service begins';
    END IF;

    SELECT COUNT(*) INTO VEXISTS FROM CMS_DAYMENU WHERE DAYSLOTID = PDAYSLOTID AND MENUITEMID = PMENUITEMID;
    IF VEXISTS > 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu item is already assigned to this day slot'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_DAYMENU (DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           BOOKUNTIL, CANCELUNTIL, AVAILQTY, MAXQTY, STATUS, APPRSTATUS, CREATEDBY, REMARKS)
    VALUES (PDAYSLOTID, PMENUITEMID, COALESCE(PISSPECIAL, 0), COALESCE(PISPREBOOK, 1),
           COALESCE(PISKIOSK, 1), PBOOKUNTIL, PCANCELUNTIL, PAVAILQTY, PMAXQTY,
           'A', 'PEN', PCREATEDBY, PREMARKS);

    SET VDAYMENUID = LAST_INSERT_ID();
    SET VDMENUNO = CONCAT('DM', LPAD(VDAYMENUID, 8, '0'));

    UPDATE CMS_DAYMENU SET DMENUNO = VDMENUNO WHERE DAYMENUID = VDAYMENUID;

    COMMIT;

    SELECT VDAYMENUID AS DAYMENUID, VDMENUNO AS DMENUNO;
END$$


CREATE PROCEDURE CMSUPDDDMENU (
    IN PDAYMENUID   INT,
    IN PAVAILQTY    INT,
    IN PMAXQTY      INT,
    IN PBOOKUNTIL   DATETIME,
    IN PCANCELUNTIL DATETIME,
    IN PISSPECIAL   TINYINT,
    IN PISPREBOOK   TINYINT,
    IN PISKIOSK     TINYINT,
    IN PREMARKS     VARCHAR(255),
    IN PCHANGEDBY   INT,
    IN PCHGREASON   VARCHAR(255)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE VNEWBOOKUNTIL DATETIME;
    DECLARE VNEWCANCELUNTIL DATETIME;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PDAYMENUID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found'; END IF;

    SELECT COALESCE(PBOOKUNTIL, BOOKUNTIL), COALESCE(PCANCELUNTIL, CANCELUNTIL)
    INTO VNEWBOOKUNTIL, VNEWCANCELUNTIL
    FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;

    IF VNEWCANCELUNTIL > VNEWBOOKUNTIL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cancel-until must be on or before booking-until';
    END IF;

    START TRANSACTION;

    -- CMS_DMENUHIST has no BOOKUNTIL/CANCELUNTIL columns, so only the
    -- fields it actually tracks are copied.
    INSERT INTO CMS_DMENUHIST (DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, STATUS, APPRSTATUS, CHANGEDBY, CHGREASON, REMARKS)
    SELECT DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, STATUS, APPRSTATUS, PCHANGEDBY, PCHGREASON, REMARKS
    FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;

    UPDATE CMS_DAYMENU
    SET    AVAILQTY    = COALESCE(PAVAILQTY, AVAILQTY),
           MAXQTY      = COALESCE(PMAXQTY, MAXQTY),
           BOOKUNTIL   = COALESCE(PBOOKUNTIL, BOOKUNTIL),
           CANCELUNTIL = COALESCE(PCANCELUNTIL, CANCELUNTIL),
           ISSPECIAL   = COALESCE(PISSPECIAL, ISSPECIAL),
           ISPREBOOK   = COALESCE(PISPREBOOK, ISPREBOOK),
           ISKIOSK     = COALESCE(PISKIOSK, ISKIOSK),
           REMARKS     = COALESCE(PREMARKS, REMARKS),
           UPDATEDAT   = CURRENT_TIMESTAMP
    WHERE  DAYMENUID   = PDAYMENUID;
    -- TRG_DAYMENU_APPR_RESET will reset APPRSTATUS to 'PEN' if it was 'APP'
    -- and AVAILQTY/MAXQTY/ISSPECIAL/ISPREBOOK/ISKIOSK changed.

    COMMIT;
    SELECT PDAYMENUID AS DAYMENUID;
END$$


CREATE PROCEDURE CMSGETDMENU (IN PDAYMENUID INT)
BEGIN
    SELECT DM.DAYMENUID, DM.DMENUNO, DM.DAYSLOTID,
           DS.SERVDATE, DS.STARTTIME, DS.ENDTIME,
           S.SERVICEID, S.SERVCODE, S.SERVNAME,
           S.CANTEENID, C.CANTEENNAME,
           DM.MENUITEMID, MI.MENUCODE, MI.ITEMNAME, MI.SHORTNAME,
           DM.ISSPECIAL, DM.ISPREBOOK, DM.ISKIOSK,
           DM.AVAILQTY, DM.MAXQTY,
           DM.BOOKUNTIL, DM.CANCELUNTIL,
           DM.STATUS, DM.APPRSTATUS,
           DM.CREATEDBY, DM.APPROVEDBY, DM.APPROVEDAT,
           DM.REMARKS, DM.CREATEDAT, DM.UPDATEDAT
    FROM   CMS_DAYMENU DM
    JOIN   CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
    JOIN   CMS_SERVICE S  ON S.SERVICEID  = DS.SERVICEID
    JOIN   CMS_CANTEEN C  ON C.CANTEENID  = S.CANTEENID
    JOIN   CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    WHERE  DM.DAYMENUID = PDAYMENUID;
END$$


CREATE PROCEDURE CMSLISTDMENU (
    IN PCANTEENID  INT,
    IN PSERVICEID  INT,
    IN PDAYSLOTID  INT,
    IN PSERVDATE   DATE,
    IN PAPPRSTATUS VARCHAR(20)
)
BEGIN
    SELECT DM.DAYMENUID, DM.DMENUNO, DM.DAYSLOTID,
           DS.SERVDATE, DS.STARTTIME, DS.ENDTIME,
           S.SERVICEID, S.SERVCODE, S.SERVNAME,
           DM.MENUITEMID, MI.MENUCODE, MI.ITEMNAME, MI.SHORTNAME,
           DM.ISSPECIAL, DM.ISPREBOOK, DM.ISKIOSK,
           DM.AVAILQTY, DM.MAXQTY,
           DM.BOOKUNTIL, DM.CANCELUNTIL,
           DM.STATUS, DM.APPRSTATUS,
           DM.CREATEDBY, DM.APPROVEDBY, DM.APPROVEDAT,
           DM.REMARKS
    FROM   CMS_DAYMENU DM
    JOIN   CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
    JOIN   CMS_SERVICE S  ON S.SERVICEID  = DS.SERVICEID
    JOIN   CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    WHERE  (PCANTEENID  IS NULL OR S.CANTEENID   = PCANTEENID)
      AND  (PSERVICEID  IS NULL OR DS.SERVICEID   = PSERVICEID)
      AND  (PDAYSLOTID  IS NULL OR DM.DAYSLOTID   = PDAYSLOTID)
      AND  (PSERVDATE   IS NULL OR DS.SERVDATE     = PSERVDATE)
      AND  (PAPPRSTATUS IS NULL OR DM.APPRSTATUS   = PAPPRSTATUS)
    ORDER BY DS.SERVDATE, DS.STARTTIME, MI.ITEMNAME;
END$$


CREATE PROCEDURE CMSAPPDMENU (
    IN PDAYMENUID  INT,
    IN PAPPROVEDBY INT,
    IN PREMARKS    VARCHAR(255)
)
BEGIN
    DECLARE VCURRENTSTATUS VARCHAR(20);
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PDAYMENUID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required'; END IF;
    IF PAPPROVEDBY IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Approver ID is required'; END IF;

    SELECT APPRSTATUS INTO VCURRENTSTATUS FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;
    IF VCURRENTSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found'; END IF;
    IF VCURRENTSTATUS <> 'PEN' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu is not in Pending status'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_DMENUHIST (DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, STATUS, APPRSTATUS, CHANGEDBY, CHGREASON, REMARKS)
    SELECT DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, STATUS, APPRSTATUS, PAPPROVEDBY, 'Approved', REMARKS
    FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;

    UPDATE CMS_DAYMENU
    SET    APPRSTATUS = 'APP',
           APPROVEDBY = PAPPROVEDBY,
           APPROVEDAT = CURRENT_TIMESTAMP,
           REMARKS    = COALESCE(PREMARKS, REMARKS),
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  DAYMENUID  = PDAYMENUID;

    COMMIT;
    SELECT PDAYMENUID AS DAYMENUID;
END$$


CREATE PROCEDURE CMSREJDMENU (
    IN PDAYMENUID  INT,
    IN PREJECTEDBY INT,
    IN PREMARKS    VARCHAR(255)
)
BEGIN
    DECLARE VCURRENTSTATUS VARCHAR(20);
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PDAYMENUID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required'; END IF;
    IF PREJECTEDBY IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Rejector ID is required'; END IF;
    IF PREMARKS IS NULL OR TRIM(PREMARKS) = '' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Rejection remarks are required';
    END IF;

    SELECT APPRSTATUS INTO VCURRENTSTATUS FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;
    IF VCURRENTSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found'; END IF;
    IF VCURRENTSTATUS <> 'PEN' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu is not in Pending status'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_DMENUHIST (DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, STATUS, APPRSTATUS, CHANGEDBY, CHGREASON, REMARKS)
    SELECT DAYMENUID, DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, STATUS, APPRSTATUS, PREJECTEDBY, 'Rejected', REMARKS
    FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;

    UPDATE CMS_DAYMENU
    SET    APPRSTATUS = 'REJ',
           APPROVEDBY = PREJECTEDBY,
           APPROVEDAT = CURRENT_TIMESTAMP,
           REMARKS    = PREMARKS,
           UPDATEDAT  = CURRENT_TIMESTAMP
    WHERE  DAYMENUID  = PDAYMENUID;

    COMMIT;
    SELECT PDAYMENUID AS DAYMENUID;
END$$




CREATE PROCEDURE CMSACTDMENU (IN PDAYMENUID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PDAYMENUID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found'; END IF;
    START TRANSACTION;
    UPDATE CMS_DAYMENU SET STATUS = 'A', UPDATEDAT = CURRENT_TIMESTAMP WHERE DAYMENUID = PDAYMENUID;
    COMMIT;
    SELECT PDAYMENUID AS DAYMENUID;
END$$


CREATE PROCEDURE CMSDEACTDMENU (IN PDAYMENUID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PDAYMENUID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found'; END IF;
    START TRANSACTION;
    UPDATE CMS_DAYMENU SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE DAYMENUID = PDAYMENUID;
    COMMIT;
    SELECT PDAYMENUID AS DAYMENUID;
END$$


CREATE PROCEDURE CMSSOLDOUTDMENU (IN PDAYMENUID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PDAYMENUID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found'; END IF;
    START TRANSACTION;
    UPDATE CMS_DAYMENU SET STATUS = 'SOLDOUT', UPDATEDAT = CURRENT_TIMESTAMP WHERE DAYMENUID = PDAYMENUID;
    COMMIT;
    SELECT PDAYMENUID AS DAYMENUID;
END$$


/* ============================================================
   CMS_MENUTPL / CMS_MENUTPLDT — Menu Templates
   ============================================================ */

CREATE PROCEDURE CMSADDMENUTPL (
    IN PCANTEENID INT,
    IN PSERVICEID INT,
    IN PTPLNAME   VARCHAR(80),
    IN PWEEKDAY   TINYINT,
    IN PCREATEDBY INT
)
BEGIN
    DECLARE VMENUTPLID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PCANTEENID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Canteen ID is required'; END IF;
    IF PSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service ID is required'; END IF;
    IF PTPLNAME IS NULL OR TRIM(PTPLNAME) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template Name is required'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUTPL (CANTEENID, SERVICEID, TPLNAME, WEEKDAY, STATUS, CREATEDBY)
    VALUES (PCANTEENID, PSERVICEID, TRIM(PTPLNAME), PWEEKDAY, 'A', PCREATEDBY);
    SET VMENUTPLID = LAST_INSERT_ID();
    COMMIT;
    SELECT VMENUTPLID AS MENUTPLID;
END$$


CREATE PROCEDURE CMSUPDMENUTPL (
    IN PMENUTPLID INT,
    IN PTPLNAME   VARCHAR(80),
    IN PWEEKDAY   TINYINT,
    IN PSTATUS    VARCHAR(20)
)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUTPLID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUTPL WHERE MENUTPLID = PMENUTPLID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template not found'; END IF;

    START TRANSACTION;
    UPDATE CMS_MENUTPL
    SET    TPLNAME   = COALESCE(PTPLNAME, TPLNAME),
           WEEKDAY   = PWEEKDAY,
           STATUS    = COALESCE(PSTATUS, STATUS),
           UPDATEDAT = CURRENT_TIMESTAMP
    WHERE  MENUTPLID = PMENUTPLID;
    COMMIT;
    SELECT PMENUTPLID AS MENUTPLID;
END$$


CREATE PROCEDURE CMSGETMENUTPL (IN PMENUTPLID INT)
BEGIN
    SELECT T.MENUTPLID, T.CANTEENID, C.CANTEENNAME,
           T.SERVICEID, S.SERVCODE, S.SERVNAME,
           T.TPLNAME, T.WEEKDAY, T.STATUS,
           T.CREATEDBY, T.CREATEDAT, T.UPDATEDAT
    FROM   CMS_MENUTPL T
    JOIN   CMS_CANTEEN C ON C.CANTEENID = T.CANTEENID
    JOIN   CMS_SERVICE S ON S.SERVICEID = T.SERVICEID
    WHERE  T.MENUTPLID = PMENUTPLID;
END$$


CREATE PROCEDURE CMSLISTMENUTPL (IN PCANTEENID INT, IN PSERVICEID INT)
BEGIN
    SELECT T.MENUTPLID, T.CANTEENID, C.CANTEENNAME,
           T.SERVICEID, S.SERVCODE, S.SERVNAME,
           T.TPLNAME, T.WEEKDAY, T.STATUS
    FROM   CMS_MENUTPL T
    JOIN   CMS_CANTEEN C ON C.CANTEENID = T.CANTEENID
    JOIN   CMS_SERVICE S ON S.SERVICEID = T.SERVICEID
    WHERE  (PCANTEENID IS NULL OR T.CANTEENID = PCANTEENID)
      AND  (PSERVICEID IS NULL OR T.SERVICEID = PSERVICEID)
      AND  T.STATUS = 'A'
    ORDER BY T.TPLNAME;
END$$


CREATE PROCEDURE CMSDEACTMENUTPL (IN PMENUTPLID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUTPLID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUTPL WHERE MENUTPLID = PMENUTPLID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template not found'; END IF;
    START TRANSACTION;
    UPDATE CMS_MENUTPL SET STATUS = 'D', UPDATEDAT = CURRENT_TIMESTAMP WHERE MENUTPLID = PMENUTPLID;
    COMMIT;
    SELECT PMENUTPLID AS MENUTPLID;
END$$


CREATE PROCEDURE CMSADDMENUTPLDT (
    IN PMENUTPLID   INT,
    IN PMENUITEMID  INT,
    IN PISSPECIAL   TINYINT,
    IN PISPREBOOK   TINYINT,
    IN PISKIOSK    TINYINT,
    IN PMAXQTY      INT,
    IN PDEFAVAILQTY INT
)
BEGIN
    DECLARE VMENUTPLDTID INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUTPLID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template ID is required'; END IF;
    IF PMENUITEMID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Menu Item ID is required'; END IF;

    START TRANSACTION;
    INSERT INTO CMS_MENUTPLDT (MENUTPLID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK, MAXQTY, DEFAVAILQTY)
    VALUES (PMENUTPLID, PMENUITEMID, COALESCE(PISSPECIAL, 0), COALESCE(PISPREBOOK, 1),
            COALESCE(PISKIOSK, 1), COALESCE(PMAXQTY, 1), COALESCE(PDEFAVAILQTY, 0));
    SET VMENUTPLDTID = LAST_INSERT_ID();
    COMMIT;
    SELECT VMENUTPLDTID AS MENUTPLDTID;
END$$


CREATE PROCEDURE CMSREMOVEMENUTPLDT (IN PMENUTPLDTID INT)
BEGIN
    DECLARE VCOUNT INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    IF PMENUTPLDTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template Detail ID is required'; END IF;
    SELECT COUNT(*) INTO VCOUNT FROM CMS_MENUTPLDT WHERE MENUTPLDTID = PMENUTPLDTID;
    IF VCOUNT = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template detail not found'; END IF;
    START TRANSACTION;
    DELETE FROM CMS_MENUTPLDT WHERE MENUTPLDTID = PMENUTPLDTID;
    COMMIT;
    SELECT PMENUTPLDTID AS MENUTPLDTID;
END$$


CREATE PROCEDURE CMSLISTMENUTPLDT (IN PMENUTPLID INT)
BEGIN
    SELECT TD.MENUTPLDTID, TD.MENUTPLID, TD.MENUITEMID,
           MI.MENUCODE, MI.SHORTNAME, MI.ITEMNAME,
           TD.ISSPECIAL, TD.ISPREBOOK, TD.ISKIOSK,
           TD.MAXQTY, TD.DEFAVAILQTY
    FROM   CMS_MENUTPLDT TD
    JOIN   CMS_MENUITEM MI ON MI.MENUITEMID = TD.MENUITEMID
    WHERE  TD.MENUTPLID = PMENUTPLID
    ORDER BY MI.ITEMNAME;
END$$


/* ============================================================
   CMSAPPLYMENUTPL — Materialise a template into day-menu rows

   Creates the day slot if it doesn't exist, then inserts
   day-menu items from the template. Booking windows default
   to: BOOKSTART = previous day 06:00, BOOKEND = slot start - 1h,
   CANCELAT = slot start - 30min.  All can be overridden after.
   ============================================================ */

CREATE PROCEDURE CMSAPPLYMENUTPL (
    IN PMENUTPLID  INT,
    IN PTARGETDATE DATE,
    IN PCREATEDBY  INT
)
BEGIN
    DECLARE VSERVICEID   INT;
    DECLARE VCANTEENID   INT;
    DECLARE VTPLSTATUS   VARCHAR(20);
    DECLARE VDEFSTART    TIME;
    DECLARE VDEFEND      TIME;
    DECLARE VDAYSLOTID   INT;
    DECLARE VITEMCOUNT   INT DEFAULT 0;
    DECLARE VINSERTED    INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PMENUTPLID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template ID is required'; END IF;
    IF PTARGETDATE IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Target Date is required'; END IF;

    SELECT T.SERVICEID, T.CANTEENID, T.STATUS
    INTO   VSERVICEID, VCANTEENID, VTPLSTATUS
    FROM   CMS_MENUTPL T
    WHERE  T.MENUTPLID = PMENUTPLID;

    IF VSERVICEID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template not found'; END IF;
    IF VTPLSTATUS <> 'A' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Template is not active'; END IF;

    SELECT DEFSTART, DEFEND INTO VDEFSTART, VDEFEND
    FROM CMS_SERVICE WHERE SERVICEID = VSERVICEID;

    START TRANSACTION;

    -- Create or find existing day slot
    SELECT DAYSLOTID INTO VDAYSLOTID
    FROM CMS_DAYSLOT WHERE SERVICEID = VSERVICEID AND SERVDATE = PTARGETDATE;

    IF VDAYSLOTID IS NULL THEN
        INSERT INTO CMS_DAYSLOT (SERVICEID, SERVDATE, STARTTIME, ENDTIME, STATUS, CREATEDBY)
        VALUES (VSERVICEID, PTARGETDATE, VDEFSTART, VDEFEND, 'A', PCREATEDBY);
        SET VDAYSLOTID = LAST_INSERT_ID();
    END IF;

    -- Insert template items as day menus (skip duplicates)
    INSERT INTO CMS_DAYMENU (DAYSLOTID, MENUITEMID, ISSPECIAL, ISPREBOOK, ISKIOSK,
           AVAILQTY, MAXQTY, BOOKSTART, BOOKEND, CANCELAT, STATUS, APPRSTATUS, ADDEDBY)
    SELECT VDAYSLOTID, TD.MENUITEMID, TD.ISSPECIAL, TD.ISPREBOOK, TD.ISKIOSK,
           TD.DEFAVAILQTY, TD.MAXQTY,
           TIMESTAMP(DATE_SUB(PTARGETDATE, INTERVAL 1 DAY), '06:00:00'),
           TIMESTAMP(PTARGETDATE, SUBTIME(VDEFSTART, '01:00:00')),
           TIMESTAMP(PTARGETDATE, SUBTIME(VDEFSTART, '00:30:00')),
           'A', 'P', PCREATEDBY
    FROM   CMS_MENUTPLDT TD
    WHERE  TD.MENUTPLID = PMENUTPLID
      AND  NOT EXISTS (
          SELECT 1 FROM CMS_DAYMENU DM
          WHERE DM.DAYSLOTID = VDAYSLOTID AND DM.MENUITEMID = TD.MENUITEMID
      );

    SET VINSERTED = ROW_COUNT();

    COMMIT;

    SELECT VDAYSLOTID AS DAYSLOTID, VINSERTED AS ITEMSINSERTED;
END$$


/* ============================================================
   CMS_APPRINST / CMS_APPRSTEP — Generic Approval Engine
   ============================================================ */

CREATE PROCEDURE CMSADDAPPRINST (
    IN PENTITYTYPE VARCHAR(30),
    IN PENTITYID   INT,
    IN PTOTLVLS    INT,
    IN PINITBY     INT
)
BEGIN
    DECLARE VAPPRINSTID INT;
    DECLARE VI INT DEFAULT 1;
    DECLARE VAPPLVLID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PENTITYTYPE IS NULL OR TRIM(PENTITYTYPE) = '' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Entity Type is required'; END IF;
    IF PENTITYID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Entity ID is required'; END IF;
    IF PTOTLVLS IS NULL OR PTOTLVLS < 1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Total levels must be >= 1'; END IF;

    START TRANSACTION;

    INSERT INTO CMS_APPRINST (ENTITYTYPE, ENTITYID, CURLVLNO, TOTLVLS, OVRSTATUS, INITBY)
    VALUES (TRIM(PENTITYTYPE), PENTITYID, 1, PTOTLVLS, 'PEND', PINITBY);
    SET VAPPRINSTID = LAST_INSERT_ID();

    -- Create one APPRSTEP row per level
    WHILE VI <= PTOTLVLS DO
        SELECT APPLVLID INTO VAPPLVLID FROM CMS_APPLVL WHERE LEVELNO = VI AND ISACTIVE = 1 LIMIT 1;

        INSERT INTO CMS_APPRSTEP (APPRINSTID, LEVELNO, APPLVLID, DECISION)
        VALUES (VAPPRINSTID, VI, VAPPLVLID, 'PEND');

        SET VI = VI + 1;
    END WHILE;

    COMMIT;
    SELECT VAPPRINSTID AS APPRINSTID;
END$$


CREATE PROCEDURE CMSGETAPPRINST (IN PAPPRINSTID INT)
BEGIN
    -- Result set 1: Instance header
    SELECT AI.APPRINSTID, AI.ENTITYTYPE, AI.ENTITYID,
           AI.CURLVLNO, AI.TOTLVLS, AI.OVRSTATUS,
           AI.INITBY, AI.INITAT, AI.UPDATEDAT
    FROM   CMS_APPRINST AI
    WHERE  AI.APPRINSTID = PAPPRINSTID;

    -- Result set 2: Steps
    SELECT AST.APPRSTEPID, AST.APPRINSTID, AST.LEVELNO,
           AST.APPLVLID, AL.LEVELNAME,
           AST.APPROVERID, U.FULLNAME AS APPROVERNAME,
           AST.DECISION, AST.REMARKS, AST.DECIDEDAT
    FROM   CMS_APPRSTEP AST
    LEFT JOIN CMS_APPLVL AL ON AL.APPLVLID = AST.APPLVLID
    LEFT JOIN CMS_USER U    ON U.USERID    = AST.APPROVERID
    WHERE  AST.APPRINSTID = PAPPRINSTID
    ORDER BY AST.LEVELNO;
END$$


CREATE PROCEDURE CMSLISTAPPRINST (
    IN PENTITYTYPE  VARCHAR(30),
    IN POVRSTATUS   VARCHAR(20),
    IN PAPPROVERID  INT
)
BEGIN
    SELECT AI.APPRINSTID, AI.ENTITYTYPE, AI.ENTITYID,
           AI.CURLVLNO, AI.TOTLVLS, AI.OVRSTATUS,
           AI.INITBY, UI.FULLNAME AS INITNAME, AI.INITAT
    FROM   CMS_APPRINST AI
    LEFT JOIN CMS_USER UI ON UI.USERID = AI.INITBY
    WHERE  (PENTITYTYPE IS NULL OR AI.ENTITYTYPE = PENTITYTYPE)
      AND  (POVRSTATUS  IS NULL OR AI.OVRSTATUS  = POVRSTATUS)
      AND  (PAPPROVERID IS NULL OR EXISTS (
          SELECT 1 FROM CMS_APPRSTEP AST
          JOIN CMS_APPLVL AL ON AL.APPLVLID = AST.APPLVLID
          JOIN CMS_CONSUMERROLE CR ON CR.ROLEID = AL.ROLEID AND CR.USERID = PAPPROVERID AND CR.ISACTIVE = 1
          WHERE AST.APPRINSTID = AI.APPRINSTID AND AST.LEVELNO = AI.CURLVLNO AND AST.DECISION = 'PEND'
      ))
    ORDER BY AI.INITAT DESC;
END$$


CREATE PROCEDURE CMSDECIDEAPPRSTEP (
    IN PAPPRINSTID INT,
    IN PLEVELNO    INT,
    IN PAPPROVERID INT,
    IN PDECISION   VARCHAR(20),
    IN PREMARKS    VARCHAR(255)
)
BEGIN
    DECLARE VCURLVL    INT;
    DECLARE VTOTLVLS   INT;
    DECLARE VOVRSTATUS VARCHAR(20);
    DECLARE VSTEPDEC   VARCHAR(20);

    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PAPPRINSTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Approval Instance ID is required'; END IF;
    IF PDECISION IS NULL OR PDECISION NOT IN ('APP', 'REJ') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Decision must be APP or REJ';
    END IF;

    SELECT CURLVLNO, TOTLVLS, OVRSTATUS INTO VCURLVL, VTOTLVLS, VOVRSTATUS
    FROM CMS_APPRINST WHERE APPRINSTID = PAPPRINSTID;
    IF VCURLVL IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Approval instance not found'; END IF;
    IF VOVRSTATUS <> 'PEND' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Approval instance is no longer pending'; END IF;

    IF PLEVELNO <> VCURLVL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'This is not the current approval level';
    END IF;

    SELECT DECISION INTO VSTEPDEC FROM CMS_APPRSTEP
    WHERE APPRINSTID = PAPPRINSTID AND LEVELNO = PLEVELNO;
    IF VSTEPDEC IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Approval step not found'; END IF;
    IF VSTEPDEC <> 'PEND' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Step has already been decided'; END IF;

    START TRANSACTION;

    UPDATE CMS_APPRSTEP
    SET    APPROVERID = PAPPROVERID,
           DECISION   = PDECISION,
           REMARKS    = PREMARKS,
           DECIDEDAT  = CURRENT_TIMESTAMP
    WHERE  APPRINSTID = PAPPRINSTID AND LEVELNO = PLEVELNO;

    IF PDECISION = 'REJ' THEN
        UPDATE CMS_APPRINST
        SET OVRSTATUS = 'REJ', UPDATEDAT = CURRENT_TIMESTAMP
        WHERE APPRINSTID = PAPPRINSTID;
    ELSEIF VCURLVL >= VTOTLVLS THEN
        UPDATE CMS_APPRINST
        SET OVRSTATUS = 'APP', UPDATEDAT = CURRENT_TIMESTAMP
        WHERE APPRINSTID = PAPPRINSTID;
    ELSE
        UPDATE CMS_APPRINST
        SET CURLVLNO = VCURLVL + 1, UPDATEDAT = CURRENT_TIMESTAMP
        WHERE APPRINSTID = PAPPRINSTID;
    END IF;

    COMMIT;
    SELECT PAPPRINSTID AS APPRINSTID, PDECISION AS DECISION;
END$$


CREATE PROCEDURE CMSCANCELAPPRINST (IN PAPPRINSTID INT, IN PCANCELLEDBY INT)
BEGIN
    DECLARE VOVRSTATUS VARCHAR(20);
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;

    IF PAPPRINSTID IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Approval Instance ID is required'; END IF;
    SELECT OVRSTATUS INTO VOVRSTATUS FROM CMS_APPRINST WHERE APPRINSTID = PAPPRINSTID;
    IF VOVRSTATUS IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Approval instance not found'; END IF;
    IF VOVRSTATUS <> 'PEND' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only pending instances can be cancelled'; END IF;

    START TRANSACTION;
    UPDATE CMS_APPRINST SET OVRSTATUS = 'CANCELLED', UPDATEDAT = CURRENT_TIMESTAMP WHERE APPRINSTID = PAPPRINSTID;
    COMMIT;
    SELECT PAPPRINSTID AS APPRINSTID;
END$$

/* ============================================================
   CMSVIEWMENU — Published Menu View (Customer-facing)

   Rewritten for new pricing model:
   - Price resolved via CMS_ITEMPRICE + CMS_ITEMPRICEDT
   - CANTEENID filter (required)
   ============================================================ */

CREATE PROCEDURE CMSVIEWMENU (
    IN PCANTEENID INT,
    IN PSERVDATE  DATE,
    IN PCTYPECODE VARCHAR(20)
)
BEGIN
    SELECT
        S.CANTEENID,
        C.CANTEENNAME,
        DS.DAYSLOTID,
        S.SERVICEID,
        S.SERVCODE,
        S.SERVNAME,
        DS.SERVDATE,
        DS.STARTTIME,
        DS.ENDTIME,
        DM.DAYMENUID,
        DM.DMENUNO,
        MI.MENUITEMID,
        MI.MENUCODE,
        MI.SHORTNAME,
        MI.ITEMNAME,
        MI.ITEMDESCR,
        DM.ISSPECIAL,
        DM.ISPREBOOK,
        DM.ISKIOSK,
        DM.AVAILQTY,
        DM.MAXQTY,
        DM.BOOKUNTIL,
        DM.CANCELUNTIL,
        (
            SELECT IPD.PRICE
            FROM   CMS_ITEMPRICE IP
            JOIN   CMS_ITEMPRICEDT IPD ON IPD.ITEMPRICEID = IP.ITEMPRICEID
            WHERE  IP.MENUITEMID  = MI.MENUITEMID
              AND  IPD.CTYPECODE  = COALESCE(PCTYPECODE, 'VISITOR')
              AND  IP.EFFFROM    <= DS.SERVDATE
              AND  IP.STATUS      = 'A'
            ORDER BY IP.EFFFROM DESC
            LIMIT 1
        ) AS DISPLAYPRICE
    FROM CMS_DAYMENU DM
    JOIN CMS_DAYSLOT DS  ON DS.DAYSLOTID  = DM.DAYSLOTID
    JOIN CMS_SERVICE S   ON S.SERVICEID   = DS.SERVICEID
    JOIN CMS_CANTEEN C   ON C.CANTEENID   = S.CANTEENID
    JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    WHERE S.CANTEENID  = PCANTEENID
      AND DS.SERVDATE  = PSERVDATE
      AND DM.APPRSTATUS = 'APP'
      AND DM.STATUS     = 'A'
      AND DS.STATUS     = 'A'
      AND S.STATUS      = 'A'
      AND MI.STATUS     = 'A'
      AND CURRENT_TIMESTAMP <= DM.BOOKUNTIL
    ORDER BY DS.STARTTIME, S.SERVNAME, MI.ITEMNAME;
END$$

DELIMITER ;
