/* ============================================================
   MODULE 3: BOOKING & SERVING STORED PROCEDURES

   PITEMSJSON shape expected by CMSADDBOOK / CMSUPDBOOKITEM:
     [ {"DAYMENUID": 101, "QTY": 2}, {"DAYMENUID": 105, "QTY": 1} ]

   Business rules enforced here (Node.js validation stays shape-only,
   same division of responsibility as Module 2):
     - PB: DAYMENU.ISPREBOOK must be 1. QTY must not exceed MAXQTY.
           No AVAILQTY check/decrement.
     - KS: DAYMENU.ISKIOSK must be 1 (live staff toggle governs this,
           see CMSTOGGLEKIOSK). No AVAILQTY check/decrement.
     - Both (CMSADDBOOK only): DAYMENU must be APPRSTATUS = 'APP', its
           day slot must be ACTIVE and match the requested
           service/date, the menu item must be ACTIVE.
           -- TODO: The original schema enforced a booking window via
           -- DM.BOOKSTART / DM.BOOKEND on CMS_DAYMENU. These columns
           -- have been removed and no equivalent exists in the current
           -- schema. Booking-window enforcement is currently inactive.
     - One active (non-cancelled) PB booking per
       (CUSTOMERID, SERVICEID, SERVICEDATE) -- enforced procedurally.
     - Rate is resolved from the customer's CTYPECODE via
       CMS_ITEMPRICE / CMS_ITEMPRICEDT (effective-date pricing),
       and frozen onto the booking item.
     - Cutoff for edits/cancellation:
       -- TODO: The original schema used MIN(DM.CANCELAT) across
       -- the booking's current day-menu rows. CANCELAT has been
       -- removed from CMS_DAYMENU and no equivalent exists in the
       -- current schema. Cutoff enforcement is currently inactive.
   ============================================================ */

USE cms_db;

DROP PROCEDURE IF EXISTS CMSADDBOOK;
DROP PROCEDURE IF EXISTS CMSUPDBOOKITEM;
DROP PROCEDURE IF EXISTS CMSCANCELBOOK;
DROP PROCEDURE IF EXISTS CMSSERVEBOOK;
DROP PROCEDURE IF EXISTS CMSNOSHOWBOOK;
DROP PROCEDURE IF EXISTS CMSTOGGLEKIOSK;
DROP PROCEDURE IF EXISTS CMSGETBOOK;
DROP PROCEDURE IF EXISTS CMSLISTBOOK;

DELIMITER $$

-- v1_module3
-- Creates a PB or KS booking header plus its items in one transaction.
CREATE PROCEDURE CMSADDBOOK (
    IN PBOOKTYPECODE VARCHAR(10),
    IN PCUSTOMERID INT,
    IN PSERVICEID INT,
    IN PSERVICEDATE DATE,
    IN PITEMSJSON JSON,
    IN PBOOKEDBY INT,
    IN PREMARKS VARCHAR(255)
)
BEGIN
    DECLARE VBOOKTYPEID INT;
    DECLARE VBOOKTYPESTATUS VARCHAR(20);
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VCUSTSTATUS VARCHAR(20);
    DECLARE VSERVPFX VARCHAR(5);
    DECLARE VSERVSTATUS VARCHAR(20);
    DECLARE VEXISTINGPB INT DEFAULT 0;
    DECLARE VITEMCOUNT INT DEFAULT 0;
    DECLARE VDISTINCTCOUNT INT DEFAULT 0;
    DECLARE VINVALIDCOUNT INT DEFAULT 0;
    DECLARE VBOOKID INT;
    DECLARE VBOOKNO VARCHAR(30);
    DECLARE VBOOKSEQ BIGINT;
    DECLARE VTOTALITEMS INT DEFAULT 0;
    DECLARE VTOTALQTY INT DEFAULT 0;
    DECLARE VTOTALAMOUNT DECIMAL(12,2) DEFAULT 0.00;
    DECLARE VLASTNO BIGINT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PBOOKTYPECODE IS NULL OR PBOOKTYPECODE NOT IN ('PB','KS') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking type must be PB or KS';
    END IF;

    IF PCUSTOMERID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer is required';
    END IF;

    IF PSERVICEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service is required';
    END IF;

    IF PSERVICEDATE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service date is required';
    END IF;

    IF PITEMSJSON IS NULL OR JSON_TYPE(PITEMSJSON) <> 'ARRAY' OR JSON_LENGTH(PITEMSJSON) = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'At least one booking item is required';
    END IF;

    SELECT BOOKTYPEID, STATUS INTO VBOOKTYPEID, VBOOKTYPESTATUS
    FROM CMS_BOOKTYPE WHERE BOOKTYPECODE = PBOOKTYPECODE;

    IF VBOOKTYPEID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking type not found';
    END IF;

    IF VBOOKTYPESTATUS <> 'A' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking type is inactive';
    END IF;

    SELECT CTYPECODE, STATUS INTO VCTYPECODE, VCUSTSTATUS
    FROM CMS_CUSTOMER WHERE CUSTOMERID = PCUSTOMERID;

    IF VCTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer not found';
    END IF;

    IF VCUSTSTATUS <> 'A' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Customer is not active';
    END IF;

    SELECT UPPER(LEFT(SERVCODE, 2)), STATUS INTO VSERVPFX, VSERVSTATUS
    FROM CMS_SERVICE WHERE SERVICEID = PSERVICEID;

    IF VSERVPFX IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service not found';
    END IF;

    IF VSERVSTATUS <> 'A' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service is not active';
    END IF;

    IF PBOOKTYPECODE = 'PB' THEN
        SELECT COUNT(*) INTO VEXISTINGPB
        FROM CMS_BOOKING
        WHERE CUSTOMERID = PCUSTOMERID
          AND SERVICEID = PSERVICEID
          AND SERVICEDATE = PSERVICEDATE
          AND BOOKTYPEID = VBOOKTYPEID
          AND STATUS <> 'CAN';

        IF VEXISTINGPB > 0 THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'An active pre-booking already exists for this service and date; use the update operation instead';
        END IF;
    END IF;

    SET VITEMCOUNT = JSON_LENGTH(PITEMSJSON);

    SELECT COUNT(DISTINCT JT.DAYMENUID) INTO VDISTINCTCOUNT
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID'
    )) AS JT;

    IF VDISTINCTCOUNT <> VITEMCOUNT THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Duplicate day menu items in the same booking are not allowed';
    END IF;

    SELECT COUNT(*) INTO VINVALIDCOUNT
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    LEFT JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID
    LEFT JOIN CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
    LEFT JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    WHERE JT.DAYMENUID IS NULL
       OR JT.QTY IS NULL OR JT.QTY < 1
       OR DM.DAYMENUID IS NULL
       OR DM.APPRSTATUS <> 'APP'
       OR DS.SERVICEID <> PSERVICEID
       OR DS.SERVDATE <> PSERVICEDATE
       OR DS.STATUS <> 'A'
       OR MI.STATUS <> 'A'
       -- TODO: The original schema had DM.BOOKSTART and DM.BOOKEND columns on
       -- CMS_DAYMENU, used here as:
       --   OR CURRENT_TIMESTAMP NOT BETWEEN DM.BOOKSTART AND DM.BOOKEND
       -- These columns have been removed from CMS_DAYMENU and no equivalent
       -- exists in the current schema. Booking-window enforcement is currently
       -- inactive and must be re-implemented when new schema fields are defined.
       OR (PBOOKTYPECODE = 'PB' AND (DM.ISPREBOOK <> 1 OR JT.QTY > DM.MAXQTY))
       OR (PBOOKTYPECODE = 'KS' AND DM.ISKIOSK <> 1);

    IF VINVALIDCOUNT > 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'One or more booking items are invalid, inactive, unavailable, or outside the booking window';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_BOOKCTR (BOOKTYPEID, SERVICEID, LASTNO)
    VALUES (VBOOKTYPEID, PSERVICEID, 0)
    ON DUPLICATE KEY UPDATE LASTNO = LASTNO;

    SELECT LASTNO INTO VLASTNO
    FROM CMS_BOOKCTR
    WHERE BOOKTYPEID = VBOOKTYPEID AND SERVICEID = PSERVICEID
    FOR UPDATE;

    SET VBOOKSEQ = VLASTNO + 1;

    UPDATE CMS_BOOKCTR SET LASTNO = VBOOKSEQ
    WHERE BOOKTYPEID = VBOOKTYPEID AND SERVICEID = PSERVICEID;

    SET VBOOKNO = CONCAT(PBOOKTYPECODE, '-', VSERVPFX, LPAD(VBOOKSEQ, 3, '0'));

    SELECT COUNT(*), SUM(JT.QTY), SUM(JT.QTY * COALESCE(
        (SELECT d.PRICE
         FROM CMS_ITEMPRICE p
         JOIN CMS_ITEMPRICEDT d ON d.ITEMPRICEID = p.ITEMPRICEID
         WHERE p.MENUITEMID = DM.MENUITEMID
           AND d.CTYPECODE = VCTYPECODE
           AND p.EFFFROM <= PSERVICEDATE
           AND p.STATUS = 'A'
         ORDER BY p.EFFFROM DESC LIMIT 1),
        0))
    INTO VTOTALITEMS, VTOTALQTY, VTOTALAMOUNT
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID;

    INSERT INTO CMS_BOOKING (
        BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE, STATUS,
        BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
        BOOKEDBY, BOOKEDON, REMARKS, CREATEDBY
    )
    VALUES (
        VBOOKNO, VBOOKTYPEID, PCUSTOMERID, PSERVICEID, PSERVICEDATE, 'CR',
        VBOOKSEQ, VTOTALITEMS, VTOTALQTY, VTOTALAMOUNT,
        PBOOKEDBY, CURRENT_TIMESTAMP, PREMARKS, PBOOKEDBY
    );

    SET VBOOKID = LAST_INSERT_ID();

    INSERT INTO CMS_BOOKITEM (BOOKID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT)
    SELECT
        VBOOKID,
        DM.DAYMENUID,
        DM.MENUITEMID,
        JT.QTY,
        COALESCE(
            (SELECT d.PRICE
             FROM CMS_ITEMPRICE p
             JOIN CMS_ITEMPRICEDT d ON d.ITEMPRICEID = p.ITEMPRICEID
             WHERE p.MENUITEMID = DM.MENUITEMID
               AND d.CTYPECODE = VCTYPECODE
               AND p.EFFFROM <= PSERVICEDATE
               AND p.STATUS = 'A'
             ORDER BY p.EFFFROM DESC LIMIT 1),
            0),
        JT.QTY * COALESCE(
            (SELECT d.PRICE
             FROM CMS_ITEMPRICE p
             JOIN CMS_ITEMPRICEDT d ON d.ITEMPRICEID = p.ITEMPRICEID
             WHERE p.MENUITEMID = DM.MENUITEMID
               AND d.CTYPECODE = VCTYPECODE
               AND p.EFFFROM <= PSERVICEDATE
               AND p.STATUS = 'A'
             ORDER BY p.EFFFROM DESC LIMIT 1),
            0)
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID;

    IF PBOOKTYPECODE = 'PB' THEN
        -- Real concurrency guard: if a concurrent request already
        -- inserted this same (CUSTOMERID, SERVICEID, SERVICEDATE),
        -- this INSERT raises a duplicate-key SQLEXCEPTION, which the
        -- EXIT HANDLER above turns into a ROLLBACK of the whole booking.
        INSERT INTO CMS_PBACTIVE (CUSTOMERID, SERVICEID, SERVICEDATE, BOOKID)
        VALUES (PCUSTOMERID, PSERVICEID, PSERVICEDATE, VBOOKID);
    END IF;

    COMMIT;

    SELECT VBOOKID AS BOOKID, VBOOKNO AS BOOKNO;
END$$

-- v1_module3
-- Full replacement of a PB booking's items, pre-cutoff only.
-- Never writes history (business rule: intermediate edits are ignored).
CREATE PROCEDURE CMSUPDBOOKITEM (
    IN PBOOKID INT,
    IN PITEMSJSON JSON,
    IN PCHANGEDBY INT
)
BEGIN
    DECLARE VBOOKTYPECODE VARCHAR(10);
    DECLARE VCUSTOMERID INT;
    DECLARE VCTYPECODE VARCHAR(20);
    DECLARE VSERVICEID INT;
    DECLARE VSERVICEDATE DATE;
    DECLARE VSTATUS VARCHAR(10);
    DECLARE VCUTOFF DATETIME;
    DECLARE VITEMCOUNT INT DEFAULT 0;
    DECLARE VDISTINCTCOUNT INT DEFAULT 0;
    DECLARE VINVALIDCOUNT INT DEFAULT 0;
    DECLARE VTOTALITEMS INT DEFAULT 0;
    DECLARE VTOTALQTY INT DEFAULT 0;
    DECLARE VTOTALAMOUNT DECIMAL(12,2) DEFAULT 0.00;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PBOOKID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking ID is required';
    END IF;

    IF PITEMSJSON IS NULL OR JSON_TYPE(PITEMSJSON) <> 'ARRAY' OR JSON_LENGTH(PITEMSJSON) = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'At least one booking item is required';
    END IF;

    SELECT BT.BOOKTYPECODE, BK.CUSTOMERID, BK.SERVICEID, BK.SERVICEDATE, BK.STATUS
    INTO VBOOKTYPECODE, VCUSTOMERID, VSERVICEID, VSERVICEDATE, VSTATUS
    FROM CMS_BOOKING BK
    JOIN CMS_BOOKTYPE BT ON BT.BOOKTYPEID = BK.BOOKTYPEID
    WHERE BK.BOOKID = PBOOKID;

    IF VBOOKTYPECODE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking not found';
    END IF;

    IF VBOOKTYPECODE <> 'PB' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only pre-bookings can be edited';
    END IF;

    IF VSTATUS <> 'CR' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking is not in an editable state';
    END IF;

    -- TODO: The original schema had DM.CANCELAT column on CMS_DAYMENU,
    -- used here as:
    --   SELECT MIN(DM.CANCELAT) INTO VCUTOFF
    --   FROM CMS_BOOKITEM BI
    --   JOIN CMS_DAYMENU DM ON DM.DAYMENUID = BI.DAYMENUID
    --   WHERE BI.BOOKID = PBOOKID;
    -- This column has been removed from CMS_DAYMENU and no equivalent
    -- exists in the current schema. Cutoff enforcement is currently
    -- inactive and must be re-implemented when new schema fields are defined.
    SET VCUTOFF = NULL;

    IF VCUTOFF IS NOT NULL AND CURRENT_TIMESTAMP >= VCUTOFF THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking cutoff time has passed; this booking can no longer be edited';
    END IF;

    SELECT CTYPECODE INTO VCTYPECODE FROM CMS_CUSTOMER WHERE CUSTOMERID = VCUSTOMERID;

    SET VITEMCOUNT = JSON_LENGTH(PITEMSJSON);

    SELECT COUNT(DISTINCT JT.DAYMENUID) INTO VDISTINCTCOUNT
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID'
    )) AS JT;

    IF VDISTINCTCOUNT <> VITEMCOUNT THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Duplicate day menu items in the same booking are not allowed';
    END IF;

    SELECT COUNT(*) INTO VINVALIDCOUNT
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    LEFT JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID
    LEFT JOIN CMS_DAYSLOT DS ON DS.DAYSLOTID = DM.DAYSLOTID
    LEFT JOIN CMS_MENUITEM MI ON MI.MENUITEMID = DM.MENUITEMID
    WHERE JT.DAYMENUID IS NULL
       OR JT.QTY IS NULL OR JT.QTY < 1
       OR DM.DAYMENUID IS NULL
       OR DM.APPRSTATUS <> 'APP'
       OR DS.SERVICEID <> VSERVICEID
       OR DS.SERVDATE <> VSERVICEDATE
       OR DS.STATUS <> 'A'
       OR MI.STATUS <> 'A'
       OR DM.ISPREBOOK <> 1
       OR JT.QTY > DM.MAXQTY;
       -- TODO: The original schema had DM.CANCELAT column on CMS_DAYMENU,
       -- used here as an additional condition:
       --   OR CURRENT_TIMESTAMP >= DM.CANCELAT
       -- This column has been removed from CMS_DAYMENU and no equivalent
       -- exists in the current schema. Per-item cutoff enforcement is
       -- currently inactive and must be re-implemented when new schema
       -- fields are defined.

    IF VINVALIDCOUNT > 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'One or more booking items are invalid, inactive, unavailable, or past cutoff';
    END IF;

    START TRANSACTION;

    DELETE FROM CMS_BOOKITEM WHERE BOOKID = PBOOKID;

    SELECT COUNT(*), SUM(JT.QTY), SUM(JT.QTY * COALESCE(
        (SELECT d.PRICE
         FROM CMS_ITEMPRICE p
         JOIN CMS_ITEMPRICEDT d ON d.ITEMPRICEID = p.ITEMPRICEID
         WHERE p.MENUITEMID = DM.MENUITEMID
           AND d.CTYPECODE = VCTYPECODE
           AND p.EFFFROM <= VSERVICEDATE
           AND p.STATUS = 'A'
         ORDER BY p.EFFFROM DESC LIMIT 1),
        0))
    INTO VTOTALITEMS, VTOTALQTY, VTOTALAMOUNT
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID;

    INSERT INTO CMS_BOOKITEM (BOOKID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT)
    SELECT
        PBOOKID,
        DM.DAYMENUID,
        DM.MENUITEMID,
        JT.QTY,
        COALESCE(
            (SELECT d.PRICE
             FROM CMS_ITEMPRICE p
             JOIN CMS_ITEMPRICEDT d ON d.ITEMPRICEID = p.ITEMPRICEID
             WHERE p.MENUITEMID = DM.MENUITEMID
               AND d.CTYPECODE = VCTYPECODE
               AND p.EFFFROM <= VSERVICEDATE
               AND p.STATUS = 'A'
             ORDER BY p.EFFFROM DESC LIMIT 1),
            0),
        JT.QTY * COALESCE(
            (SELECT d.PRICE
             FROM CMS_ITEMPRICE p
             JOIN CMS_ITEMPRICEDT d ON d.ITEMPRICEID = p.ITEMPRICEID
             WHERE p.MENUITEMID = DM.MENUITEMID
               AND d.CTYPECODE = VCTYPECODE
               AND p.EFFFROM <= VSERVICEDATE
               AND p.STATUS = 'A'
             ORDER BY p.EFFFROM DESC LIMIT 1),
            0)
    FROM JSON_TABLE(PITEMSJSON, '$[*]' COLUMNS (
        DAYMENUID INT PATH '$.DAYMENUID',
        QTY INT PATH '$.QTY'
    )) AS JT
    JOIN CMS_DAYMENU DM ON DM.DAYMENUID = JT.DAYMENUID;

    UPDATE CMS_BOOKING
    SET TOTALITEMS = VTOTALITEMS,
        TOTALQTY = VTOTALQTY,
        TOTALAMOUNT = VTOTALAMOUNT,
        UPDATEDBY = PCHANGEDBY,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE BOOKID = PBOOKID;

    COMMIT;
END$$

-- v1_module3
-- Cancels a booking. PISSTAFFOVERRIDE=1 bypasses the cutoff check
-- (Node.js role middleware decides who is allowed to pass 1).
-- Always writes history: cancellation is a terminal transition.
CREATE PROCEDURE CMSCANCELBOOK (
    IN PBOOKID INT,
    IN PCANCELLEDBY INT,
    IN PISSTAFFOVERRIDE TINYINT,
    IN PCHGREASON VARCHAR(255)
)
BEGIN
    DECLARE VSTATUS VARCHAR(10);
    DECLARE VCUTOFF DATETIME;
    DECLARE VBOOKHISTID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PBOOKID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking ID is required';
    END IF;

    SELECT STATUS INTO VSTATUS FROM CMS_BOOKING WHERE BOOKID = PBOOKID;

    IF VSTATUS IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking not found';
    END IF;

    IF VSTATUS <> 'CR' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking cannot be cancelled from its current state';
    END IF;

    IF COALESCE(PISSTAFFOVERRIDE, 0) = 0 THEN
        -- TODO: The original schema had DM.CANCELAT column on CMS_DAYMENU,
        -- used here as:
        --   SELECT MIN(DM.CANCELAT) INTO VCUTOFF
        --   FROM CMS_BOOKITEM BI
        --   JOIN CMS_DAYMENU DM ON DM.DAYMENUID = BI.DAYMENUID
        --   WHERE BI.BOOKID = PBOOKID;
        -- This column has been removed from CMS_DAYMENU and no equivalent
        -- exists in the current schema. Cutoff enforcement is currently
        -- inactive and must be re-implemented when new schema fields are defined.
        SET VCUTOFF = NULL;

        IF VCUTOFF IS NOT NULL AND CURRENT_TIMESTAMP >= VCUTOFF THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cancellation cutoff time has passed';
        END IF;
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_BOOKHIST (
        BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
        STATUS, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
        BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
        REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, CHANGEDBY, CHGREASON
    )
    SELECT
        BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
        STATUS, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
        BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
        REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, PCANCELLEDBY, PCHGREASON
    FROM CMS_BOOKING
    WHERE BOOKID = PBOOKID;

    SET VBOOKHISTID = LAST_INSERT_ID();

    INSERT INTO CMS_BOOKITMHS (BOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUS)
    SELECT VBOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUS
    FROM CMS_BOOKITEM
    WHERE BOOKID = PBOOKID;

    UPDATE CMS_BOOKING
    SET STATUS = 'CAN',
        CANCELLEDBY = PCANCELLEDBY,
        CANCELLEDON = CURRENT_TIMESTAMP,
        REMARKS = COALESCE(PCHGREASON, REMARKS),
        UPDATEDBY = PCANCELLEDBY,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE BOOKID = PBOOKID;

    -- No-op for KS bookings (they never have a CMS_PBACTIVE row).
    DELETE FROM CMS_PBACTIVE WHERE BOOKID = PBOOKID;

    COMMIT;
END$$

-- v1_module3
-- Marks a booking as served. Always writes history. Restricted to
-- today's bookings -- serving is a physical counter action, so a
-- future-dated PB booking cannot be marked served early.
CREATE PROCEDURE CMSSERVEBOOK (
    IN PBOOKID INT,
    IN PSERVEDBY INT
)
BEGIN
    DECLARE VSTATUS VARCHAR(10);
    DECLARE VSERVICEDATE DATE;
    DECLARE VBOOKHISTID INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PBOOKID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking ID is required';
    END IF;

    SELECT STATUS, SERVICEDATE INTO VSTATUS, VSERVICEDATE FROM CMS_BOOKING WHERE BOOKID = PBOOKID;

    IF VSTATUS IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking not found';
    END IF;

    IF VSTATUS <> 'CR' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Booking cannot be served from its current state';
    END IF;

    IF VSERVICEDATE <> CURDATE() THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only bookings for today can be served';
    END IF;

    START TRANSACTION;

    INSERT INTO CMS_BOOKHIST (
        BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
        STATUS, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
        BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
        REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, CHANGEDBY, CHGREASON
    )
    SELECT
        BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
        STATUS, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
        BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
        REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, PSERVEDBY, 'Served'
    FROM CMS_BOOKING
    WHERE BOOKID = PBOOKID;

    SET VBOOKHISTID = LAST_INSERT_ID();

    INSERT INTO CMS_BOOKITMHS (BOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUS)
    SELECT VBOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUS
    FROM CMS_BOOKITEM
    WHERE BOOKID = PBOOKID;

    UPDATE CMS_BOOKING
    SET STATUS = 'SRV',
        SERVEDBY = PSERVEDBY,
        SERVEDON = CURRENT_TIMESTAMP,
        UPDATEDBY = PSERVEDBY,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE BOOKID = PBOOKID;

    COMMIT;
END$$

-- v1_module3
-- End-of-day batch job. Marks any still-CR booking for the given
-- service date as No Show and writes history for each. Pass
-- PSERVICEID to scope the run to one service; pass NULL to close
-- out every service for that date in one call.
CREATE PROCEDURE CMSNOSHOWBOOK (
    IN PSERVICEDATE DATE,
    IN PSERVICEID INT,
    IN PCHANGEDBY INT
)
BEGIN
    DECLARE VDONE INT DEFAULT 0;
    DECLARE VBOOKID INT;
    DECLARE VBOOKHISTID INT;

    DECLARE VCUR CURSOR FOR
        SELECT BOOKID FROM CMS_BOOKING
        WHERE SERVICEDATE = PSERVICEDATE
          AND STATUS = 'CR'
          AND (PSERVICEID IS NULL OR SERVICEID = PSERVICEID);

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET VDONE = 1;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PSERVICEDATE IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Service date is required';
    END IF;

    START TRANSACTION;

    OPEN VCUR;

    READLOOP: LOOP
        FETCH VCUR INTO VBOOKID;
        IF VDONE = 1 THEN
            LEAVE READLOOP;
        END IF;

        INSERT INTO CMS_BOOKHIST (
            BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
            STATUS, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
            BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
            REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, CHANGEDBY, CHGREASON
        )
        SELECT
            BOOKID, BOOKNO, BOOKTYPEID, CUSTOMERID, SERVICEID, SERVICEDATE,
            STATUS, BOOKSEQNO, TOTALITEMS, TOTALQTY, TOTALAMOUNT,
            BOOKEDBY, BOOKEDON, CANCELLEDBY, CANCELLEDON, SERVEDBY, SERVEDON, NOSHOWON,
            REMARKS, CREATEDBY, CREATEDAT, UPDATEDBY, UPDATEDAT, PCHANGEDBY, 'End of day no-show'
        FROM CMS_BOOKING
        WHERE BOOKID = VBOOKID;

        SET VBOOKHISTID = LAST_INSERT_ID();

        INSERT INTO CMS_BOOKITMHS (BOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUS)
        SELECT VBOOKHISTID, BOOKITEMID, DAYMENUID, MENUITEMID, QTY, RATE, AMOUNT, REMARKS, STATUS
        FROM CMS_BOOKITEM
        WHERE BOOKID = VBOOKID;

        UPDATE CMS_BOOKING
        SET STATUS = 'NOS',
            NOSHOWON = CURRENT_TIMESTAMP,
            UPDATEDBY = PCHANGEDBY,
            UPDATEDAT = CURRENT_TIMESTAMP
        WHERE BOOKID = VBOOKID;
    END LOOP;

    CLOSE VCUR;

    COMMIT;
END$$

-- v1_module3
-- Lightweight live toggle for kiosk availability. Deliberately does
-- NOT go through CMSUPDMENU/CMSUPDSLOT and writes no history: this is
-- a frequent, low-stakes operational flag change, not a formal edit.
CREATE PROCEDURE CMSTOGGLEKIOSK (
    IN PDAYMENUID INT,
    IN PISKIOSK TINYINT,
    IN PCHANGEDBY INT
)
BEGIN
    DECLARE VEXISTS INT DEFAULT 0;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    IF PDAYMENUID IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day Menu ID is required';
    END IF;

    IF PISKIOSK IS NULL OR PISKIOSK NOT IN (0, 1) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid kiosk availability flag';
    END IF;

    SELECT COUNT(*) INTO VEXISTS FROM CMS_DAYMENU WHERE DAYMENUID = PDAYMENUID;

    IF VEXISTS = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Day menu not found';
    END IF;

    START TRANSACTION;

    UPDATE CMS_DAYMENU
    SET ISKIOSK = PISKIOSK,
        UPDATEDAT = CURRENT_TIMESTAMP
    WHERE DAYMENUID = PDAYMENUID;

    COMMIT;
END$$

-- ------------------------------------------------------------
-- CMSGETBOOK - Fetch a single booking header and its items
-- ------------------------------------------------------------
CREATE PROCEDURE CMSGETBOOK(
    IN PBOOKID INT
)
BEGIN
    -- Result Set 1: Booking Header
    SELECT 
        B.BOOKID, B.BOOKNO, B.BOOKTYPEID, BT.BOOKTYPECODE, BT.BOOKTYPENAME,
        B.CUSTOMERID, C.CTYPECODE, C.DISPNAME AS CUSTOMERNAME,
        B.SERVICEID, S.SERVNAME, B.SERVICEDATE,
        B.STATUS, B.TOTALITEMS, B.TOTALQTY, B.TOTALAMOUNT,
        B.BOOKEDBY, U.FULLNAME AS BOOKEDBYNAME, B.BOOKEDON,
        B.CANCELLEDBY, B.CANCELLEDON, B.SERVEDBY, B.SERVEDON, B.NOSHOWON, B.REMARKS
    FROM CMS_BOOKING B
    INNER JOIN CMS_BOOKTYPE BT ON BT.BOOKTYPEID = B.BOOKTYPEID
    INNER JOIN CMS_CUSTOMER C ON C.CUSTOMERID = B.CUSTOMERID
    INNER JOIN CMS_SERVICE S ON S.SERVICEID = B.SERVICEID
    LEFT JOIN CMS_USER U ON U.USERID = B.BOOKEDBY
    WHERE B.BOOKID = PBOOKID;

    -- Result Set 2: Booking Items
    SELECT 
        BI.BOOKITEMID, BI.DAYMENUID, BI.MENUITEMID, MI.MENUCODE, MI.MENUNAME,
        BI.QTY, BI.RATE, BI.AMOUNT, BI.REMARKS, BI.STATUS
    FROM CMS_BOOKITEM BI
    INNER JOIN CMS_MENUITEM MI ON MI.MENUITEMID = BI.MENUITEMID
    WHERE BI.BOOKID = PBOOKID;
END$$

-- ------------------------------------------------------------
-- CMSLISTBOOK - List bookings with optional filters
-- ------------------------------------------------------------
CREATE PROCEDURE CMSLISTBOOK(
    IN PCUSTOMERID INT,
    IN PSERVICEID INT,
    IN PSTARTDATE DATE,
    IN PENDDATE DATE,
    IN PSTATUS VARCHAR(10)
)
BEGIN
    SELECT 
        B.BOOKID, B.BOOKNO, BT.BOOKTYPECODE, 
        B.CUSTOMERID, C.DISPNAME AS CUSTOMERNAME,
        B.SERVICEID, S.SERVNAME, B.SERVICEDATE,
        B.STATUS, B.TOTALITEMS, B.TOTALQTY, B.TOTALAMOUNT
    FROM CMS_BOOKING B
    INNER JOIN CMS_BOOKTYPE BT ON BT.BOOKTYPEID = B.BOOKTYPEID
    INNER JOIN CMS_CUSTOMER C ON C.CUSTOMERID = B.CUSTOMERID
    INNER JOIN CMS_SERVICE S ON S.SERVICEID = B.SERVICEID
    WHERE (PCUSTOMERID IS NULL OR B.CUSTOMERID = PCUSTOMERID)
      AND (PSERVICEID IS NULL OR B.SERVICEID = PSERVICEID)
      AND (PSTARTDATE IS NULL OR B.SERVICEDATE >= PSTARTDATE)
      AND (PENDDATE IS NULL OR B.SERVICEDATE <= PENDDATE)
      AND (PSTATUS IS NULL OR B.STATUS = PSTATUS)
    ORDER BY B.SERVICEDATE DESC, B.BOOKNO DESC;
END$$

DELIMITER ;
