
USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_CANTEEN;

SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE CMS_CANTEEN (
    CANTEENID INT AUTO_INCREMENT PRIMARY KEY,
    CENTERID INT NOT NULL,
    CANTEENCODE VARCHAR(20) NOT NULL,
    CANTEENNAME VARCHAR(120) NOT NULL,
    LOCATION VARCHAR(150),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'A',

    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY UQ_CENTER_CANTEEN
    (
        CENTERID,
        CANTEENCODE
    ),

    CONSTRAINT FK_CAN_CENTER
        FOREIGN KEY (CENTERID)
        REFERENCES CMS_CENTER(CENTERID)
) ENGINE=InnoDB;

