
USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_CENTER;

SET FOREIGN_KEY_CHECKS = 1;




CREATE TABLE CMS_CENTER (
    CENTERID INT AUTO_INCREMENT PRIMARY KEY,
    CENTERCODE VARCHAR(20) NOT NULL UNIQUE,
    CENTERNAME VARCHAR(120) NOT NULL,
    LOCATION VARCHAR(150),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'A',
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

