USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_CUSTOMER;

SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE CMS_CUSTOMER (
    CUSTOMERID INT AUTO_INCREMENT PRIMARY KEY,
    USERID INT NULL UNIQUE,
    CTYPECODE VARCHAR(20) NOT NULL,
    DISPNAME VARCHAR(120) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'A',
    VALIDFROM DATETIME NULL,
    VALIDUNTIL DATETIME NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_CUST_USER FOREIGN KEY (USERID) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_CUST_TYPE FOREIGN KEY (CTYPECODE) REFERENCES CMS_CUSTTYPE(CTYPECODE)
) ENGINE=InnoDB;
