USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_DAYMENU;
DROP TABLE IF EXISTS CMS_DMENUHIST;

SET FOREIGN_KEY_CHECKS = 1;

/* ============================================================
   DAYMENU -- item offered on a specific day-slot.
   STATUS      = operational availability (A/D), can flip
                 many times a day, unrelated to approval.
   APPRSTATUS  = single-level manager approval workflow state.
   ============================================================ */


CREATE TABLE CMS_DAYMENU (
    DAYMENUID   INT AUTO_INCREMENT PRIMARY KEY,
    DMENUNO     VARCHAR(20) NULL UNIQUE,
    DAYSLOTID   INT NOT NULL,
    MENUITEMID  INT NOT NULL,
    ISBASE      TINYINT(1) NOT NULL DEFAULT 1,
    ISSPECIAL   TINYINT(1) NOT NULL DEFAULT 0,
    ISPREBOOK   TINYINT(1) NOT NULL DEFAULT 1,
    ISKIOSK    TINYINT(1) NOT NULL DEFAULT 1,
    BOOKUNTIL    DATETIME NOT NULL,
    CANCELUNTIL  DATETIME NOT NULL,   
    AVAILQTY    INT NOT NULL DEFAULT 0,
    MAXQTY      INT NOT NULL DEFAULT 1,
    STATUS      VARCHAR(20) NOT NULL DEFAULT 'A',      -- operational: A / D / 
    APPRSTATUS  VARCHAR(20) NOT NULL DEFAULT 'PEN',       -- approval workflow: PEN / APP / REJ
    APPROVEDBY  INT NULL,
    APPROVEDAT  DATETIME NULL,
    REMARKS     VARCHAR(255),
    CREATEDAT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATEDBY     INT NOT NULL,
    UPDATEDAT   DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_DAYMENU (DAYSLOTID, MENUITEMID),
    CONSTRAINT FK_DM_SLOT FOREIGN KEY (DAYSLOTID) REFERENCES CMS_DAYSLOT(DAYSLOTID),
    CONSTRAINT FK_DM_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_DM_ADD  FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_DM_APPR FOREIGN KEY (APPROVEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_DM_QTY      CHECK (MAXQTY >= 1 AND AVAILQTY >= 0),
    CONSTRAINT CK_DM_CHANNELS CHECK (ISPREBOOK IN (0,1) AND ISKIOSK IN (0,1) AND ISSPECIAL IN (0,1)),
    CONSTRAINT CK_DM_STATUS   CHECK (STATUS IN ('A','D')),
    CONSTRAINT CK_DM_TIMES CHECK (CANCELUNTIL <= BOOKUNTIL),
    CONSTRAINT CK_DM_APPR     CHECK (APPRSTATUS IN ('PEN','APP','REJ'))
) ENGINE=InnoDB;



CREATE TABLE CMS_DMENUHIST (
    DMENUHISTID INT AUTO_INCREMENT PRIMARY KEY,
    DAYMENUID   INT NOT NULL,
    DAYSLOTID   INT NOT NULL,
    MENUITEMID  INT NOT NULL,
    ISSPECIAL   TINYINT(1) NOT NULL,
    ISPREBOOK   TINYINT(1) NOT NULL,
    ISKIOSK    TINYINT(1) NOT NULL,
    AVAILQTY    INT NOT NULL,
    MAXQTY      INT NOT NULL,
    STATUS      VARCHAR(20) NOT NULL,
    APPRSTATUS  VARCHAR(20) NOT NULL,
    CHANGEDBY   INT NOT NULL,
    CHANGEDAT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON   VARCHAR(255),
    REMARKS     VARCHAR(255),
    CONSTRAINT FK_DMH_DM   FOREIGN KEY (DAYMENUID) REFERENCES CMS_DAYMENU(DAYMENUID),
    CONSTRAINT FK_DMH_SLOT FOREIGN KEY (DAYSLOTID) REFERENCES CMS_DAYSLOT(DAYSLOTID),
    CONSTRAINT FK_DMH_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_DMH_BY   FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;




/* ============================================================
   TRIGGERS
   ============================================================ */

DELIMITER $$

-- Editing an approved day-menu row forces it back to Pending

DROP TRIGGER IF EXISTS TRG_DAYMENU_APPR_RESET;

CREATE TRIGGER TRG_DAYMENU_APPR_RESET
BEFORE UPDATE ON CMS_DAYMENU
FOR EACH ROW
BEGIN
    IF OLD.APPRSTATUS = 'APP' AND (
        OLD.AVAILQTY  <> NEW.AVAILQTY OR
        OLD.MAXQTY    <> NEW.MAXQTY OR
        OLD.ISSPECIAL <> NEW.ISSPECIAL OR
        OLD.ISPREBOOK <> NEW.ISPREBOOK OR
        OLD.ISKIOSK  <> NEW.ISKIOSK
    ) THEN
        SET NEW.APPRSTATUS = 'PEN';
        SET NEW.APPROVEDBY = NULL;
        SET NEW.APPROVEDAT = NULL;
    END IF;
END$$

DELIMITER ;
