USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;


DROP TABLE IF EXISTS CMS_DAYSLOT;
DROP TABLE IF EXISTS CMS_SLOTHIST;


SET FOREIGN_KEY_CHECKS = 1;



/* ============================================================
   DAYSLOT -- dated instance of a service. Canteen-scoping falls
   out for free via SERVICEID.
   ============================================================ */

CREATE TABLE CMS_DAYSLOT (
    DAYSLOTID INT AUTO_INCREMENT PRIMARY KEY,
    SERVICEID INT NOT NULL,
    SERVDATE  DATE NOT NULL,
    CANTEENID INT NOT NULL,
    STARTTIME TIME NOT NULL,
    ENDTIME   TIME NOT NULL,
    STATUS    VARCHAR(20) NOT NULL DEFAULT 'A',
    CREATEDBY INT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_DAYSLOT (CANTEENID,SERVICEID, SERVDATE),
    CONSTRAINT FK_DS_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_DS_BY   FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_DS_CAN FOREIGN KEY (CANTEENID) REFERENCES CMS_CANTEEN(CANTEENID),
    CONSTRAINT CK_DS_TIME   CHECK (ENDTIME > STARTTIME),
    CONSTRAINT CK_DS_STATUS CHECK (STATUS IN ('A','D'))
) ENGINE=InnoDB;

CREATE TABLE CMS_SLOTHIST (
    SLOTHISTID INT AUTO_INCREMENT PRIMARY KEY,
    DAYSLOTID  INT NOT NULL,
    SERVICEID  INT NOT NULL,
    CANTEENID INT NOT NULL,
    SERVDATE   DATE NOT NULL,
    STARTTIME  TIME NOT NULL,
    ENDTIME    TIME NOT NULL,
    STATUS     VARCHAR(20) NOT NULL,
    CHANGEDBY  INT NOT NULL,
    CHANGEDAT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON  VARCHAR(255),
    CONSTRAINT FK_SLH_SLOT FOREIGN KEY (DAYSLOTID) REFERENCES CMS_DAYSLOT(DAYSLOTID),
    CONSTRAINT FK_SLH_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_SLH_BY   FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_SLH_CAN FOREIGN KEY (CANTEENID) REFERENCES CMS_CANTEEN(CANTEENID)
) ENGINE=InnoDB;


