USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_MENUTPLDT;
DROP TABLE IF EXISTS CMS_MENUTPL;

SET FOREIGN_KEY_CHECKS = 1;

/* ============================================================
   MENUTPL / MENUTPLDT -- recurring templates so "copy previous
   day/week/month menu" is a materialization from a named
   template, not an ad-hoc row-copy.
   WEEKDAY: 1=Mon..7=Sun; NULL = ad-hoc/reusable template not
   tied to a specific weekday (e.g. a "festival day" template).
   ============================================================ */

CREATE TABLE CMS_MENUTPL (
    MENUTPLID INT AUTO_INCREMENT PRIMARY KEY,
    CANTEENID INT NOT NULL,
    SERVICEID INT NOT NULL,
    TPLNAME   VARCHAR(80) NOT NULL,
    WEEKDAY   TINYINT NULL,
    STATUS    VARCHAR(20) NOT NULL DEFAULT 'A',
    CREATEDBY INT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_MENUTPL (CANTEENID, SERVICEID, TPLNAME),
    CONSTRAINT FK_MTPL_CAN  FOREIGN KEY (CANTEENID) REFERENCES CMS_CANTEEN(CANTEENID),
    CONSTRAINT FK_MTPL_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_MTPL_BY   FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_MTPL_WEEKDAY CHECK (WEEKDAY IS NULL OR WEEKDAY BETWEEN 1 AND 7),
    CONSTRAINT CK_MTPL_STATUS  CHECK (STATUS IN ('A','D'))
) ENGINE=InnoDB;

CREATE TABLE CMS_MENUTPLDT (
    MENUTPLDTID INT AUTO_INCREMENT PRIMARY KEY,
    MENUTPLID   INT NOT NULL,
    MENUITEMID  INT NOT NULL,
    ISSPECIAL   TINYINT(1) NOT NULL DEFAULT 0,
    ISPREBOOK   TINYINT(1) NOT NULL DEFAULT 1,
    ISKIOSK    TINYINT(1) NOT NULL DEFAULT 1,
    MAXQTY      INT NOT NULL DEFAULT 1,
    DEFAVAILQTY INT NOT NULL DEFAULT 0,
    UNIQUE KEY UQ_MTPLDT (MENUTPLID, MENUITEMID),
    CONSTRAINT FK_MTPLDT_TPL  FOREIGN KEY (MENUTPLID) REFERENCES CMS_MENUTPL(MENUTPLID),
    CONSTRAINT FK_MTPLDT_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT CK_MTPLDT_QTY CHECK (MAXQTY >= 1 AND DEFAVAILQTY >= 0)
) ENGINE=InnoDB;



