USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_ROLE;
-- DROP TABLE IF EXISTS CMS_ROLESCN;

SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE CMS_ROLE (
    ROLEID INT AUTO_INCREMENT PRIMARY KEY,
    ROLECODE VARCHAR(50) NOT NULL UNIQUE,
    ROLENAME VARCHAR(100) NOT NULL,
    DESCR VARCHAR(255),
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- CREATE TABLE CMS_ROLESCN (
--     ROLESCNID INT AUTO_INCREMENT PRIMARY KEY,
--     ROLEID INT NOT NULL,
--     SCREENID INT NOT NULL,
--     CANVIEW TINYINT(1) NOT NULL DEFAULT 0,
--     CANCREATE TINYINT(1) NOT NULL DEFAULT 0,
--     CANUPDATE TINYINT(1) NOT NULL DEFAULT 0,
--     CANDELETE TINYINT(1) NOT NULL DEFAULT 0,
--     ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
--     CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
--     UNIQUE KEY UQ_ROLESCN (ROLEID, SCREENID),
--     CONSTRAINT FK_RS_ROLE FOREIGN KEY (ROLEID) REFERENCES CMS_ROLE(ROLEID),
--     CONSTRAINT FK_RS_SCREEN FOREIGN KEY (SCREENID) REFERENCES CMS_SCREEN(SCREENID)
-- ) ENGINE=InnoDB;
