USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;


DROP TABLE IF EXISTS CMS_SERVICE;
DROP TABLE IF EXISTS CMS_SERVHIST;

SET FOREIGN_KEY_CHECKS = 1;

/* ============================================================
   SERVICE -- global service catalog (Breakfast / Lunch / ...)
   Canteen scoping happens at CMS_DAYSLOT level (DAYSLOT.CANTEENID).
   ============================================================ */
CREATE TABLE CMS_SERVICE (
    SERVICEID   INT AUTO_INCREMENT PRIMARY KEY,
    SERVCODE    VARCHAR(20) NOT NULL,          -- globally unique service code
    SERVNAME    VARCHAR(80) NOT NULL,
    DEFSTART    TIME NOT NULL,                 -- default window, copied onto day slots
    DEFEND      TIME NOT NULL,
    STATUS      VARCHAR(20) NOT NULL DEFAULT 'A',  -- A = active, D = disabled
    CREATEDBY   INT NOT NULL,
    CREATEDAT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT   DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_SERV_CODE (SERVCODE),
    CONSTRAINT FK_SERV_BY  FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_SERV_TIME     CHECK (DEFEND > DEFSTART),
    CONSTRAINT CK_SERV_STATUS   CHECK (STATUS IN ('A','D'))
) ENGINE=InnoDB;

CREATE TABLE CMS_SERVHIST (
    SERVHISTID INT AUTO_INCREMENT PRIMARY KEY,
    SERVICEID  INT NOT NULL,
    SERVCODE   VARCHAR(20) NOT NULL,
    SERVNAME   VARCHAR(80) NOT NULL,
    DEFSTART   TIME NOT NULL,
    DEFEND     TIME NOT NULL,
    VALIDFROM  DATE NULL,
    VALIDUNTIL DATE NULL,
    STATUS     VARCHAR(20) NOT NULL,
    CHANGEDBY  INT NOT NULL,
    CHANGEDAT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON  VARCHAR(255),
    CONSTRAINT FK_SH_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_SH_BY   FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;
