USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_ACCKEY;

SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE CMS_ACCKEY (
    ACCKEYID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT NOT NULL,
    KEYTYPE VARCHAR(30) NOT NULL,
    KEYVALUE VARCHAR(255) NOT NULL UNIQUE,
    EXPIRESAT DATETIME NULL,
    STATUSID INT NOT NULL DEFAULT 10,
    CREATEDBY INT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    LASTUSEDAT DATETIME NULL,
    CONSTRAINT FK_AK_CUST FOREIGN KEY (CUSTOMERID) REFERENCES CMS_CUSTOMER(CUSTOMERID),
    CONSTRAINT FK_AK_BY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_KEYTYPE CHECK (KEYTYPE IN ('QR','RFID','EMPCARD','VISPASS','TEMPTOKEN')),
    CONSTRAINT FK_AK_STATUS FOREIGN KEY (STATUSID) REFERENCES CMS_STATUS(STATUSID)
) ENGINE=InnoDB;
