USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_CANTEENROLE;

SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE CMS_CANTEENROLE (
    USRCANROLEID INT AUTO_INCREMENT PRIMARY KEY,
    USERID INT NOT NULL,
    ROLEID INT NOT NULL,
    CANTEENID INT NOT NULL,
    ISDEFAULT TINYINT(1) NOT NULL DEFAULT 0,
    VALIDFROM DATETIME NULL,
    VALIDUNTIL DATETIME NULL,
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    ASSIGNEDBY INT NULL,
    ASSIGNEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_USRCANROLE
    (
        USERID,
        ROLEID,
        CANTEENID
    ),

    CONSTRAINT FK_UCR_USER
        FOREIGN KEY (USERID)
        REFERENCES CMS_USER(USERID),

    CONSTRAINT FK_UCR_ROLE
        FOREIGN KEY (ROLEID)
        REFERENCES CMS_ROLE(ROLEID),

    CONSTRAINT FK_UCR_CANTEEN
        FOREIGN KEY (CANTEENID)
        REFERENCES CMS_CANTEEN(CANTEENID),

    CONSTRAINT FK_UCR_BY
        FOREIGN KEY (ASSIGNEDBY)
        REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;
