USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_CONSUMERROLE;

SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE CMS_CONSUMERROLE (
    USRROLEID INT AUTO_INCREMENT PRIMARY KEY,
    USERID INT NOT NULL,
    ROLEID INT NOT NULL,
    ASSIGNEDBY INT NULL,
    ASSIGNEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VALIDFROM DATETIME NULL,
    VALIDUNTIL DATETIME NULL,
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    UNIQUE KEY UQ_USRROLE (USERID, ROLEID),
    CONSTRAINT FK_UR_USER FOREIGN KEY (USERID) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLEID) REFERENCES CMS_ROLE(ROLEID),
    CONSTRAINT FK_UR_BY FOREIGN KEY (ASSIGNEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;
