USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_DAYMENU;
DROP TABLE IF EXISTS CMS_DMENUHIST;

SET FOREIGN_KEY_CHECKS = 1;

/* ============================================================
   DAYMENU -- item offered on a specific day-slot.
   STATUSID    = operational availability (10=ACT, 11=DIS)
   ============================================================ */

CREATE TABLE CMS_DAYMENU (
    DAYMENUID   INT AUTO_INCREMENT PRIMARY KEY,
    DMENUNO     VARCHAR(20) NOT NULL UNIQUE,          -- Auto-generated via CMSGENAUTO
    DAYSLOTID   INT NOT NULL,
    MENUITEMID  INT NOT NULL,
    ISBASE      TINYINT(1) NOT NULL DEFAULT 1,
    ISSPECIAL   TINYINT(1) NOT NULL DEFAULT 0,
    ISPREBOOK   TINYINT(1) NOT NULL DEFAULT 1,
    ISKIOSK     TINYINT(1) NOT NULL DEFAULT 1,
    BOOKUNTIL   DATETIME NOT NULL,
    CANCELUNTIL DATETIME NOT NULL,   
    AVAILQTY    INT NULL,
    MAXQTY      INT NOT NULL DEFAULT 1,
    STATUSID    INT NOT NULL DEFAULT 10,              -- 10 = 'ACT' (Active)
    CREATEDAT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATEDBY   INT NOT NULL,
    UPDATEDAT   DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_DAYMENU (DAYSLOTID, MENUITEMID),
    CONSTRAINT FK_DM_SLOT FOREIGN KEY (DAYSLOTID) REFERENCES CMS_DAYSLOT(DAYSLOTID),
    CONSTRAINT FK_DM_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_DM_ADD  FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_DM_STATUS FOREIGN KEY (STATUSID) REFERENCES CMS_STATUS(STATUSID),
    CONSTRAINT CK_DM_QTY    CHECK (MAXQTY >= 1 AND (AVAILQTY IS NULL OR AVAILQTY >= 0)),
    CONSTRAINT CK_DM_CHANNELS CHECK (ISPREBOOK IN (0,1) AND ISKIOSK IN (0,1) AND ISSPECIAL IN (0,1)),
    CONSTRAINT CK_DM_TIMES CHECK (CANCELUNTIL <= BOOKUNTIL)
) ENGINE=InnoDB;


CREATE TABLE CMS_DMENUHIST (
    DMENUHISTID INT AUTO_INCREMENT PRIMARY KEY,
    DAYMENUID   INT NOT NULL,                         -- Historical reference (no FK constraint to permit parent deletion)
    DMENUNO     VARCHAR(20) NOT NULL,                 -- Historical tracking of generated ID
    DAYSLOTID   INT NOT NULL,
    MENUITEMID  INT NOT NULL,
    ISSPECIAL   TINYINT(1) NOT NULL,
    ISPREBOOK   TINYINT(1) NOT NULL,
    ISKIOSK     TINYINT(1) NOT NULL,
    ISBASE      TINYINT(1) NOT NULL,
    BOOKUNTIL   DATETIME NOT NULL,
    CANCELUNTIL DATETIME NOT NULL,
    AVAILQTY    INT NULL,
    MAXQTY      INT NOT NULL,
    STATUSID    INT NOT NULL,
    CHANGEDBY   INT NOT NULL,
    CHANGEDAT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON   VARCHAR(255),
    CONSTRAINT FK_DMH_SLOT   FOREIGN KEY (DAYSLOTID) REFERENCES CMS_DAYSLOT(DAYSLOTID),
    CONSTRAINT FK_DMH_ITEM   FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_DMH_BY     FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_DMH_STATUS FOREIGN KEY (STATUSID) REFERENCES CMS_STATUS(STATUSID)
) ENGINE=InnoDB;