USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_SLOTHIST;
DROP TABLE IF EXISTS CMS_DAYSLOT;

SET FOREIGN_KEY_CHECKS = 1;

/* ============================================================
   DAYSLOT -- dated instance of a service. Canteen-scoping falls
   out for free via SERVICEID.
   ============================================================ */

CREATE TABLE CMS_DAYSLOT (
    DAYSLOTID INT AUTO_INCREMENT PRIMARY KEY,
    SLOTNO VARCHAR(30) NOT NULL UNIQUE,             --Auto-generated ID (e.g., SLT202608220001)
    SERVICEID INT NOT NULL,
    SERVDATE  DATE NOT NULL,
    CANTEENID INT NOT NULL,
    STARTTIME TIME NOT NULL,
    ENDTIME   TIME NOT NULL,
    STATUSID  INT NOT NULL DEFAULT 10,              -- CHANGED: 10 = 'ACT'
    APPRSTATUSID INT NOT NULL DEFAULT 20,           -- CHANGED: 20 = 'DRF'
    MENUSUBMITTEDBY INT NULL,
    MENUSUBMITTEDAT DATETIME NULL,
    MENUAPPROVEDBY INT NULL,
    MENUAPPROVEDAT DATETIME NULL,
    MENUREMARKS VARCHAR(255) NULL,
    CREATEDBY INT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_DAYSLOT (CANTEENID, SERVICEID, SERVDATE),
    CONSTRAINT FK_DS_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_DS_BY   FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_DS_CAN  FOREIGN KEY (CANTEENID) REFERENCES CMS_CANTEEN(CANTEENID),
    CONSTRAINT FK_DS_MSBY FOREIGN KEY (MENUSUBMITTEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_DS_MABY FOREIGN KEY (MENUAPPROVEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_DS_STATUS FOREIGN KEY (STATUSID) REFERENCES CMS_STATUS(STATUSID),         -- NEW: FK to CMS_STATUS
    CONSTRAINT FK_DS_APPRSTATUS FOREIGN KEY (APPRSTATUSID) REFERENCES CMS_STATUS(STATUSID), -- NEW: FK to CMS_STATUS
    CONSTRAINT CK_DS_TIME   CHECK (ENDTIME > STARTTIME)
) ENGINE=InnoDB;

CREATE TABLE CMS_SLOTHIST (
    SLOTHISTID INT AUTO_INCREMENT PRIMARY KEY,
    DAYSLOTID  INT NOT NULL,
    SLOTNO     VARCHAR(30) NOT NULL,
    SERVICEID  INT NOT NULL,
    CANTEENID INT NOT NULL,
    SERVDATE   DATE NOT NULL,
    STARTTIME  TIME NOT NULL,
    ENDTIME    TIME NOT NULL,
    STATUSID   INT NOT NULL,
    APPRSTATUSID INT NOT NULL,
    MENUSUBMITTEDBY INT NULL,
    MENUSUBMITTEDAT DATETIME NULL,
    MENUAPPROVEDBY INT NULL,
    MENUAPPROVEDAT DATETIME NULL,
    MENUREMARKS VARCHAR(255) NULL,
    CHANGEDBY  INT NOT NULL,
    CHANGEDAT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON  VARCHAR(255),
    CONSTRAINT FK_SLH_SLOT FOREIGN KEY (DAYSLOTID) REFERENCES CMS_DAYSLOT(DAYSLOTID),
    CONSTRAINT FK_SLH_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_SLH_BY   FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_SLH_CAN  FOREIGN KEY (CANTEENID) REFERENCES CMS_CANTEEN(CANTEENID),
    CONSTRAINT FK_SLH_STATUS FOREIGN KEY (STATUSID) REFERENCES CMS_STATUS(STATUSID),         -- ADDED
    CONSTRAINT FK_SLH_APPRSTATUS FOREIGN KEY (APPRSTATUSID) REFERENCES CMS_STATUS(STATUSID)  -- ADDED
) ENGINE=InnoDB;

