USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_PERMEMP;
DROP TABLE IF EXISTS CMS_CONTEMP;
DROP TABLE IF EXISTS CMS_OCEEMP;
DROP TABLE IF EXISTS CMS_VISITOR;

SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE CMS_PERMEMP (
    PERMEMPID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT NOT NULL UNIQUE,
    EMPCODE VARCHAR(50) NOT NULL UNIQUE,
    DEPT VARCHAR(100) NOT NULL,
    DESIG VARCHAR(100) NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_PE_CUST FOREIGN KEY (CUSTOMERID) REFERENCES CMS_CUSTOMER(CUSTOMERID)
) ENGINE=InnoDB;

CREATE TABLE CMS_CONTEMP (
    CONTEMPID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT NOT NULL UNIQUE,
    CONTCODE VARCHAR(50) NOT NULL UNIQUE,
    VENDORNAME VARCHAR(150) NOT NULL,
    CONTSTART DATE NOT NULL,
    CONTEND DATE NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_CE_CUST FOREIGN KEY (CUSTOMERID) REFERENCES CMS_CUSTOMER(CUSTOMERID),
    CONSTRAINT CK_CONT_DATES CHECK (CONTEND >= CONTSTART)
) ENGINE=InnoDB;

CREATE TABLE CMS_OCEEMP (
    OCEEMPID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT NOT NULL UNIQUE,
    EMPCODE VARCHAR(50) NOT NULL,
    CENTERNAME VARCHAR(120) NOT NULL,
    DEPT VARCHAR(100),
    DESIG VARCHAR(100),
    VALIDFROM DATETIME NULL,
    VALIDUNTIL DATETIME NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_OCE_CODE_CENTRE (EMPCODE, CENTERNAME),
    CONSTRAINT FK_OCE_CUST FOREIGN KEY (CUSTOMERID) REFERENCES CMS_CUSTOMER(CUSTOMERID)
) ENGINE=InnoDB;

CREATE TABLE CMS_VISITOR (
    VISITORID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMERID INT NOT NULL UNIQUE,
    VISNAME VARCHAR(120) NOT NULL,
    VISMOBILE VARCHAR(20),
    VISORG VARCHAR(150),
    VISPURPOSE VARCHAR(255),
    VISDATE DATE NOT NULL,
    VALIDUNTIL DATETIME NOT NULL,
    CREATEDBY INT NOT NULL,
    STATUSID INT NOT NULL DEFAULT 10,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_VIS_CUST FOREIGN KEY (CUSTOMERID) REFERENCES CMS_CUSTOMER(CUSTOMERID),
    CONSTRAINT FK_VIS_BY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_VIS_STATUS FOREIGN KEY (STATUSID) REFERENCES CMS_STATUS(STATUSID)
) ENGINE=InnoDB;
