USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_HOLIDAY;

SET FOREIGN_KEY_CHECKS = 1;

/* ============================================================
   CMS_HOLIDAY -- System-wide holidays to prevent menu generation
   ============================================================ */

CREATE TABLE CMS_HOLIDAY (
    HOLIDAYID   INT AUTO_INCREMENT PRIMARY KEY,
    HOLIDAYDATE DATE NOT NULL UNIQUE,
    HOLIDAYNAME VARCHAR(100) NOT NULL,
    HOLIDAYTYPE VARCHAR(20) DEFAULT 'NATIONAL',
    ISRECURRING TINYINT(1) DEFAULT 0,                 -- 1 = Recurs yearly (e.g. fixed dates like Jan 1)
    STATUSID    INT NOT NULL DEFAULT 10,              -- 10 = 'ACT'
    CREATEDBY   INT NOT NULL,
    CREATEDAT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT   DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_HOL_STATUS FOREIGN KEY (STATUSID) REFERENCES CMS_STATUS(STATUSID),
    CONSTRAINT FK_HOL_BY     FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;
