USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_MENUITEM;
DROP TABLE IF EXISTS CMS_MENUHIST;
DROP TABLE IF EXISTS CMS_ITEMPRICE;
DROP TABLE IF EXISTS CMS_ITEMPRICEDT;

SET FOREIGN_KEY_CHECKS = 1;


/* ============================================================
   MENUITEM -- shared catalog, no price columns (see ITEMPRICE)
   ============================================================ */
CREATE TABLE CMS_MENUITEM (
    MENUITEMID INT AUTO_INCREMENT PRIMARY KEY,
    SERVICEID  INT NULL,                             -- Primary Service / Meal Category (NULL = All Services/Generic)
    MENUCODE   VARCHAR(20) NOT NULL UNIQUE,          -- Auto-generated via CMSGENAUTO (Prefix: ITM)
    SHORTNAME  VARCHAR(30) NOT NULL,
    ITEMNAME   VARCHAR(100) NOT NULL,
    ITEMDESCR  VARCHAR(255),
    ISSPECIAL  TINYINT(1) NOT NULL DEFAULT 0,
    STATUSID   INT NOT NULL DEFAULT 10,              -- 10 = 'ACT' (Active)
    CREATEDBY  INT NOT NULL,
    CREATEDAT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT  DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_MI_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_MI_BY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_MI_STATUS FOREIGN KEY (STATUSID) REFERENCES CMS_STATUS(STATUSID),
    CONSTRAINT CK_MI_SPECIAL CHECK (ISSPECIAL IN (0, 1)),
    INDEX IX_MI_SERVICEID (SERVICEID)
) ENGINE=InnoDB;

CREATE TABLE CMS_MENUHIST (
    MENUHISTID INT AUTO_INCREMENT PRIMARY KEY,
    MENUITEMID INT NOT NULL,
    SERVICEID  INT NULL,
    MENUCODE   VARCHAR(20) NOT NULL,
    SHORTNAME  VARCHAR(30) NOT NULL,
    ITEMNAME   VARCHAR(100) NOT NULL,
    ITEMDESCR  VARCHAR(255),
    ISSPECIAL  TINYINT(1) NOT NULL,
    STATUSID   INT NOT NULL,
    CHANGEDBY  INT NOT NULL,
    CHANGEDAT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHGREASON  VARCHAR(255),
    CONSTRAINT FK_MH_SERV FOREIGN KEY (SERVICEID) REFERENCES CMS_SERVICE(SERVICEID),
    CONSTRAINT FK_MH_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_MH_BY   FOREIGN KEY (CHANGEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_MH_STATUS FOREIGN KEY (STATUSID) REFERENCES CMS_STATUS(STATUSID)
) ENGINE=InnoDB;

/* ============================================================
   ITEMPRICE (header) + ITEMPRICEDT (per customer-type detail)

   No EFFUNTIL column: the end of one price band is implied by
   the EFFFROM of the next row for that item (type-2 SCD style).
   ============================================================ */
   
CREATE TABLE CMS_ITEMPRICE (
    ITEMPRICEID INT AUTO_INCREMENT PRIMARY KEY,
    MENUITEMID  INT NOT NULL,
    EFFFROM     DATE NOT NULL,
    STATUSID    INT NOT NULL DEFAULT 10,              -- 10 = 'ACT' (Active)
    CREATEDBY   INT NOT NULL,
    CREATEDAT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT   DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UQ_ITEMPRICE (MENUITEMID, EFFFROM),
    CONSTRAINT FK_IP_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT FK_IP_BY   FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_IP_STATUS FOREIGN KEY (STATUSID) REFERENCES CMS_STATUS(STATUSID),
    KEY IX_IP_ITEM_EFF (MENUITEMID, EFFFROM)
) ENGINE=InnoDB;

CREATE TABLE CMS_ITEMPRICEDT (
    ITEMPRICEDTID INT AUTO_INCREMENT PRIMARY KEY,
    ITEMPRICEID   INT NOT NULL,
    CTYPECODE     VARCHAR(20) NOT NULL,   -- FK to CMS_CUSTTYPE
    PRICE         DECIMAL(10,2) NOT NULL,
    UNIQUE KEY UQ_IPDT (ITEMPRICEID, CTYPECODE),
    CONSTRAINT FK_IPDT_HDR  FOREIGN KEY (ITEMPRICEID) REFERENCES CMS_ITEMPRICE(ITEMPRICEID),
    CONSTRAINT FK_IPDT_CTYPE FOREIGN KEY (CTYPECODE) REFERENCES CMS_CUSTTYPE(CTYPECODE),
    CONSTRAINT CK_IPDT_PRICE CHECK (PRICE >= 0)
) ENGINE=InnoDB;