USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_OFFAPPR;
DROP TABLE IF EXISTS CMS_OFFBOOK;
DROP TABLE IF EXISTS CMS_OFFBOOKCTR;
DROP TABLE IF EXISTS CMS_OFFCOMBO_ITEM;
DROP TABLE IF EXISTS CMS_OFFCOMBO;
DROP TABLE IF EXISTS CMS_OFFSERV;
DROP TABLE IF EXISTS CMS_LVLMAP;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- 1. CMS_LVLMAP: Employee Level to Approver Tier Mapping
-- ============================================================
CREATE TABLE CMS_LVLMAP (
    LVLMAPID INT AUTO_INCREMENT PRIMARY KEY,
    EMPLEVEL INT NOT NULL UNIQUE,
    APPRLVL VARCHAR(10) NOT NULL,
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATEDBY INT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDBY INT NULL,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_LM_CREATEDBY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_LM_UPDATEDBY FOREIGN KEY (UPDATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_LM_APPRLVL CHECK (APPRLVL IN ('L1', 'L2'))
) ENGINE=InnoDB;

-- ============================================================
-- 2. CMS_OFFSERV: Official Service Master (Canteen Scoped)
-- ============================================================
CREATE TABLE CMS_OFFSERV (
    OFFSERVID INT AUTO_INCREMENT PRIMARY KEY,
    CANTEENID INT NOT NULL,
    SERVNAME VARCHAR(100) NOT NULL,
    DESCR VARCHAR(500) NULL,
    CUTOFFHOURS INT NOT NULL DEFAULT 24,
    STATUSID INT NOT NULL DEFAULT 10,
    CREATEDBY INT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDBY INT NULL,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_OS_CANTEEN FOREIGN KEY (CANTEENID) REFERENCES CMS_CANTEEN(CANTEENID),
    CONSTRAINT FK_OS_STATUS FOREIGN KEY (STATUSID) REFERENCES CMS_STATUS(STATUSID),
    CONSTRAINT FK_OS_CREATEDBY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_OS_UPDATEDBY FOREIGN KEY (UPDATEDBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;

-- ============================================================
-- 5. CMS_OFFCOMBO: Predefined Combos with Total Unit Price
-- ============================================================
CREATE TABLE CMS_OFFCOMBO (
    OFFCOMBOID INT AUTO_INCREMENT PRIMARY KEY,
    OFFSERVID INT NOT NULL,
    COMBONAME VARCHAR(100) NOT NULL,
    DESCR VARCHAR(255) NULL,
    COMBOPRICE DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    STATUSID INT NOT NULL DEFAULT 10,
    CREATEDBY INT NOT NULL,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDBY INT NULL,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_OC_SERVICE FOREIGN KEY (OFFSERVID) REFERENCES CMS_OFFSERV(OFFSERVID) ON DELETE CASCADE,
    CONSTRAINT FK_OC_STATUS FOREIGN KEY (STATUSID) REFERENCES CMS_STATUS(STATUSID),
    CONSTRAINT FK_OC_CREATEDBY FOREIGN KEY (CREATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_OC_UPDATEDBY FOREIGN KEY (UPDATEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT CK_OC_PRICE CHECK (COMBOPRICE >= 0)
) ENGINE=InnoDB;

-- ============================================================
-- 6. CMS_OFFCOMBO_ITEM: Combo Menu Item Mappings
-- ============================================================
CREATE TABLE CMS_OFFCOMBO_ITEM (
    COMBOITEMID INT AUTO_INCREMENT PRIMARY KEY,
    OFFCOMBOID INT NOT NULL,
    MENUITEMID INT NOT NULL,
    QTY INT NOT NULL DEFAULT 1,
    UNIQUE KEY UQ_COMBO_ITEM (OFFCOMBOID, MENUITEMID),
    CONSTRAINT FK_OCI_COMBO FOREIGN KEY (OFFCOMBOID) REFERENCES CMS_OFFCOMBO(OFFCOMBOID) ON DELETE CASCADE,
    CONSTRAINT FK_OCI_ITEM FOREIGN KEY (MENUITEMID) REFERENCES CMS_MENUITEM(MENUITEMID),
    CONSTRAINT CK_OCI_QTY CHECK (QTY >= 1)
) ENGINE=InnoDB;

-- ============================================================
-- 7. CMS_OFFBOOKCTR: Counter for Sequential Booking Numbers
-- ============================================================
CREATE TABLE CMS_OFFBOOKCTR (
    CANTEENID INT NOT NULL,
    OFFSERVID INT NOT NULL,
    LASTNO BIGINT NOT NULL DEFAULT 0,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (CANTEENID, OFFSERVID),
    CONSTRAINT FK_OBC_CANTEEN FOREIGN KEY (CANTEENID) REFERENCES CMS_CANTEEN(CANTEENID),
    CONSTRAINT FK_OBC_SERVICE FOREIGN KEY (OFFSERVID) REFERENCES CMS_OFFSERV(OFFSERVID)
) ENGINE=InnoDB;

-- ============================================================
-- 8. CMS_OFFBOOK: Official Booking Header
-- ============================================================
CREATE TABLE CMS_OFFBOOK (
    OFFBOOKID INT AUTO_INCREMENT PRIMARY KEY,
    BOOKNO VARCHAR(35) NOT NULL UNIQUE,
    CANTEENID INT NOT NULL,
    OFFSERVID INT NOT NULL,
    OFFCOMBOID INT NOT NULL,
    CUSTOMERID INT NOT NULL,
    BOOKEDBY INT NOT NULL,
    PURPOSE VARCHAR(255) NOT NULL,
    VENUE VARCHAR(255) NOT NULL,
    EVENTDATETIME DATETIME NOT NULL,
    QUANTITY INT NOT NULL,
    NOOFPEOPLE INT NOT NULL,
    UNITPRICE DECIMAL(10,2) NOT NULL,
    TOTALAMOUNT DECIMAL(12,2) NOT NULL,
    APPRLVL VARCHAR(10) NOT NULL,
    APPROVERID INT NOT NULL,
    STATUSID INT NOT NULL DEFAULT 35,
    BOOKEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDBY INT NULL,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_OB_CANTEEN FOREIGN KEY (CANTEENID) REFERENCES CMS_CANTEEN(CANTEENID),
    CONSTRAINT FK_OB_SERVICE FOREIGN KEY (OFFSERVID) REFERENCES CMS_OFFSERV(OFFSERVID),
    CONSTRAINT FK_OB_COMBO FOREIGN KEY (OFFCOMBOID) REFERENCES CMS_OFFCOMBO(OFFCOMBOID),
    CONSTRAINT FK_OB_CUSTOMER FOREIGN KEY (CUSTOMERID) REFERENCES CMS_CUSTOMER(CUSTOMERID),
    CONSTRAINT FK_OB_BOOKEDBY FOREIGN KEY (BOOKEDBY) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_OB_APPROVER FOREIGN KEY (APPROVERID) REFERENCES CMS_USER(USERID),
    CONSTRAINT FK_OB_STATUS FOREIGN KEY (STATUSID) REFERENCES CMS_STATUS(STATUSID),
    CONSTRAINT CK_OB_QTY CHECK (QUANTITY >= 1),
    CONSTRAINT CK_OB_PEOPLE CHECK (NOOFPEOPLE >= 1),
    CONSTRAINT CK_OB_TOTAL CHECK (TOTALAMOUNT >= 0)
) ENGINE=InnoDB;

-- ============================================================
-- 9. CMS_OFFAPPR: Approval & Resubmission Audit Trail
-- ============================================================
CREATE TABLE CMS_OFFAPPR (
    OFFAPPRID INT AUTO_INCREMENT PRIMARY KEY,
    OFFBOOKID INT NOT NULL,
    ACTIONBY INT NOT NULL,
    ACTIONROLE VARCHAR(30) NOT NULL,
    ACTION VARCHAR(20) NOT NULL,
    REJREASON VARCHAR(500) NULL,
    ACTIONAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_OA_BOOK FOREIGN KEY (OFFBOOKID) REFERENCES CMS_OFFBOOK(OFFBOOKID) ON DELETE CASCADE,
    CONSTRAINT FK_OA_USER FOREIGN KEY (ACTIONBY) REFERENCES CMS_USER(USERID)
) ENGINE=InnoDB;
