USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_ROLE;


SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE CMS_ROLE (
    ROLEID INT AUTO_INCREMENT PRIMARY KEY,
    ROLECODE VARCHAR(50) NOT NULL UNIQUE,
    ROLENAME VARCHAR(100) NOT NULL,
    DESCR VARCHAR(255),
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

