USE cms_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS CMS_USER;

SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE CMS_USER (
    USERID INT AUTO_INCREMENT PRIMARY KEY,
    LOGINID VARCHAR(50) NOT NULL UNIQUE,
    FULLNAME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(120) NULL UNIQUE,
    MOBILENO VARCHAR(20) NULL,
    PWDHASH VARCHAR(255) NOT NULL,
    AUTHPROV VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    AUTHID VARCHAR(120) NULL,
    ISACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATEDAT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
